function build = customArtifact_Nicole()
    % Nicole 默认构筑。
    % 以专武「尘光七谕 / Angelos' Heptades」为基准，面板偏高攻击力、
    % 双暴与适量充能，方便同时覆盖：
    % 1. 战技护盾与 Grace / Guidance 攻击加成；
    % 2. 爆发投影的前后台协同；
    % 3. 专武对前台角色与 Hexerei 后台角色的团队增伤。
    build = struct( ...
        'Weapon', 'Angelos'' Heptades', ...
        'WeaponATK', 741, ...
        'WeaponSubStatType', 'ATK%', ...
        'WeaponSubStatValue', 0.165, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 1.18, ...
        'FlatATK', 344, ...
        'ER', 1.45, ...
        'EM', 80, ...
        'CritRate', 0.62, ...
        'CritDMG', 1.42, ...
        'PyroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.00, ...
        'SkillDMGBonus', 0.15, ...
        'BurstDMGBonus', 0.18, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'GoldenTroupe', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Nicole', 'artifacts_Nicole.csv');
    writetable(struct2table(build), outputPath);
end
