function build = customArtifact_Freminet()
    % Default Freminet build favoring physical Shattering Pressure while keeping Cryo support value.
    build = struct( ...
        'Weapon', '苇海信标', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.331, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.88, ...
        'FlatATK', 311, ...
        'ER', 1.15, ...
        'EM', 40, ...
        'CritRate', 0.72, ...
        'CritDMG', 1.85, ...
        'CryoDMGBonus', 0.18, ...
        'PhysicalDMGBonus', 0.583, ...
        'NormalDMGBonus', 0.18, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.18, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'PaleFlame', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Freminet', 'artifacts_Freminet.csv');
    writetable(struct2table(build), outputPath);
end
