function build = customArtifact_Mavuika()
    % Default ATK/crit Pyro build for Mavuika's fighting-spirit burst window.
    build = struct( ...
        'Weapon', 'SunforgedClaymore', ...
        'WeaponATK', 741, ...
        'AtkBonus', 0.76, ...
        'FlatATK', 311, ...
        'CritRate', 0.70, ...
        'CritDMG', 2.24, ...
        'PyroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Mavuika', 'artifacts_Mavuika.csv');
    writetable(struct2table(build), outputPath);
end
