function build = customArtifact_Dori()
    % Default Dori build balancing burst uptime with modest Electro damage.
    build = struct( ...
        'Weapon', 'FavoniusGreatsword', ...
        'WeaponATK', 454, ...
        'HPBonus', 0.60, ...
        'AtkBonus', 0.35, ...
        'FlatATK', 120, ...
        'ER', 1.95, ...
        'CritRate', 0.40, ...
        'CritDMG', 1.00, ...
        'ElectroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.12, ...
        'BurstDMGBonus', 0.15, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'NoblesseOblige', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Dori', 'artifacts_Dori.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
