function build = customArtifact_Candace()
    % Default Candace build for HP-scaled skill and burst support damage.
    build = struct( ...
        'Weapon', 'FavoniusLance', ...
        'WeaponATK', 565, ...
        'HPBonus', 0.95, ...
        'FlatHP', 4780, ...
        'ER', 1.50, ...
        'CritRate', 0.60, ...
        'CritDMG', 1.70, ...
        'HydroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.15, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'NoblesseOblige', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Candace', 'artifacts_Candace.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
