function [totalDMG, dps, breakdown, rotationTime] = simulateCandaceDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Candace simulator modeling HP-scaled skill, burst waves, and Hydro-infused normals.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Candace', 'rotation_Candace.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Candace', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Candace', 'talents_Candace.csv');
    talent = readtable(talentPath);
    normalLevel = talentLevel;
    hpBonusByNormal = 0.005;
    n1Weight = hpBonusByNormal / max(getTalentValue(talent, 'Normal', 'x1HitDMG', normalLevel), 1e-6);
    n2Weight = hpBonusByNormal / max(getTalentValue(talent, 'Normal', 'x2HitDMG', normalLevel), 1e-6);
    n3Weight = hpBonusByNormal / max(getTalentValue(talent, 'Normal', 'x3HitDMG', normalLevel), 1e-6);
    n4Weight = hpBonusByNormal / max(getTalentValue(talent, 'Normal', 'x4HitDMG', normalLevel), 1e-6);
    allowVape = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1;
    preferredAura = "";
    if allowVape
        preferredAura = "Pyro";
    end
    hydroReady = getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1;

    actions = struct();
    actions.EHold = struct('TalentGroup', "Skill", 'Param', "ChargedUpDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", 'ActionScalingMode', "HP", 'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(allowVape), 'Note', "Sacred Rite hold");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", 'ActionScalingMode', "HP", 'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(allowVape), 'PostSetBurstActiveTime', 9.0, 'Note', "Wagtail's Tide");
    actions.Wave = struct('TalentGroup', "Burst", 'Param', "WaveImpactDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", 'ActionScalingMode', "HP", 'BaseMultiplier', 1.00, ...
        'HitCount', 3 + double(constellation >= 6), 'AllowAmplify', double(allowVape), 'Note', "Crimson Crown waves");
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'HPWeight', n1Weight, ...
        'AllowAmplify', double(allowVape), 'Note', "Hydro normal 1");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'HPWeight', n2Weight, ...
        'AllowAmplify', double(allowVape), 'Note', "Hydro normal 2");
    actions.N3 = struct('TalentGroup', "Normal", 'Param', "x3HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'HPWeight', n3Weight, ...
        'AllowAmplify', double(allowVape), 'Note', "Hydro normal 3");
    actions.N4 = struct('TalentGroup', "Normal", 'Param', "x4HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'HPWeight', n4Weight, ...
        'AllowAmplify', double(allowVape), 'Note', "Hydro normal 4");

    spec = struct( ...
        'Element', "Hydro", ...
        'ScalingMode', "HP", ...
        'PreferredAmplifyAura', preferredAura, ...
        'DefaultActionTime', 0.65, ...
        'DefaultRotation', {{'EHold', 'Q', 'Wave', 'N1', 'N2', 'N3', 'N4', 'Wave', 'N1', 'N2', 'N3', 'N4'}}, ...
        'ActionTimeMap', struct('EHold', 0.85, 'Q', 1.00, 'Wave', 2.30, 'N1', 0.30, 'N2', 0.32, 'N3', 0.38, 'N4', 0.45), ...
        'Actions', actions);

    if hydroReady
        spec.DefaultRotation = {{'EHold', 'Q', 'Wave', 'N1', 'N2', 'N3', 'N4', 'Wave', 'N1', 'N2', 'N3', 'N4'}};
    end

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Candace', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
