function build = customArtifact_Zibai()
    % Default DEF/crit build for Zibai's Geo constructs and charge finisher.
    build = struct( ...
        'Weapon', 'CloudhoofBlade', ...
        'WeaponATK', 608, ...
        'DEFBonus', 1.05, ...
        'FlatDEF', 260, ...
        'CritRate', 0.74, ...
        'CritDMG', 2.08, ...
        'GeoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 60, ...
        'ResShred', 0.00 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Zibai', 'artifacts_Zibai.csv');
    writetable(struct2table(build), outputPath);
end
