function build = customArtifact_Varka()
    % Default Varka build oriented around anemo claymore carry output.
    build = struct( ...
        'Weapon', 'Beacon of the Reed Sea', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.331, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.94, ...
        'FlatATK', 311, ...
        'EM', 100, ...
        'ER', 1.15, ...
        'CritRate', 0.80, ...
        'CritDMG', 2.04, ...
        'AnemoDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.18, ...
        'SkillDMGBonus', 0.22, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'ViridescentVenerer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Varka', 'artifacts_Varka.csv');
    if exist(fileparts(outputPath), 'dir') ~= 7
        mkdir(fileparts(outputPath));
    end
    writetable(struct2table(build), outputPath);
end
