function [totalDMG, dps, breakdown, rotationTime] = simulateKachinaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Kachina medium-detail simulator emphasizing drill/support geo hits.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Kachina', 'rotation_Kachina.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Kachina', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "DrillDEF", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetSkillActiveTime', 18.0, 'PostSetStacks', 1, ...
        'Note', "Turbo drill deploy");
    actions.Drill = struct('TalentGroup', "Skill", 'Param', "TickDEF", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PerStackMultiplier', 0.14, 'SkillWindowMultiplier', 0.06, ...
        'PostAddStacks', 1, 'PostMaxStacks', 3, 'C1DamageBonus', 0.08, 'Note', "Drill support hit");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "BurstDEF", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetBurstActiveTime', 10.0, 'C2CritRateBonus', 0.08, ...
        'Note', "Burst impact");
    actions.Quake = struct('TalentGroup', "Burst", 'Param', "QuakeDEF", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'BurstWindowMultiplier', 0.10, 'C6CritDMGBonus', 0.28, 'Note', "Burst quake");

    spec = struct( ...
        'Element', "Geo", ...
        'ScalingMode', "DEF", ...
        'DefaultActionTime', 0.9, ...
        'ActionTimeMap', struct('E', 0.60, 'Drill', 1.20, 'Q', 1.05, 'Quake', 1.10), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Kachina', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
