function build = customArtifact_Dehya()
    % Default Dehya build balancing HP-backed burst punches and off-field field damage.
    build = struct( ...
        'Weapon', '苇海信标', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.331, ...
        'WeaponRefinement', 1, ...
        'HPBonus', 0.72, ...
        'FlatHP', 4780, ...
        'AtkBonus', 0.74, ...
        'FlatATK', 311, ...
        'ER', 1.50, ...
        'EM', 80, ...
        'CritRate', 0.74, ...
        'CritDMG', 1.95, ...
        'PyroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.24, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'VourukashasGlow', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Dehya', 'artifacts_Dehya.csv');
    writetable(struct2table(build), outputPath);
end
