function build = customArtifact_Skirk()
    % 丝柯克默认构筑。
    % 该函数同时服务于单角色入口和统一配队入口，返回的结构体会被
    % 同步写回 CSV，便于你在脚本和表格之间保持同一套默认面板。
    build = struct( ...
        'Weapon', 'Azurelight', ...
        'WeaponATK', 674, ...
        'AtkBonus', 0.76, ...
        'FlatATK', 311, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.05, ...
        'CryoDMGBonus', 0.616, ...
        'NormalDMGBonus', 0.40, ...
        'SkillDMGBonus', 0.15, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'EM', 40, ...
        'ArtifactSet1', 'BlizzardStrayer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1 ...
    );

    % 将默认构筑回写到 data 目录，方便人工检查或二次修改。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Skirk', 'artifacts_Skirk.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
