function [totalDMG, dps, breakdown, rotationTime, audit] = simulateEmilieDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Emilie simulator emphasizing Lumidouce Case uptime and thorn procs.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Emilie', 'rotation_Emilie.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Emilie', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetSkillActiveTime', 22.0, 'Note', "Fragrance Extraction");
    actions.CaseHit = struct('TalentGroup', "Skill", 'Param', "Level2LumidouceCaseAttackDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'SkillWindowMultiplier', 0.08, 'C1DamageBonus', 0.08, 'Note', "Case attack");
    actions.Thorn = struct('TalentGroup', "Skill", 'Param', "SpiritbreathThornDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'Note', "Spiritbreath thorn");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "Level3LumidouceCaseAttackDMG", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetBurstActiveTime', 2.8, 'C2CritRateBonus', 0.10, 'C6CritDMGBonus', 0.30, ...
        'Note', "Aromatic Explication");

    spec = struct( ...
        'Element', "Dendro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.9, ...
        'DefaultRotation', {{'E', 'CaseHit', 'CaseHit', 'CaseHit', 'CaseHit', 'Q', 'Thorn', 'Thorn'}}, ...
        'ActionTimeMap', struct('E', 0.55, 'CaseHit', 3.20, 'Q', 1.05, 'Thorn', 2.80), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Emilie', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

