function [totalDMG, dps, breakdown, rotationTime] = simulateEmilieDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Emilie medium-detail simulator emphasizing off-field lumidouce hits.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Emilie', 'rotation_Emilie.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Emilie', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillATK", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetSkillActiveTime', 22.0, 'PostSetStacks', 1, ...
        'Note', "Lumidouce case deploy");
    actions.CaseHit = struct('TalentGroup', "Skill", 'Param', "CaseHitATK", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PerStackMultiplier', 0.16, 'SkillWindowMultiplier', 0.08, ...
        'PostAddStacks', 1, 'PostMaxStacks', 3, 'C1DamageBonus', 0.08, 'Note', "Case coordinated bloom");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "BurstATK", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetBurstActiveTime', 12.0, 'PostSetStacks', 2, ...
        'C2CritRateBonus', 0.10, 'Note', "Burst lantern");
    actions.BurstHit = struct('TalentGroup', "Burst", 'Param', "BurstHitATK", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'PerStackMultiplier', 0.12, 'BurstWindowMultiplier', 0.10, ...
        'C6CritDMGBonus', 0.30, 'Note', "Burst follow-up");

    spec = struct( ...
        'Element', "Dendro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.9, ...
        'ActionTimeMap', struct('E', 0.60, 'CaseHit', 1.30, 'Q', 1.15, 'BurstHit', 1.20), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Emilie', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
