function build = customArtifact_Nahida()
    % Default Nahida build emphasizing EM-scaling Tri-Karma damage.
    build = struct( ...
        'Weapon', 'AThousandFloatingDreams', ...
        'WeaponATK', 542, ...
        'EM', 780, ...
        'CritRate', 0.55, ...
        'CritDMG', 1.50, ...
        'DendroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.10, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'DeepwoodMemories', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Nahida', 'artifacts_Nahida.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
