function build = customArtifact_Wriothesley()
    % Default Wriothesley build for enhanced Cryo normal/charged stringing.
    build = struct( ...
        'Weapon', '金流监督', ...
        'WeaponATK', 674, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.221, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.92, ...
        'FlatATK', 311, ...
        'ER', 1.15, ...
        'EM', 40, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.30, ...
        'CryoDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.20, ...
        'ChargedDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.18, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'MarechausseeHunter', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Wriothesley', 'artifacts_Wriothesley.csv');
    writetable(struct2table(build), outputPath);
end
