function [totalDMG, dps, breakdown, rotationTime, audit] = simulateWriothesleyDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Wriothesley high-detail simulator.
    % 重点：
    % - Chilling Penalty 的普攻 / 重击 / 星超导分支
    % - Prosecution Edict 层数对 ATK 的动态提升
    % - C1 / C2 / C6 的分支倍率与追加伤害
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Wriothesley', 'rotation_Wriothesley.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Wriothesley', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Wriothesley', 'talents_Wriothesley.csv');
    talent = readtable(talentPath);

    normalLevel = talentLevel + 3 * double(constellation >= 3);
    skillLevel = talentLevel;
    burstLevel = talentLevel + 3 * double(constellation >= 5);

    stellarConductReady = logical(getFieldOrDefault(teamContext, 'StellarConductEnabled', false));
    meltReady = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1;

    enhancedMultiplier = getTalentValue(talent, 'Skill', 'EnhancedRepellingFistDMG', skillLevel);
    p2AtkBonus = 0.06;
    normalCritRateBonus = 0.10 * double(constellation >= 6 && stellarConductReady);
    normalCritDMGBonus = 0.80 * double(constellation >= 6 && stellarConductReady);
    chargedCritRateBonus = 0.10 * double(constellation >= 6);
    chargedCritDMGBonus = 0.80 * double(constellation >= 6);
    stellarTaggedBonus = getFieldOrDefault(teamContext, 'StellarConductTaggedDMGBonus', 0) + 0.30 * double(stellarConductReady);

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "EnhancedRepellingFistDMG", ...
        'MVOverride', 0, ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'PostSetSkillActiveTime', 10.0, ...
        'PostSetStacks', 0, ...
        'PostAddStacks', 1, ...
        'PostMaxStacks', 5, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'Note', "Icefang Rush");

    actions.N1 = localMakeEnhancedNormalAction('x1HitDMG', "Enhanced normal 1", normalLevel, enhancedMultiplier, meltReady, normalCritRateBonus, normalCritDMGBonus, p2AtkBonus, 1.00);
    actions.N2 = localMakeEnhancedNormalAction('x2HitDMG', "Enhanced normal 2", normalLevel, enhancedMultiplier, meltReady, normalCritRateBonus, normalCritDMGBonus, p2AtkBonus, 1.00);
    actions.N3 = localMakeEnhancedNormalAction('x3HitDMG', "Enhanced normal 3", normalLevel, enhancedMultiplier, meltReady, normalCritRateBonus, normalCritDMGBonus, p2AtkBonus, 1.00);
    actions.N4 = localMakeEnhancedNormalAction('x4HitDMG', "Enhanced normal 4", normalLevel, enhancedMultiplier, meltReady, normalCritRateBonus, normalCritDMGBonus, p2AtkBonus, 1.00);
    actions.N5 = localMakeEnhancedNormalAction('x5HitDMG', "Enhanced normal 5", normalLevel, enhancedMultiplier, meltReady, normalCritRateBonus, normalCritDMGBonus, p2AtkBonus, 1.00);
    if constellation >= 2 && ~stellarConductReady
        actions.N1.MinStacksMultiplierThreshold = 5;
        actions.N2.MinStacksMultiplierThreshold = 5;
        actions.N3.MinStacksMultiplierThreshold = 5;
        actions.N4.MinStacksMultiplierThreshold = 5;
        actions.N5.MinStacksMultiplierThreshold = 5;
        actions.N1.MinStacksMultiplierBonus = 0.25;
        actions.N2.MinStacksMultiplierBonus = 0.25;
        actions.N3.MinStacksMultiplierBonus = 0.25;
        actions.N4.MinStacksMultiplierBonus = 0.25;
        actions.N5.MinStacksMultiplierBonus = 0.25;
    end

    if constellation >= 2
        actions.N1C2 = localMakeEnhancedNormalAction('x1HitDMG', "C2 enhanced normal 1", normalLevel, enhancedMultiplier, meltReady, normalCritRateBonus, normalCritDMGBonus, p2AtkBonus, 1.00);
        actions.N2C2 = localMakeEnhancedNormalAction('x2HitDMG', "C2 enhanced normal 2", normalLevel, enhancedMultiplier, meltReady, normalCritRateBonus, normalCritDMGBonus, p2AtkBonus, 1.00);
        actions.N3C2 = localMakeEnhancedNormalAction('x3HitDMG', "C2 enhanced normal 3", normalLevel, enhancedMultiplier, meltReady, normalCritRateBonus, normalCritDMGBonus, p2AtkBonus, 1.00);
        actions.N4C2 = localMakeEnhancedNormalAction('x4HitDMG', "C2 enhanced normal 4", normalLevel, enhancedMultiplier, meltReady, normalCritRateBonus, normalCritDMGBonus, p2AtkBonus, 1.00);
        actions.N5C2 = localMakeEnhancedNormalAction('x5HitDMG', "C2 enhanced normal 5", normalLevel, enhancedMultiplier, meltReady, normalCritRateBonus, normalCritDMGBonus, p2AtkBonus, 1.00);
        actions.N1C2.MinStacksMultiplierThreshold = 5;
        actions.N2C2.MinStacksMultiplierThreshold = 5;
        actions.N3C2.MinStacksMultiplierThreshold = 5;
        actions.N4C2.MinStacksMultiplierThreshold = 5;
        actions.N5C2.MinStacksMultiplierThreshold = 5;
        actions.N1C2.MinStacksMultiplierBonus = 0.25;
        actions.N2C2.MinStacksMultiplierBonus = 0.25;
        actions.N3C2.MinStacksMultiplierBonus = 0.25;
        actions.N4C2.MinStacksMultiplierBonus = 0.25;
        actions.N5C2.MinStacksMultiplierBonus = 0.25;
    end

    actions.N3Stellar = localMakeStellarFollowUp('x3HitDMG', "N3 Stellar follow-up", normalLevel, enhancedMultiplier * 0.40, stellarTaggedBonus, p2AtkBonus, "Normal");
    actions.N5Stellar = localMakeStellarFollowUp('x5HitDMG', "N5 Stellar follow-up", normalLevel, enhancedMultiplier * 0.60, stellarTaggedBonus, p2AtkBonus, "Normal");
    actions.N5StellarBuffed = localMakeStellarFollowUp('x5HitDMG', "C1-buffed N5 Stellar follow-up", normalLevel, enhancedMultiplier * 0.60, stellarTaggedBonus + 0.50 * double(constellation >= 1), p2AtkBonus, "Normal");
    if constellation >= 2 && stellarConductReady
        actions.N3Stellar.MinStacksMultiplierThreshold = 5;
        actions.N5Stellar.MinStacksMultiplierThreshold = 5;
        actions.N5StellarBuffed.MinStacksMultiplierThreshold = 5;
        actions.N3Stellar.MinStacksMultiplierBonus = enhancedMultiplier * 0.20;
        actions.N5Stellar.MinStacksMultiplierBonus = enhancedMultiplier * 0.30;
        actions.N5StellarBuffed.MinStacksMultiplierBonus = enhancedMultiplier * 0.30;
    end
    if constellation >= 2
        actions.N3StellarC2 = localMakeStellarFollowUp('x3HitDMG', "C2 enhanced N3 Stellar follow-up", normalLevel, enhancedMultiplier * 0.40, stellarTaggedBonus, p2AtkBonus, "Normal");
        actions.N5StellarC2 = localMakeStellarFollowUp('x5HitDMG', "C2 enhanced N5 Stellar follow-up", normalLevel, enhancedMultiplier * 0.60, stellarTaggedBonus, p2AtkBonus, "Normal");
        actions.N5StellarBuffedC2 = localMakeStellarFollowUp('x5HitDMG', "C2 / C1 enhanced N5 Stellar follow-up", normalLevel, enhancedMultiplier * 0.60, stellarTaggedBonus + 0.50 * double(constellation >= 1), p2AtkBonus, "Normal");
        actions.N3StellarC2.MinStacksMultiplierThreshold = 5;
        actions.N5StellarC2.MinStacksMultiplierThreshold = 5;
        actions.N5StellarBuffedC2.MinStacksMultiplierThreshold = 5;
        actions.N3StellarC2.MinStacksMultiplierBonus = enhancedMultiplier * 0.20;
        actions.N5StellarC2.MinStacksMultiplierBonus = enhancedMultiplier * 0.30;
        actions.N5StellarBuffedC2.MinStacksMultiplierBonus = enhancedMultiplier * 0.30;
    end

    actions.Rebuke = localMakeChargedAction('ChargedAttackDMG', "Rebuke: Vaulting Fist", normalLevel, 1.50 + 1.50 * double(constellation >= 1), meltReady, chargedCritRateBonus, chargedCritDMGBonus, p2AtkBonus, 0.0, "Normal");
    actions.Luster = localMakeChargedAction('ChargedAttackDMG', "Luster: Vaulting Fist", normalLevel, 1.00, meltReady, chargedCritRateBonus, chargedCritDMGBonus, p2AtkBonus, 0.0, "Normal");
    actions.LusterBuffed = localMakeChargedAction('ChargedAttackDMG', "C1-buffed Luster: Vaulting Fist", normalLevel, 1.00, meltReady, chargedCritRateBonus, chargedCritDMGBonus, p2AtkBonus, 0.50 * double(constellation >= 1), "Normal");

    if constellation >= 2 && ~stellarConductReady
        actions.RebukeC2 = localMakeChargedAction('ChargedAttackDMG', "C2 enhanced Rebuke: Vaulting Fist", normalLevel, 1.50 + 1.50 * double(constellation >= 1), meltReady, chargedCritRateBonus, chargedCritDMGBonus, p2AtkBonus, 0.0, "Normal");
        actions.RebukeC2.MinStacksMultiplierThreshold = 5;
        actions.RebukeC2.MinStacksMultiplierBonus = 0.30;
    end

    actions.LusterStellar = localMakeStellarFollowUp('ChargedAttackDMG', "Luster Stellar follow-up", normalLevel, 1.00, stellarTaggedBonus, p2AtkBonus, "Charged");
    actions.LusterStellarBuffed = localMakeStellarFollowUp('ChargedAttackDMG', "C1-buffed Luster Stellar follow-up", normalLevel, 1.00, stellarTaggedBonus + 0.50 * double(constellation >= 1), p2AtkBonus, "Charged");
    if constellation >= 2 && stellarConductReady
        actions.LusterStellar.MinStacksMultiplierThreshold = 5;
        actions.LusterStellarBuffed.MinStacksMultiplierThreshold = 5;
        actions.LusterStellar.MinStacksMultiplierBonus = 0.50;
        actions.LusterStellarBuffed.MinStacksMultiplierBonus = 0.50;
    end
    if constellation >= 2 && stellarConductReady
        actions.LusterStellarC2 = localMakeStellarFollowUp('ChargedAttackDMG', "C2 enhanced Luster Stellar follow-up", normalLevel, 1.00, stellarTaggedBonus, p2AtkBonus, "Charged");
        actions.LusterStellarBuffedC2 = localMakeStellarFollowUp('ChargedAttackDMG', "C2 / C1 enhanced Luster Stellar follow-up", normalLevel, 1.00, stellarTaggedBonus + 0.50 * double(constellation >= 1), p2AtkBonus, "Charged");
        actions.LusterStellarC2.MinStacksMultiplierThreshold = 5;
        actions.LusterStellarBuffedC2.MinStacksMultiplierThreshold = 5;
        actions.LusterStellarC2.MinStacksMultiplierBonus = 0.50;
        actions.LusterStellarBuffedC2.MinStacksMultiplierBonus = 0.50;
    end

    actions.C6Icicle = localMakeC6IcicleAction('ChargedAttackDMG', "C6 Rebuke icicle", normalLevel, chargedCritRateBonus, chargedCritDMGBonus, p2AtkBonus, 1.00);
    actions.N5Icicle = localMakeStellarFollowUp('x5HitDMG', "C6 N5 stellar icicle", normalLevel, enhancedMultiplier * 0.40, stellarTaggedBonus, p2AtkBonus, "Normal");
    actions.LusterIcicle = localMakeStellarFollowUp('ChargedAttackDMG', "C6 Luster stellar icicle", normalLevel, 0.40, stellarTaggedBonus, p2AtkBonus, "Charged");

    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'PerStackDamageBonus', 0.40 * double(constellation >= 2), ...
        'PerStackATKBonus', p2AtkBonus, ...
        'ApplyGauge', 1.0, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'LunarisAttackName', "ElementalBurst_Bullet", ...
        'LunarisDamageParam', "Wriothesley_ElementalBurst_Damage", ...
        'Note', "Darkgold Wolfbite");
    actions.Blade = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "SurgingBladeDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'PerStackDamageBonus', 0.40 * double(constellation >= 2), ...
        'PerStackATKBonus', p2AtkBonus, ...
        'HitCount', 5, ...
        'ApplyGauge', 1.0, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'LunarisAttackName', "ElementalBurst_Bullet", ...
        'LunarisDamageParam', "Wriothesley_ElementalBurst_Damage", ...
        'Note', "Surging blades");

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Pyro", ...
        'DefaultActionTime', 0.55, ...
        'DefaultRotation', {localBuildDefaultRotation(stellarConductReady, constellation)}, ...
        'ActionTimeMap', localBuildActionTimeMap(constellation, stellarConductReady), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Wriothesley', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function action = localMakeEnhancedNormalAction(paramName, note, talentLevel, baseMultiplier, meltReady, critRateBonus, critDMGBonus, atkBonus, baseActionBonus)
    action = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', talentLevel, ...
        'Param', paramName, ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', baseMultiplier, ...
        'PerStackATKBonus', atkBonus, ...
        'BaseActionDamageBonus', baseActionBonus, ...
        'ApplyGauge', 1.0, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'CritRateBonus', critRateBonus, ...
        'CritDMGBonus', critDMGBonus, ...
        'PostAddStacks', 1, ...
        'PostMaxStacks', 5, ...
        'LunarisAttackName', "ExtraAttack_Strike", ...
        'LunarisDamageParam', "Wriothesley_ExtraAttack_Damage_AtkRatio", ...
        'Note', note);
end

function action = localMakeChargedAction(paramName, note, talentLevel, baseMultiplier, meltReady, critRateBonus, critDMGBonus, atkBonus, baseActionBonus, damageField)
    action = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', talentLevel, ...
        'Param', paramName, ...
        'DamageField', damageField, ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', baseMultiplier, ...
        'PerStackATKBonus', atkBonus, ...
        'BaseActionDamageBonus', baseActionBonus, ...
        'ApplyGauge', 1.0, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'CritRateBonus', critRateBonus, ...
        'CritDMGBonus', critDMGBonus, ...
        'PostAddStacks', 1, ...
        'PostMaxStacks', 5, ...
        'LunarisAttackName', "NormalAttack_Damage_Handler", ...
        'LunarisDamageParam', "ChargedAttackDMG", ...
        'Note', note);
end

function action = localMakeStellarFollowUp(paramName, note, talentLevel, baseMultiplier, damageBonus, atkBonus, damageField)
    action = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', talentLevel, ...
        'Param', paramName, ...
        'DamageField', damageField, ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', baseMultiplier, ...
        'PerStackATKBonus', atkBonus, ...
        'BaseActionDamageBonus', damageBonus, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'Note', note);
end

function action = localMakeC6IcicleAction(paramName, note, talentLevel, critRateBonus, critDMGBonus, atkBonus, baseMultiplier)
    action = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', talentLevel, ...
        'Param', paramName, ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', baseMultiplier, ...
        'PerStackATKBonus', atkBonus, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'CritRateBonus', critRateBonus, ...
        'CritDMGBonus', critDMGBonus, ...
        'LunarisAttackName', "NormalAttack_Damage_Handler", ...
        'LunarisDamageParam', "ChargedAttackDMG", ...
        'Note', note);
end

function rotation = localBuildDefaultRotation(stellarConductReady, constellation)
    if stellarConductReady
        if constellation >= 2
            n3Stellar = 'N3StellarC2';
            n5Stellar = 'N5StellarC2';
            n5StellarBuffed = 'N5StellarBuffedC2';
            lusterStellar = 'LusterStellarBuffedC2';
        else
            n3Stellar = 'N3Stellar';
            n5Stellar = 'N5Stellar';
            n5StellarBuffed = 'N5StellarBuffed';
            lusterStellar = 'LusterStellarBuffed';
        end
        if constellation >= 1
            lusterMain = 'LusterBuffed';
        else
            lusterMain = 'Luster';
        end

        rotation = {'E', 'N1', 'N2', 'N3', n3Stellar, 'N4', 'N5'};
        if constellation >= 6
            rotation{end + 1} = 'N5Icicle';
        end
        rotation = [rotation, {n5Stellar, lusterMain}];
        if constellation >= 6
            rotation{end + 1} = 'LusterIcicle';
        end
        rotation = [rotation, {lusterStellar, 'N1', 'N2', 'N3', n3Stellar, 'N4', 'N5'}];
        if constellation >= 6
            rotation{end + 1} = 'N5Icicle';
        end
        rotation = [rotation, {n5StellarBuffed, lusterMain}];
        if constellation >= 6
            rotation{end + 1} = 'LusterIcicle';
        end
        rotation = [rotation, {lusterStellar, 'Q', 'Blade'}];
        return;
    end

    if constellation >= 2
        secondCycleNormals = {'N1C2', 'N2C2', 'N3C2', 'N4C2', 'N5C2'};
        rebukeAction = 'RebukeC2';
    else
        secondCycleNormals = {'N1', 'N2', 'N3', 'N4', 'N5'};
        rebukeAction = 'Rebuke';
    end

    rotation = {'E', 'N1', 'N2', 'N3', 'N4', 'N5', rebukeAction};
    if constellation >= 6
        rotation{end + 1} = 'C6Icicle';
    end
    rotation = [rotation, secondCycleNormals, {rebukeAction}];
    if constellation >= 6
        rotation{end + 1} = 'C6Icicle';
    end
    rotation = [rotation, {'Q', 'Blade'}];
end

function timeMap = localBuildActionTimeMap(constellation, stellarConductReady)
    timeMap = struct();
    timeMap.E = 0.60;
    timeMap.N1 = 0.35;
    timeMap.N2 = 0.35;
    timeMap.N3 = 0.40;
    timeMap.N4 = 0.45;
    timeMap.N5 = 0.55;
    timeMap.Rebuke = 0.80;
    timeMap.RebukeC2 = 0.80;
    timeMap.Luster = 0.80;
    timeMap.LusterBuffed = 0.80;
    timeMap.Q = 1.10;
    timeMap.Blade = 0.35;
    timeMap.C6Icicle = 0.01;
    timeMap.N5Icicle = 0.01;
    timeMap.LusterIcicle = 0.01;

    timeMap.N1C2 = 0.35;
    timeMap.N2C2 = 0.35;
    timeMap.N3C2 = 0.40;
    timeMap.N4C2 = 0.45;
    timeMap.N5C2 = 0.55;

    timeMap.N3Stellar = 0.01;
    timeMap.N5Stellar = 0.01;
    timeMap.N5StellarBuffed = 0.01;
    timeMap.LusterStellar = 0.01;
    timeMap.LusterStellarBuffed = 0.01;

    if constellation >= 2 && stellarConductReady
        timeMap.N3StellarC2 = 0.01;
        timeMap.N5StellarC2 = 0.01;
        timeMap.N5StellarBuffedC2 = 0.01;
        timeMap.LusterStellarC2 = 0.01;
        timeMap.LusterStellarBuffedC2 = 0.01;
    end
end
