function [totalDMG, dps, breakdown, rotationTime] = simulateWriothesleyDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Wriothesley simulator modeling enhanced Cryo normals, Rebuke charged punches, and burst follow-up blades.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Wriothesley', 'rotation_Wriothesley.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Wriothesley', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Wriothesley', 'talents_Wriothesley.csv');
    talent = readtable(talentPath);
    skillLevel = talentLevel + 3 * double(constellation >= 3);
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    enhancedMultiplier = getTalentValue(talent, 'Skill', 'EnhancedRepellingFistDMG', skillLevel);
    burstHitMV = getTalentValue(talent, 'Burst', 'SkillDMG', burstLevel);
    rebukeMultiplier = 1.50 + 1.50 * double(constellation >= 1);
    c2BurstBonus = 2.00 * double(constellation >= 2);

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "EnhancedRepellingFistDMG", ...
        'DamageField', "SkillDMGBonus", 'PostSetSkillActiveTime', 10.0, 'Note', "Icefang Rush");
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', enhancedMultiplier, 'Note', "Enhanced normal 1");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', enhancedMultiplier, 'Note', "Enhanced normal 2");
    actions.N3 = struct('TalentGroup', "Normal", 'Param', "x3HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', enhancedMultiplier, 'Note', "Enhanced normal 3");
    actions.N4 = struct('TalentGroup', "Normal", 'Param', "x4HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', enhancedMultiplier, 'Note', "Enhanced normal 4");
    actions.N5 = struct('TalentGroup', "Normal", 'Param', "x5HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', enhancedMultiplier, 'Note', "Enhanced normal 5");
    actions.Rebuke = struct('TalentGroup', "Normal", 'Param', "ChargedAttackDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', rebukeMultiplier, 'CritRateBonus', 0.10 * double(constellation >= 6), ...
        'CritDMGBonus', 0.80 * double(constellation >= 6), 'Note', "Rebuke: Vaulting Fist");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'MVOverride', burstHitMV, ...
        'DamageField', "BurstDMGBonus", 'ActionElement', "Cryo", 'HitCount', 1, ...
        'FlatDamageBonus', c2BurstBonus, 'Note', "Darkgold Wolfbite");
    actions.Blade = struct('TalentGroup', "Burst", 'Param', "SurgingBladeDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", 'HitCount', 5, 'FlatDamageBonus', c2BurstBonus, 'Note', "Surging blades");
    actions.C6Icicle = struct('TalentGroup', "Normal", 'Param', "ChargedAttackDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 2, 'Note', "C6 icicles");

    defaultRotation = {'E', 'N1', 'N2', 'N3', 'N4', 'N5', 'Rebuke', 'N1', 'N2', 'N3', 'N4', 'N5', 'Rebuke', 'Q', 'Blade'};
    if constellation >= 6
        defaultRotation = {'E', 'N1', 'N2', 'N3', 'N4', 'N5', 'Rebuke', 'C6Icicle', 'N1', 'N2', 'N3', 'N4', 'N5', 'Rebuke', 'C6Icicle', 'Q', 'Blade'};
    end

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.55, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct('E', 0.60, 'N1', 0.35, 'N2', 0.35, 'N3', 0.40, 'N4', 0.45, 'N5', 0.55, ...
            'Rebuke', 0.80, 'Q', 1.10, 'Blade', 0.35, 'C6Icicle', 0.10), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Wriothesley', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
