function build = customArtifact_ShikanoinHeizou()
    % Default Heizou build for skill nuke and burst follow-up.
    build = struct( ...
        'Weapon', 'TulaytullahsRemembrance', ...
        'WeaponATK', 674, ...
        'WeaponSubStatType', 'CD', ...
        'WeaponSubStatValue', 0.441, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.46, ...
        'FlatATK', 150, ...
        'EM', 180, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.10, ...
        'AnemoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.22, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'ViridescentVenerer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'ShikanoinHeizou', 'artifacts_ShikanoinHeizou.csv');
    writetable(struct2table(build), outputPath);
end
