function [totalDMG, dps, breakdown, rotationTime, audit] = simulateRaidenShogunDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Raiden Shogun 高精度反应元数据模拟。
    % 这里先聚焦统一反应引擎最敏感的部分：
    % 1. E 起手命中与协同雷击拆分，并给出真实 Gauge / ICD；
    % 2. Q 梦想一刀与梦想一心期间的普攻 / 重击 / 下落拆分；
    % 3. Burst 期普攻按 Burst 伤害窗结算，并显式写入 Lunaris 攻击名。
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'RaidenShogun', 'rotation_RaidenShogun.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'RaidenShogun', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    burstResolveStacks = localResolveDefaultResolveStacks(teamContext, constellation);
    burstTalentLevel = talentLevel + 3 * double(constellation >= 5);
    resolveBonusMV = getTalentValue(localReadTalentTable(), 'Burst', 'ResolveBonus', burstTalentLevel) * burstResolveStacks;

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), ...
        'LunarisAttackName', "SkillObj_ElementalArt_EyeBoom", ...
        'LunarisDamageParam', "ElementalArt_Attack", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'Note', "Transcendence: Baleful Omen cast");
    actions.Eye = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "CoordinatedATKDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', 12, ...
        'HitTimeline', [0.9, 0.9 * ones(1, 11)], ...
        'AllowCatalyze', double(aggravateReady), ...
        'LunarisAttackName', "Elf", ...
        'LunarisDamageParam', "Elf_Attack|Elf_RemoteAttackRatio|MUL", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'Note', "Eye of Stormy Judgment coordinated attacks");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "MusouNoHitotachiBaseDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'FlatMVBonus', resolveBonusMV, ...
        'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), ...
        'PostSetBurstActiveTime', getTalentValue(localReadTalentTable(), 'Burst', 'MusouIsshinDuration', burstTalentLevel), ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "ElementalBurst_BaseDamage|BurstDamageDelta|ADD", ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'Note', "Secret Art: Musou Shinsetsu");
    actions.B1 = localBurstNormalAction("x1HitDMG", "FallingAnthem", "FallingAnthem_Normal_Rank_1_Katana_Damage|KatanaDamageDelta|ADD", 1.0, "Burst normal 1", aggravateReady);
    actions.B2 = localBurstNormalAction("x2HitDMG", "FallingAnthem", "FallingAnthem_Normal_Rank_2_Katana_Damage|KatanaDamageDelta|ADD", 1.0, "Burst normal 2", aggravateReady);
    actions.B3 = localBurstNormalAction("x3HitDMG", "FallingAnthem", "FallingAnthem_Normal_Loop_Katana_Damage|KatanaDamageDelta|ADD", 0.0, "Burst normal 3", aggravateReady);
    actions.B4 = localBurstNormalAction("x4HitDMG", "FallingAnthem", "FallingAnthem_Normal_Loop_Katana_Damage|KatanaDamageDelta|ADD", 0.0, "Burst normal 4", aggravateReady);
    actions.B5 = localBurstNormalAction("x5HitDMG", "FallingAnthem", "FallingAnthem_Normal_Loop_Katana_Damage|KatanaDamageDelta|ADD", 0.0, "Burst normal 5", aggravateReady);
    actions.BCA = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), ...
        'LunarisAttackName', "FallingAnthem", ...
        'LunarisDamageParam', "FallingAnthem_Normal_Loop_Katana_Damage|KatanaDamageDelta|ADD", ...
        'ApplyGauge', 0.0, ...
        'ICDRule', "Independent", ...
        'Note', "Burst charged attack");
    actions.BPlunge = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "LowHighPlungeDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'ActionScalingMode', "ATK", ...
        'AllowCatalyze', 0, ...
        'LunarisAttackName', "FallingAnthem", ...
        'LunarisDamageParam', "FallingAnthem_Normal_Rank_2_Katana_Damage|KatanaDamageDelta|ADD", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'Note', "Burst high plunge");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.55, ...
        'DefaultRotation', {{'E', 'Q', 'B1', 'B2', 'B3', 'B4', 'B5', 'BCA', 'B1', 'B2', 'B3', 'B4', 'B5', 'Eye'}}, ...
        'ActionTimeMap', struct( ...
            'E', 0.70, ...
            'Eye', 10.80, ...
            'Q', 1.10, ...
            'B1', 0.24, ...
            'B2', 0.24, ...
            'B3', 0.30, ...
            'B4', 0.34, ...
            'B5', 0.42, ...
            'BCA', 0.70, ...
            'BPlunge', 0.90), ...
        'Actions', actions);

    if constellation >= 2
        build = applyStructOverrides(build, struct('EnemyDefReduct', ...
            getFieldOrDefault(build, 'EnemyDefReduct', 0) + 0.60));
    end

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'RaidenShogun', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function action = localBurstNormalAction(paramName, attackName, damageParam, gauge, note, aggravateReady)
    action = struct( ...
        'TalentGroup', "Burst", ...
        'Param', string(paramName), ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), ...
        'LunarisAttackName', string(attackName), ...
        'LunarisDamageParam', string(damageParam), ...
        'ApplyGauge', double(gauge), ...
        'ICDRule', "Independent", ...
        'Note', string(note));
end

function resolveStacks = localResolveDefaultResolveStacks(teamContext, constellation)
    memberCount = getFieldOrDefault(teamContext, 'MemberCount', 1);
    memberConstellations = getFieldOrDefault(teamContext, 'MemberConstellations', 0);
    memberNames = string(getFieldOrDefault(teamContext, 'MemberNames', "RaidenShogun"));
    energyTemplate = [60 70 80 80];
    resolvePerEnergy = 0.19;
    if constellation >= 1
        resolvePerEnergy = resolvePerEnergy * 1.20;
    end

    resolveStacks = 0;
    for i = 1:min(memberCount, numel(energyTemplate))
        if memberNames(i) == "RaidenShogun"
            continue;
        end
        gainMultiplier = 1.0;
        if getCharacterElement(memberNames(i)) == "Electro"
            gainMultiplier = 1.8;
        end
        resolveStacks = resolveStacks + energyTemplate(i) * resolvePerEnergy * gainMultiplier;
    end
    resolveStacks = min(60, max(36, resolveStacks + 6 * double(any(memberConstellations >= 1))));
end

function talent = localReadTalentTable()
    persistent talentTable
    if isempty(talentTable)
        talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'RaidenShogun', 'talents_RaidenShogun.csv');
        talentTable = readtable(talentPath);
    end
    talent = talentTable;
end
