function build = customArtifact_Zibai()
    % 兹白默认构筑。
    % 默认面板以防御、双暴和岩伤为主，适配泉场与重击终结段。
    build = struct( ...
        'Weapon', 'CloudhoofBlade', ...
        'WeaponATK', 608, ...
        'DEFBonus', 1.05, ...
        'FlatDEF', 260, ...
        'CritRate', 0.74, ...
        'CritDMG', 2.08, ...
        'GeoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 60, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'HuskOfOpulentDreams', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1 ...
    );

    % 回写 CSV，供分析入口和统一入口共同使用。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Zibai', 'artifacts_Zibai.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
