function build = customArtifact_Kachina()
    % Default Kachina build focused on geo support skill damage and DEF.
    build = struct( ...
        'Weapon', 'FootprintOfTheRainbow', ...
        'WeaponATK', 565, ...
        'DEFBonus', 1.02, ...
        'FlatDEF', 180, ...
        'CritRate', 0.60, ...
        'CritDMG', 1.72, ...
        'GeoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.26, ...
        'BurstDMGBonus', 0.18, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'ScrollOfTheHeroOfCinderCity', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Kachina', 'artifacts_Kachina.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
