function [totalDMG, dps, breakdown, rotationTime] = simulateKachinaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Kachina simulator emphasizing Turbo Twirly uptime.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Kachina', 'rotation_Kachina.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Kachina', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "TurboTwirlyMountedDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetSkillActiveTime', 20.0, 'Note', "Turbo Twirly deploy");
    actions.Drill = struct('TalentGroup', "Skill", 'Param', "TurboTwirlyIndependentDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'C1DamageBonus', 0.08, 'Note', "Turbo Twirly hit");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetBurstActiveTime', 12.0, 'C2CritRateBonus', 0.08, 'C6CritDMGBonus', 0.28, ...
        'Note', "Time to Get Serious!");

    spec = struct( ...
        'Element', "Geo", ...
        'ScalingMode', "DEF", ...
        'DefaultActionTime', 0.9, ...
        'DefaultRotation', {{'E', 'Drill', 'Drill', 'Drill', 'Drill', 'Q'}}, ...
        'ActionTimeMap', struct('E', 0.55, 'Drill', 3.20, 'Q', 1.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Kachina', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
