function build = customArtifact_Nilou()
    % HP-oriented baseline build for Nilou's Hydro damage plus Bountiful
    % Core contribution in Hydro/Dendro teams.
    build = struct( ...
        'Weapon', 'KeyOfKhajNisut', ...
        'WeaponATK', 542, ...
        'HPBonus', 1.86, ...
        'FlatHP', 4780, ...
        'CritRate', 0.36, ...
        'CritDMG', 1.18, ...
        'HydroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 320, ...
        'ResShred', 0.00 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Nilou', 'artifacts_Nilou.csv');
    writetable(struct2table(build), outputPath);
end
