function build = customArtifact_Lauma()
    % EM-leaning default build for Lauma's Lunar-Bloom support profile.
    build = struct( ...
        'Weapon', 'MoonforestPrayer', ...
        'WeaponATK', 542, ...
        'AtkBonus', 0.18, ...
        'FlatATK', 120, ...
        'EM', 980, ...
        'CritRate', 0.34, ...
        'CritDMG', 0.88, ...
        'DendroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'HealingBonus', 0.00, ...
        'ResShred', 0.00 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Lauma', 'artifacts_Lauma.csv');
    writetable(struct2table(build), outputPath);
end
