function build = customArtifact_Lauma()
    % 菈乌玛默认构筑。
    % 当前默认面板偏向精通与草伤，服务月绽放辅助定位。
    build = struct( ...
        'Weapon', 'MoonforestPrayer', ...
        'WeaponATK', 542, ...
        'AtkBonus', 0.18, ...
        'FlatATK', 120, ...
        'EM', 980, ...
        'CritRate', 0.34, ...
        'CritDMG', 0.88, ...
        'DendroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'HealingBonus', 0.00, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'DeepwoodMemories', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1 ...
    );

    % 将默认构筑写回 CSV，方便后续直接从表格查看和微调。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Lauma', 'artifacts_Lauma.csv');
    writetable(struct2table(build), outputPath);
end
