function [totalDMG, dps, breakdown, rotationTime] = simulateKinichDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Kinich simulator emphasizing Scalespiker cannon loops and burst breaths.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Kinich', 'rotation_Kinich.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Kinich', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "LoopShotDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 0.00, 'PostSetSkillActiveTime', 10.0, 'Note', "Canopy Hunter");
    actions.Loop = struct('TalentGroup', "Skill", 'Param', "LoopShotDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'SkillWindowMultiplier', 0.10, 'C1DamageBonus', 0.10, 'Note', "Loop shot");
    actions.Cannon = struct('TalentGroup', "Skill", 'Param', "ScalespikerCannonDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'SkillWindowMultiplier', 0.12, 'C2CritRateBonus', 0.10, 'Note', "Scalespiker cannon");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'C6CritDMGBonus', 0.35, 'Note', "Burst cast");
    actions.Breath = struct('TalentGroup', "Burst", 'Param', "DragonBreathDMG", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'Note', "Dragon breath");

    spec = struct( ...
        'Element', "Dendro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.8, ...
        'DefaultRotation', {{'Q', 'Breath', 'Breath', 'E', 'Loop', 'Loop', 'Loop', 'Loop', 'Cannon'}}, ...
        'ActionTimeMap', struct('E', 0.35, 'Loop', 0.80, 'Cannon', 1.00, 'Q', 1.00, 'Breath', 1.60), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Kinich', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
