function build = customArtifact_Chiori()
    % Default Chiori build focused on geo doll damage and crit.
    build = struct( ...
        'Weapon', 'UrakuMisugiri', ...
        'WeaponATK', 542, ...
        'DEFBonus', 0.86, ...
        'FlatDEF', 160, ...
        'CritRate', 0.74, ...
        'CritDMG', 2.12, ...
        'GeoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.32, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'HuskOfOpulentDreams', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Chiori', 'artifacts_Chiori.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
