function [totalDMG, dps, breakdown, rotationTime, audit] = simulateGanyuDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Ganyu high-precision simulator for charged shots, bloom hits, skill
    % taunt bloom, burst icicles, and C1 Cryo RES shred / energy return.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Ganyu', 'rotation_Ganyu.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Ganyu', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talent = readtable(char(resolveCharacterDataFile('Ganyu', 'talents')));
    actions = struct();

    chargedCritBonus = 0.20;
    c1ResShred = 0.15 * double(constellation >= 1);
    c6Instant = double(constellation >= 6);
    c6FreeCharged = 0.0;

    actions.Charge1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "AimedShotChargeLevel1", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Bullet_ShootArrow_WithIce", ...
        'LunarisDamageParam', "DamageWithIce", ...
        'Note', "Level 1 aimed shot");
    actions.Frostflake = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "FrostflakeArrowDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'CritRateBonus', chargedCritBonus, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Bullet_ShootArrow_WithIce_BeforeFission", ...
        'LunarisDamageParam', "DamageWithIce_BeforeFission", ...
        'Note', "Frostflake arrow");
    actions.Bloom = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "FrostflakeArrowBloomDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'CritRateBonus', chargedCritBonus, ...
        'C1ExtraResShred', c1ResShred, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Bullet_ShootArrow_WithIce_AfterFission", ...
        'LunarisDamageParam', "DamageWithIce_AfterFission", ...
        'Note', "Frostflake bloom");
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "SkillObj_IceBreaker_Dummy", ...
        'LunarisDamageParam', "damage", ...
        'Note', "Trail of the Qilin cast");
    actions.EBloom = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "SkillObj_IceBreaker_Dummy_EndBoom", ...
        'LunarisDamageParam', "damage", ...
        'Note', "Ice Lotus bloom");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "IceShardDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', 12, ...
        'HitTimeline', [0.35, 0.35, 0.35, 0.35, 0.45, 0.45, 0.45, 0.45, 0.55, 0.55, 0.55, 0.55], ...
        'C1ExtraResShred', c1ResShred, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "3 hits / 2.5s", ...
        'LunarisAttackName', "Bullet_UnbreakableIce_Iceberg1", ...
        'LunarisDamageParam', "damage", ...
        'Note', "Celestial Shower icicles");
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'ICDRule', "Independent", ...
        'Note', "Fallback normal attack");

    if constellation >= 6
        c6FreeCharged = 1;
    end

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.85, ...
        'DefaultRotation', {{'E', 'EBloom', 'Charge1', 'Frostflake', 'Bloom', 'Charge1', 'Frostflake', 'Bloom', 'Q'}}, ...
        'ActionTimeMap', struct( ...
            'Charge1', 0.55, ...
            'Frostflake', 1.05, ...
            'Bloom', 0.10, ...
            'E', 0.70, ...
            'EBloom', 0.35, ...
            'Q', 1.05, ...
            'N1', 0.35), ...
        'Actions', actions);

    if c6FreeCharged > 0
        spec.DefaultRotation = {{'E', 'EBloom', 'Charge1', 'Frostflake', 'Bloom', 'Frostflake', 'Bloom', 'Q'}};
    end

    workBuild = build;
    workBuild.CryoDMGBonus = getFieldOrDefault(workBuild, 'CryoDMGBonus', 0) + 0.15 * double(constellation >= 4);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Ganyu', workBuild, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
