function [totalDMG, dps, breakdown, rotationTime, audit] = simulateYaeMikoDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Yae Miko simulator with triple-totem setup, EM passive, and burst detonation.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'YaeMiko', 'rotation_YaeMiko.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'YaeMiko', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    workBuild = build;
    skillLevel = talentLevel + 3 * double(constellation >= 3);
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    reactionReady = getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1 ...
        && getFieldOrDefault(teamContext, 'ElectroCount', 0) >= 1;
    stellarConductReady = logical(getFieldOrDefault(teamContext, 'StellarConductEnabled', false));
    if constellation >= 2
        workBuild.EM = getFieldOrDefault(workBuild, 'EM', 0) + 200;
    end
    emTotal = getFieldOrDefault(workBuild, 'EM', 0) + getFieldOrDefault(teamContext, 'EMBonus', 0);
    sakuraPassiveBonus = 0.0015 * emTotal;
    if constellation >= 4
        workBuild.ElectroDMGBonus = getFieldOrDefault(workBuild, 'ElectroDMGBonus', 0) + 0.20;
        workBuild.BurstDMGBonus = getFieldOrDefault(workBuild, 'BurstDMGBonus', 0) + 1.00;
    end

    totemLevelParam = "SesshouSakuraDMGLevel3";
    totemAttackName = "FoxTower_ThunderFall_Level3";
    totemDamageParam = "FoxTower_Damage_Level_3";
    if constellation >= 2
        totemLevelParam = "SesshouSakuraDMGLevel4";
        totemAttackName = "FoxTower_ThunderFall_Level4";
        totemDamageParam = "FoxTower_Damage_Level_4";
    end
    tickHitCount = 9;
    p4ProcCount = 5 * double(reactionReady);
    stellarTaggedBonus = getFieldOrDefault(teamContext, 'StellarConductTaggedDMGBonus', 0);

    actions = struct();
    actions.E1 = struct('TalentGroup', "Skill", 'TalentLevelOverride', skillLevel, 'Param', "SesshouSakuraDMGLevel1", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 0, 'AllowCatalyze', 0, 'Note', "Sesshou Sakura placement 1");
    actions.E2 = struct('TalentGroup', "Skill", 'TalentLevelOverride', skillLevel, 'Param', "SesshouSakuraDMGLevel2", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 0, 'AllowCatalyze', 0, 'Note', "Sesshou Sakura placement 2");
    actions.E3 = struct('TalentGroup', "Skill", 'TalentLevelOverride', skillLevel, 'Param', "SesshouSakuraDMGLevel3", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 0, 'AllowCatalyze', 0, 'Note', "Sesshou Sakura placement 3");
    actions.Tick = struct('TalentGroup', "Skill", 'TalentLevelOverride', skillLevel, 'Param', totemLevelParam, 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'HitCount', tickHitCount, 'BaseActionDamageBonus', sakuraPassiveBonus, ...
        'C6EnemyDefIgnore', 0.60, 'ApplyGauge', 1.0, 'ICDRule', "Independent", ...
        'LunarisAttackName', totemAttackName, 'LunarisDamageParam', totemDamageParam, ...
        'Note', "Sesshou Sakura ticks");
    actions.TickBuff = struct('TalentGroup', "Skill", 'TalentLevelOverride', skillLevel, 'Param', totemLevelParam, 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'MVOverride', 0, 'FlatDirectATKWeight', 0.80, ...
        'HitCount', p4ProcCount, 'ApplyGauge', 0.0, 'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'Note', "P4 enhanced Sesshou Sakura");
    actions.TickStellar = struct('TalentGroup', "Skill", 'TalentLevelOverride', skillLevel, 'Param', totemLevelParam, 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'MVOverride', 0, 'FlatDirectATKWeight', 1.25, ...
        'HitCount', p4ProcCount * double(stellarConductReady), 'ApplyGauge', 0.0, 'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'CritDMGBonus', 1.50 * double(constellation >= 6), ...
        'BaseActionDamageBonus', stellarTaggedBonus, ...
        'Note', "Radiance Stellar-Conduct follow-up");
    actions.Q = struct('TalentGroup', "Burst", 'TalentLevelOverride', burstLevel, 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'Note', "Great Secret Art");
    actions.Thunder = struct('TalentGroup', "Burst", 'TalentLevelOverride', burstLevel, 'Param', "TenkoThunderboltDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'HitCount', 3, 'Note', "Tenko Thunderbolt");
    actions.ResetE1 = struct('TalentGroup', "Skill", 'TalentLevelOverride', skillLevel, 'Param', "SesshouSakuraDMGLevel1", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 0, 'ApplyGauge', 1.0, 'ICDRule', "Independent", ...
        'LunarisAttackName', "Attack01_Bullet_Material", 'LunarisDamageParam', "Attack01_Damage", ...
        'Note', "Post-burst recast 1");
    actions.ResetE2 = struct('TalentGroup', "Skill", 'TalentLevelOverride', skillLevel, 'Param', "SesshouSakuraDMGLevel2", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 0, 'ApplyGauge', 1.0, 'ICDRule', "Independent", ...
        'LunarisAttackName', "Attack02_Bullet_Material", 'LunarisDamageParam', "Attack02_Damage", ...
        'Note', "Post-burst recast 2");
    actions.ResetE3 = struct('TalentGroup', "Skill", 'TalentLevelOverride', skillLevel, 'Param', "SesshouSakuraDMGLevel3", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 0, 'ApplyGauge', 1.0, 'ICDRule', "Independent", ...
        'LunarisAttackName', "Attack03_Bullet_Material", 'LunarisDamageParam', "Attack03_Damage", ...
        'Note', "Post-burst recast 3");

    defaultRotation = {'E1', 'E2', 'E3', 'Tick', 'Q', 'Thunder', 'ResetE1', 'ResetE2', 'ResetE3', 'Tick'};
    if reactionReady
        defaultRotation = {'E1', 'E2', 'E3', 'Tick', 'TickBuff', 'Q', 'Thunder', 'ResetE1', 'ResetE2', 'ResetE3', 'Tick', 'TickBuff'};
    end
    if stellarConductReady
        defaultRotation = [defaultRotation(1:4), {'TickStellar'}, defaultRotation(5:end-1), {'TickStellar'}, defaultRotation(end)];
    end

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.70, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct( ...
            'E1', 0.28, 'E2', 0.28, 'E3', 0.32, 'Tick', 12.60, ...
            'TickBuff', 0.01, 'TickStellar', 0.01, ...
            'Q', 1.18, 'Thunder', 0.45, 'ResetE1', 0.28, 'ResetE2', 0.28, 'ResetE3', 0.32), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'YaeMiko', workBuild, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

