function build = customArtifact_Wanderer()
    % Default Wanderer build focused on Windfavored normal strings.
    build = struct( ...
        'Weapon', 'TulaytullahsRemembrance', ...
        'WeaponATK', 674, ...
        'AtkBonus', 0.82, ...
        'FlatATK', 311, ...
        'CritRate', 0.78, ...
        'CritDMG', 2.20, ...
        'AnemoDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.30, ...
        'ChargedDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'DesertPavilionChronicle', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Wanderer', 'artifacts_Wanderer.csv');
    writetable(struct2table(build), outputPath);
end
