function build = customArtifact_Lynette()
    % Default Lynette build for general Anemo quickswap damage and VV support.
    build = struct( ...
        'Weapon', '苍古自由之誓', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'EM', ...
        'WeaponSubStatValue', 198.45, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.76, ...
        'FlatATK', 220, ...
        'ER', 1.45, ...
        'EM', 220, ...
        'CritRate', 0.68, ...
        'CritDMG', 1.65, ...
        'AnemoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'ViridescentVenerer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Lynette', 'artifacts_Lynette.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
