function build = customArtifact_Diluc()
    % Default Diluc build for triple skill weave and pyro burst.
    build = struct( ...
        'Weapon', 'WolfsGravestone', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'ATK', ...
        'WeaponSubStatValue', 0.496, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.96, ...
        'FlatATK', 311, ...
        'EM', 100, ...
        'CritRate', 0.72, ...
        'CritDMG', 1.90, ...
        'PyroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.18, ...
        'SkillDMGBonus', 0.00, ...
        'BurstDMGBonus', 0.00, ...
        'ArtifactSet1', 'CrimsonWitchOfFlames', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Diluc', 'artifacts_Diluc.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
