function [totalDMG, dps, breakdown, rotationTime, audit] = simulateBarbaraDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Barbara high-detail simulator.
    % 1. E is modeled as Hydro application plus Melody Loop periodic damage.
    % 2. C2 is reflected through the E-window Hydro bonus; C4 energy refund is not direct damage.
    % 3. Q remains healing-only and only reserves rotation time.
    % 4. The default rotation is kept as a simple on-field support loop.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Barbara', 'rotation_Barbara.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Barbara', 'Constellation', constellation, 'Build', build)}, 20, struct(), enemy);
    end

    hydroBonusWindow = 0.15 * double(constellation >= 2);
    vapeReady = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1;

    actions = struct();
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'AllowAmplify', double(vapeReady), ...
        'SkillWindowDamageBonus', hydroBonusWindow, 'LunarisAttackName', "Attack01", 'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Normal 1");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'AllowAmplify', double(vapeReady), ...
        'SkillWindowDamageBonus', hydroBonusWindow, 'LunarisAttackName', "Attack02", 'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Normal 2");
    actions.N3 = struct('TalentGroup', "Normal", 'Param', "x3HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'AllowAmplify', double(vapeReady), ...
        'SkillWindowDamageBonus', hydroBonusWindow, 'LunarisAttackName', "Attack03", 'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Normal 3");
    actions.N4 = struct('TalentGroup', "Normal", 'Param', "x4HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'AllowAmplify', double(vapeReady), ...
        'SkillWindowDamageBonus', hydroBonusWindow, 'LunarisAttackName', "Attack04Damage", 'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Normal 4");
    actions.CA = struct('TalentGroup', "Normal", 'Param', "ChargedAttackDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'AllowAmplify', double(vapeReady), ...
        'SkillWindowDamageBonus', hydroBonusWindow, 'LunarisAttackName', "ExtraAttack_Damage", ...
        'LunarisDamageParam', "Barbara_ExtraAttack", 'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Charged");
    actions.E = struct('TalentGroup', "Skill", 'Param', "DropletDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'PostSetSkillActiveTime', 15.0, ...
        'HitCount', 1, 'AllowAmplify', double(vapeReady), 'SkillWindowDamageBonus', hydroBonusWindow, ...
        'LunarisAttackName', "WetShiled", 'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Melody Loop cast");
    actions.Loop = struct('TalentGroup', "Skill", 'Param', "DropletDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'HitCount', 3, ...
        'AllowAmplify', double(vapeReady), 'SkillWindowDamageBonus', hydroBonusWindow, 'LunarisAttackName', "WetShiled", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Melody Loop droplets");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "Regeneration", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", 'ActionScalingMode', "HP", 'MVOverride', 0, 'BaseMultiplier', 1.00, 'Note', "Shining Miracle healing only");

    spec = struct( ...
        'Element', "Hydro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.80, ...
        'DefaultRotation', {{'E', 'N1', 'N2', 'N3', 'CA', 'Loop', 'Q'}}, ...
        'ActionTimeMap', struct('N1', 0.40, 'N2', 0.42, 'N3', 0.45, 'N4', 0.52, 'CA', 0.95, 'E', 0.80, 'Loop', 2.40, 'Q', 1.10), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Barbara', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
