function [totalDMG, dps, breakdown, rotationTime] = simulateBarbaraDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % 芭芭拉高精度近似模拟。
    % 建模要点：
    % 1. E 拆为落地挂水与 Melody Loop 周期伤害；
    % 2. C2 通过 E 期间水伤加成体现，C4 重击回能不直接计伤害；
    % 3. Q 仍视为纯治疗，不伪造伤害，只保留轮转时间；
    % 4. 默认按站场驾驶/挂水辅助的简化轴处理。
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Barbara', 'rotation_Barbara.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Barbara', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    hydroBonusWindow = 0.15 * double(constellation >= 2);
    vapeReady = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1;

    actions = struct();
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'AllowAmplify', double(vapeReady), ...
        'SkillWindowDamageBonus', hydroBonusWindow, 'LunarisAttackName', "Attack01", 'Note', "Normal 1");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'AllowAmplify', double(vapeReady), ...
        'SkillWindowDamageBonus', hydroBonusWindow, 'LunarisAttackName', "Attack02", 'Note', "Normal 2");
    actions.N3 = struct('TalentGroup', "Normal", 'Param', "x3HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'AllowAmplify', double(vapeReady), ...
        'SkillWindowDamageBonus', hydroBonusWindow, 'LunarisAttackName', "Attack03", 'Note', "Normal 3");
    actions.N4 = struct('TalentGroup', "Normal", 'Param', "x4HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'AllowAmplify', double(vapeReady), ...
        'SkillWindowDamageBonus', hydroBonusWindow, 'LunarisAttackName', "Attack04Damage", 'Note', "Normal 4");
    actions.CA = struct('TalentGroup', "Normal", 'Param', "ChargedAttackDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'AllowAmplify', double(vapeReady), ...
        'SkillWindowDamageBonus', hydroBonusWindow, 'ApplyGauge', 0, 'CanApplyAura', false, 'Note', "Charged");
    actions.E = struct('TalentGroup', "Skill", 'Param', "DropletDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'PostSetSkillActiveTime', 15.0, ...
        'HitCount', 1, 'AllowAmplify', double(vapeReady), 'SkillWindowDamageBonus', hydroBonusWindow, ...
        'LunarisAttackName', "WetShiled", 'Note', "Melody Loop cast");
    actions.Loop = struct('TalentGroup', "Skill", 'Param', "DropletDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", 'BaseMultiplier', 1.00, 'HitCount', 3, ...
        'AllowAmplify', double(vapeReady), 'SkillWindowDamageBonus', hydroBonusWindow, 'LunarisAttackName', "WetShiled", 'Note', "Melody Loop droplets");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "Regeneration", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", 'ActionScalingMode', "HP", 'MVOverride', 0, 'BaseMultiplier', 1.00, 'Note', "Shining Miracle healing only");

    spec = struct( ...
        'Element', "Hydro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.80, ...
        'DefaultRotation', {{'E', 'N1', 'N2', 'N3', 'CA', 'Loop', 'Q'}}, ...
        'ActionTimeMap', struct('N1', 0.40, 'N2', 0.42, 'N3', 0.45, 'N4', 0.52, 'CA', 0.95, 'E', 0.80, 'Loop', 2.40, 'Q', 1.10), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Barbara', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
