function [enemyState, reaction] = applyElementalHitToEnemy(enemyState, triggerElement, gaugeUnits, teamContext, deltaTime)
    % 兼容旧接口：将一次元素命中应用到怪物状态。
    %
    % 旧代码主要用它来服务增幅反应倍率判定，因此这里保留同名入口，
    % 但内部改为调用新的统一反应结算层。
    if nargin < 3 || isempty(gaugeUnits)
        gaugeUnits = 1.0;
    end
    if nargin < 4 || isempty(teamContext)
        teamContext = struct();
    end
    if nargin < 5 || isempty(deltaTime)
        deltaTime = 0;
    end

    hitDescriptor = struct( ...
        'HitElement', string(triggerElement), ...
        'ApplyElement', string(triggerElement), ...
        'ApplyGauge', gaugeUnits, ...
        'CanApplyAura', true, ...
        'AllowAmplify', true, ...
        'AllowCatalyze', true, ...
        'AllowTransformative', true);
    result = resolveReactionForHit(enemyState, hitDescriptor, struct(), teamContext, struct(), deltaTime);
    enemyState = result.EnemyState;

    reaction = struct( ...
        'Name', string(result.PrimaryReaction), ...
        'IsAmplifying', any(strcmpi(string(result.PrimaryReaction), ["Vaporize", "Melt"])), ...
        'AmplifyMultiplier', result.AmplifyMultiplier, ...
        'ConsumedAura', "", ...
        'AppliedAura', string(triggerElement));
end
