function build = buildGenericCharacterArtifact(characterName)
    % Construct a generic default build for imported characters that do not
    % yet have a hand-tuned customArtifact_<Character> implementation.
    % The goal is not final calibration; it is to provide a stable,
    % non-prebaked baseline that works with the current five-piece artifact
    % pipeline and GUI/editor flow.
    initProjectPaths();

    registryEntry = getCharacterRegistryEntry(characterName);
    key = string(registryEntry.Key);
    if strlength(key) == 0
        key = string(characterName);
    end

    [baseInfo, hasBaseInfo] = localReadCharacterBaseInfo(key);
    if ~hasBaseInfo
        error('No character base data found for %s.', characterName);
    end

    weaponTable = listWeaponsForCharacter(key);
    [weaponRow, hasWeapon] = localSelectDefaultWeapon(weaponTable);

    element = string(registryEntry.Element);
    if strlength(element) == 0
        element = string(baseInfo.Element);
    end

    ascensionType = upper(char(string(baseInfo.AscensionType)));
    mainStats = localResolveMainStats(key, registryEntry, ascensionType, element);
    recommendedSet = localResolveRecommendedSet(key);

    build = struct( ...
        'Weapon', char(getFieldOrDefault(weaponRow, 'Name', "")), ...
        'WeaponATK', double(getFieldOrDefault(weaponRow, 'BaseATK', 0)), ...
        'WeaponSubStatType', char(getFieldOrDefault(weaponRow, 'SubstatType', "")), ...
        'WeaponSubStatValue', double(getFieldOrDefault(weaponRow, 'SubstatValue', 0)), ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.20, ...
        'FlatATK', 80, ...
        'HPBonus', 0.12, ...
        'FlatHP', 800, ...
        'DEFBonus', 0.06, ...
        'FlatDEF', 40, ...
        'ER', 1.00, ...
        'EM', 0, ...
        'CritRate', 0.50, ...
        'CritDMG', 1.00, ...
        'PhysicalDMGBonus', 0.00, ...
        'PyroDMGBonus', 0.00, ...
        'HydroDMGBonus', 0.00, ...
        'CryoDMGBonus', 0.00, ...
        'ElectroDMGBonus', 0.00, ...
        'AnemoDMGBonus', 0.00, ...
        'GeoDMGBonus', 0.00, ...
        'DendroDMGBonus', 0.00, ...
        'NormalDMGBonus', 0.00, ...
        'ChargeDMGBonus', 0.00, ...
        'ChargedDMGBonus', 0.00, ...
        'PlungeDMGBonus', 0.00, ...
        'SkillDMGBonus', 0.00, ...
        'BurstDMGBonus', 0.00, ...
        'HealingBonus', 0.00, ...
        'ReactionDMGBonus', 0.00, ...
        'ShieldBonus', 0.00, ...
        'LunarChargedBonus', 0.00, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', char(recommendedSet), ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1, ...
        'ArtifactRecommended', char(recommendedSet), ...
        'ArtifactUsePieceModel', 1, ...
        'ArtifactApplySetBonuses', 1, ...
        'ArtifactLegacyTotalsIncludeSetBonuses', 0, ...
        'ArtifactAutoDistributeResidualSubstats', 1, ...
        'ArtifactFlowerSet', char(recommendedSet), ...
        'ArtifactFlowerMainStat', 'FlatHP', ...
        'ArtifactFlowerMainValue', getArtifactMainStatValue('Flower', 'FlatHP'), ...
        'ArtifactFlowerSubstats', '', ...
        'ArtifactFeatherSet', char(recommendedSet), ...
        'ArtifactFeatherMainStat', 'FlatATK', ...
        'ArtifactFeatherMainValue', getArtifactMainStatValue('Feather', 'FlatATK'), ...
        'ArtifactFeatherSubstats', '', ...
        'ArtifactSandsSet', char(recommendedSet), ...
        'ArtifactSandsMainStat', char(mainStats.Sands), ...
        'ArtifactSandsMainValue', getArtifactMainStatValue('Sands', mainStats.Sands), ...
        'ArtifactSandsSubstats', '', ...
        'ArtifactGobletSet', char(recommendedSet), ...
        'ArtifactGobletMainStat', char(mainStats.Goblet), ...
        'ArtifactGobletMainValue', getArtifactMainStatValue('Goblet', mainStats.Goblet), ...
        'ArtifactGobletSubstats', '', ...
        'ArtifactCircletSet', char(recommendedSet), ...
        'ArtifactCircletMainStat', char(mainStats.Circlet), ...
        'ArtifactCircletMainValue', getArtifactMainStatValue('Circlet', mainStats.Circlet), ...
        'ArtifactCircletSubstats', '');

    build = localApplyStatHeuristics(build, key, registryEntry, ascensionType, element, hasWeapon);
    build = normalizeArtifactBuild(build, key);

    outputPath = fullfile(fileparts(mfilename('fullpath')), '..', 'data', char(key), ...
        sprintf('artifacts_%s.csv', char(key)));
    if exist(fileparts(outputPath), 'dir') ~= 7
        mkdir(fileparts(outputPath));
    end
    writetable(struct2table(build), outputPath);
end

function [info, tf] = localReadCharacterBaseInfo(characterKey)
    info = struct('AscensionType', "", 'Element', "", 'Weapon', "");
    tf = false;
    funcFolder = fileparts(mfilename('fullpath'));
    projectRoot = fileparts(funcFolder);
    files = dir(fullfile(projectRoot, 'data', char(characterKey), 'characters_*.csv'));
    if isempty(files)
        return;
    end

    tbl = readtable(fullfile(files(1).folder, files(1).name), 'TextType', 'string');
    if isempty(tbl)
        return;
    end

    info.AscensionType = string(localTableString(tbl, 'AscensionType', 1));
    info.Element = string(localTableString(tbl, 'Element', 1));
    info.Weapon = string(localTableString(tbl, 'Weapon', 1));
    tf = true;
end

function [row, tf] = localSelectDefaultWeapon(weaponTable)
    row = struct('Name', "", 'BaseATK', 0, 'SubstatType', "", 'SubstatValue', 0);
    tf = false;
    if isempty(weaponTable)
        return;
    end

    idx = find(double(weaponTable.Rank) >= 4, 1, 'first');
    if isempty(idx)
        idx = 1;
    end

    row = table2struct(weaponTable(idx, :));
    tf = true;
end

function mainStats = localResolveMainStats(characterKey, registryEntry, ascensionType, element)
    profile = getArtifactModelProfile(characterKey, struct());
    mainStats = struct( ...
        'Sands', string(profile.SandsMainStat), ...
        'Goblet', string(profile.GobletMainStat), ...
        'Circlet', string(profile.CircletMainStat));

    weaponType = lower(char(string(registryEntry.WeaponType)));
    roleHint = lower(char(string(characterKey)));
    element = lower(char(string(element)));

    if any(strcmp(ascensionType, {'EM', 'ELEMENTALMASTERY'}))
        if any(strcmp(element, {'anemo', 'dendro', 'electro'}))
            mainStats.Sands = "EM";
        end
    elseif any(strcmp(ascensionType, {'ER', 'ENERGYRECHARGE'}))
        mainStats.Sands = "ER";
    elseif any(strcmp(ascensionType, {'HP', 'HPPCT', 'HPBONUS'})) ...
            && (strcmp(element, 'hydro') || contains(roleHint, 'kokomi'))
        mainStats.Sands = "HPBonus";
    elseif any(strcmp(ascensionType, {'DEF', 'DEFPCT', 'DEFBONUS'})) ...
            && strcmp(element, 'geo')
        mainStats.Sands = "DEFBonus";
    end

    if strcmp(weaponType, 'catalyst') && strcmp(element, 'anemo') && any(strcmp(ascensionType, {'EM', 'ELEMENTALMASTERY'}))
        mainStats.Circlet = "EM";
    end
    if contains(roleHint, 'kokomi') || strcmp(ascensionType, 'HB')
        mainStats.Circlet = "HealingBonus";
    elseif any(strcmp(ascensionType, {'CD', 'CRITDMG'}))
        mainStats.Circlet = "CritRate";
    elseif any(strcmp(ascensionType, {'CR', 'CRITRATE'}))
        mainStats.Circlet = "CritDMG";
    end

    if strcmp(element, 'physical')
        mainStats.Goblet = "PhysicalDMGBonus";
    end
end

function setId = localResolveRecommendedSet(characterKey)
    importProfile = localImportedCharacterSetMap();
    token = lower(char(string(characterKey)));
    if isKey(importProfile, token)
        setId = string(importProfile(token));
    else
        setId = "None";
    end
end

function build = localApplyStatHeuristics(build, characterKey, registryEntry, ascensionType, element, hasWeapon)
    elementField = localElementBonusField(element);
    if strlength(elementField) > 0
        build.(elementField) = 0.466;
    end

    roleToken = lower(char(string(characterKey)));
    weaponType = lower(char(string(registryEntry.WeaponType)));
    if any(strcmp(ascensionType, {'EM', 'ELEMENTALMASTERY'}))
        build.EM = build.EM + 120;
    elseif any(strcmp(ascensionType, {'ER', 'ENERGYRECHARGE'}))
        build.ER = 1.45;
    elseif any(strcmp(ascensionType, {'HP', 'HPPCT', 'HPBONUS'}))
        build.HPBonus = build.HPBonus + 0.30;
        build.FlatHP = build.FlatHP + 1000;
    elseif any(strcmp(ascensionType, {'DEF', 'DEFPCT', 'DEFBONUS'}))
        build.DEFBonus = build.DEFBonus + 0.30;
        build.FlatDEF = build.FlatDEF + 100;
    end

    if contains(roleToken, 'kokomi')
        build.CritRate = -0.95;
        build.CritDMG = 0.50;
        build.HPBonus = build.HPBonus + 0.46;
        build.HealingBonus = max(build.HealingBonus, 0.359);
        build.HydroDMGBonus = max(build.HydroDMGBonus, 0.466);
    elseif contains(roleToken, 'bennett') || contains(roleToken, 'mika') || contains(roleToken, 'dahlia')
        build.ER = max(build.ER, 1.80);
    elseif contains(roleToken, 'zhongli') || contains(roleToken, 'layla') || contains(roleToken, 'diona') || contains(roleToken, 'kirara')
        build.HPBonus = build.HPBonus + 0.46;
        build.FlatHP = build.FlatHP + 1200;
    elseif contains(roleToken, 'yunjin') || contains(roleToken, 'gorou') || contains(roleToken, 'noelle') || contains(roleToken, 'albedo')
        build.DEFBonus = build.DEFBonus + 0.46;
        build.FlatDEF = build.FlatDEF + 120;
    elseif strcmp(weaponType, 'bow') && strcmpi(char(element), 'anemo')
        build.ER = max(build.ER, 1.40);
    end

    if ~hasWeapon
        build.Weapon = '';
        build.WeaponATK = 0;
        build.WeaponSubStatType = '';
        build.WeaponSubStatValue = 0;
    end
end

function fieldName = localElementBonusField(element)
    switch lower(char(string(element)))
        case 'pyro'
            fieldName = "PyroDMGBonus";
        case 'hydro'
            fieldName = "HydroDMGBonus";
        case 'cryo'
            fieldName = "CryoDMGBonus";
        case 'electro'
            fieldName = "ElectroDMGBonus";
        case 'anemo'
            fieldName = "AnemoDMGBonus";
        case 'geo'
            fieldName = "GeoDMGBonus";
        case 'dendro'
            fieldName = "DendroDMGBonus";
        otherwise
            fieldName = "";
    end
end

function setMap = localImportedCharacterSetMap()
    setMap = containers.Map('KeyType', 'char', 'ValueType', 'char');
    entries = { ...
        'albedo', 'HuskOfOpulentDreams'; ...
        'aloy', 'BlizzardStrayer'; ...
        'beidou', 'EmblemOfSeveredFate'; ...
        'bennett', 'NoblesseOblige'; ...
        'chongyun', 'BlizzardStrayer'; ...
        'diona', 'NoblesseOblige'; ...
        'eula', 'PaleFlame'; ...
        'fischl', 'GoldenTroupe'; ...
        'ganyu', 'BlizzardStrayer'; ...
        'kaedeharakazuha', 'ViridescentVenerer'; ...
        'keqing', 'ThunderingFury'; ...
        'kirara', 'DeepwoodMemories'; ...
        'klee', 'CrimsonWitchOfFlames'; ...
        'kujousara', 'EmblemOfSeveredFate'; ...
        'mona', 'NoblesseOblige'; ...
        'ningguang', 'NighttimeWhispersInTheEchoingWoods'; ...
        'noelle', 'HuskOfOpulentDreams'; ...
        'qiqi', 'OceanHuedClam'; ...
        'raidenshogun', 'EmblemOfSeveredFate'; ...
        'rosaria', 'BlizzardStrayer'; ...
        'sangonomiyakokomi', 'OceanHuedClam'; ...
        'sayu', 'ViridescentVenerer'; ...
        'sucrose', 'ViridescentVenerer'; ...
        'tartaglia', 'NymphsDream'; ...
        'thoma', 'FlowerOfParadiseLost'; ...
        'xiao', 'VermillionHereafter'; ...
        'xingqiu', 'EmblemOfSeveredFate'; ...
        'xinyan', 'PaleFlame'; ...
        'yanfei', 'WanderersTroupe'; ...
        'yoimiya', 'ShimenawasReminiscence'; ...
        'zhongli', 'TenacityOfTheMillelith' ...
    };
    for i = 1:size(entries, 1)
        setMap(entries{i, 1}) = entries{i, 2};
    end
end

function value = localTableString(tbl, fieldName, rowIndex)
    value = "";
    if nargin < 3
        rowIndex = 1;
    end
    if isempty(tbl) || ~ismember(fieldName, tbl.Properties.VariableNames) || rowIndex > height(tbl)
        return;
    end
    value = string(tbl.(fieldName)(rowIndex));
end
