function registry = getArtifactSetRegistry()
    % 返回工程统一使用的圣遗物套装注册表。
    % 该注册表同时服务于：
    % 1. GUI 下拉框、主题色与图标拉取；
    % 2. 套装 2 件 / 4 件效果的统一分发；
    % 3. 未来继续扩充更多套装时的单点维护。
    %
    % 字段说明：
    % Id            内部稳定 ID，后端逻辑与 build 字段均使用该值
    % DisplayName   GUI 显示名称
    % ShortLabel    图标上的短标签
    % ThemeColor    GUI 主题配色
    % ApiSlug       预留给在线图标/描述拉取的 slug
    % Effect2Pc     2 件套效果说明
    % Effect4Pc     4 件套效果说明
    % IsImplemented 当前版本是否已在后端精算

    entries = { ...
        'None', '无套装', 'NONE', [0.55 0.58 0.64], '', ...
            '无额外套装效果。', ...
            '无额外套装效果。', true; ...
        'ATK18', '攻击力 18% 通用 2 件套', 'ATK', [0.76 0.52 0.28], 'gladiatorsfinale', ...
            '攻击力提高 18%。', ...
            '仅作为泛用 2 件套占位使用。', true; ...
        'HP20', '生命值 20% 通用 2 件套', 'HP', [0.35 0.63 0.56], 'tenacityofthemillelith', ...
            '生命值提高 20%。', ...
            '仅作为泛用 2 件套占位使用。', true; ...
        'EM80', '元素精通 80 通用 2 件套', 'EM', [0.54 0.46 0.72], 'wandererstroupe', ...
            '元素精通提高 80 点。', ...
            '仅作为泛用 2 件套占位使用。', true; ...
        'ER20', '元素充能 20% 通用 2 件套', 'ER', [0.44 0.55 0.78], 'emblemofseveredfate', ...
            '元素充能效率提高 20%。', ...
            '仅作为泛用 2 件套占位使用。', true; ...
        'Healing15', '治疗加成 15% 通用 2 件套', 'HEAL', [0.70 0.54 0.62], 'songofdayspast', ...
            '治疗加成提高 15%。', ...
            '仅作为泛用 2 件套占位使用。', true; ...
        'Pyro15', '炽烈的炎之 2 件套', 'PYRO', [0.82 0.38 0.24], 'crimsonwitchofflames', ...
            '火元素伤害加成提高 15%。', ...
            '4 件效果依套装而异，此通用占位不精算。', true; ...
        'Hydro15', '沉沦之心 2 件套', 'HYDRO', [0.29 0.58 0.84], 'heartofdepth', ...
            '水元素伤害加成提高 15%。', ...
            '4 件效果依套装而异，此通用占位不精算。', true; ...
        'Cryo15', '冰风迷途的勇士 2 件套', 'CRYO', [0.52 0.76 0.93], 'blizzardstrayer', ...
            '冰元素伤害加成提高 15%。', ...
            '4 件效果依套装而异，此通用占位不精算。', true; ...
        'Electro15', '如雷的盛怒 2 件套', 'ELEC', [0.49 0.41 0.83], 'thunderingfury', ...
            '雷元素伤害加成提高 15%。', ...
            '4 件效果依套装而异，此通用占位不精算。', true; ...
        'Anemo15', '翠绿之影 2 件套', 'ANEMO', [0.34 0.71 0.60], 'viridescentvenerer', ...
            '风元素伤害加成提高 15%。', ...
            '4 件效果依套装而异，此通用占位不精算。', true; ...
        'Geo15', '悠古的磐岩 2 件套', 'GEO', [0.78 0.66 0.35], 'archaicpetra', ...
            '岩元素伤害加成提高 15%。', ...
            '4 件效果依套装而异，此通用占位不精算。', true; ...
        'Dendro15', '深林的记忆 2 件套', 'DEND', [0.34 0.57 0.38], 'deepwoodmemories', ...
            '草元素伤害加成提高 15%。', ...
            '4 件效果依套装而异，此通用占位不精算。', true; ...
        'GoldenTroupe', '黄金剧团', 'GT', [0.81 0.67 0.26], 'goldentroupe', ...
            '元素战技造成的伤害提升 20%。', ...
            '元素战技造成的伤害提升 25%；处于队伍后台时额外提升 25%。', true; ...
        'MarechausseeHunter', '逐影猎人', 'MH', [0.47 0.57 0.72], 'marechausseehunter', ...
            '普通攻击与重击造成的伤害提升 15%。', ...
            '生命值变化时暴击率提升 12%，最多叠加 3 层。', true; ...
        'FragmentOfHarmonicWhimsy', '谐律异想断章', 'HW', [0.83 0.44 0.33], 'fragmentofharmonicwhimsy', ...
            '攻击力提高 18%。', ...
            '生命之契数值变化后，伤害提高 18%，最多 3 层。', true; ...
        'ObsidianCodex', '黑曜秘典', 'OC', [0.26 0.33 0.41], 'obsidiancodex', ...
            '装备者处于夜魂加持状态，并在场上时，造成的伤害提升 15%。', ...
            '消耗夜魂值时，暴击率提高 40%，持续 6 秒。', true; ...
        'BlizzardStrayer', '冰风迷途的勇士', 'BS', [0.52 0.76 0.93], 'blizzardstrayer', ...
            '冰元素伤害加成提高 15%。', ...
            '攻击受冰元素影响的敌人时暴击率提高 20%；若敌人被冻结，额外提高 20%。', true; ...
        'DeepwoodMemories', '深林的记忆', 'DM', [0.34 0.57 0.38], 'deepwoodmemories', ...
            '草元素伤害加成提高 15%。', ...
            '元素战技或元素爆发命中敌人后，敌人的草元素抗性降低 30%。', true; ...
        'NoblesseOblige', '昔日宗室之仪', 'NO', [0.56 0.49 0.72], 'noblesseoblige', ...
            '元素爆发造成的伤害提升 20%。', ...
            '施放元素爆发后，队伍中所有角色攻击力提升 20%。', true; ...
        'TenacityOfTheMillelith', '千岩牢固', 'TM', [0.53 0.63 0.42], 'tenacityofthemillelith', ...
            '生命值提升 20%。', ...
            '元素战技命中敌人后，队伍中附近角色攻击力提升 20%。', true; ...
        'HuskOfOpulentDreams', '华馆梦醒形骸记', 'HUSK', [0.72 0.60 0.34], 'huskofopulentdreams', ...
            '防御力提高 30%。', ...
            '叠层获得防御力与岩伤加成，最多 4 层。', true; ...
        'HeartOfDepth', '沉沦之心', 'HOD', [0.29 0.58 0.84], 'heartofdepth', ...
            '水元素伤害加成提高 15%。', ...
            '施放元素战技后，普通攻击与重击伤害提高 30%。', true; ...
        'WanderersTroupe', '流浪大地的乐团', 'WT', [0.72 0.54 0.35], 'wandererstroupe', ...
            '元素精通提高 80 点。', ...
            '法器、弓角色重击伤害提高 35%。', true; ...
        'ViridescentVenerer', '翠绿之影', 'VV', [0.34 0.71 0.60], 'viridescentvenerer', ...
            '风元素伤害加成提高 15%。', ...
            '扩散反应伤害提高，并降低对应元素抗性 40%。', false; ...
        'SongOfDaysPast', '昔时之歌', 'SDP', [0.74 0.62 0.48], 'songofdayspast', ...
            '治疗加成提高 15%。', ...
            '治疗会记录总治疗量并转化为下次造成伤害时的追加伤害。', false; ...
        'NighttimeWhispersInTheEchoingWoods', '回声之林夜话', 'NW', [0.60 0.47 0.31], 'nighttimewhispersintheechoingwoods', ...
            '攻击力提高 18%。', ...
            '结晶护盾存在时，造成伤害提高 20%，岩伤额外提高。', false; ...
        'ScrollOfTheHeroOfCinderCity', '烬城勇者绘卷', 'SHCC', [0.88 0.56 0.30], 'scrolloftheheroofcindercity', ...
            '夜魂迸发触发后，元素精通提升。', ...
            '依据触发的元素类型为队伍提供更高幅度增伤。', false; ...
        'DesertPavilionChronicle', '沙上楼阁史话', 'DPC', [0.84 0.67 0.43], 'desertpavilionchronicle', ...
            '风元素伤害加成提高 15%。', ...
            '重击命中后提升攻速、普通攻击、重击与下落攻击伤害。', false; ...
        'OceanHuedClam', '海染砗磲', 'OHC', [0.44 0.68 0.76], 'oceanhuedclam', ...
            '治疗加成提高 15%。', ...
            '治疗量会累积为海染泡沫并造成伤害。', false; ...
        'EmblemOfSeveredFate', '绝缘之旗印', 'EOSF', [0.44 0.55 0.78], 'emblemofseveredfate', ...
            '元素充能效率提高 20%。', ...
            '元素爆发伤害基于元素充能效率提高。', false; ...
        'GildedDreams', '饰金之梦', 'GD', [0.72 0.60 0.46], 'gildeddreams', ...
            '元素精通提高 80 点。', ...
            '根据队伍元素类型获得攻击力或元素精通。', false; ...
        'Instructor', '教官', 'INST', [0.50 0.58 0.60], 'instructor', ...
            '元素精通提高 80 点。', ...
            '触发元素反应后提升全队元素精通。', false; ...
        'FlowerOfParadiseLost', '乐园遗落之花', 'FPL', [0.79 0.53 0.41], 'flowerofparadiselost', ...
            '元素精通提高 80 点。', ...
            '绽放、超绽放与烈绽放伤害提升并叠层。', false; ...
        'CrimsonWitchOfFlames', '炽烈的炎之魔女', 'CW', [0.82 0.38 0.24], 'crimsonwitchofflames', ...
            '火元素伤害加成提高 15%。', ...
            '超载、燃烧伤害提高；蒸发、融化系数提高；施放战技后 2 件套效果可叠层。', false; ...
        'ThunderingFury', '如雷的盛怒', 'TF', [0.50 0.41 0.83], 'thunderingfury', ...
            '雷元素伤害加成提高 15%。', ...
            '强化感电、超载、超绽放等反应，并在触发时缩短战技冷却。', false; ...
        'ArchaicPetra', '悠古的磐岩', 'AP', [0.78 0.66 0.35], 'archaicpetra', ...
            '岩元素伤害加成提高 15%。', ...
            '拾取结晶反应产生的晶片后，全队对应元素伤害加成提高。', false; ...
        'GladiatorsFinale', '角斗士的终幕礼', 'GLAD', [0.76 0.52 0.28], 'gladiatorsfinale', ...
            '攻击力提高 18%。', ...
            '单手剑、双手剑、长柄武器角色普通攻击伤害提高 35%。', false; ...
        'ShimenawasReminiscence', '追忆之注连', 'SHIME', [0.76 0.52 0.28], 'shimenawasreminiscence', ...
            '攻击力提高 18%。', ...
            '施放战技时消耗元素能量，提高普通攻击、重击与下落攻击伤害。', false; ...
        'VourukashasGlow', '花海甘露之光', 'VG', [0.35 0.63 0.56], 'vourukashasglow', ...
            '生命值提升 20%。', ...
            '战技与爆发伤害提高；受到伤害后效果进一步增强。', false; ...
        'NymphsDream', '水仙之梦', 'NYMPH', [0.29 0.58 0.84], 'nymphsdream', ...
            '水元素伤害加成提高 15%。', ...
            '不同攻击类型命中后叠层，提高攻击力与水伤。', false ...
    };

    registry = repmat(struct( ...
        'Id', "", ...
        'DisplayName', "", ...
        'ShortLabel', "", ...
        'ThemeColor', [0.55 0.58 0.64], ...
        'ApiSlug', "", ...
        'Effect2Pc', "", ...
        'Effect4Pc', "", ...
        'IsImplemented', false), 1, size(entries, 1));

    for i = 1:size(entries, 1)
        registry(i).Id = string(entries{i, 1});
        registry(i).DisplayName = string(entries{i, 2});
        registry(i).ShortLabel = string(entries{i, 3});
        registry(i).ThemeColor = entries{i, 4};
        registry(i).ApiSlug = string(entries{i, 5});
        registry(i).Effect2Pc = string(entries{i, 6});
        registry(i).Effect4Pc = string(entries{i, 7});
        registry(i).IsImplemented = logical(entries{i, 8});
    end
end
