function cfg = getDefaultCharacterConfig(name, overrides)
    % Resolve a name used by the unified entry into a complete default
    % config bundle: display name, build, talent level, constellation, and
    % the default rotation file.
    initProjectPaths();
    if nargin < 2
        overrides = struct();
    end

    funcFolder = fileparts(mfilename('fullpath'));
    projectRoot = fileparts(funcFolder);
    key = lower(strtrim(char(string(name))));

    switch key
        case {'skirk'}
            cfg = struct( ...
                'Name', 'Skirk', ...
                'DisplayName', "Skirk", ...
                'TalentLevel', 10, ...
                'Constellation', 0, ...
                'Build', customArtifact_Skirk(), ...
                'RotationFile', fullfile(projectRoot, 'data', 'Skirk', 'rotation_Skirk.txt'));
        case {'escoffier'}
            cfg = struct( ...
                'Name', 'Escoffier', ...
                'DisplayName', "Escoffier", ...
                'TalentLevel', 10, ...
                'Constellation', 0, ...
                'Build', customArtifact_Escoffier(), ...
                'RotationFile', fullfile(projectRoot, 'data', 'Escoffier', 'rotation_Escoffier.txt'));
        case {'arlecchino'}
            cfg = struct( ...
                'Name', 'Arlecchino', ...
                'DisplayName', "Arlecchino", ...
                'TalentLevel', 10, ...
                'Constellation', 0, ...
                'Build', customArtifact_Arlecchino(), ...
                'RotationFile', fullfile(projectRoot, 'data', 'Arlecchino', 'rotation_Arlecchino.txt'));
        case {'furina'}
            furinaBuild = readtable(fullfile(projectRoot, 'data', 'Furina', 'artifacts_Furina.csv'));
            cfg = struct( ...
                'Name', 'Furina', ...
                'DisplayName', "Furina", ...
                'TalentLevel', 10, ...
                'Constellation', 6, ...
                'Build', table2struct(furinaBuild(1, :)), ...
                'RotationFile', fullfile(projectRoot, 'data', 'Furina', 'rotation_Furina.txt'));
        case {'lauma', '菈乌玛'}
            cfg = struct( ...
                'Name', 'Lauma', ...
                'DisplayName', "菈乌玛", ...
                'TalentLevel', 10, ...
                'Constellation', 0, ...
                'Build', customArtifact_Lauma(), ...
                'RotationFile', fullfile(projectRoot, 'data', 'Lauma', 'rotation_Lauma.txt'));
        case {'ineffa', '伊涅芙'}
            cfg = struct( ...
                'Name', 'Ineffa', ...
                'DisplayName', "伊涅芙", ...
                'TalentLevel', 10, ...
                'Constellation', 0, ...
                'Build', customArtifact_Ineffa(), ...
                'RotationFile', fullfile(projectRoot, 'data', 'Ineffa', 'rotation_Ineffa.txt'));
        case {'linnea', 'linnia', '莉奈娅'}
            cfg = struct( ...
                'Name', 'Linnea', ...
                'DisplayName', "莉奈娅", ...
                'TalentLevel', 10, ...
                'Constellation', 0, ...
                'Build', customArtifact_Linnea(), ...
                'RotationFile', fullfile(projectRoot, 'data', 'Linnea', 'rotation_Linnea.txt'));
        case {'nilou', '妮露'}
            cfg = struct( ...
                'Name', 'Nilou', ...
                'DisplayName', "妮露", ...
                'TalentLevel', 10, ...
                'Constellation', 0, ...
                'Build', customArtifact_Nilou(), ...
                'RotationFile', fullfile(projectRoot, 'data', 'Nilou', 'rotation_Nilou.txt'));
        case {'nefer', '奈芙尔'}
            cfg = struct( ...
                'Name', 'Nefer', ...
                'DisplayName', "奈芙尔", ...
                'TalentLevel', 10, ...
                'Constellation', 0, ...
                'Build', customArtifact_Nefer(), ...
                'RotationFile', fullfile(projectRoot, 'data', 'Nefer', 'rotation_Nefer.txt'));
        otherwise
            error('Unsupported character in unified entry: %s', name);
    end

    cfg = localApplyConfigOverrides(cfg, overrides);
end

function cfg = localApplyConfigOverrides(cfg, overrides)
    if isempty(overrides)
        return;
    end

    if isfield(overrides, 'Build')
        cfg.Build = applyStructOverrides(cfg.Build, overrides.Build);
        overrides = rmfield(overrides, 'Build');
    end

    if isfield(overrides, 'Name')
        overrides = rmfield(overrides, 'Name');
    end

    cfg = applyStructOverrides(cfg, overrides);
end
