function cfg = getDefaultCharacterConfig(name)
    % Resolve a name used by the unified entry into a complete default
    % config bundle: display name, build, talent level, constellation, and
    % the default rotation file.
    initProjectPaths();
    funcFolder = fileparts(mfilename('fullpath'));
    projectRoot = fileparts(funcFolder);
    key = lower(strtrim(char(string(name))));

    switch key
        case {'skirk', '丝柯克'}
            cfg = struct( ...
                'Name', 'Skirk', ...
                'DisplayName', "丝柯克", ...
                'TalentLevel', 10, ...
                'Constellation', 0, ...
                'Build', customArtifact_Skirk(), ...
                'RotationFile', fullfile(projectRoot, 'data', 'Skirk', 'rotation_Skirk.txt'));
        case {'escoffier', '爱可菲'}
            cfg = struct( ...
                'Name', 'Escoffier', ...
                'DisplayName', "爱可菲", ...
                'TalentLevel', 10, ...
                'Constellation', 0, ...
                'Build', customArtifact_Escoffier(), ...
                'RotationFile', fullfile(projectRoot, 'data', 'Escoffier', 'rotation_Escoffier.txt'));
        case {'arlecchino', '阿蕾奇诺'}
            cfg = struct( ...
                'Name', 'Arlecchino', ...
                'DisplayName', "阿蕾奇诺", ...
                'TalentLevel', 10, ...
                'Constellation', 0, ...
                'Build', customArtifact_Arlecchino(), ...
                'RotationFile', fullfile(projectRoot, 'data', 'Arlecchino', 'rotation_Arlecchino.txt'));
        case {'furina', '芙宁娜'}
            furinaBuild = readtable(fullfile(projectRoot, 'data', 'Furina', 'artifacts_Furina.csv'));
            cfg = struct( ...
                'Name', 'Furina', ...
                'DisplayName', "芙宁娜", ...
                'TalentLevel', 10, ...
                'Constellation', 6, ...
                'Build', table2struct(furinaBuild(1, :)), ...
                'RotationFile', fullfile(projectRoot, 'data', 'Furina', 'rotation_Furina.txt'));
        otherwise
            error('Unsupported character in unified entry: %s', name);
    end
end
