function summary = importLegacyRosterBatch(options)
    % Import the current backlog of older roster characters into data/<Character>.
    % This batch intentionally uses explicit Key/Id pairs so it does not
    % depend on fragile live-index decoding when the local cache or remote
    % schema changes.
    if nargin < 1
        options = struct();
    end
    if ~isfield(options, 'Language')
        options.Language = "en";
    end
    if ~isfield(options, 'Overwrite')
        options.Overwrite = true;
    end

    requests = repmat(struct('Key', "", 'Id', "", 'DisplayName', "", 'AvatarKey', ""), 31, 1);
    rows = { ...
        'Albedo', '10000038', 'Albedo', 'Albedo'; ...
        'Aloy', '10000062', 'Aloy', 'Aloy'; ...
        'Beidou', '10000024', 'Beidou', 'Beidou'; ...
        'Bennett', '10000032', 'Bennett', 'Bennett'; ...
        'Chongyun', '10000036', 'Chongyun', 'Chongyun'; ...
        'Diona', '10000039', 'Diona', 'Diona'; ...
        'Eula', '10000051', 'Eula', 'Eula'; ...
        'Fischl', '10000031', 'Fischl', 'Fischl'; ...
        'Ganyu', '10000037', 'Ganyu', 'Ganyu'; ...
        'KaedeharaKazuha', '10000047', 'Kaedehara Kazuha', 'Kazuha'; ...
        'Keqing', '10000042', 'Keqing', 'Keqing'; ...
        'Kirara', '10000061', 'Kirara', 'Kirara'; ...
        'Klee', '10000029', 'Klee', 'Klee'; ...
        'KujouSara', '10000056', 'Kujou Sara', 'Sara'; ...
        'Mona', '10000041', 'Mona', 'Mona'; ...
        'Ningguang', '10000027', 'Ningguang', 'Ningguang'; ...
        'Noelle', '10000034', 'Noelle', 'Noelle'; ...
        'Qiqi', '10000035', 'Qiqi', 'Qiqi'; ...
        'RaidenShogun', '10000052', 'Raiden Shogun', 'Shougun'; ...
        'Rosaria', '10000045', 'Rosaria', 'Rosaria'; ...
        'SangonomiyaKokomi', '10000054', 'Sangonomiya Kokomi', 'Kokomi'; ...
        'Sayu', '10000053', 'Sayu', 'Sayu'; ...
        'Sucrose', '10000043', 'Sucrose', 'Sucrose'; ...
        'Tartaglia', '10000033', 'Tartaglia', 'Tartaglia'; ...
        'Thoma', '10000050', 'Thoma', 'Thoma'; ...
        'Xiao', '10000026', 'Xiao', 'Xiao'; ...
        'Xingqiu', '10000025', 'Xingqiu', 'Xingqiu'; ...
        'Xinyan', '10000044', 'Xinyan', 'Xinyan'; ...
        'Yanfei', '10000048', 'Yanfei', 'Yanfei'; ...
        'Yoimiya', '10000049', 'Yoimiya', 'Yoimiya'; ...
        'Zhongli', '10000030', 'Zhongli', 'Zhongli' ...
    };

    for i = 1:size(rows, 1)
        requests(i) = struct( ...
            'Key', string(rows{i, 1}), ...
            'Id', string(rows{i, 2}), ...
            'DisplayName', string(rows{i, 3}), ...
            'AvatarKey', string(rows{i, 4}));
    end

    summary = importLunarisCharacterData(requests, options);
end
