function build = materializeArtifactPieceModel(characterName, build, teamContext)
    % Expand a legacy aggregate build into a piece-wise artifact model.
    if nargin < 3 || isempty(teamContext)
        teamContext = struct();
    end

    build = normalizeArtifactBuild(build, characterName);
    if ~logical(getFieldOrDefault(build, 'ArtifactUsePieceModel', 1))
        return;
    end
    if isfield(build, 'ArtifactEffectiveSubstatCount')
        build = optimizeEffectiveArtifactSubstats(characterName, build, teamContext);
        return;
    end
    if ~logical(getFieldOrDefault(build, 'ArtifactAutoDistributeResidualSubstats', 1))
        return;
    end
    if localHasExplicitSubstatData(build)
        return;
    end

    mainContribution = localCollectMainContribution(build);
    ascensionContribution = getCharacterAscensionBonus(characterName);
    weaponContribution = getWeaponSubstatBonus(build);
    legacySetContribution = localEmptyStatStruct();
    if logical(getFieldOrDefault(build, 'ArtifactApplySetBonuses', 0))
        legacySetContribution = getArtifactLegacySetContribution(characterName, build, teamContext);
    end

    residual = localInferResidualSubstats( ...
        build, mainContribution, ascensionContribution, weaponContribution, legacySetContribution);
    if ~localHasAnyResidual(residual)
        return;
    end

    [build, slotSummaries] = localDistributeResidualSubstats(build, residual);
    slotNames = {'Flower', 'Feather', 'Sands', 'Goblet', 'Circlet'};
    for i = 1:numel(slotNames)
        build.(sprintf('Artifact%sSubstats', slotNames{i})) = slotSummaries{i};
    end
    build.ArtifactPieceModelVersion = 1;
    build.ArtifactSubstatsAutoGenerated = 1;
end

function tf = localHasExplicitSubstatData(build)
    slotNames = {'Flower', 'Feather', 'Sands', 'Goblet', 'Circlet'};
    suffixes = localResidualFieldOrder();
    tf = false;
    for i = 1:numel(slotNames)
        summaryField = sprintf('Artifact%sSubstats', slotNames{i});
        if strlength(string(getFieldOrDefault(build, summaryField, ""))) > 0
            tf = true;
            return;
        end
        for j = 1:numel(suffixes)
            fieldName = sprintf('Artifact%sSubstat%s', slotNames{i}, suffixes{j});
            if abs(getFieldOrDefault(build, fieldName, 0)) > 1e-9
                tf = true;
                return;
            end
        end
    end
end

function contribution = localCollectMainContribution(build)
    contribution = localEmptyStatStruct();
    slotNames = {'Flower', 'Feather', 'Sands', 'Goblet', 'Circlet'};
    for i = 1:numel(slotNames)
        statType = string(getFieldOrDefault(build, sprintf('Artifact%sMainStat', slotNames{i}), ""));
        statValue = double(getFieldOrDefault(build, sprintf('Artifact%sMainValue', slotNames{i}), 0));
        contribution = localAccumulateStat(contribution, statType, statValue);
    end
end

function residual = localInferResidualSubstats(build, mainContribution, ascensionContribution, weaponContribution, legacySetContribution)
    residual = localEmptyStatStruct();
    fields = localResidualFieldOrder();
    for i = 1:numel(fields)
        fieldName = fields{i};
        if strcmp(fieldName, 'ER')
            legacyValue = getFieldOrDefault(build, fieldName, 1.0);
        else
            legacyValue = getFieldOrDefault(build, fieldName, 0);
        end

        residual.(fieldName) = max(0, legacyValue ...
            - getFieldOrDefault(mainContribution, fieldName, 0) ...
            - getFieldOrDefault(ascensionContribution, fieldName, 0) ...
            - getFieldOrDefault(weaponContribution, fieldName, 0) ...
            - getFieldOrDefault(legacySetContribution, fieldName, 0));
    end
end

function tf = localHasAnyResidual(residual)
    fields = localResidualFieldOrder();
    tf = false;
    for i = 1:numel(fields)
        if abs(getFieldOrDefault(residual, fields{i}, 0)) > 1e-9
            tf = true;
            return;
        end
    end
end

function [build, slotSummaries] = localDistributeResidualSubstats(build, residual)
    slotNames = {'Flower', 'Feather', 'Sands', 'Goblet', 'Circlet'};
    fieldOrder = localResidualFieldOrder();
    slotCounts = zeros(1, numel(slotNames));
    slotEntries = repmat({strings(1, 0)}, 1, numel(slotNames));

    for i = 1:numel(fieldOrder)
        fieldName = fieldOrder{i};
        value = getFieldOrDefault(residual, fieldName, 0);
        if abs(value) <= 1e-9
            continue;
        end

        slotIndex = localSelectSlot(build, fieldName, slotCounts);
        numericField = sprintf('Artifact%sSubstat%s', slotNames{slotIndex}, fieldName);
        build.(numericField) = value;
        slotEntries{slotIndex}(end + 1) = sprintf('%s=%.6g', fieldName, value); %#ok<AGROW>
        slotCounts(slotIndex) = slotCounts(slotIndex) + 1;
    end

    slotSummaries = cell(1, numel(slotNames));
    for i = 1:numel(slotNames)
        if isempty(slotEntries{i})
            slotSummaries{i} = '';
        else
            slotSummaries{i} = char(strjoin(slotEntries{i}, '; '));
        end
    end
end

function slotIndex = localSelectSlot(build, statField, slotCounts)
    slotNames = {'Flower', 'Feather', 'Sands', 'Goblet', 'Circlet'};
    candidates = zeros(1, 0);
    statField = string(statField);
    for i = 1:numel(slotNames)
        mainField = sprintf('Artifact%sMainStat', slotNames{i});
        mainType = string(getFieldOrDefault(build, mainField, ""));
        if ~localMainMatchesSubstat(mainType, statField) && slotCounts(i) < 4
            candidates(end + 1) = i; %#ok<AGROW>
        end
    end

    if isempty(candidates)
        candidates = find(slotCounts == min(slotCounts));
    end

    if numel(candidates) == 1
        slotIndex = candidates(1);
        return;
    end

    preferred = localPreferredSlotOrder(statField);
    bestRank = inf;
    slotIndex = candidates(1);
    for i = 1:numel(candidates)
        idx = candidates(i);
        rank = find(preferred == idx, 1, 'first');
        if isempty(rank)
            rank = numel(preferred) + idx / 100;
        end
        score = rank + slotCounts(idx) / 10;
        if score < bestRank
            bestRank = score;
            slotIndex = idx;
        end
    end
end

function preferred = localPreferredSlotOrder(statField)
    switch char(string(statField))
        case {'CritRate', 'CritDMG'}
            preferred = [1 2 4 5 3];
        case {'ER', 'EM'}
            preferred = [3 4 5 1 2];
        case {'AtkBonus', 'HPBonus', 'DEFBonus'}
            preferred = [1 2 4 5 3];
        otherwise
            preferred = [1 2 3 4 5];
    end
end

function tf = localMainMatchesSubstat(mainType, statField)
    mainType = lower(char(string(mainType)));
    statField = lower(char(string(statField)));
    switch statField
        case 'atkbonus'
            tf = any(strcmp(mainType, {'atkpct', 'atkbonus'}));
        case 'hpbonus'
            tf = any(strcmp(mainType, {'hppct', 'hpbonus'}));
        case 'defbonus'
            tf = any(strcmp(mainType, {'defpct', 'defbonus'}));
        case 'er'
            tf = any(strcmp(mainType, {'er', 'energyrecharge'}));
        case 'em'
            tf = any(strcmp(mainType, {'em', 'elementalmastery'}));
        case 'critrate'
            tf = any(strcmp(mainType, {'critrate', 'cr'}));
        case 'critdmg'
            tf = any(strcmp(mainType, {'critdmg', 'cd'}));
        case 'flatatk'
            tf = strcmp(mainType, 'flatatk');
        case 'flathp'
            tf = strcmp(mainType, 'flathp');
        case 'flatdef'
            tf = strcmp(mainType, 'flatdef');
        otherwise
            tf = false;
    end
end

function fields = localResidualFieldOrder()
    fields = {'CritRate', 'CritDMG', 'AtkBonus', 'HPBonus', 'DEFBonus', ...
        'ER', 'EM', 'FlatATK', 'FlatHP', 'FlatDEF'};
end

function contribution = localAccumulateStat(contribution, statType, statValue)
    statType = string(statType);
    switch lower(char(statType))
        case {'flatatk'}
            contribution.FlatATK = contribution.FlatATK + statValue;
        case {'flathp'}
            contribution.FlatHP = contribution.FlatHP + statValue;
        case {'flatdef'}
            contribution.FlatDEF = contribution.FlatDEF + statValue;
        case {'atkpct', 'atkbonus', 'atk%'}
            contribution.AtkBonus = contribution.AtkBonus + statValue;
        case {'hppct', 'hpbonus', 'hp%'}
            contribution.HPBonus = contribution.HPBonus + statValue;
        case {'defpct', 'defbonus', 'def%'}
            contribution.DEFBonus = contribution.DEFBonus + statValue;
        case {'er', 'energyrecharge'}
            contribution.ER = contribution.ER + statValue;
        case {'em', 'elementalmastery'}
            contribution.EM = contribution.EM + statValue;
        case {'critrate', 'cr'}
            contribution.CritRate = contribution.CritRate + statValue;
        case {'critdmg', 'cd'}
            contribution.CritDMG = contribution.CritDMG + statValue;
    end
end

function stats = localEmptyStatStruct()
    stats = struct( ...
        'AtkBonus', 0, ...
        'FlatATK', 0, ...
        'HPBonus', 0, ...
        'FlatHP', 0, ...
        'DEFBonus', 0, ...
        'FlatDEF', 0, ...
        'ER', 0, ...
        'EM', 0, ...
        'CritRate', 0, ...
        'CritDMG', 0, ...
        'PyroDMGBonus', 0, ...
        'HydroDMGBonus', 0, ...
        'CryoDMGBonus', 0, ...
        'ElectroDMGBonus', 0, ...
        'AnemoDMGBonus', 0, ...
        'GeoDMGBonus', 0, ...
        'DendroDMGBonus', 0, ...
        'NormalDMGBonus', 0, ...
        'ChargeDMGBonus', 0, ...
        'ChargedDMGBonus', 0, ...
        'PlungeDMGBonus', 0, ...
        'SkillDMGBonus', 0, ...
        'BurstDMGBonus', 0, ...
        'HealingBonus', 0, ...
        'ResShred', 0);
end
