projectRoot = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(projectRoot, 'functions')));
initProjectPaths();
req = [ ...
    struct('Key', "Tighnari", 'Id', "10000069", 'DisplayName', "Tighnari", 'AvatarKey', "Tighnari"), ...
    struct('Key', "KamisatoAyato", 'Id', "10000066", 'DisplayName', "Kamisato Ayato", 'AvatarKey', "Ayato"), ...
    struct('Key', "KukiShinobu", 'Id', "10000065", 'DisplayName', "Kuki Shinobu", 'AvatarKey', "Shinobu"), ...
    struct('Key', "YunJin", 'Id', "10000064", 'DisplayName', "Yun Jin", 'AvatarKey', "Yunjin"), ...
    struct('Key', "Shenhe", 'Id', "10000063", 'DisplayName', "Shenhe", 'AvatarKey', "Shenhe"), ...
    struct('Key', "Yelan", 'Id', "10000060", 'DisplayName', "Yelan", 'AvatarKey', "Yelan"), ...
    struct('Key', "ShikanoinHeizou", 'Id', "10000059", 'DisplayName', "Shikanoin Heizou", 'AvatarKey', "Heizo"), ...
    struct('Key', "YaeMiko", 'Id', "10000058", 'DisplayName', "Yae Miko", 'AvatarKey', "Yae"), ...
    struct('Key', "AratakiItto", 'Id', "10000057", 'DisplayName', "Arataki Itto", 'AvatarKey', "Itto"), ...
    struct('Key', "Gorou", 'Id', "10000055", 'DisplayName', "Gorou", 'AvatarKey', "Gorou") ...
];

summary = importLunarisCharacterData(req, struct('Language', "en", 'Overwrite', true));
disp(summary(:, {'Key', 'Id', 'Status', 'Message'}));
