projectRoot = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(projectRoot, 'functions')));
initProjectPaths();

req = [ ...
    struct('Key', "KamisatoAyaka", 'Id', "10000002", 'DisplayName', "Kamisato Ayaka", 'AvatarKey', "Ayaka"), ...
    struct('Key', "Jean", 'Id', "10000003", 'DisplayName', "Jean", 'AvatarKey', "Qin"), ...
    struct('Key', "Lisa", 'Id', "10000006", 'DisplayName', "Lisa", 'AvatarKey', "Lisa"), ...
    struct('Key', "Barbara", 'Id', "10000014", 'DisplayName', "Barbara", 'AvatarKey', "Barbara"), ...
    struct('Key', "Kaeya", 'Id', "10000015", 'DisplayName', "Kaeya", 'AvatarKey', "Kaeya"), ...
    struct('Key', "Diluc", 'Id', "10000016", 'DisplayName', "Diluc", 'AvatarKey', "Diluc"), ...
    struct('Key', "Razor", 'Id', "10000020", 'DisplayName', "Razor", 'AvatarKey', "Razor"), ...
    struct('Key', "Amber", 'Id', "10000021", 'DisplayName', "Amber", 'AvatarKey', "Amber"), ...
    struct('Key', "Venti", 'Id', "10000022", 'DisplayName', "Venti", 'AvatarKey', "Venti"), ...
    struct('Key', "Xiangling", 'Id', "10000023", 'DisplayName', "Xiangling", 'AvatarKey', "Xiangling") ...
];

summary = importLunarisCharacterData(req, struct('Language', "en", 'Overwrite', true));
disp(summary(:, {'Key', 'Id', 'Status', 'Message'}));
