function [totalDMG, dps, breakdown, rotationTime, audit] = simulateIllugaDPS( ...
        build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Illuga high-detail simulator.
    % Focus:
    % - EM + DEF dual-scaling press/hold skill and burst opener.
    % - Haunted Night's Oriole-Song stack pool from burst, including
    %   Hydro/Geo party scaling and Lunar-Crystallize enhancement tags.
    % - C2 Aedon follow-up triggered every 7 consumed Nightingale stacks.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Illuga', 'rotation_Illuga.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Illuga', 'Constellation', constellation, 'Build', build)}, 20, struct(), enemy);
    end
    teamContext = localStripIllugaSelfSupport(teamContext);

    talent = readtable(char(resolveCharacterDataFile('Illuga', 'talents')));
    skillLevel = localClampTalentLevel(talentLevel + 3 * double(constellation >= 5));
    burstLevel = localClampTalentLevel(talentLevel + 3 * double(constellation >= 3));
    enemyTargetCount = max(1, round(getFieldOrDefault(enemy, 'TargetCount', ...
        getFieldOrDefault(enemy, 'EnemyCount', 1))));

    hydroGeoCount = getFieldOrDefault(teamContext, 'HydroCount', 0) + getFieldOrDefault(teamContext, 'GeoCount', 0);
    moonsignActive = localHasAscendantMoonsignIlluga(teamContext);
    lunarCrystallizeEnabled = logical(getFieldOrDefault(teamContext, 'LunarCrystallizeEnabled', false));
    geoReactionReady = getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'PyroCrystallizeReady', false) ...
        || getFieldOrDefault(teamContext, 'GeoReactionReady', false);

    nightingaleStacks = 21;
    constructStacks = 5 * min(3, getFieldOrDefault(teamContext, 'GeoCount', 0) - 1);
    totalStacks = nightingaleStacks + max(0, constructStacks);
    stackBonusEM = localResolveNightingaleEMWeight(hydroGeoCount, lunarCrystallizeEnabled);
    c2ProcCount = floor(totalStacks / 7) * double(constellation >= 2);

    actions = struct();
    actions.Press = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "PressDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Geo", ...
        'MVOverride', 4.8256, ...
        'ActionScalingMode', "EM", ...
        'FlatDirectDEFWeight', 2.4128, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt", ...
        'LunarisDamageParam', "ElementalArt_Damage", ...
        'CanTriggerReaction', true, ...
        'AllowTransformative', double(geoReactionReady), ...
        'Note', "Dawnbearing Songbird press");
    actions.Hold = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "HoldDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Geo", ...
        'MVOverride', 6.0320, ...
        'ActionScalingMode', "EM", ...
        'FlatDirectDEFWeight', 3.0160, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt", ...
        'LunarisDamageParam', "ElementalArt_Damage", ...
        'CanTriggerReaction', true, ...
        'AllowTransformative', double(geoReactionReady), ...
        'Note', "Dawnbearing Songbird hold");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Geo", ...
        'MVOverride', 8.2720, ...
        'ActionScalingMode', "EM", ...
        'FlatDirectDEFWeight', 4.1360, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'PostSetBurstActiveTime', 20.0, ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "ElementalBurst_Damage", ...
        'CanTriggerReaction', true, ...
        'AllowTransformative', double(geoReactionReady), ...
        'Note', "Shadowless Reflection");
    actions.SongBoost = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Geo", ...
        'MVOverride', 0, ...
        'FlatDirectEMWeight', stackBonusEM, ...
        'HitCount', max(1, min(3, enemyTargetCount)), ...
        'HitTimeline', 0.10 * ones(1, max(1, min(3, enemyTargetCount))), ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'BurstWindowDamageBonus', 0.00, ...
        'Note', "Nightingale's Song support");
    actions.C2Aedon = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Geo", ...
        'MVOverride', 0, ...
        'FlatDirectEMWeight', 4.00, ...
        'FlatDirectDEFWeight', 2.00, ...
        'HitCount', max(1, c2ProcCount), ...
        'HitTimeline', 0.25 * ones(1, max(1, c2ProcCount)), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'CanTriggerReaction', true, ...
        'AllowTransformative', double(geoReactionReady), ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "ElementalBurst_Damage", ...
        'Note', "C2 Aedon follow-up");

    defaultRotation = {'Press', 'Q', 'SongBoost', 'Hold'};
    if constellation >= 2 && c2ProcCount > 0
        defaultRotation{end + 1} = 'C2Aedon'; %#ok<AGROW>
    end

    spec = struct( ...
        'Element', "Geo", ...
        'ScalingMode', "EM", ...
        'DefaultActionTime', 0.85, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct('Press', 0.55, 'Q', 1.00, 'SongBoost', 0.45, 'Hold', 0.85, 'C2Aedon', 0.45), ...
        'InitializeStateFn', @(state, hookContext) localInitializeState(state, hookContext, totalStacks, moonsignActive), ...
        'BeforeActionFn', @localBeforeAction, ...
        'AfterActionFn', @localAfterAction, ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Illuga', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function state = localInitializeState(state, hookContext, totalStacks, moonsignActive) %#ok<INUSD>
    state.Stacks = totalStacks;
    state.CustomValue = double(moonsignActive);
end

function [state, actionSpec, actionTime, note] = localBeforeAction( ...
        state, actionKey, actionSpec, actionTime, note, hookContext)
    if actionKey == "SongBoost"
        consumedStacks = min(getFieldOrDefault(state, 'Stacks', 0), max(1, double(getFieldOrDefault(actionSpec, 'HitCount', 1))));
        actionSpec.HitCount = consumedStacks;
        actionSpec.HitTimeline = 0.10 * ones(1, max(1, consumedStacks));
        if getFieldOrDefault(state, 'CustomValue', 0) > 0
            note = localAppendNote(note, "Moonsign");
        end
        note = localAppendNote(note, "Song x" + string(consumedStacks));
    elseif actionKey == "Press" || actionKey == "Hold" || actionKey == "Q"
        if getFieldOrDefault(state, 'CustomValue', 0) > 0
            note = localAppendNote(note, "Lightkeeper");
        end
    end
end

function [state, note] = localAfterAction(state, actionKey, actionSpec, actionDamage, reactionTags, note, hookContext) %#ok<INUSD>
    if actionKey == "SongBoost"
        consumedStacks = max(1, double(getFieldOrDefault(actionSpec, 'HitCount', 1)));
        state.Stacks = max(0, getFieldOrDefault(state, 'Stacks', 0) - consumedStacks);
        note = localAppendNote(note, "Stacks " + string(state.Stacks));
    end
end

function weight = localResolveNightingaleEMWeight(hydroGeoCount, lunarCrystallizeEnabled)
    hydroGeoCount = max(0, min(3, round(hydroGeoCount)));
    if lunarCrystallizeEnabled
        switch hydroGeoCount
            case 1
                weight = 0.48;
            case 2
                weight = 0.96;
            otherwise
                weight = 1.60 * double(hydroGeoCount >= 3);
        end
        return;
    end

    switch hydroGeoCount
        case 1
            weight = 0.07;
        case 2
            weight = 0.14;
        otherwise
            weight = 0.24 * double(hydroGeoCount >= 3);
    end
end

function tf = localHasAscendantMoonsignIlluga(teamContext)
    tf = hasAscendantMoonsign(teamContext);
end

function teamContext = localStripIllugaSelfSupport(teamContext)
    if logical(getFieldOrDefault(teamContext, 'IllugaSelfSupportRemoved', false))
        return;
    end

    support = getFieldOrDefault(teamContext, 'IllugaSupport', struct());
    teamContext.GeoCritRateBonus = max(0, getFieldOrDefault(teamContext, 'GeoCritRateBonus', 0) - getFieldOrDefault(support, 'GeoCritRateBonus', 0));
    teamContext.GeoCritDMGBonus = max(0, getFieldOrDefault(teamContext, 'GeoCritDMGBonus', 0) - getFieldOrDefault(support, 'GeoCritDMGBonus', 0));
    teamContext.EMBonus = max(0, getFieldOrDefault(teamContext, 'EMBonus', 0) - getFieldOrDefault(support, 'SharedEMBonus', 0));
    teamContext.IllugaSelfSupportRemoved = true;
end

function level = localClampTalentLevel(level)
    level = max(1, min(15, round(level)));
end

function note = localAppendNote(baseNote, suffix)
    if strlength(string(baseNote)) == 0
        note = string(suffix);
    else
        note = string(baseNote) + ", " + string(suffix);
    end
end
