function [totalDMG, dps, breakdown, rotationTime, audit] = simulateEulaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Eula simulator with press/hold skill split, Grimheart consumption,
    % burst opening slash, Lightfall Sword stack approximation, and
    % physical / Cryo split handling.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Eula', 'rotation_Eula.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Eula', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talent = readtable(char(resolveCharacterDataFile('Eula', 'talents')));
    skillLevel = talentLevel + 3 * double(constellation >= 3);
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    grimheartStacks = 2;
    burstStacks = localDefaultBurstStacks(constellation);

    cryoResShred = getTalentValue(talent, 'Skill', 'CryoRESDecrease', skillLevel) * double(grimheartStacks >= 2);
    physResShred = getTalentValue(talent, 'Skill', 'PhysicalRESDecrease', skillLevel) * double(grimheartStacks >= 2);
    burstBonusMV = getTalentValue(talent, 'Burst', 'DMGPerStack', burstLevel) * burstStacks;

    actions = struct();
    actions.EPress1 = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "PressDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'PostAddStacks', 1, ...
        'PostMaxStacks', 2, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Click", ...
        'LunarisDamageParam', "ElementalArt_Click_Damage", ...
        'Note', "Icetide Vortex press 1");
    actions.EPress2 = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "PressDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'PreSetStacks', 1, ...
        'PostAddStacks', 1, ...
        'PostMaxStacks', 2, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Click", ...
        'LunarisDamageParam', "ElementalArt_Click_Damage", ...
        'Note', "Icetide Vortex press 2");
    actions.EHold = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "HoldDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'PreSetStacks', grimheartStacks, ...
        'PostSetStacks', 0, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Burst", ...
        'LunarisDamageParam', "ElementalArt_Burst_Damage", ...
        'Note', "Icetide Vortex hold slash");
    actions.Icewhirl = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "IcewhirlBrandDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'PreSetStacks', grimheartStacks, ...
        'PostSetStacks', 0, ...
        'ExtraResShred', cryoResShred, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_ExtraAttack_1", ...
        'LunarisDamageParam', "ElementalArt_Extra_Damage", ...
        'Note', "Icewhirl Brand");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'PostSetBurstActiveTime', 7.0, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Attack", ...
        'LunarisDamageParam', "Elemental_Burst_Damage", ...
        'Note', "Glacial Illumination cast");
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'PostAddCustomValue', 1, ...
        'ApplyGauge', 0.0, ...
        'ICDRule', "Independent", ...
        'Note', "Normal 1 during burst");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'PostAddCustomValue', 1, ...
        'ApplyGauge', 0.0, ...
        'ICDRule', "Independent", ...
        'Note', "Normal 2 during burst");
    actions.N3 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'PostAddCustomValue', 1, ...
        'ApplyGauge', 0.0, ...
        'ICDRule', "Independent", ...
        'Note', "Normal 3 during burst");
    actions.N4 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x4HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'PostAddCustomValue', 1, ...
        'ApplyGauge', 0.0, ...
        'ICDRule', "Independent", ...
        'Note', "Normal 4 during burst");
    actions.Lightfall = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "LightfallSwordBaseDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'PreSetCustomValue', burstStacks, ...
        'FlatMVBonus', burstBonusMV, ...
        'ExtraResShred', physResShred, ...
        'ApplyGauge', 0.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Judgment", ...
        'LunarisDamageParam', "Elemental_Burst_Judgment_BaseDamage|Elemental_Burst_Judgment_Ratio|Elemental_Burst_Judgment_Damage_Factor|MUL|ADD", ...
        'Note', "Lightfall Sword explosion");

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.60, ...
        'DefaultRotation', {{'EPress1', 'EPress2', 'Q', 'N1', 'N2', 'N3', 'N4', 'EHold', 'Icewhirl', 'N1', 'N2', 'Lightfall'}}, ...
        'ActionTimeMap', struct( ...
            'EPress1', 0.42, ...
            'EPress2', 0.42, ...
            'EHold', 0.82, ...
            'Icewhirl', 0.20, ...
            'Q', 1.05, ...
            'N1', 0.48, ...
            'N2', 0.52, ...
            'N3', 0.60, ...
            'N4', 0.64, ...
            'Lightfall', 0.10), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Eula', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function burstStacks = localDefaultBurstStacks(constellation)
    burstStacks = 12;
    if constellation >= 2
        burstStacks = burstStacks + 1;
    end
    if constellation >= 6
        burstStacks = burstStacks + 5;
    end
end
