function [totalDMG, dps, breakdown, rotationTime, audit] = simulateNingguangDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Ningguang simulator with Star Jade generation, Jade Screen buff window,
    % burst split between core gems and screen gems, and C6 seven-jade follow-up.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Ningguang', 'rotation_Ningguang.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Ningguang', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'PostSetSkillActiveTime', 10.0, ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Geo", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ServantStone_Material", ...
        'LunarisDamageParam', "Elemental_Art_Damage", ...
        'Note', "Jade Screen");
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "NormalAttackDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'PostAddStacks', 1, ...
        'PostMaxStacks', 3, ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Geo", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttackDamage", ...
        'LunarisDamageParam', "NormalAttack_Damage", ...
        'Note', "Normal gem");
    actions.CA = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'SkillWindowDamageBonus', 0.12, ...
        'PostSetStacks', 0, ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Geo", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ExtraAttack_Damage", ...
        'LunarisDamageParam', "ExtraAttack_Damage", ...
        'Note', "Charged attack main hit");
    actions.Jade3 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "DMGPerStarJade", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'SkillWindowDamageBonus', 0.12, ...
        'HitCount', 3, ...
        'HitTimeline', 0.05 * ones(1, 3), ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Geo", ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "GemBullet_Damage", ...
        'LunarisDamageParam', "GemBullet_Damage", ...
        'Note', "Three Star Jades");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "DMGPerGem", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'SkillWindowDamageBonus', 0.12, ...
        'HitCount', 6, ...
        'HitTimeline', 0.08 * ones(1, 6), ...
        'PostC6AddStacks', 7, ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Geo", ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Avatar_ElementalBurst_Bullet_Damage", ...
        'LunarisDamageParam', "ElementalBurst_Bullet_Damage", ...
        'Note', "Starshatter core gems");
    actions.QScreen = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "DMGPerGem", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'SkillWindowDamageBonus', 0.12, ...
        'HitCount', 6, ...
        'HitTimeline', 0.08 * ones(1, 6), ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Geo", ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "GemBullet_Damage", ...
        'LunarisDamageParam', "GemBullet_Damage", ...
        'Note', "Jade Screen extra gems");
    actions.Jade7 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "DMGPerStarJade", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'SkillWindowDamageBonus', 0.12, ...
        'HitCount', 7, ...
        'HitTimeline', 0.05 * ones(1, 7), ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Geo", ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "GemBullet_Damage", ...
        'LunarisDamageParam', "GemBullet_Damage", ...
        'Note', "C6 seven Star Jades");

    defaultRotation = {'E', 'N1', 'N1', 'N1', 'CA', 'Jade3', 'Q', 'QScreen'};
    if constellation >= 6
        defaultRotation = {'E', 'N1', 'N1', 'N1', 'CA', 'Jade3', 'Q', 'QScreen', 'CA', 'Jade7'};
    end

    spec = struct( ...
        'Element', "Geo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.50, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct( ...
            'E', 0.70, ...
            'N1', 0.30, ...
            'CA', 0.55, ...
            'Jade3', 0.18, ...
            'Q', 0.55, ...
            'QScreen', 0.20, ...
            'Jade7', 0.28), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Ningguang', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
