function [totalDMG, dps, breakdown, rotationTime, audit] = simulateDahliaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Dahlia simulator with tap/hold shower variants, burst refresh window,
    % Benison-derived follow-up shield triggers, and HP-based support hooks.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Dahlia', 'rotation_Dahlia.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Dahlia', 'Constellation', constellation, 'Build', build)}, 20, struct(), enemy);
    end

    base = readtable(char(resolveCharacterDataFile('Dahlia', 'characters')));
    normalLevel = localClampTalentLevel(talentLevel);
    skillLevel = localClampTalentLevel(talentLevel + 3 * double(constellation >= 5));
    burstLevel = localClampTalentLevel(talentLevel + 3 * double(constellation >= 3));
    freezeReady = getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1;
    hydroAmplifyReady = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1;
    benisonStacks = 2 + 2 * double(freezeReady);
    benisonRefreshCount = min(4, benisonStacks);
    refreshTimeline = 2.20 * ones(1, max(1, benisonRefreshCount));
    burstDuration = 12.0 + 3.0 * double(constellation >= 4);
    favonianATKSpeed = min(0.20, 0.005 * (base.BaseHP(1) * (1 + getFieldOrDefault(build, 'HPBonus', 0)) ...
        + getFieldOrDefault(build, 'FlatHP', 0)) / 1000);
    if constellation >= 6
        favonianATKSpeed = favonianATKSpeed + 0.10;
    end

    actions = struct();
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'CanApplyAura', false, ...
        'Note', "Normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'CanApplyAura', false, ...
        'Note', "Normal 2");
    actions.N3 = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'CanApplyAura', false, ...
        'Note', "Normal 3");
    actions.N4 = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "x4HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'CanApplyAura', false, ...
        'Note', "Normal 4");
    actions.CA = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'CanApplyAura', false, ...
        'Note', "Charged attack");
    actions.ETap = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'HitTimeline', 0.60, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "SkillObj_Jackbox", ...
        'LunarisDamageParam', "ElementalArt_Damage", ...
        'AllowAmplify', double(hydroAmplifyReady), ...
        'PreferredAmplifyAura', localResolveDahliaAura(teamContext), ...
        'AllowTransformative', double(freezeReady), ...
        'Note', "Sacramental Shower tap detonation");
    actions.EHold = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'HitTimeline', 0.88, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "SkillObj_Jackbox", ...
        'LunarisDamageParam', "ElementalArt_Damage", ...
        'AllowAmplify', double(hydroAmplifyReady), ...
        'PreferredAmplifyAura', localResolveDahliaAura(teamContext), ...
        'AllowTransformative', double(freezeReady), ...
        'Note', "Sacramental Shower hold detonation");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'PostSetBurstActiveTime', burstDuration, ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "ElementalBurst_Damage", ...
        'AllowAmplify', double(hydroAmplifyReady), ...
        'PreferredAmplifyAura', localResolveDahliaAura(teamContext), ...
        'AllowTransformative', double(freezeReady), ...
        'Note', "Radiant Psalter");
    actions.Refresh = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "ShieldOfSacredFavorDMGAbsorption", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "None", ...
        'MVOverride', 0, ...
        'BaseMultiplier', 0.00, ...
        'HitCount', benisonRefreshCount, ...
        'HitTimeline', refreshTimeline, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'Note', "Benison refresh utility");

    defaultRotation = {'ETap', 'Q', 'N1', 'N2', 'N3', 'N4'};
    if freezeReady
        defaultRotation = {'EHold', 'Q', 'N1', 'N2', 'N3', 'N4'};
    end

    spec = struct( ...
        'Element', "Hydro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.85, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct('N1', 0.34, 'N2', 0.34, 'N3', 0.40, 'N4', 0.50, ...
            'CA', 0.72, 'ETap', 0.60, 'EHold', 0.88, 'Q', 1.00, 'Refresh', 0.01), ...
        'InitializeStateFn', @(state, hookContext) localInitializeState(state, hookContext, favonianATKSpeed), ...
        'BeforeActionFn', @localBeforeAction, ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Dahlia', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function aura = localResolveDahliaAura(teamContext)
    if getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1
        aura = "Pyro";
    elseif getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1
        aura = "Cryo";
    else
        aura = "";
    end
end

function state = localInitializeState(state, hookContext, favonianATKSpeed) %#ok<INUSD>
    state.FavonianATKSpeed = favonianATKSpeed;
end

function [state, actionSpec, actionTime, note] = localBeforeAction( ...
        state, actionKey, actionSpec, actionTime, note, hookContext) %#ok<INUSD>
    if getFieldOrDefault(state, 'BurstActiveTime', 0) > 1e-6 && any(actionKey == ["N1", "N2", "N3", "N4"])
        atkSpeed = max(0, getFieldOrDefault(state, 'FavonianATKSpeed', 0));
        if atkSpeed > 0
            actionTime = actionTime / (1 + atkSpeed);
            note = localAppendNote(note, "Favonian Favor SPD");
        end
    end
end

function note = localAppendNote(baseNote, suffix)
    if strlength(string(baseNote)) == 0
        note = string(suffix);
    else
        note = string(baseNote) + ", " + string(suffix);
    end
end

function level = localClampTalentLevel(level)
    level = max(1, min(15, round(level)));
end
