function [totalDMG, dps, breakdown, rotationTime, audit] = simulateFischlDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Fischl 高精度近似模拟。
    % 建模重点：
    % 1. 将召唤 Oz、Oz 后台射击、元素爆发起手命中拆开；
    % 2. 为主要雷伤命中补上显式 ApplyGauge / ICD / Lunaris 攻击映射；
    % 3. 先覆盖反应最敏感的主要命中，A4 / C6 额外追击留待后续细抠。
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Fischl', 'rotation_Fischl.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Fischl', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    summonExtraAtk = 2.00 * double(constellation >= 2);
    burstExtraAtk = 2.22 * double(constellation >= 4);
    ozHitTimeline = ones(1, 10);

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SummoningDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'FlatDirectATKWeight', summonExtraAtk, ...
        'LunarisAttackName', "Ability_Skill_S_CrowSummon", ...
        'LunarisDamageParam', "AS_Fischl_ProudSkill_32_P2_SummonAttack", ...
        'ApplyGauge', 1.0, 'ICDGroup', "Fischl_Oz", 'ICDRule', "4 hits / 5s", ...
        'Note', "Nightrider summon hit");
    actions.Oz = struct('TalentGroup', "Skill", 'Param', "OzsATKDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'HitCount', numel(ozHitTimeline), ...
        'HitTimeline', ozHitTimeline, 'AllowCatalyze', double(aggravateReady), ...
        'LunarisAttackName', "Skill_S_Crow_AutoAttack_Hit_01", ...
        'LunarisDamageParam', "AS_Fischl_ProudSkill_32_Damage_AttackRatio", ...
        'ApplyGauge', 1.0, 'ICDGroup', "Fischl_Oz", 'ICDRule', "4 hits / 5s", ...
        'Note', "Oz turret shots");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "FallingThunderDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'FlatDirectATKWeight', burstExtraAtk, ...
        'LunarisAttackName', "Ability_Skill_E_CrowQueen", ...
        'LunarisDamageParam', "AS_Fischl_Talent_334_OnceDamage_AttackRatio", ...
        'ApplyGauge', 2.0, 'ICDGroup', "Fischl_Oz", 'ICDRule', "4 hits / 5s", ...
        'Note', "Midnight Phantasmagoria impact");
    actions.QOz = struct('TalentGroup', "Skill", 'Param', "OzsATKDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'HitCount', numel(ozHitTimeline), ...
        'HitTimeline', ozHitTimeline, 'AllowCatalyze', double(aggravateReady), ...
        'LunarisAttackName', "Skill_S_Crow_AutoAttack_Hit_01", ...
        'LunarisDamageParam', "AS_Fischl_ProudSkill_32_Damage_AttackRatio", ...
        'ApplyGauge', 1.0, 'ICDGroup', "Fischl_Oz", 'ICDRule', "4 hits / 5s", ...
        'Note', "Oz shots after burst refresh");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.80, ...
        'DefaultRotation', {{'E', 'Oz', 'Q', 'QOz'}}, ...
        'ActionTimeMap', struct('E', 0.70, 'Oz', 10.00, 'Q', 1.10, 'QOz', 10.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Fischl', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
