function [totalDMG, dps, breakdown, rotationTime, audit] = simulateFischlDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Fischl explicit summon / Oz / burst refresh script with approximation.
    % Summon impact, Oz turret shots, burst impact, and Oz refresh shots are
    % modeled as separate actions with explicit gauge and ICD data.
    % Remaining approximation: standalone AUTO rotation still does not infer
    % how often A4 and C6 follow-up attacks should be triggered.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Fischl', 'rotation_Fischl.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Fischl', 'Constellation', constellation, 'Build', build)}, 20, struct(), enemy);
    end

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    summonExtraAtk = 2.00 * double(constellation >= 2);
    burstExtraAtk = 2.22 * double(constellation >= 4);
    a4RetributionAtkWeight = 0.80; % Passive A4: Undone Be Thy Sinful Hex.
    jointAttackAtkWeight = 0.30 * double(constellation >= 6); % C6: Evernight Raven.
    ozHitTimeline = ones(1, 10);

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SummoningDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'FlatDirectATKWeight', summonExtraAtk, ...
        'LunarisAttackName', "Ability_Skill_S_CrowSummon", ...
        'LunarisDamageParam', "AS_Fischl_ProudSkill_32_P2_SummonAttack", ...
        'ApplyGauge', 1.0, 'ICDGroup', "Fischl_Oz", 'ICDRule', "4 hits / 5s", ...
        'Note', "Nightrider summon hit");
    actions.Oz = struct('TalentGroup', "Skill", 'Param', "OzsATKDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'HitCount', numel(ozHitTimeline), ...
        'HitTimeline', ozHitTimeline, 'AllowCatalyze', double(aggravateReady), ...
        'LunarisAttackName', "Skill_S_Crow_AutoAttack_Hit_01", ...
        'LunarisDamageParam', "AS_Fischl_ProudSkill_32_Damage_AttackRatio", ...
        'ApplyGauge', 1.0, 'ICDGroup', "Fischl_Oz", 'ICDRule', "4 hits / 5s", ...
        'Note', "Oz turret shots");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "FallingThunderDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'FlatDirectATKWeight', burstExtraAtk, ...
        'LunarisAttackName', "Ability_Skill_E_CrowQueen", ...
        'LunarisDamageParam', "AS_Fischl_Talent_334_OnceDamage_AttackRatio", ...
        'ApplyGauge', 2.0, 'ICDGroup', "Fischl_Oz", 'ICDRule', "4 hits / 5s", ...
        'Note', "Midnight Phantasmagoria impact");
    actions.QOz = struct('TalentGroup', "Skill", 'Param', "OzsATKDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'HitCount', numel(ozHitTimeline), ...
        'HitTimeline', ozHitTimeline, 'AllowCatalyze', double(aggravateReady), ...
        'LunarisAttackName', "Skill_S_Crow_AutoAttack_Hit_01", ...
        'LunarisDamageParam', "AS_Fischl_ProudSkill_32_Damage_AttackRatio", ...
        'ApplyGauge', 1.0, 'ICDGroup', "Fischl_Oz", 'ICDRule', "4 hits / 5s", ...
        'Note', "Oz shots after burst refresh");
    actions.OzJointAttack = struct('TalentGroup', "Skill", 'Param', "OzsATKDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'MVOverride', 0, 'FlatDirectATKWeight', jointAttackAtkWeight, ...
        'AllowCatalyze', double(aggravateReady), ...
        'LunarisAttackName', "Talent_D_Crow_NormalAttack_01", ...
        'LunarisDamageParam', "AS_Fischl_Talent_336_AttackRatio_AssistAttack", ...
        'ApplyGauge', 1.0, 'ICDGroup', "Fischl_Oz", 'ICDRule', "4 hits / 5s", ...
        'Note', "C6 Oz coordinated attack");
    actions.OzA4Retribution = struct('TalentGroup', "Skill", 'Param', "OzsATKDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'MVOverride', 0, 'FlatDirectATKWeight', a4RetributionAtkWeight, ...
        'AllowCatalyze', double(aggravateReady), ...
        'LunarisAttackName', "Talent_ElementReactionAttackThunder_Hit", ...
        'LunarisDamageParam', "AS_Fischl_ProudSkill_22_ElementReactionAttack_AttackRatio", ...
        'ApplyGauge', 1.0, 'ICDGroup', "Fischl_Oz", 'ICDRule', "4 hits / 5s", ...
        'Note', "A4 Thundering Retribution");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.80, ...
        'DefaultRotation', {{'E', 'Oz', 'Q', 'QOz'}}, ...
        'ActionTimeMap', struct('E', 0.70, 'Oz', 10.00, 'Q', 1.10, 'QOz', 10.00, ...
            'OzJointAttack', 0.05, 'OzA4Retribution', 0.05), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Fischl', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
