function [totalDMG, dps, breakdown, rotationTime] = simulateSigewinneDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Sigewinne medium-detail simulator with HP-scaling hydro actions.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Sigewinne', 'rotation_Sigewinne.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Sigewinne', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "BubbleHP", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetSkillActiveTime', 10.0, 'PostSetMarks', 2, ...
        'C1DamageBonus', 0.08, 'Note', "Bubble shot");
    actions.Follow = struct('TalentGroup', "Skill", 'Param', "FollowHP", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PerMarkMultiplier', 0.14, 'SkillWindowMultiplier', 0.06, ...
        'PostAddMarks', -1, 'PostSetStacks', 1, 'Note', "Support bubble hit");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "BurstHP", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'AllowAmplify', 1, 'ReactionBonus', 0.12, 'PostSetBurstActiveTime', 12.0, ...
        'C2CritRateBonus', 0.10, 'C6CritDMGBonus', 0.35, 'Note', "Burst beam");
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "N1ATK", 'DamageField', "NormalDMGBonus", ...
        'BaseMultiplier', 1.00, 'Note', "Normal attack");

    spec = struct( ...
        'Element', "Hydro", ...
        'ScalingMode', "HP", ...
        'PreferredAmplifyAura', "Pyro", ...
        'DefaultActionTime', 0.8, ...
        'ActionTimeMap', struct('E', 0.65, 'Follow', 1.05, 'Q', 1.20, 'N1', 0.45), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Sigewinne', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
