function [totalDMG, dps, breakdown, rotationTime, audit] = simulateSigewinneDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Sigewinne simulator emphasizing HP-scaled bubble hits and short burst.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Sigewinne', 'rotation_Sigewinne.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Sigewinne', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "BolsteringBubblebalmDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'ActionScalingMode', "HP", 'HitCount', 5, 'PostSetSkillActiveTime', 18.0, ...
        'Note', "Bolstering Bubblebalm");
    actions.Follow = struct('TalentGroup', "Skill", 'Param', "SurgingBladeDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'ActionScalingMode', "HP", 'HitCount', 2, 'C1DamageBonus', 0.08, 'Note', "Surging blade");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'ActionScalingMode', "HP", 'PostSetBurstActiveTime', 2.5, 'C2CritRateBonus', 0.10, ...
        'Note', "Super Saturated Syringing");

    spec = struct( ...
        'Element', "Hydro", ...
        'ScalingMode', "HP", ...
        'DefaultActionTime', 0.85, ...
        'DefaultRotation', {{'E', 'Q', 'Follow', 'Follow', 'Follow'}}, ...
        'ActionTimeMap', struct('E', 1.20, 'Follow', 2.50, 'Q', 0.95), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Sigewinne', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

