function build = customArtifact_Collei()
    % Default Collei build focusing on skill and burst Dendro application damage.
    build = struct( ...
        'Weapon', 'TheStringless', ...
        'WeaponATK', 510, ...
        'AtkBonus', 0.46, ...
        'FlatATK', 150, ...
        'ER', 1.60, ...
        'CritRate', 0.60, ...
        'CritDMG', 1.50, ...
        'DendroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.24, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'DeepwoodMemories', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Collei', 'artifacts_Collei.csv');
    writetable(struct2table(build), outputPath);
end
