function [totalDMG, dps, breakdown, rotationTime] = simulateColleiDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Collei simulator modeling boomerang passes and burst leaps.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Collei', 'rotation_Collei.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Collei', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    spreadReady = getFieldOrDefault(teamContext, 'ElectroCount', 0) >= 1;
    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'HitCount', 2, ...
        'AllowCatalyze', double(spreadReady), 'Note', "Floral Brush boomerang");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "ExplosionDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(spreadReady), ...
        'PostSetBurstActiveTime', 6.0, 'Note', "Trump-Card Kitty explosion");
    actions.Leap = struct('TalentGroup', "Burst", 'Param', "LeapDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'HitCount', 6 + 2 * double(constellation >= 2), ...
        'AllowCatalyze', double(spreadReady), 'Note', "Burst leaps");
    actions.C6Sprout = struct('TalentGroup', "Burst", 'Param', "LeapDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 0.80, 'HitCount', 2, 'AllowCatalyze', double(spreadReady), ...
        'Note', "C6 extra sprouts");

    defaultRotation = {'E', 'Q', 'Leap'};
    if constellation >= 6
        defaultRotation = {'E', 'Q', 'Leap', 'C6Sprout'};
    end

    spec = struct( ...
        'Element', "Dendro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.80, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct('E', 0.80, 'Q', 0.95, 'Leap', 6.00, 'C6Sprout', 0.20), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Collei', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
