function [totalDMG, dps, breakdown, rotationTime] = simulateColleiDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Collei simulator modeling boomerang passes and burst leaps.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Collei', 'rotation_Collei.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Collei', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    spreadReady = getFieldOrDefault(teamContext, 'ElectroCount', 0) >= 1;
    actions = struct();
    actions.EGo = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'ApplyGauge', 1.0, ...
        'LunarisAttackName', "Bullet_ElementalArt_Bullet", 'LunarisDamageParam', "ElementalArt_DMG", ...
        'ICDGroup', "Collei_Boomerang_Go", 'ICDRule', "11 hits / 5s", 'AllowCatalyze', double(spreadReady), ...
        'Note', "Floral Brush boomerang go");
    actions.EBack = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'ApplyGauge', 1.0, ...
        'LunarisAttackName', "Bullet_ElementalArt_Bullet", 'LunarisDamageParam', "ElementalArt_DMG", ...
        'ICDGroup', "Collei_Boomerang_Back", 'ICDRule', "11 hits / 5s", 'AllowCatalyze', double(spreadReady), ...
        'Note', "Floral Brush boomerang back");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "ExplosionDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(spreadReady), ...
        'PostSetBurstActiveTime', 6.0, 'ApplyGauge', 1.0, ...
        'LunarisAttackName', "SkillObj_ElementalBurst_Dummy", 'LunarisDamageParam', "Elemental_Burst_DMG1", ...
        'ICDGroup', "Collei_Elemental_Burst", 'ICDRule', "12 hits / 3s", 'Note', "Trump-Card Kitty explosion");
    actions.Leap = struct('TalentGroup', "Burst", 'Param', "LeapDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'HitCount', 6 + 2 * double(constellation >= 2), ...
        'ApplyGauge', 1.0, 'LunarisAttackName', "SkillObj_ElementalBurst_Dummy_Cat", 'LunarisDamageParam', "Elemental_Burst_DMG2", ...
        'ICDGroup', "Collei_Elemental_Burst", 'ICDRule', "12 hits / 3s", 'AllowCatalyze', double(spreadReady), 'Note', "Burst leaps");
    actions.C6Sprout = struct('TalentGroup', "Burst", 'Param', "LeapDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 0.80, 'HitCount', 2, 'ApplyGauge', 1.0, ...
        'LunarisAttackName', "SkillObj_ElementalBurst_Dummy_Cat_Talent", 'LunarisDamageParam', "Elemental_Burst_DMG_Talent", ...
        'ICDGroup', "Collei_Constellation_6", 'ICDRule', "Independent", 'AllowCatalyze', double(spreadReady), ...
        'Note', "C6 extra sprouts");

    defaultRotation = {'EGo', 'EBack', 'Q', 'Leap'};
    if constellation >= 6
        defaultRotation = {'EGo', 'EBack', 'Q', 'Leap', 'C6Sprout'};
    end

    spec = struct( ...
        'Element', "Dendro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.80, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct('EGo', 0.35, 'EBack', 0.35, 'Q', 0.95, 'Leap', 6.00, 'C6Sprout', 0.20), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Collei', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
