function build = customArtifact_Jahoda()
    % Default Jahoda build for anemo bow damage and burst uptime.
    build = struct( ...
        'Weapon', 'Polar Star', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.331, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.88, ...
        'FlatATK', 311, ...
        'EM', 120, ...
        'ER', 1.25, ...
        'CritRate', 0.80, ...
        'CritDMG', 2.02, ...
        'AnemoDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.15, ...
        'SkillDMGBonus', 0.22, ...
        'BurstDMGBonus', 0.22, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'ViridescentVenerer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Jahoda', 'artifacts_Jahoda.csv');
    if exist(fileparts(outputPath), 'dir') ~= 7
        mkdir(fileparts(outputPath));
    end
    writetable(struct2table(build), outputPath);
end
