function [totalDMG, dps, breakdown, rotationTime, audit] = simulateJahodaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Jahoda simulator with smoke-bomb fallback, flask discharge,
    % Moonsign meowball cadence, and timeline-aware robot conversion.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Jahoda', 'rotation_Jahoda.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Jahoda', 'Constellation', constellation, 'Build', build)}, 20, struct(), enemy);
    end

    normalLevel = localClampTalentLevel(talentLevel);
    skillLevel = localClampTalentLevel(talentLevel + 3 * double(constellation >= 5));
    burstLevel = localClampTalentLevel(talentLevel + 3 * double(constellation >= 3));
    pyroCount = getFieldOrDefault(teamContext, 'PyroCount', 0);
    hydroCount = getFieldOrDefault(teamContext, 'HydroCount', 0);
    electroCount = getFieldOrDefault(teamContext, 'ElectroCount', 0);
    cryoCount = getFieldOrDefault(teamContext, 'CryoCount', 0);
    enemyTargetCount = max(1, round(getFieldOrDefault(enemy, 'TargetCount', getFieldOrDefault(enemy, 'EnemyCount', 1))));

    dominantElement = localResolveJahodaElement(teamContext);
    convertedElement = dominantElement;
    conversionReady = strlength(convertedElement) > 0;
    if ~conversionReady
        convertedElement = "Hydro";
    end
    moonsignActive = hasAscendantMoonsign(teamContext);
    enhancementElements = localResolveJahodaEnhancementElements(teamContext, constellation, moonsignActive);
    robotCount = 2 + double(any(strcmpi(enhancementElements, 'Electro')));
    robotInterval = 2.20 * (1 - 0.10 * double(any(strcmpi(enhancementElements, 'Cryo'))));
    robotHitCount = max(1, floor(12.0 / robotInterval));
    robotTimeline = robotInterval * ones(1, robotHitCount);
    robotDamageBonus = 0.30 * double(any(strcmpi(enhancementElements, 'Pyro')));
    meowballCount = 3;
    if moonsignActive
        meowballCount = 4;
    end
    meowballTimeline = 1.00 * ones(1, meowballCount);
    bounceCount = max(1, double(constellation >= 1) * meowballCount);
    bounceTimeline = 0.10 * ones(1, bounceCount);
    critSupportRate = 0.05 * double(constellation >= 6 && moonsignActive);
    critSupportDmg = 0.40 * double(constellation >= 6 && moonsignActive);
    critWindowDuration = 20.0 * double(constellation >= 6 && moonsignActive);

    allowConvertedAmplify = conversionReady && any(strcmpi(convertedElement, {'Hydro', 'Pyro', 'Cryo'}));
    allowConvertedCatalyze = conversionReady && strcmpi(convertedElement, 'Electro');
    allowConvertedTransformative = conversionReady && any(strcmpi(convertedElement, {'Hydro', 'Pyro', 'Cryo', 'Electro'}));

    actions = struct();
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'CanApplyAura', false, ...
        'Note', "Normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', 2, ...
        'HitTimeline', [0.00, 0.06], ...
        'CanApplyAura', false, ...
        'Note', "Normal 2 dual hit");
    actions.N3 = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'CanApplyAura', false, ...
        'Note', "Normal 3");
    actions.Aimed = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "FullyChargedAimedShot", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Bullet_ShootArrow_Enchanted_WithWind", ...
        'LunarisDamageParam', "DamageWithWind", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Fully charged shot");
    actions.Smoke = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "SmokeBombDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt", ...
        'LunarisDamageParam', "ElementalArt_SmokeAttack", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Smoke bomb");
    actions.FlaskPartial = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "UnfilledTreasureFlaskDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Second_Attack", ...
        'LunarisDamageParam', "ElementalArt_AvatarExplode_Uncharged", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Unfilled flask discharge");
    actions.FlaskFull = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "FilledTreasureFlaskDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Second_Attack", ...
        'LunarisDamageParam', "ElementalArt_AvatarExplode", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'PostSetSkillActiveTime', critWindowDuration, ...
        'Note', "Filled flask discharge");
    actions.Meowball = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "MeowballDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', convertedElement, ...
        'BaseMultiplier', double(conversionReady), ...
        'HitCount', meowballCount, ...
        'HitTimeline', meowballTimeline, ...
        'ApplyGauge', double(conversionReady), ...
        'ICDGroup', "Jahoda_Meowball", ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Bullet_ElementalArt_Attack", ...
        'LunarisDamageParam', "ElementalArt_BulletExplode", ...
        'CanApplyAura', conversionReady, ...
        'CanTriggerReaction', conversionReady, ...
        'AllowAmplify', double(allowConvertedAmplify), ...
        'AllowCatalyze', double(allowConvertedCatalyze), ...
        'AllowTransformative', double(allowConvertedTransformative), ...
        'PreferredAmplifyAura', localResolveJahodaAura(convertedElement, teamContext), ...
        'SkillWindowCritRateBonus', critSupportRate, ...
        'SkillWindowCritDMGBonus', critSupportDmg, ...
        'Note', localBuildJahodaConversionNote("Fluffy Meowball", convertedElement));
    actions.MeowBounce = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "MeowballDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', convertedElement, ...
        'BaseMultiplier', 0.50 * double(conversionReady) * double(enemyTargetCount >= 2), ...
        'HitCount', bounceCount, ...
        'HitTimeline', bounceTimeline, ...
        'ApplyGauge', double(conversionReady), ...
        'ICDGroup', "Jahoda_Meowball_C1", ...
        'ICDRule', "2 hits / 15s", ...
        'LunarisAttackName', "Bullet_ElementalArt_Attack", ...
        'LunarisDamageParam', "ElementalArt_BulletExplode", ...
        'CanApplyAura', conversionReady, ...
        'CanTriggerReaction', conversionReady, ...
        'AllowAmplify', double(allowConvertedAmplify), ...
        'AllowCatalyze', double(allowConvertedCatalyze), ...
        'AllowTransformative', double(allowConvertedTransformative), ...
        'PreferredAmplifyAura', localResolveJahodaAura(convertedElement, teamContext), ...
        'SkillWindowCritRateBonus', critSupportRate, ...
        'SkillWindowCritDMGBonus', critSupportDmg, ...
        'Note', localBuildJahodaConversionNote("C1 Meowball bounce", convertedElement));
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'PostSetBurstActiveTime', 12.0, ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "ElementalBurst_AvatarExplode", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'SkillWindowCritRateBonus', critSupportRate, ...
        'SkillWindowCritDMGBonus', critSupportDmg, ...
        'Note', "Hidden Aces cast");
    actions.Robot = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "PurrsonalCoordinatedAssistanceRobotDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', convertedElement, ...
        'BaseMultiplier', double(conversionReady) * robotCount * (1 + robotDamageBonus), ...
        'HitCount', robotHitCount, ...
        'HitTimeline', robotTimeline, ...
        'ApplyGauge', double(conversionReady), ...
        'ICDGroup', "Jahoda_Robot", ...
        'ICDRule', "4 hits / 15s", ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "ElementalBurst_BulletExplode", ...
        'CanApplyAura', conversionReady, ...
        'CanTriggerReaction', conversionReady, ...
        'AllowAmplify', double(allowConvertedAmplify), ...
        'AllowCatalyze', double(allowConvertedCatalyze), ...
        'AllowTransformative', double(allowConvertedTransformative), ...
        'PreferredAmplifyAura', localResolveJahodaAura(convertedElement, teamContext), ...
        'SkillWindowCritRateBonus', critSupportRate, ...
        'SkillWindowCritDMGBonus', critSupportDmg, ...
        'Note', localBuildJahodaConversionNote("Purrsonal coordinated robots", convertedElement));

    if conversionReady
        defaultRotation = {'FlaskFull'};
        if moonsignActive
            defaultRotation{end + 1} = 'Meowball'; %#ok<AGROW>
            if constellation >= 1
                defaultRotation{end + 1} = 'MeowBounce'; %#ok<AGROW>
            end
        end
        defaultRotation{end + 1} = 'Q'; %#ok<AGROW>
        defaultRotation{end + 1} = 'Robot'; %#ok<AGROW>
    else
        defaultRotation = {'Smoke', 'FlaskPartial', 'Q'};
    end

    spec = struct( ...
        'Element', "Anemo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.75, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct('N1', 0.35, 'N2', 0.34, 'N3', 0.42, 'Aimed', 0.80, ...
            'Smoke', 0.55, 'FlaskPartial', 0.85, 'FlaskFull', 0.90, 'Meowball', 4.20, ...
            'MeowBounce', 0.45, 'Q', 1.05, 'Robot', max(2.4, sum(robotTimeline))), ...
        'InitializeStateFn', @(state, hookContext) localInitializeState(state, hookContext, moonsignActive), ...
        'BeforeActionFn', @localBeforeAction, ...
        'AfterActionFn', @localAfterAction, ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Jahoda', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function element = localResolveJahodaElement(teamContext)
    [timelineElement, usedTimeline] = localResolveJahodaElementFromTimeline(teamContext);
    if usedTimeline
        element = timelineElement;
        return;
    end

    priority = ["Pyro", "Hydro", "Electro", "Cryo"];
    counts = [ ...
        getFieldOrDefault(teamContext, 'PyroCount', 0), ...
        getFieldOrDefault(teamContext, 'HydroCount', 0), ...
        getFieldOrDefault(teamContext, 'ElectroCount', 0), ...
        getFieldOrDefault(teamContext, 'CryoCount', 0)];

    element = "";
    bestCount = 0;
    for i = 1:numel(priority)
        if counts(i) > bestCount
            bestCount = counts(i);
            element = priority(i);
        end
    end
end

function [element, usedTimeline] = localResolveJahodaElementFromTimeline(teamContext)
    element = "";
    usedTimeline = false;

    timelineTable = getFieldOrDefault(teamContext, 'TimelineTable', table());
    if isempty(timelineTable) || ~istable(timelineTable) || height(timelineTable) == 0
        return;
    end
    if ~all(ismember({'Character', 'Action', 'StartTime'}, timelineTable.Properties.VariableNames))
        return;
    end

    rowCharacters = string(timelineTable.Character);
    rowActions = string(timelineTable.Action);
    anchorMask = strcmpi(rowCharacters, "Jahoda") ...
        & any(rowActions == ["FlaskFull", "FlaskPartial", "Smoke", "Q"], 2);
    if ~any(anchorMask)
        return;
    end

    usedTimeline = true;
    anchorRow = localResolveJahodaAnchorRow(timelineTable(anchorMask, :));
    priorRows = localResolveJahodaPriorRows(timelineTable, anchorRow);
    if isempty(priorRows)
        return;
    end

    latestRow = priorRows(end, :);
    if ismember('AuraState', latestRow.Properties.VariableNames)
        auraState = string(latestRow.AuraState(1));
        if strlength(strtrim(auraState)) > 0
            element = localResolveJahodaAuraStateElement(auraState);
            return;
        end
    end

    element = localResolveJahodaElementFromRecentHits(priorRows);
end

function anchorRow = localResolveJahodaAnchorRow(rows)
    sortKey = double(rows.StartTime);
    if ismember('Order', rows.Properties.VariableNames)
        sortRows = [sortKey, double(rows.Order), (1:height(rows)).'];
        sortRows = sortrows(sortRows, [1 2 3]);
        order = sortRows(:, 3);
    else
        [~, order] = sort(sortKey);
    end
    anchorRow = rows(order(1), :);
end

function priorRows = localResolveJahodaPriorRows(timelineTable, anchorRow)
    startTimes = double(timelineTable.StartTime);
    priorMask = startTimes < double(anchorRow.StartTime(1)) - 1e-9;

    if ismember('Order', timelineTable.Properties.VariableNames) ...
            && ismember('Order', anchorRow.Properties.VariableNames)
        sameTimeMask = abs(startTimes - double(anchorRow.StartTime(1))) <= 1e-9 ...
            & double(timelineTable.Order) < double(anchorRow.Order(1));
        priorMask = priorMask | sameTimeMask;
    end

    priorRows = timelineTable(priorMask, :);
    if isempty(priorRows)
        return;
    end

    if ismember('Order', priorRows.Properties.VariableNames)
        sortRows = [double(priorRows.StartTime), double(priorRows.Order), (1:height(priorRows)).'];
        sortRows = sortrows(sortRows, [1 2 3]);
        priorRows = priorRows(sortRows(:, 3), :);
    else
        [~, order] = sort(double(priorRows.StartTime));
        priorRows = priorRows(order, :);
    end
end

function element = localResolveJahodaAuraStateElement(auraState)
    element = "";
    priority = localResolveJahodaPriority();
    auraText = string(auraState);
    for i = 1:numel(priority)
        if contains(auraText, priority(i) + ":", 'IgnoreCase', true)
            element = priority(i);
            return;
        end
    end
end

function element = localResolveJahodaElementFromRecentHits(priorRows)
    element = "";
    if isempty(priorRows)
        return;
    end

    hitElements = repmat("", height(priorRows), 1);
    if ismember('HitElement', priorRows.Properties.VariableNames)
        hitElements = string(priorRows.HitElement);
    end

    applyGauge = zeros(height(priorRows), 1);
    if ismember('ApplyGauge', priorRows.Properties.VariableNames)
        applyGauge = double(priorRows.ApplyGauge);
    end

    priority = localResolveJahodaPriority();
    for rowIndex = height(priorRows):-1:1
        if applyGauge(rowIndex) <= 0
            continue;
        end

        rowElement = string(hitElements(rowIndex));
        if any(strcmpi(rowElement, priority))
            element = localResolveJahodaPriorityElement(rowElement);
            return;
        end
    end
end

function priority = localResolveJahodaPriority()
    priority = ["Pyro", "Hydro", "Electro", "Cryo"];
end

function element = localResolveJahodaPriorityElement(element)
    priority = localResolveJahodaPriority();
    element = string(element);
    for i = 1:numel(priority)
        if strcmpi(element, priority(i))
            element = priority(i);
            return;
        end
    end
    element = "";
end

function aura = localResolveJahodaAura(element, teamContext)
    switch lower(char(string(element)))
        case 'hydro'
            aura = "Pyro";
            if getFieldOrDefault(teamContext, 'PyroCount', 0) <= 0
                aura = "";
            end
        case 'pyro'
            if getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1
                aura = "Hydro";
            elseif getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1
                aura = "Cryo";
            else
                aura = "";
            end
        case 'cryo'
            if getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1
                aura = "Pyro";
            else
                aura = "";
            end
        otherwise
            aura = "";
    end
end

function elements = localResolveJahodaEnhancementElements(teamContext, constellation, moonsignActive)
    priority = ["Pyro", "Hydro", "Electro", "Cryo"];
    counts = [ ...
        getFieldOrDefault(teamContext, 'PyroCount', 0), ...
        getFieldOrDefault(teamContext, 'HydroCount', 0), ...
        getFieldOrDefault(teamContext, 'ElectroCount', 0), ...
        getFieldOrDefault(teamContext, 'CryoCount', 0)];

    [~, order] = sortrows([(-counts(:)) (1:numel(priority)).']);
    sortedPriority = priority(order);
    sortedCounts = counts(order);
    elements = sortedPriority(sortedCounts > 0);
    if isempty(elements)
        elements = strings(1, 0);
        return;
    end

    if ~(moonsignActive && constellation >= 2)
        elements = elements(1);
    else
        elements = elements(1:min(2, numel(elements)));
    end
end

function state = localInitializeState(state, hookContext, moonsignActive) %#ok<INUSD>
    state.CustomValue = double(moonsignActive);
end

function [state, actionSpec, actionTime, note] = localBeforeAction( ...
        state, actionKey, actionSpec, actionTime, note, hookContext) %#ok<INUSD>
    if actionKey == "FlaskFull" && getFieldOrDefault(state, 'CustomValue', 0) > 0
        actionSpec.MVOverride = 0;
        actionSpec.ApplyGauge = 0.0;
        actionSpec.CanApplyAura = false;
        actionSpec.CanTriggerReaction = false;
        note = localAppendNote(note, "Moonsign storage");
    end
end

function [state, note] = localAfterAction(state, actionKey, actionSpec, actionDamage, reactionTags, note, hookContext) %#ok<INUSD>
    if actionKey == "Q" && getFieldOrDefault(hookContext, 'Constellation', 0) >= 4 ...
            && strlength(string(getFieldOrDefault(actionSpec, 'ActionElement', ""))) > 0
            note = localAppendNote(note, "C4 +4E");
    elseif actionKey == "FlaskFull" && getFieldOrDefault(state, 'CustomValue', 0) > 0
        note = localAppendNote(note, "Meowball timeline");
    end
end

function level = localClampTalentLevel(level)
    level = max(1, min(15, round(level)));
end

function note = localAppendNote(baseNote, suffix)
    if strlength(string(baseNote)) == 0
        note = string(suffix);
    else
        note = string(baseNote) + ", " + string(suffix);
    end
end

function note = localBuildJahodaConversionNote(baseNote, convertedElement)
    note = string(baseNote) + " (" + string(convertedElement) + " convert)";
end
