function [totalDMG, dps, breakdown, rotationTime, audit] = simulateJahodaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Jahoda simulator with smoke-bomb fallback, flask discharge,
    % Moonsign meowball cadence, and element-priority robot conversion.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Jahoda', 'rotation_Jahoda.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Jahoda', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    pyroCount = getFieldOrDefault(teamContext, 'PyroCount', 0);
    hydroCount = getFieldOrDefault(teamContext, 'HydroCount', 0);
    electroCount = getFieldOrDefault(teamContext, 'ElectroCount', 0);
    cryoCount = getFieldOrDefault(teamContext, 'CryoCount', 0);
    enemyTargetCount = max(1, round(getFieldOrDefault(enemy, 'TargetCount', getFieldOrDefault(enemy, 'EnemyCount', 1))));

    convertedElement = localResolveJahodaElement(teamContext);
    conversionReady = strlength(convertedElement) > 0;
    if ~conversionReady
        convertedElement = "Hydro";
    end
    moonsignActive = localHasAscendantMoonsign(teamContext);
    robotCount = 2 + double(electroCount >= max([pyroCount, hydroCount, cryoCount, 1]));
    robotInterval = 2.20 * (1 - 0.10 * double(cryoCount >= max([pyroCount, hydroCount, electroCount, 1])));
    robotHitCount = max(1, floor(12.0 / robotInterval));
    robotTimeline = robotInterval * ones(1, robotHitCount);
    robotDamageBonus = 0.30 * double(pyroCount >= max([hydroCount, electroCount, cryoCount, 1]));
    meowballCount = 3;
    if moonsignActive
        meowballCount = 4;
    end
    meowballTimeline = 1.00 * ones(1, meowballCount);
    bounceCount = double(constellation >= 1) * meowballCount;
    bounceTimeline = 0.10 * ones(1, max(1, bounceCount));
    critSupportRate = 0.05 * double(constellation >= 6 && moonsignActive);
    critSupportDmg = 0.40 * double(constellation >= 6 && moonsignActive);

    allowConvertedAmplify = conversionReady && any(strcmpi(convertedElement, {'Hydro', 'Pyro', 'Cryo'}));
    allowConvertedCatalyze = conversionReady && strcmpi(convertedElement, 'Electro');
    allowConvertedTransformative = conversionReady && any(strcmpi(convertedElement, {'Hydro', 'Pyro', 'Cryo', 'Electro'}));

    actions = struct();
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'CanApplyAura', false, ...
        'Note', "Normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', 2, ...
        'HitTimeline', [0.00, 0.06], ...
        'CanApplyAura', false, ...
        'Note', "Normal 2 dual hit");
    actions.N3 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'CanApplyAura', false, ...
        'Note', "Normal 3");
    actions.Aimed = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "FullyChargedAimedShot", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Bullet_ShootArrow_Enchanted_WithWind", ...
        'LunarisDamageParam', "DamageWithWind", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Fully charged shot");
    actions.Smoke = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SmokeBombDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt", ...
        'LunarisDamageParam', "ElementalArt_SmokeAttack", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Smoke bomb");
    actions.FlaskPartial = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "UnfilledTreasureFlaskDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Second_Attack", ...
        'LunarisDamageParam', "ElementalArt_AvatarExplode_Uncharged", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Unfilled flask discharge");
    actions.FlaskFull = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "FilledTreasureFlaskDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Second_Attack", ...
        'LunarisDamageParam', "ElementalArt_AvatarExplode", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'C6CritRateBonus', critSupportRate, ...
        'C6CritDMGBonus', critSupportDmg, ...
        'Note', "Filled flask discharge");
    actions.Meowball = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "MeowballDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', convertedElement, ...
        'BaseMultiplier', double(conversionReady), ...
        'HitCount', meowballCount, ...
        'HitTimeline', meowballTimeline, ...
        'ApplyGauge', double(conversionReady), ...
        'ICDGroup', "Jahoda_Meowball", ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Bullet_ElementalArt_Attack", ...
        'LunarisDamageParam', "ElementalArt_BulletExplode", ...
        'CanApplyAura', conversionReady, ...
        'CanTriggerReaction', conversionReady, ...
        'AllowAmplify', double(allowConvertedAmplify), ...
        'AllowCatalyze', double(allowConvertedCatalyze), ...
        'AllowTransformative', double(allowConvertedTransformative), ...
        'PreferredAmplifyAura', localResolveJahodaAura(convertedElement, teamContext), ...
        'C6CritRateBonus', critSupportRate, ...
        'C6CritDMGBonus', critSupportDmg, ...
        'Note', "Fluffy Meowball");
    actions.MeowBounce = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "MeowballDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', convertedElement, ...
        'BaseMultiplier', 0.50 * double(conversionReady) * double(enemyTargetCount >= 2), ...
        'HitCount', meowballCount, ...
        'HitTimeline', bounceTimeline, ...
        'ApplyGauge', double(conversionReady), ...
        'ICDGroup', "Jahoda_Meowball_C1", ...
        'ICDRule', "2 hits / 15s", ...
        'LunarisAttackName', "Bullet_ElementalArt_Attack", ...
        'LunarisDamageParam', "ElementalArt_BulletExplode", ...
        'CanApplyAura', conversionReady, ...
        'CanTriggerReaction', conversionReady, ...
        'AllowAmplify', double(allowConvertedAmplify), ...
        'AllowCatalyze', double(allowConvertedCatalyze), ...
        'AllowTransformative', double(allowConvertedTransformative), ...
        'PreferredAmplifyAura', localResolveJahodaAura(convertedElement, teamContext), ...
        'C6CritRateBonus', critSupportRate, ...
        'C6CritDMGBonus', critSupportDmg, ...
        'Note', "C1 Meowball bounce");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'PostSetBurstActiveTime', 12.0, ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "ElementalBurst_AvatarExplode", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Hidden Aces cast");
    actions.Robot = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "PurrsonalCoordinatedAssistanceRobotDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', convertedElement, ...
        'BaseMultiplier', double(conversionReady) * robotCount * (1 + robotDamageBonus), ...
        'HitCount', robotHitCount, ...
        'HitTimeline', robotTimeline, ...
        'ApplyGauge', double(conversionReady), ...
        'ICDGroup', "Jahoda_Robot", ...
        'ICDRule', "4 hits / 15s", ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "ElementalBurst_BulletExplode", ...
        'CanApplyAura', conversionReady, ...
        'CanTriggerReaction', conversionReady, ...
        'AllowAmplify', double(allowConvertedAmplify), ...
        'AllowCatalyze', double(allowConvertedCatalyze), ...
        'AllowTransformative', double(allowConvertedTransformative), ...
        'PreferredAmplifyAura', localResolveJahodaAura(convertedElement, teamContext), ...
        'Note', "Purrsonal coordinated robots");

    if conversionReady
        defaultRotation = {'FlaskFull'};
    else
        defaultRotation = {'FlaskPartial'};
    end
    if moonsignActive
        defaultRotation{end + 1} = 'Meowball'; %#ok<AGROW>
        if constellation >= 1
            defaultRotation{end + 1} = 'MeowBounce'; %#ok<AGROW>
        end
    end
    defaultRotation{end + 1} = 'Q'; %#ok<AGROW>
    defaultRotation{end + 1} = 'Robot'; %#ok<AGROW>

    spec = struct( ...
        'Element', "Anemo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.75, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct('N1', 0.35, 'N2', 0.34, 'N3', 0.42, 'Aimed', 0.80, ...
            'Smoke', 0.55, 'FlaskPartial', 0.85, 'FlaskFull', 0.90, 'Meowball', 4.20, ...
            'MeowBounce', 0.45, 'Q', 1.05, 'Robot', max(2.4, sum(robotTimeline))), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Jahoda', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function element = localResolveJahodaElement(teamContext)
    priority = ["Pyro", "Hydro", "Electro", "Cryo"];
    counts = [ ...
        getFieldOrDefault(teamContext, 'PyroCount', 0), ...
        getFieldOrDefault(teamContext, 'HydroCount', 0), ...
        getFieldOrDefault(teamContext, 'ElectroCount', 0), ...
        getFieldOrDefault(teamContext, 'CryoCount', 0)];

    element = "";
    bestCount = 0;
    for i = 1:numel(priority)
        if counts(i) > bestCount
            bestCount = counts(i);
            element = priority(i);
        end
    end
end

function aura = localResolveJahodaAura(element, teamContext)
    switch lower(char(string(element)))
        case 'hydro'
            aura = "Pyro";
            if getFieldOrDefault(teamContext, 'PyroCount', 0) <= 0
                aura = "";
            end
        case 'pyro'
            if getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1
                aura = "Hydro";
            elseif getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1
                aura = "Cryo";
            else
                aura = "";
            end
        case 'cryo'
            if getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1
                aura = "Pyro";
            else
                aura = "";
            end
        otherwise
            aura = "";
    end
end

function tf = localHasAscendantMoonsign(teamContext)
    members = getFieldOrDefault(teamContext, 'Members', {});
    tf = false;
    if isstruct(members)
        for i = 1:numel(members)
            name = lower(char(string(getFieldOrDefault(members(i), 'Name', ""))));
            if any(strcmp(name, {'jahoda', 'aino', 'illuga'}))
                tf = true;
                return;
            end
        end
    elseif iscell(members)
        for i = 1:numel(members)
            name = lower(char(string(getFieldOrDefault(members{i}, 'Name', ""))));
            if any(strcmp(name, {'jahoda', 'aino', 'illuga'}))
                tf = true;
                return;
            end
        end
    end
end
