function build = customArtifact_Shenhe()
    % Default Shenhe build for ATK-based cryo support and quickswap burst.
    build = struct( ...
        'Weapon', 'CalamityQueller', ...
        'WeaponATK', 741, ...
        'WeaponSubStatType', 'ATK', ...
        'WeaponSubStatValue', 0.165, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.96, ...
        'FlatATK', 220, ...
        'ER', 1.65, ...
        'CritRate', 0.55, ...
        'CritDMG', 1.35, ...
        'CryoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'NoblesseOblige', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Shenhe', 'artifacts_Shenhe.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
