function build = customArtifact_Columbina(selectedWeapon)
    % 哥伦比娅默认构筑。
    % 当前版本延续项目里“面板聚合 build + 套装编译”的风格：
    % 1. 默认以高双暴 / 高生命值 / 4 黄金剧团为近似模板；
    % 2. 武器允许从 weapons.csv 中切换；
    % 3. 回写到 data/Columbina/artifacts_Columbina.csv，便于 GUI 直接加载。
    if nargin < 1 || strlength(string(selectedWeapon)) == 0
        selectedWeapon = "帷间夜曲";
    end

    thisFolder = fileparts(mfilename('fullpath'));
    projectRoot = fileparts(fileparts(thisFolder));
    weaponPath = fullfile(projectRoot, 'data', 'weapons.csv');
    weapons = readtable(weaponPath, 'TextType', 'string');

    weaponName = string(selectedWeapon);
    idx = find(weapons.Name == weaponName, 1, 'first');
    if isempty(idx)
        idx = find(weapons.Name == "帷间夜曲", 1, 'first');
    end
    if isempty(idx)
        idx = 1;
    end

    build = struct( ...
        'Weapon', char(weapons.Name(idx)), ...
        'WeaponATK', weapons.BaseATK(idx), ...
        'WeaponSubStatType', char(weapons.SubstatType(idx)), ...
        'WeaponSubStatValue', weapons.SubstatValue(idx), ...
        'WeaponRefinement', 1, ...
        'HPBonus', 1.42, ...
        'FlatHP', 4780, ...
        'AtkBonus', 0.00, ...
        'FlatATK', 311, ...
        'ER', 1.10, ...
        'EM', 120, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.20, ...
        'HydroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.15, ...
        'ChargeDMGBonus', 0.18, ...
        'ChargedDMGBonus', 0.18, ...
        'SkillDMGBonus', 0.60, ...
        'BurstDMGBonus', 0.20, ...
        'ReactionDMGBonus', 0.35, ...
        'ResShred', 0.00, ...
        'Set4_MoonPromote', 0.00, ...
        'Set4_GravityBonus', 0.00, ...
        'Set4_InterfereBonus', 0.00, ...
        'PromoteBonus', 0.00, ...
        'TeamHPAbove50Mult', 0.00, ...
        'ArtifactSet1', 'GoldenTroupe', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1 ...
    );

    outputPath = fullfile(projectRoot, 'data', 'Columbina', 'artifacts_Columbina.csv');
    if exist(fileparts(outputPath), 'dir') ~= 7
        mkdir(fileparts(outputPath));
    end
    writetable(struct2table(build), outputPath);
end
