function build = customArtifact_Varesa()
    % 瓦雷莎默认构筑。
    % 默认面板突出双暴、攻击与雷伤，辅以少量精通，
    % 用于高精度站场下落/突进轮转模拟。
    build = struct( ...
        'Weapon', 'VividNotions', ...
        'WeaponATK', 674, ...
        'AtkBonus', 1.12, ...
        'FlatATK', 320, ...
        'EM', 120, ...
        'CritRate', 0.84, ...
        'CritDMG', 2.06, ...
        'ElectroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'PlungeDMGBonus', 0.28, ...
        'NormalDMGBonus', 0.12, ...
        'ResShred', 0.00 ...
    );

    % 回写默认构筑数据。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Varesa', 'artifacts_Varesa.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
