function [totalDMG, dps, breakdown, rotationTime, audit] = simulateBennettDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Bennett simulator with tap / charge skill branches, burst cast, and
    % C6 Pyro-infused normals for carry-field testing.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Bennett', 'rotation_Bennett.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Bennett', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    infusedElement = "Physical";
    if constellation >= 6
        infusedElement = "Pyro";
    end

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "PressDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Strike01_01", ...
        'LunarisDamageParam', "Strike_01", ...
        'Note', "Passion Overload tap");
    actions.E1A = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "ChargeLevel1DMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Strike02_01", ...
        'LunarisDamageParam', "Strike_02_01", ...
        'Note', "Passion Overload charge 1 hit 1");
    actions.E1B = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "ChargeLevel1DMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", ...
        'MVOverride', 1.0, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Strike02_02", ...
        'LunarisDamageParam', "Strike_02_02", ...
        'Note', "Passion Overload charge 1 hit 2");
    actions.E2A = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "ChargeLevel2DMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Strike03_01", ...
        'LunarisDamageParam', "Strike_03_01", ...
        'Note', "Passion Overload charge 2 hit 1");
    actions.E2B = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "ChargeLevel2DMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", ...
        'MVOverride', 1.0, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Strike03_02", ...
        'LunarisDamageParam', "Strike_03_02", ...
        'Note', "Passion Overload charge 2 hit 2");
    actions.EExplode = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "ExplosionDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Explode", ...
        'LunarisDamageParam', "Strike_03_03", ...
        'Note', "Passion Overload explosion");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Hydro", ...
        'PostSetBurstActiveTime', 12.0, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Strike", ...
        'LunarisDamageParam', "Burst_DMG", ...
        'Note', "Fantastic Voyage cast");
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', infusedElement, ...
        'BaseMultiplier', 1.00, ...
        'BurstWindowDamageBonus', 0.15 * double(constellation >= 6), ...
        'AllowAmplify', double(strcmpi(char(infusedElement), 'Pyro')), ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', double(strcmpi(char(infusedElement), 'Pyro')), ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "FallingAnthem", ...
        'LunarisDamageParam', "FallingAnthem_Normal_Rank_1_Damage", ...
        'Note', "Normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', infusedElement, ...
        'BaseMultiplier', 1.00, ...
        'BurstWindowDamageBonus', 0.15 * double(constellation >= 6), ...
        'AllowAmplify', double(strcmpi(char(infusedElement), 'Pyro')), ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 0.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "FallingAnthem", ...
        'LunarisDamageParam', "FallingAnthem_Normal_Loop_Damage", ...
        'Note', "Normal 2");

    spec = struct( ...
        'Element', "Pyro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.60, ...
        'DefaultRotation', {{'Q', 'E', 'N1', 'N2', 'E'}}, ...
        'ActionTimeMap', struct( ...
            'E', 0.44, ...
            'E1A', 0.30, ...
            'E1B', 0.36, ...
            'E2A', 0.34, ...
            'E2B', 0.34, ...
            'EExplode', 0.24, ...
            'Q', 0.98, ...
            'N1', 0.34, ...
            'N2', 0.40), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Bennett', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
