function validateTeamAutoPlanCarryFallbackRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    furina = getDefaultCharacterConfig('Furina');
    yelan = getDefaultCharacterConfig('Yelan');
    xianyun = getDefaultCharacterConfig('Xianyun');
    jean = getDefaultCharacterConfig('Jean');

    spec = struct( ...
        'Members', {{furina, yelan, xianyun, jean}}, ...
        'RotationDuration', 20, ...
        'SharedBuffs', struct('ReactionMode', "Realistic"));

    [teamResult, ~] = simulateTeamDPS(spec, enemy);
    plan = teamResult.PlannedRotation;
    execution = plan.ExecutionTable;

    assert(istable(execution) && height(execution) == 4, ...
        'Auto-plan regression should still produce one execution row per enabled member.');
    assert(isfield(plan, 'CandidateCount') && plan.CandidateCount > 1, ...
        'Auto-plan regression should now evaluate multiple team timeline candidates instead of accepting the first static template merge.');
    assert(isfield(plan, 'SelectionMode') && contains(string(plan.SelectionMode), "timeline"), ...
        'Auto-plan regression should expose a timeline-ranked selection mode after evaluating shared team candidates.');
    assert(isfield(plan, 'SelectionScore') && isfinite(plan.SelectionScore), ...
        'Auto-plan regression should expose the selected timeline candidate score.');

    furinaRow = execution(string(execution.Character) == "Furina", :);
    assert(~isempty(furinaRow), ...
        'Furina team regression should keep Furina in the execution table.');
    assert(double(furinaRow.EndTime(1) - furinaRow.StartTime(1)) < 9.0, ...
        'Low-confidence auto-plan should avoid stretching Furina into a long solo carry window.');
    assert(double(furinaRow.EndTime(1) - furinaRow.StartTime(1)) > 4.0, ...
        'Low-confidence auto-plan should still reserve a meaningful Furina action window instead of collapsing to a pure support stub.');

    furinaPlan = plan.MemberPlans(strcmpi(string({plan.MemberPlans.Name}), "Furina"));
    assert(~isempty(furinaPlan), ...
        'Auto-plan regression should expose a Furina member plan.');
    assert(~strcmpi(char(string(furinaPlan.PlanningSource)), 'reference-carry'), ...
        'Low-confidence auto-plan should not fall back to Furina''s full solo carry reference rotation.');
    assert(strcmpi(char(string(furinaPlan.Role)), 'Support') || strcmpi(char(string(furinaPlan.Role)), 'Hybrid'), ...
        'Low-confidence auto-plan should treat Furina as a support-lean team member instead of a forced solo hypercarry in this mixed-support sample.');
    assert(~contains(string(furinaPlan.RotationText), "Heavy"), ...
        'Low-confidence auto-plan should trim Furina''s support-lean fallback away from the old heavy solo loop.');

    warnings = string(getFieldOrDefault(teamResult, 'PlanningWarnings', strings(0, 1)));
    assert(~isempty(warnings), ...
        'Team regression should still surface planning warnings when loop energy is missing.');
    assert(double(getFieldOrDefault(teamResult.TimelineSummary, 'IdleTime', inf)) < 2.0, ...
        'Timeline-ranked auto-plan should keep idle time near realistic rotation levels for the Furina mixed-support sample.');

    disp('validateTeamAutoPlanCarryFallbackRegression passed');
end
