function validateKaeyaRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cfg0 = getDefaultCharacterConfig('Kaeya', struct('Constellation', 0, 'TalentLevel', 10));
    cfg2 = getDefaultCharacterConfig('Kaeya', struct('Constellation', 2, 'TalentLevel', 10));
    cfg6 = getDefaultCharacterConfig('Kaeya', struct('Constellation', 6, 'TalentLevel', 10));
    ctx0 = buildTeamContext({cfg0}, 20, struct('ReactionMode', "Realistic"), enemy);
    ctx2 = buildTeamContext({cfg2}, 20, struct('ReactionMode', "Realistic"), enemy);
    ctx6 = buildTeamContext({cfg6}, 20, struct('ReactionMode', "Realistic"), enemy);
    shortRotation = [tempname, '.txt'];
    cleanupShortRotation = onCleanup(@() localDeleteIfExists(shortRotation)); %#ok<NASGU>
    fid = fopen(shortRotation, 'w');
    assert(fid > 0, 'Failed to create temporary Kaeya regression rotation file.');
    fprintf(fid, 'N1\nCA\n');
    fclose(fid);
    cryoAuraEnemy = enemy;
    cryoAuraEnemy.InitialAuraElement = "Cryo";
    cryoAuraEnemy.InitialAuraGauge = 1.0;
    ctx6CryoAura = buildTeamContext({cfg6}, 20, struct('ReactionMode', "Realistic"), cryoAuraEnemy);

    [damage0, ~, breakdown0, rotationTime0, audit0] = simulateKaeyaDPS( ...
        cfg0.Build, enemy, cfg0.RotationFile, cfg0.TalentLevel, cfg0.Constellation, ctx0);
    [damage6, ~, breakdown6, rotationTime6, audit6] = simulateKaeyaDPS( ...
        cfg6.Build, enemy, cfg6.RotationFile, cfg6.TalentLevel, cfg6.Constellation, ctx6);
    [damage6CryoAura, ~, breakdown6CryoAura] = simulateKaeyaDPS( ...
        cfg6.Build, cryoAuraEnemy, shortRotation, cfg6.TalentLevel, cfg6.Constellation, ctx6CryoAura);
    [damage6NoAura, ~, breakdown6NoAura] = simulateKaeyaDPS( ...
        cfg6.Build, enemy, shortRotation, cfg6.TalentLevel, cfg6.Constellation, ctx6);
    burstOnlyRotation = [tempname, '.txt'];
    cleanupBurstRotation = onCleanup(@() localDeleteIfExists(burstOnlyRotation)); %#ok<NASGU>
    fid = fopen(burstOnlyRotation, 'w');
    assert(fid > 0, 'Failed to create temporary Kaeya burst regression rotation file.');
    fprintf(fid, 'Q\n');
    fclose(fid);
    defeatEvents = table( ...
        [2.0; 4.0], ...
        ["Kaeya"; "Kaeya"], ...
        ["Defeat"; "Defeat"], ...
        ["EnemyDefeat"; "EnemyDefeat"], ...
        ["Q"; "Q"], ...
        [2.5; 2.5], ...
        'VariableNames', {'Time', 'Character', 'EventKind', 'EventName', 'SourceAction', 'Value'});
    defeatCtx = buildTeamContext({cfg2}, 20, struct('ReactionMode', "Realistic", 'CombatEventTable', defeatEvents), enemy);
    [damage2NoDefeat, ~, breakdown2NoDefeat] = simulateKaeyaDPS( ...
        cfg2.Build, enemy, burstOnlyRotation, cfg2.TalentLevel, cfg2.Constellation, ctx2);
    [damage2Defeat, ~, breakdown2Defeat] = simulateKaeyaDPS( ...
        cfg2.Build, enemy, burstOnlyRotation, cfg2.TalentLevel, cfg2.Constellation, defeatCtx);

    actions0 = string(breakdown0.Action);
    q0 = breakdown0(actions0 == "Q", :);
    q6 = breakdown6(string(breakdown6.Action) == "Q", :);
    q2NoDefeat = breakdown2NoDefeat(string(breakdown2NoDefeat.Action) == "Q", :);
    q2Defeat = breakdown2Defeat(string(breakdown2Defeat.Action) == "Q", :);
    ca0 = breakdown0(actions0 == "CA", :);
    notes6 = string(breakdown6.Note);
    notes6CryoAura = string(breakdown6CryoAura.Note);
    notes6NoAura = string(breakdown6NoAura.Note);

    assert(damage0 > 0 && rotationTime0 > 0 && damage6 > 0 && rotationTime6 > 0 ...
        && damage6CryoAura > 0 && damage6NoAura > 0, ...
        'Kaeya regression should produce positive damage and rotation time for both C0 and C6.');
    assert(isequal(actions0', ["E", "Q", "N1", "N2", "N3", "CA"]), ...
        'Kaeya regression should preserve the Frostgnaw -> Glacial Waltz -> physical string order.');
    assert(height(q0) == 1 && contains(string(q0.Note), "x8"), ...
        'Kaeya C0 burst regression should keep the 8-tick Glacial Waltz note.');
    assert(height(q6) == 1 && contains(string(q6.Note), "x9"), ...
        'Kaeya C6 burst regression should keep the extra Glacial Waltz tick.');
    assert(height(ca0) == 1 && contains(string(ca0.Note), "x2"), ...
        'Kaeya charged attack regression should keep the 2-hit physical note.');
    assert(damage6 > damage0, ...
        'Kaeya C6 regression should outdamage the C0 script through the extra burst tick.');
    assert(any(contains(notes6, "C1 cryo crit")), ...
        'Kaeya default regression should preserve the self-applied Cryo aura before the physical follow-up string.');
    assert(~any(contains(notes6NoAura, "C1 cryo crit")), ...
        'Kaeya physical-only regression should not assume the C1 cryo crit bonus without an explicit Cryo/Frozen aura.');
    assert(any(contains(notes6CryoAura, "C1 cryo crit")), ...
        'Kaeya regression should expose the C1 cryo crit note once the enemy starts with an explicit Cryo aura.');
    assert(damage6CryoAura > damage6NoAura, ...
        'Kaeya regression should deal more damage when the explicit Cryo aura enables the C1 crit bonus in a physical-only string.');
    assert(~any(audit0.Rows.ApplyGaugeFallback | audit0.Rows.ICDFallback) ...
        && ~any(audit6.Rows.ApplyGaugeFallback | audit6.Rows.ICDFallback), ...
        'Kaeya regression should keep explicit gauge and ICD metadata for the scripted rotation.');
    assert(height(q2NoDefeat) == 1 && contains(string(q2NoDefeat.Note), "x8"), ...
        'Kaeya C2 without explicit enemy defeats should keep the baseline 8-tick burst note.');
    assert(height(q2Defeat) == 1 ...
            && contains(string(q2Defeat.Note), "C2 ext +5.0s") ...
            && contains(string(q2Defeat.Note), "x13"), ...
        'Kaeya C2 should extend Glacial Waltz when explicit defeat events are supplied.');
    assert(damage2Defeat > damage2NoDefeat, ...
        'Kaeya C2 explicit-defeat regression should outdamage the no-defeat burst sample through the added burst ticks.');

    disp('validateKaeyaRegression passed');
end

function localDeleteIfExists(path)
    if exist(path, 'file') == 2
        delete(path);
    end
end
