function validateTeamAutoPlanEnergyLoopRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    furina = getDefaultCharacterConfig('Furina', struct('Constellation', 0, 'TalentLevel', 10));
    barbara = getDefaultCharacterConfig('Barbara');
    lisa = getDefaultCharacterConfig('Lisa');

    spec = struct( ...
        'Members', {{furina, barbara, lisa}}, ...
        'RotationDuration', 20, ...
        'SharedBuffs', struct('ReactionMode', "Realistic"));

    [teamResult, ~] = simulateTeamDPS(spec, enemy);
    plan = teamResult.PlannedRotation;
    memberPlans = plan.MemberPlans;

    assert(isfield(plan, 'SelectionMode') && contains(string(plan.SelectionMode), "energy-relaxed"), ...
        'Auto-plan should now compare and select energy-relaxed team candidates when the burst-heavy baseline cannot loop.');

    burstPlanCount = 0;
    for i = 1:numel(memberPlans)
        burstPlanCount = burstPlanCount + double(any(strcmpi(string(memberPlans(i).RotationTokens), "Q")));
    end
    assert(burstPlanCount < 3, ...
        'Energy-aware auto-plan should no longer schedule every member burst in the Furina/Barbara/Lisa sample.');

    baseContext = buildTeamContext({furina, barbara, lisa}, 20, struct('ReactionMode', "Realistic"), enemy);
    naivePlan = struct( ...
        'RotationDuration', 20, ...
        'CarryIndex', 3, ...
        'ExecutionOrder', [2, 1, 3], ...
        'ArchetypeInfo', identifyTeamArchetype({furina, barbara, lisa}, struct('ReactionMode', "Realistic")), ...
        'MemberPlans', [ ...
            struct('Name', "Furina", 'Role', "Support", 'RotationTokens', {{'Q', 'E', 'N1', 'N2', 'N3'}}, 'StartTime', 2.95), ...
            struct('Name', "Barbara", 'Role', "Support", 'RotationTokens', {{'E', 'Q', 'N1', 'N2'}}, 'StartTime', 0.0), ...
            struct('Name', "Lisa", 'Role', "Carry", 'RotationTokens', {{'ETap', 'CA', 'ETap', 'EHold3', 'Q', 'CA', 'CA', 'CA', 'CA', 'CA', 'CA', 'CA', 'CA'}}, 'StartTime', 6.42)]);
    naiveTimeline = simulateTeamTimeline({furina, barbara, lisa}, naivePlan, baseContext, enemy, struct());

    assert(teamResult.LoopReadiness > naiveTimeline.LoopReadiness, ...
        'Energy-aware auto-plan should improve next-cycle loop readiness over the old burst-heavy stitched baseline.');
    assert(double(getFieldOrDefault(teamResult.TimelineSummary, 'IdleTime', inf)) ...
            < double(getFieldOrDefault(naiveTimeline.TimelineSummary, 'IdleTime', inf)), ...
        'Energy-aware auto-plan should also reduce the large idle hole left by the old stitched baseline.');

    warnings = string(getFieldOrDefault(teamResult, 'PlanningWarnings', strings(0, 1)));
    loopWarnings = warnings(startsWith(strtrim(warnings), "Loop energy missing:", 'IgnoreCase', true));
    if ~isempty(loopWarnings)
        assert(~(contains(loopWarnings(1), "Furina") && contains(loopWarnings(1), "Barbara") && contains(loopWarnings(1), "Lisa")), ...
            'Energy-aware auto-plan should no longer keep all three burst deficits in the primary loop warning.');
    end

    disp('validateTeamAutoPlanEnergyLoopRegression passed');
end
