function validateFurinaRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cfg = getDefaultCharacterConfig('Furina', struct('Constellation', 0, 'TalentLevel', 10));
    teamContext = buildTeamContext({cfg}, 20, struct('ReactionMode', "Realistic"), enemy);

    singerRotation = [tempname, '.txt'];
    cleanup = onCleanup(@() localDeleteIfExists(singerRotation)); %#ok<NASGU>
    fid = fopen(singerRotation, 'w');
    assert(fid > 0, 'Failed to create temporary Furina regression rotation file.');
    fprintf(fid, 'SwitchPneuma\nE\nSinger\nSinger\n');
    fclose(fid);

    [damage10, ~, breakdown10, ~, audit10] = simulateFurinaDPS( ...
        cfg.Build, enemy, singerRotation, 10, cfg.Constellation, teamContext);
    [damage15, ~, breakdown15] = simulateFurinaDPS( ...
        cfg.Build, enemy, singerRotation, 15, cfg.Constellation, teamContext);

    healRows10 = breakdown10(strcmp(string(breakdown10.Action), "Singer_Heal"), :);
    healRows15 = breakdown15(strcmp(string(breakdown15.Action), "Singer_Heal"), :);
    talent10 = readtable(char(resolveCharacterDataFile('Furina', 'talents')), 'TextType', 'string');
    singerRow = talent10(strcmp(string(talent10.Param), "众水的歌者治疗量"), :);
    assert(~isempty(singerRow) && isfinite(singerRow.AuxLevel10(1)) && singerRow.AuxLevel10(1) > 0, ...
        'Furina talent export should persist the singer flat-heal AuxLevel column.');
    assert(height(healRows10) == 2, 'Furina Singer regression should record one heal row per Singer tick.');
    assert(all(healRows10.Damage > 0), 'Furina Singer heal rows should stay positive.');
    assert(~any(strcmp(string(breakdown10.Action), "SingerAuto_Heal")), ...
        'Explicit Singer actions should suppress auto-generated Singer background heals.');
    assert(sum(healRows15.Damage) > sum(healRows10.Damage), ...
        'Furina Singer heal should scale upward when the aux flat heal value increases by talent level.');
    assert(damage10 > 0 && damage15 > 0, ...
        'Furina Singer regression should keep the opening skill damage active.');

    singerAuditRows = audit10.Rows(strcmp(string(audit10.Rows.Action), "Singer"), :);
    assert(height(singerAuditRows) == 2 ...
        && all(singerAuditRows.ApplyGaugeSource == "not_applicable") ...
        && all(isnan(singerAuditRows.ApplyGauge)), ...
        'Furina Singer audit rows should stay as non-damaging utility actions.');

    sharedApproxBonus = getFieldOrDefault(teamContext, 'ApproxFurinaBonus', 0);
    assert(sharedApproxBonus > 0, ...
        'Furina team context should still expose an approximate shared burst bonus for teammates.');
    assert(abs(sharedApproxBonus - 0.60) > 1e-6, ...
        'Furina team context should now derive the shared burst bonus from timeline behavior instead of the legacy fixed C0 constant.');

    normalRotation = [tempname, '.txt'];
    normalCleanup = onCleanup(@() localDeleteIfExists(normalRotation)); %#ok<NASGU>
    fid = fopen(normalRotation, 'w');
    assert(fid > 0, 'Failed to create temporary Furina normal regression rotation file.');
    fprintf(fid, 'N1\n');
    fclose(fid);

    noApproxContext = teamContext;
    noApproxContext.AllDMGBonus = getFieldOrDefault(noApproxContext, 'AllDMGBonus', 0) - sharedApproxBonus;
    noApproxContext.ApproxFurinaBonus = 0;

    [normalDamageWith, ~, normalBreakdown] = simulateFurinaDPS( ...
        cfg.Build, enemy, normalRotation, 10, cfg.Constellation, teamContext);
    [normalDamageWithout, ~] = simulateFurinaDPS( ...
        cfg.Build, enemy, normalRotation, 10, cfg.Constellation, noApproxContext);
    assert(abs(normalDamageWith - normalDamageWithout) < 1e-6 * max(1, abs(normalDamageWith)), ...
        'Furina self simulation should strip ApproxFurinaBonus to avoid double-counting the shared burst heuristic.');

    chars = readtable(char(resolveCharacterDataFile('Furina', 'characters')), 'TextType', 'string');
    baseATK = double(chars.BaseATK(1));
    atkValue = (baseATK + getFieldOrDefault(cfg.Build, 'WeaponATK', 0)) ...
        * (1 + getFieldOrDefault(cfg.Build, 'AtkBonus', 0) + getFieldOrDefault(noApproxContext, 'ATKBonus', 0)) ...
        + getFieldOrDefault(cfg.Build, 'FlatATK', 0) + getFieldOrDefault(noApproxContext, 'FlatATK', 0);
    critMult = calcExpectedCritMultiplier(getFieldOrDefault(cfg.Build, 'CritRate', 0), getFieldOrDefault(cfg.Build, 'CritDMG', 0));
    normalBonus = 1 + getFieldOrDefault(cfg.Build, 'NormalDMGBonus', 0) ...
        + getFieldOrDefault(cfg.Build, 'PhysicalDMGBonus', 0) ...
        + getFieldOrDefault(noApproxContext, 'PhysicalDMGBonus', 0) ...
        + getFieldOrDefault(noApproxContext, 'AllDMGBonus', 0);
    expectedN1Damage = atkValue * double(talent10.Level10(1)) * normalBonus * critMult ...
        * calcDamageMultiplier(90, enemy, getFieldOrDefault(cfg.Build, 'ResShred', 0) ...
        + getFieldOrDefault(noApproxContext, 'PhysicalResShred', 0));

    n1Rows = normalBreakdown(strcmp(string(normalBreakdown.Action), "N1"), :);
    assert(height(n1Rows) == 1, 'Furina normal regression should isolate one N1 row.');
    assert(abs(n1Rows.Damage - expectedN1Damage) < 1e-6 * max(1, expectedN1Damage), ...
        'Furina N1 should now use the physical ATK-based path instead of the old HP-based Hydro approximation.');

    barbara = getDefaultCharacterConfig('Barbara');
    lisa = getDefaultCharacterConfig('Lisa');
    furinaTeam = buildTeamContext({cfg, barbara, lisa}, 20, struct('ReactionMode', "Realistic"), enemy);
    soloFurinaTeam = buildTeamContext({cfg}, 20, struct('ReactionMode', "Realistic"), enemy);
    assert(getFieldOrDefault(furinaTeam, 'ApproxFurinaBonus', 0) > getFieldOrDefault(soloFurinaTeam, 'ApproxFurinaBonus', 0), ...
        'Furina timeline-derived team bonus should increase when a more realistic multi-member rotation can build better HP rhythm and burst coverage.');

    guiStyleEnemy = struct('Level', 90, 'Res', 0.10, 'DefReduct', 0, ...
        'ReactionMode', "Realistic", 'AutoSupportAura', false, 'EnemyCount', 1, 'TargetCount', 1);
    guiStyleTeamSpec = struct( ...
        'Members', {{cfg, barbara, lisa}}, ...
        'RotationDuration', 20, ...
        'SharedBuffs', struct());
    guiStyleTeamResult = simulateTeamDPS(guiStyleTeamSpec, guiStyleEnemy);
    assert(isstruct(guiStyleTeamResult) && isfield(guiStyleTeamResult, 'DPS') ...
            && isfinite(guiStyleTeamResult.DPS) && guiStyleTeamResult.DPS > 0, ...
        'Furina should complete a full team simulation through the unified team entry without throwing team-mode errors.');
    timelineOnlySharedBuffs = struct( ...
        'ReactionMode', "Realistic", ...
        'TimelineSummary', getFieldOrDefault(guiStyleTeamResult, 'TimelineSummary', struct()), ...
        'MemberTimelineSummary', getFieldOrDefault(guiStyleTeamResult, 'MemberTimelineSummary', table()), ...
        'EnergySummary', getFieldOrDefault(guiStyleTeamResult, 'EnergySummary', table()), ...
        'EnergyTimeline', getFieldOrDefault(guiStyleTeamResult, 'EnergyTimeline', table()), ...
        'ActiveEffectsTable', getFieldOrDefault(guiStyleTeamResult, 'ActiveEffectsTable', table()), ...
        'HealthEventTable', table(), ...
        'FinalEnemyState', getFieldOrDefault(guiStyleTeamResult, 'FinalEnemyState', struct()), ...
        'LoopReadiness', getFieldOrDefault(guiStyleTeamResult, 'LoopReadiness', 0), ...
        'CanLoopNextCycle', getFieldOrDefault(guiStyleTeamResult, 'CanLoopNextCycle', false), ...
        'ApproxFurinaBonus', []);
    noHealthLogContext = buildTeamContext({cfg, barbara, lisa}, 20, timelineOnlySharedBuffs, enemy);
    assert(abs(getFieldOrDefault(guiStyleTeamResult.TeamContext, 'ApproxFurinaBonus', 0) ...
            - getFieldOrDefault(noHealthLogContext, 'ApproxFurinaBonus', 0)) > 1e-4, ...
        'Furina team context should now materially change when explicit team HP event logs are present.');
    assert(isfield(guiStyleTeamResult, 'HealthEventTable') ...
            && istable(guiStyleTeamResult.HealthEventTable) ...
            && height(guiStyleTeamResult.HealthEventTable) >= 1, ...
        'Furina team simulation should surface explicit HealthEventTable rows once timeline HP events are modeled.');
    assert(any(strcmpi(string(guiStyleTeamResult.HealthEventTable.EventKind), "Drain")) ...
            && any(strcmpi(string(guiStyleTeamResult.HealthEventTable.EventKind), "Heal")), ...
        'Furina team simulation should record both HP drain and healing events for fanfare rhythm evaluation.');

    teamFurinaRows = guiStyleTeamResult.Breakdown(strcmp(string(guiStyleTeamResult.Breakdown.Character), "Furina"), :);
    autoSalonRows = teamFurinaRows(strcmp(string(teamFurinaRows.Action), "SalonTick"), :);
    qRows = teamFurinaRows(strcmp(string(teamFurinaRows.Action), "Q"), :);
    assert(height(autoSalonRows) >= 1 && sum(autoSalonRows.Damage) > 0, ...
        'Furina team simulation should derive positive SalonTick background damage from the active companion window.');
    assert(height(qRows) <= 1, ...
        'Furina team simulation should schedule at most one burst row in the unified team entry.');
    if height(qRows) == 1
        assert(contains(string(qRows.Note), "fanfare=0"), ...
            'Furina C0 burst should start at zero fanfare instead of the old scripted 150-point opening state.');
    else
        assert(contains(string(getFieldOrDefault(guiStyleTeamResult.PlannedRotation, 'SelectionMode', "")), "energy-relaxed"), ...
            'If the unified team planner skips Furina''s burst, it should do so through the explicit energy-relaxed auto-plan branch.');
    end

    explicitHealthEvents = table( ...
        [1.0; 2.0; 4.0; 6.0], ...
        ["Furina"; "Barbara"; "Furina"; "Barbara"], ...
        ["SalonTick#1"; "Q"; "SalonTick#2"; "Q"], ...
        ["EffectTick"; "MemberAction"; "EffectTick"; "MemberAction"], ...
        ["Drain"; "Heal"; "Drain"; "Heal"], ...
        ["SalonDrain"; "ShiningMiracleHeal"; "SalonDrain"; "ShiningMiracleHeal"], ...
        ["AllMembers"; "AllMembers"; "AllMembers"; "AllMembers"], ...
        [3; 3; 3; 3], ...
        [1; 1; 1; 1], ...
        [3; 3; 3; 3], ...
        ["SalonMembers"; ""; "SalonMembers"; ""], ...
        'VariableNames', {'Time', 'Character', 'Action', 'SourceType', 'EventKind', ...
        'EventName', 'TargetScope', 'TargetCount', 'UnitsPerTarget', 'TotalUnits', 'EffectTag'});
    sparseHealthEvents = explicitHealthEvents(1:2, :);

    explicitSharedBuffs = struct( ...
        'ReactionMode', "Realistic", ...
        'TimelineSummary', struct('MemberOccupiedTime', 12, 'SwapTime', 1.2), ...
        'MemberTimelineSummary', table(["Furina"; "Barbara"; "Lisa"], [2.5; 2.0; 2.0], [6.0; 0.0; 0.0], ...
            'VariableNames', {'Character', 'ScheduledActionTime', 'BackgroundEventTime'}), ...
        'EnergySummary', table(["Furina"; "Barbara"; "Lisa"], [60; 80; 80], [65; 80; 80], ...
            'VariableNames', {'Character', 'BurstCost', 'EndEnergy'}), ...
        'ActiveEffectsTable', table(["Furina"; "Furina"], ["Q"; "E"], ["Fanfare"; "SalonMembers"], [0.5; 0.6], [18.5; 20.0], ...
            ["Support"; "Support"], ["Autonomous"; "Autonomous"], ["CompanionPeriodic"; "CompanionPeriodic"], ...
            ["SalonTick"; "SalonTick"], [2.4; 2.4], [8; 8], ...
            'VariableNames', {'Character', 'Action', 'EffectTag', 'StartTime', 'EndTime', 'Role', ...
            'DriverKind', 'DriverMode', 'DriverAction', 'DriverInterval', 'DriverCount'}), ...
        'HealthEventTable', explicitHealthEvents, ...
        'LoopReadiness', 0.90);
    sparseSharedBuffs = explicitSharedBuffs;
    sparseSharedBuffs.HealthEventTable = sparseHealthEvents;

    richContext = buildTeamContext({cfg, barbara, lisa}, 20, explicitSharedBuffs, enemy);
    sparseContext = buildTeamContext({cfg, barbara, lisa}, 20, sparseSharedBuffs, enemy);
    assert(getFieldOrDefault(richContext, 'ApproxFurinaBonus', 0) > getFieldOrDefault(sparseContext, 'ApproxFurinaBonus', 0), ...
        'Denser explicit team HP event logs should increase Furina shared bonus estimation over sparse heal/drain rhythms.');

    startFigureCount = numel(findall(groot, 'Type', 'Figure'));
    app = GenshinDMGApp();
    appCleanup = onCleanup(@() localDeleteIfValid(app)); %#ok<NASGU>
    drawnow;

    afterLaunchFigureCount = numel(findall(groot, 'Type', 'Figure'));
    assert(afterLaunchFigureCount == startFigureCount + 1, ...
        'App startup should keep the single-character editor in a lazy separate window instead of occupying main UI space.');

    app.runTeam();
    drawnow;
    assert(string(app.LastSimulationMode) == "整队", ...
        'App Furina regression should complete through the GUI team entry.');
    assert(isstruct(app.LastTeamResult) && isfield(app.LastTeamResult, 'DPS') ...
            && isfinite(app.LastTeamResult.DPS) && app.LastTeamResult.DPS > 0, ...
        'App Furina regression should produce a positive team DPS result.');

    afterTeamFigureCount = numel(findall(groot, 'Type', 'Figure'));
    assert(afterTeamFigureCount == startFigureCount + 1, ...
        'Running a team simulation should not auto-open the single-character editor window.');

    disp('validateFurinaRegression passed');
end

function localDeleteIfExists(path)
    if exist(path, 'file') == 2
        delete(path);
    end
end

function localDeleteIfValid(handleObj)
    if ~isempty(handleObj) && isvalid(handleObj)
        delete(handleObj);
    end
end
