function validateRotationTokenExpansionRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    build = struct();
    teamContext = buildTeamContext({struct('Name', 'Nicole', 'Constellation', 0, 'Build', build)}, 20, struct('ReactionMode', "Realistic"), enemy);
    spec = struct( ...
        'Element', "Pyro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.7, ...
        'DefaultRotation', {{'Q', 'QLoopx2'}}, ...
        'ActionTimeMap', struct('Q', 1.0, 'QLoop', 0.5), ...
        'Actions', struct( ...
            'Q', struct('TalentGroup', "Burst", 'Param', "CastATK", 'DamageField', "BurstDMGBonus", 'ActionElement', "Pyro", 'Note', "Cast"), ...
            'QLoop', struct('TalentGroup', "Burst", 'Param', "ProjectionATK", 'DamageField', "BurstDMGBonus", 'ActionElement', "Pyro", 'Note', "Loop")));

    [~, ~, ~, ~, audit] = simulateSimpleCharacterDPS( ...
        'Nicole', build, enemy, "", 10, 0, teamContext, spec);

    assert(isequal(string(audit.Rows.Action), ["Q"; "QLoop"; "QLoop"]), ...
        'simulateSimpleCharacterDPS should expand trailing xN tokens into repeated action rows.');
    assert(~any(strcmp(string(audit.Rows.Action), "QLoopx2")), ...
        'Expanded action rows should never retain the original xN token suffix.');

    disp('validateRotationTokenExpansionRegression passed');
end
