function validateIfaRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Approximate", ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cfgC0 = getDefaultCharacterConfig('Ifa', struct('Constellation', 0));
    cfgC2 = getDefaultCharacterConfig('Ifa', struct('Constellation', 2));
    bennett = struct('Name', 'Bennett', 'Constellation', 0, 'Build', customArtifact_Bennett());

    contextC0 = buildTeamContext( ...
        {cfgC0, bennett}, 20, struct('ReactionMode', "Approximate"), enemy);
    contextC2 = buildTeamContext( ...
        {cfgC2, bennett}, 20, struct('ReactionMode', "Approximate", 'NightsoulPointPool', 40), enemy);
    soloContext = buildTeamContext( ...
        {cfgC0}, 20, struct('ReactionMode', "Approximate"), enemy);

    [damageC0, ~, breakdownC0] = simulateIfaDPS( ...
        cfgC0.Build, enemy, cfgC0.RotationFile, cfgC0.TalentLevel, cfgC0.Constellation, contextC0);
    [damageC2, ~, breakdownC2] = simulateIfaDPS( ...
        cfgC2.Build, enemy, cfgC2.RotationFile, cfgC2.TalentLevel, cfgC2.Constellation, contextC2);
    [~, ~, breakdownSolo] = simulateIfaDPS( ...
        cfgC0.Build, enemy, cfgC0.RotationFile, cfgC0.TalentLevel, cfgC0.Constellation, soloContext);

    multiEnemy = enemy;
    multiEnemy.EnemyCount = 2;
    multiEnemy.TargetCount = 2;
    multiContext = buildTeamContext( ...
        {cfgC0, bennett}, 20, struct('ReactionMode', "Approximate"), multiEnemy);
    [~, ~, breakdownMulti] = simulateIfaDPS( ...
        cfgC0.Build, multiEnemy, cfgC0.RotationFile, cfgC0.TalentLevel, cfgC0.Constellation, multiContext);

    supportRowsC0 = breakdownC0(contains(string(breakdownC0.Action), "Support"), :);
    supportRowsC2 = breakdownC2(contains(string(breakdownC2.Action), "Support"), :);
    markRowsC0 = breakdownC0(strcmp(string(breakdownC0.Action), "Mark"), :);
    markRowsMulti = breakdownMulti(strcmp(string(breakdownMulti.Action), "Mark"), :);

    assert(damageC2 > damageC0, ...
        'Ifa C2 with an explicit extra Nightsoul pool should outdamage the baseline Rescue rotation.');
    assert(all(contains(string(supportRowsC0.Note), "Rescue")), ...
        'Ifa support actions should annotate their Rescue Essentials state.');
    assert(all(contains(string(supportRowsC2.Note), "Rescue")), ...
        'Ifa C2 support actions should annotate their enlarged Rescue Essentials state.');
    assert(sum(supportRowsC2.Damage) > sum(supportRowsC0.Damage), ...
        'Ifa Support damage should increase when Rescue Essentials and C2 are both strengthened.');
    assert(height(markRowsC0) == 1 && ~contains(string(markRowsC0.Note(1)), "x4"), ...
        'Single-target Ifa burst should not approximate Sedation Mark as a fixed 4-hit pulse train.');
    assert(height(markRowsMulti) == 1 && contains(string(markRowsMulti.Note(1)), "x2"), ...
        'Multi-target Ifa burst should scale Sedation Mark explosions with the number of marked targets.');
    assert(~any(strcmp(string(breakdownSolo.Action), "Mark")), ...
        'Ifa should not create Sedation Mark explosions when no absorbable element is available.');

    timelineEnemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);
    xingqiu = getDefaultCharacterConfig('Xingqiu');
    pyroHydroMembers = {cfgC0, bennett, xingqiu};

    hydroTimeline = localBuildIfaTimeline([ ...
        localIfaTimelineRow(1, 0.50, "Bennett", "E", "Pyro", 1, "Pyro:1.00U"), ...
        localIfaTimelineRow(2, 1.40, "Xingqiu", "E", "Hydro", 1, "Hydro:1.00U"), ...
        localIfaTimelineRow(3, 2.00, "Ifa", "Q", "Anemo", 1, "Hydro:1.00U")]);
    pyroTimeline = localBuildIfaTimeline([ ...
        localIfaTimelineRow(1, 0.50, "Xingqiu", "E", "Hydro", 1, "Hydro:1.00U"), ...
        localIfaTimelineRow(2, 1.40, "Bennett", "E", "Pyro", 1, "Pyro:1.00U"), ...
        localIfaTimelineRow(3, 2.00, "Ifa", "Q", "Anemo", 1, "Pyro:1.00U")]);
    emptyAuraTimeline = localBuildIfaTimeline([ ...
        localIfaTimelineRow(1, 2.00, "Ifa", "Q", "Anemo", 1, "None")]);

    hydroContext = buildTeamContext(pyroHydroMembers, 20, struct( ...
        'ReactionMode', "Realistic", ...
        'TimelineTable', hydroTimeline), timelineEnemy);
    pyroContext = buildTeamContext(pyroHydroMembers, 20, struct( ...
        'ReactionMode', "Realistic", ...
        'TimelineTable', pyroTimeline), timelineEnemy);
    emptyAuraContext = buildTeamContext(pyroHydroMembers, 20, struct( ...
        'ReactionMode', "Realistic", ...
        'TimelineTable', emptyAuraTimeline), timelineEnemy);

    [~, ~, hydroBreakdown] = simulateIfaDPS( ...
        cfgC0.Build, timelineEnemy, cfgC0.RotationFile, cfgC0.TalentLevel, cfgC0.Constellation, hydroContext);
    [~, ~, pyroBreakdown] = simulateIfaDPS( ...
        cfgC0.Build, timelineEnemy, cfgC0.RotationFile, cfgC0.TalentLevel, cfgC0.Constellation, pyroContext);
    [~, ~, emptyAuraBreakdown] = simulateIfaDPS( ...
        cfgC0.Build, timelineEnemy, cfgC0.RotationFile, cfgC0.TalentLevel, cfgC0.Constellation, emptyAuraContext);

    hydroMarkRows = hydroBreakdown(strcmp(string(hydroBreakdown.Action), "Mark"), :);
    pyroMarkRows = pyroBreakdown(strcmp(string(pyroBreakdown.Action), "Mark"), :);
    emptyAuraMarkRows = emptyAuraBreakdown(strcmp(string(emptyAuraBreakdown.Action), "Mark"), :);

    assert(height(hydroMarkRows) == 1 && contains(string(hydroMarkRows.Note(1)), "Hydro absorb"), ...
        'Ifa should absorb Hydro when the real pre-burst aura state is Hydro, even in a Pyro+Hydro roster tie.');
    assert(height(pyroMarkRows) == 1 && contains(string(pyroMarkRows.Note(1)), "Pyro absorb"), ...
        'Ifa should absorb Pyro when the real pre-burst aura state is Pyro.');
    assert(isempty(emptyAuraMarkRows), ...
        'Ifa should skip Sedation Mark explosions when the real pre-burst aura state is empty.');

    disp('validateIfaRegression passed');
end

function row = localIfaTimelineRow(order, startTime, character, action, hitElement, applyGauge, auraState)
    row = struct( ...
        'Order', double(order), ...
        'StartTime', double(startTime), ...
        'Character', string(character), ...
        'Action', string(action), ...
        'HitElement', string(hitElement), ...
        'ApplyGauge', double(applyGauge), ...
        'AuraState', string(auraState));
end

function timelineTable = localBuildIfaTimeline(rows)
    order = reshape([rows.Order], [], 1);
    startTime = reshape([rows.StartTime], [], 1);
    character = reshape(string({rows.Character}), [], 1);
    action = reshape(string({rows.Action}), [], 1);
    hitElement = reshape(string({rows.HitElement}), [], 1);
    applyGauge = reshape([rows.ApplyGauge], [], 1);
    auraState = reshape(string({rows.AuraState}), [], 1);

    timelineTable = table(order, startTime, character, action, hitElement, applyGauge, auraState, ...
        'VariableNames', {'Order', 'StartTime', 'Character', 'Action', 'HitElement', 'ApplyGauge', 'AuraState'});
end
