function validateTeamHealthEventTimelineRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    furina = getDefaultCharacterConfig('Furina', struct('Constellation', 0, 'TalentLevel', 10));
    barbara = getDefaultCharacterConfig('Barbara');
    teamContext = buildTeamContext({furina, barbara}, 20, struct('ReactionMode', "Realistic"), enemy);

    rotationPlan = struct( ...
        'RotationDuration', 20, ...
        'MemberPlans', [ ...
            struct('Name', "Barbara", 'Role', "Support", 'RotationTokens', {{'Q'}}, 'StartTime', 0.8), ...
            struct('Name', "Furina", 'Role', "Support", 'RotationTokens', {{'E'}}, 'StartTime', 4.0)]);

    result = simulateTeamTimeline({barbara, furina}, rotationPlan, teamContext, enemy, struct());
    healthEvents = result.HealthEventTable;

    assert(istable(healthEvents) && height(healthEvents) >= 2, ...
        'Team timeline should surface explicit HP event rows for healing and drain windows.');
    assert(any(strcmpi(string(healthEvents.EventKind), "Heal")), ...
        'Team timeline should record at least one healing event row.');
    assert(any(strcmpi(string(healthEvents.EventKind), "Drain")), ...
        'Team timeline should record at least one HP drain event row.');

    healRows = healthEvents(strcmpi(string(healthEvents.EventKind), "Heal"), :);
    drainRows = healthEvents(strcmpi(string(healthEvents.EventKind), "Drain"), :);
    assert(any(strcmpi(string(healRows.Character), "Barbara")) && all(double(healRows.TargetCount) >= 1), ...
        'Barbara burst heal should be represented as a team HP restoration event.');
    assert(any(strcmpi(string(drainRows.Character), "Furina")) && all(double(drainRows.TargetCount) >= 1), ...
        'Furina Salon ticks should be represented as team HP drain events.');
    assert(issorted(double(healthEvents.Time)), ...
        'Health event rows should stay sorted by time for downstream fanfare/timeline consumers.');

    ringPlan = struct( ...
        'RotationDuration', 20, ...
        'MemberPlans', [ ...
            struct('Name', "Barbara", 'Role', "Support", 'RotationTokens', {{'E'}}, 'StartTime', 0.8), ...
            struct('Name', "Furina", 'Role', "Support", 'RotationTokens', {{'E'}}, 'StartTime', 4.0)]);
    ringResult = simulateTeamTimeline({barbara, furina}, ringPlan, teamContext, enemy, struct());
    ringHealthEvents = ringResult.HealthEventTable;
    ringHealRows = ringHealthEvents(strcmpi(string(ringHealthEvents.EventName), "MelodyLoopHeal"), :);
    assert(~isempty(ringHealRows) ...
            && any(strcmpi(string(ringHealRows.SourceType), "EffectTick")) ...
            && all(strcmpi(string(ringHealRows.Character), "Barbara")), ...
        'Barbara skill should now surface periodic Melody Loop heal rows through the shared team health timeline.');

    disp('validateTeamHealthEventTimelineRegression passed');
end
