function validateTeamTimelineAuraICDRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    aino = getDefaultCharacterConfig('Aino', struct('Constellation', 2));
    fischl = getDefaultCharacterConfig('Fischl', struct('Constellation', 6));
    teamContext = buildTeamContext({aino, fischl}, 20, struct('ReactionMode', "Realistic"), enemy);

    rotationPlan = struct( ...
        'RotationDuration', 20, ...
        'MemberPlans', [ ...
            struct('Role', "Driver", 'RotationTokens', {{'Q'}}, 'StartTime', 0), ...
            struct('Role', "OffField", 'RotationTokens', {{'E', 'Oz'}}, 'StartTime', 0)]);

    result = simulateTeamTimeline({aino, fischl}, rotationPlan, teamContext, enemy, struct());
    timeline = result.TimelineTable;

    ainoRows = timeline(string(timeline.Character) == "Aino", :);
    ozRows = timeline(contains(string(timeline.Action), "Oz", 'IgnoreCase', true), :);

    assert(~isempty(ainoRows), 'Team timeline should include Aino rows.');
    assert(~isempty(ozRows), 'Team timeline should include Oz background rows.');
    assert(all(ismember(["CanApplyAura", "ApplyGaugeSource", "ICDRule", "ICDGroup", "ICDSource"], string(timeline.Properties.VariableNames))), ...
        'Team timeline should expose aura and ICD columns.');
    assert(all(strcmp(string(ozRows.ApplyGaugeSource), "metadata") | strcmp(string(ozRows.ApplyGaugeSource), "inferred")), ...
        'Oz background rows should resolve ApplyGauge from metadata or inference.');
    assert(any(strcmp(string(ozRows.ICDRule), "4 hits / 5s")), ...
        'Oz background rows should carry the resolved ICD rule.');
    assert(any(strcmp(string(ainoRows.Action), "Q")) && any(ainoRows.ApplyGauge == 0 | ainoRows.ApplyGauge == 1), ...
        'Aino team timeline should retain explicit gauge information on the burst row.');

    disp('validateTeamTimelineAuraICDRegression passed');
end
