function validateLisaRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cfg4 = getDefaultCharacterConfig('Lisa', struct('Constellation', 4, 'TalentLevel', 10));
    cfg6 = getDefaultCharacterConfig('Lisa', struct('Constellation', 6, 'TalentLevel', 10));
    ctx4 = buildTeamContext({cfg4}, 20, struct('ReactionMode', "Realistic"), enemy);
    ctx6 = buildTeamContext({cfg6}, 20, struct('ReactionMode', "Realistic"), enemy);

    [damage4, ~, breakdown4, rotationTime4, audit4] = simulateLisaDPS( ...
        cfg4.Build, enemy, "", cfg4.TalentLevel, cfg4.Constellation, ctx4);
    [damage6, ~, breakdown6, rotationTime6, audit6] = simulateLisaDPS( ...
        cfg6.Build, enemy, "", cfg6.TalentLevel, cfg6.Constellation, ctx6);

    actions4 = string(breakdown4.Action);
    actions6 = string(breakdown6.Action);
    q4 = breakdown4(actions4 == "Q", :);

    assert(damage4 > 0 && rotationTime4 > 0 && damage6 > 0 && rotationTime6 > 0, ...
        'Lisa regression should produce positive damage and rotation time for both C4 and C6.');
    assert(height(q4) == 1 && contains(string(q4.Note), "x24"), ...
        'Lisa C4 regression should keep the doubled expected Lightning Rose hit count.');
    assert(isequal(actions6', ["EHold3", "Q", "CA", "ETap", "EHold2"]), ...
        'Lisa C6 regression should preserve the scripted 3-stack hold-E opener.');
    assert(~any(audit4.Rows.ApplyGaugeFallback | audit4.Rows.ICDFallback) ...
        && ~any(audit6.Rows.ApplyGaugeFallback | audit6.Rows.ICDFallback), ...
        'Lisa regression should keep explicit gauge and ICD metadata for the scripted rotation.');

    disp('validateLisaRegression passed');
end
