function validateJahodaTimelineConversionRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    jahoda = getDefaultCharacterConfig('Jahoda', struct('Constellation', 0));
    bennett = getDefaultCharacterConfig('Bennett');
    xingqiu = getDefaultCharacterConfig('Xingqiu');
    members = {jahoda, bennett, xingqiu};

    hydroTimeline = localBuildJahodaTimeline([ ...
        localJahodaTimelineRow(1, 0.50, "Bennett", "E", "Pyro", 1, "Pyro:1.00U"), ...
        localJahodaTimelineRow(2, 1.40, "Xingqiu", "E", "Hydro", 1, "Hydro:1.00U"), ...
        localJahodaTimelineRow(3, 2.00, "Jahoda", "FlaskFull", "Anemo", 1, "Hydro:1.00U")]);
    pyroTimeline = localBuildJahodaTimeline([ ...
        localJahodaTimelineRow(1, 0.50, "Xingqiu", "E", "Hydro", 1, "Hydro:1.00U"), ...
        localJahodaTimelineRow(2, 1.40, "Bennett", "E", "Pyro", 1, "Pyro:1.00U"), ...
        localJahodaTimelineRow(3, 2.00, "Jahoda", "FlaskFull", "Anemo", 1, "Pyro:1.00U")]);
    emptyAuraTimeline = localBuildJahodaTimeline([ ...
        localJahodaTimelineRow(1, 2.00, "Jahoda", "FlaskFull", "Anemo", 1, "None")]);

    hydroContext = buildTeamContext(members, 20, struct( ...
        'ReactionMode', "Realistic", ...
        'TimelineTable', hydroTimeline), enemy);
    pyroContext = buildTeamContext(members, 20, struct( ...
        'ReactionMode', "Realistic", ...
        'TimelineTable', pyroTimeline), enemy);
    emptyAuraContext = buildTeamContext(members, 20, struct( ...
        'ReactionMode', "Realistic", ...
        'TimelineTable', emptyAuraTimeline), enemy);

    [~, ~, hydroBreakdown] = simulateJahodaDPS( ...
        jahoda.Build, enemy, jahoda.RotationFile, jahoda.TalentLevel, jahoda.Constellation, hydroContext);
    [~, ~, pyroBreakdown] = simulateJahodaDPS( ...
        jahoda.Build, enemy, jahoda.RotationFile, jahoda.TalentLevel, jahoda.Constellation, pyroContext);
    [~, ~, emptyAuraBreakdown] = simulateJahodaDPS( ...
        jahoda.Build, enemy, jahoda.RotationFile, jahoda.TalentLevel, jahoda.Constellation, emptyAuraContext);

    hydroRobotRows = hydroBreakdown(strcmp(string(hydroBreakdown.Action), "Robot"), :);
    pyroRobotRows = pyroBreakdown(strcmp(string(pyroBreakdown.Action), "Robot"), :);

    assert(height(hydroRobotRows) == 1 && contains(string(hydroRobotRows.Note(1)), "Hydro convert"), ...
        'Jahoda should convert to Hydro when the real flask-entry aura is Hydro.');
    assert(height(pyroRobotRows) == 1 && contains(string(pyroRobotRows.Note(1)), "Pyro convert"), ...
        'Jahoda should convert to Pyro when the real flask-entry aura is Pyro.');
    assert(any(strcmp(string(emptyAuraBreakdown.Action), "Smoke")) ...
        && any(strcmp(string(emptyAuraBreakdown.Action), "FlaskPartial")), ...
        'Jahoda should fall back to the smoke + partial flask path when no real conversion aura is present.');
    assert(~any(strcmp(string(emptyAuraBreakdown.Action), "Robot")) ...
        && ~any(strcmp(string(emptyAuraBreakdown.Action), "Meowball")), ...
        'Jahoda should not emit converted follow-up actions when no real aura is present.');

    disp('validateJahodaTimelineConversionRegression passed');
end

function row = localJahodaTimelineRow(order, startTime, character, action, hitElement, applyGauge, auraState)
    row = struct( ...
        'Order', double(order), ...
        'StartTime', double(startTime), ...
        'Character', string(character), ...
        'Action', string(action), ...
        'HitElement', string(hitElement), ...
        'ApplyGauge', double(applyGauge), ...
        'AuraState', string(auraState));
end

function timelineTable = localBuildJahodaTimeline(rows)
    order = reshape([rows.Order], [], 1);
    startTime = reshape([rows.StartTime], [], 1);
    character = reshape(string({rows.Character}), [], 1);
    action = reshape(string({rows.Action}), [], 1);
    hitElement = reshape(string({rows.HitElement}), [], 1);
    applyGauge = reshape([rows.ApplyGauge], [], 1);
    auraState = reshape(string({rows.AuraState}), [], 1);

    timelineTable = table(order, startTime, character, action, hitElement, applyGauge, auraState, ...
        'VariableNames', {'Order', 'StartTime', 'Character', 'Action', 'HitElement', 'ApplyGauge', 'AuraState'});
end
