function validateDahliaRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    cfgC5 = getDefaultCharacterConfig('Dahlia', struct('Constellation', 5));
    cfgC6 = getDefaultCharacterConfig('Dahlia', struct('Constellation', 6));

    [damageC5, ~, breakdownC5, rotationTimeC5] = simulateDahliaDPS( ...
        cfgC5.Build, enemy, cfgC5.RotationFile, cfgC5.TalentLevel, cfgC5.Constellation, ...
        buildTeamContext({cfgC5}, 20, struct('ReactionMode', "Realistic"), enemy));
    [damageC6, ~, breakdownC6, rotationTimeC6] = simulateDahliaDPS( ...
        cfgC6.Build, enemy, cfgC6.RotationFile, cfgC6.TalentLevel, cfgC6.Constellation, ...
        buildTeamContext({cfgC6}, 20, struct('ReactionMode', "Realistic"), enemy));

    normalRowsC6 = breakdownC6(contains(string(breakdownC6.Action), ["N1", "N2", "N3", "N4"]), :);

    assert(rotationTimeC6 < rotationTimeC5, ...
        'Dahlia C6 should shorten the default rotation via the extra Favonian Favor ATK SPD.');
    assert(abs(damageC6 - damageC5) < 1e-6 * max(1, abs(damageC5)), ...
        'Dahlia C6 should not directly inflate damage in the current self-DPS model.');
    assert(any(contains(string(breakdownC6.Note), "detonation")), ...
        'Dahlia E notes should reflect the delayed Shower detonation model.');
    assert(all(contains(string(normalRowsC6.Note), "Favonian Favor SPD")), ...
        'Dahlia normal actions under burst should annotate the Favonian Favor ATK SPD window.');

    approximateEnemy = enemy;
    approximateEnemy.ReactionMode = "Approximate";
    approximateEnemy.AutoSupportAura = true;
    amber = getDefaultCharacterConfig('Amber');
    kaeya = getDefaultCharacterConfig('Kaeya');
    auraMembers = {cfgC5, amber, kaeya};
    pyroTimeline = localBuildDahliaTimeline([ ...
        localDahliaTimelineRow(1, 0.50, "Kaeya", "E", "Cryo", 1, "Cryo:1.00U"), ...
        localDahliaTimelineRow(2, 1.40, "Amber", "E", "Pyro", 1, "Pyro:1.00U"), ...
        localDahliaTimelineRow(3, 2.00, "Dahlia", "EHold", "Hydro", 1, "Pyro:1.00U")]);
    cryoTimeline = localBuildDahliaTimeline([ ...
        localDahliaTimelineRow(1, 0.50, "Amber", "E", "Pyro", 1, "Pyro:1.00U"), ...
        localDahliaTimelineRow(2, 1.40, "Kaeya", "E", "Cryo", 1, "Cryo:1.00U"), ...
        localDahliaTimelineRow(3, 2.00, "Dahlia", "EHold", "Hydro", 1, "Cryo:1.00U")]);
    pyroContext = buildTeamContext(auraMembers, 20, struct( ...
        'ReactionMode', "Approximate", ...
        'TimelineTable', pyroTimeline), approximateEnemy);
    cryoContext = buildTeamContext(auraMembers, 20, struct( ...
        'ReactionMode', "Approximate", ...
        'TimelineTable', cryoTimeline), approximateEnemy);

    [~, ~, pyroBreakdown] = simulateDahliaDPS( ...
        cfgC5.Build, approximateEnemy, cfgC5.RotationFile, cfgC5.TalentLevel, cfgC5.Constellation, pyroContext);
    [~, ~, cryoBreakdown] = simulateDahliaDPS( ...
        cfgC5.Build, approximateEnemy, cfgC5.RotationFile, cfgC5.TalentLevel, cfgC5.Constellation, cryoContext);
    pyroHoldRows = pyroBreakdown(strcmp(string(pyroBreakdown.Action), "EHold"), :);
    cryoHoldRows = cryoBreakdown(strcmp(string(cryoBreakdown.Action), "EHold"), :);

    assert(height(pyroHoldRows) == 1 && height(cryoHoldRows) == 1 ...
        && pyroHoldRows.Damage(1) > cryoHoldRows.Damage(1), ...
        'Dahlia approximate support-aura selection should follow the timeline-derived Pyro/Cryo state.');

    disp('validateDahliaRegression passed');
end

function row = localDahliaTimelineRow(order, startTime, character, action, hitElement, applyGauge, auraState)
    row = struct( ...
        'Order', double(order), ...
        'StartTime', double(startTime), ...
        'Character', string(character), ...
        'Action', string(action), ...
        'HitElement', string(hitElement), ...
        'ApplyGauge', double(applyGauge), ...
        'AuraState', string(auraState));
end

function timelineTable = localBuildDahliaTimeline(rows)
    order = reshape([rows.Order], [], 1);
    startTime = reshape([rows.StartTime], [], 1);
    character = reshape(string({rows.Character}), [], 1);
    action = reshape(string({rows.Action}), [], 1);
    hitElement = reshape(string({rows.HitElement}), [], 1);
    applyGauge = reshape([rows.ApplyGauge], [], 1);
    auraState = reshape(string({rows.AuraState}), [], 1);

    timelineTable = table(order, startTime, character, action, hitElement, applyGauge, auraState, ...
        'VariableNames', {'Order', 'StartTime', 'Character', 'Action', 'HitElement', 'ApplyGauge', 'AuraState'});
end
