function validateAinoJahodaTimelineRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 2, ...
        'TargetCount', 2);

    aino = getDefaultCharacterConfig('Aino', struct('Constellation', 4));
    jahoda = getDefaultCharacterConfig('Jahoda', struct('Constellation', 2));
    teamContext = buildTeamContext({aino, jahoda}, 20, struct('ReactionMode', "Realistic"), enemy);

    [~, ~, breakdownAino] = simulateAinoDPS(aino.Build, enemy, aino.RotationFile, aino.TalentLevel, aino.Constellation, teamContext);
    [~, ~, breakdownJahoda] = simulateJahodaDPS(jahoda.Build, enemy, jahoda.RotationFile, jahoda.TalentLevel, jahoda.Constellation, teamContext);

    assert(any(contains(string(breakdownAino.Action), "C2Ball")) || ...
        any(contains(string(breakdownAino.Action), "Q")), ...
        'Aino breakdown should expose the burst follow-up path.');
    assert(any(contains(string(breakdownJahoda.Action), "Robot")) || ...
        any(contains(string(breakdownJahoda.Action), "Meowball")), ...
        'Jahoda breakdown should expose the converted follow-up path.');

    tempDir = tempname;
    mkdir(tempDir);
    cleanup = onCleanup(@() rmdir(tempDir, 's')); %#ok<NASGU>
    aino.RotationFile = writeTempRotationFile(tempDir, 'Aino', 1, "Q");
    jahoda.RotationFile = writeTempRotationFile(tempDir, 'Jahoda', 2, sprintf('FlaskFull\nQ\n'));

    teamSpec = struct('Members', { {aino, jahoda} }, 'RotationDuration', 20, ...
        'SharedBuffs', struct('ReactionMode', "Realistic"), ...
        'PlanOptions', struct('DisableAutoPlan', true));
    teamResult = simulateTeamDPS(teamSpec, enemy);
    timeline = teamResult.TimelineTable;
    assert(any(contains(string(timeline.Action), "DuckyWaterBall")) || ...
        any(contains(string(timeline.EffectTag), "CoolYourJetsDucky")), ...
        'Team timeline should include Aino background driver metadata.');
    assert(any(contains(string(timeline.Action), "RobotStrike")) || ...
        any(contains(string(timeline.EffectTag), "PurrsonalCoordinatedAssistanceRobots")), ...
        'Team timeline should include Jahoda background driver metadata.');
    assert(any(strlength(string(timeline.HitElement)) > 0), ...
        'Timeline hits should keep a resolved element for background actions.');
    ainoBurstRows = timeline(string(timeline.Character) == "Aino" ...
        & string(timeline.Action) == "Q", :);
    assert(~isempty(ainoBurstRows) && all(ainoBurstRows.ApplyGauge == 0), ...
        'Aino Q should hand off Hydro application to the ducky ticks.');
    jahodaFlaskRows = timeline(string(timeline.Character) == "Jahoda" ...
        & string(timeline.Action) == "FlaskFull", :);
    assert(~isempty(jahodaFlaskRows) && all(jahodaFlaskRows.ApplyGauge == 0), ...
        'Jahoda FlaskFull under Moonsign should store the flask and defer gauge to Meowball.');

    jahodaC5 = getDefaultCharacterConfig('Jahoda', struct('Constellation', 5));
    jahodaC6 = getDefaultCharacterConfig('Jahoda', struct('Constellation', 6));
    jahodaContextC5 = buildTeamContext({aino, jahodaC5}, 20, struct('ReactionMode', "Realistic"), enemy);
    jahodaContextC6 = buildTeamContext({aino, jahodaC6}, 20, struct('ReactionMode', "Realistic"), enemy);
    [damageC5, ~] = simulateJahodaDPS( ...
        jahodaC5.Build, enemy, jahodaC5.RotationFile, jahodaC5.TalentLevel, jahodaC5.Constellation, jahodaContextC5);
    [damageC6, ~] = simulateJahodaDPS( ...
        jahodaC6.Build, enemy, jahodaC6.RotationFile, jahodaC6.TalentLevel, jahodaC6.Constellation, jahodaContextC6);
    assert(damageC6 > damageC5, ...
        'Jahoda C6 should outdamage C5 once the Moonsign crit window is applied.');

    disp('validateAinoJahodaTimelineRegression passed');
end
