function validateTeamAutoPlanCarryFallbackRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    furina = getDefaultCharacterConfig('Furina');
    yelan = getDefaultCharacterConfig('Yelan');
    xianyun = getDefaultCharacterConfig('Xianyun');
    jean = getDefaultCharacterConfig('Jean');

    spec = struct( ...
        'Members', {{furina, yelan, xianyun, jean}}, ...
        'RotationDuration', 20, ...
        'SharedBuffs', struct('ReactionMode', "Realistic"));

    [teamResult, ~] = simulateTeamDPS(spec, enemy);
    plan = teamResult.PlannedRotation;
    execution = plan.ExecutionTable;

    assert(istable(execution) && height(execution) == 4, ...
        'Auto-plan regression should still produce one execution row per enabled member.');
    assert(isfield(plan, 'CandidateCount') && plan.CandidateCount >= 12, ...
        'Auto-plan regression should now search a materially broader set of team timeline candidates instead of a tiny fixed merge list.');
    assert(isfield(plan, 'SelectionMode') && contains(string(plan.SelectionMode), "timeline"), ...
        'Auto-plan regression should expose a timeline-ranked selection mode after evaluating shared team candidates.');
    assert(isfield(plan, 'SelectionScore') && isfinite(plan.SelectionScore), ...
        'Auto-plan regression should expose the selected timeline candidate score.');
    assert(contains(string(plan.SelectionMode), "carry=Furina"), ...
        'Mixed-support Furina sample should no longer drift into unrelated sustain-only carry picks such as Jean.');

    furinaRow = execution(string(execution.Character) == "Furina", :);
    assert(~isempty(furinaRow), ...
        'Furina team regression should keep Furina in the execution table.');
    assert(double(furinaRow.EndTime(1) - furinaRow.StartTime(1)) < 9.5, ...
        'Low-confidence auto-plan should avoid stretching Furina back into the old near-full solo carry loop.');
    assert(double(furinaRow.EndTime(1) - furinaRow.StartTime(1)) > 4.0, ...
        'Low-confidence auto-plan should still reserve a meaningful Furina action window instead of collapsing to a pure support stub.');

    furinaPlan = plan.MemberPlans(strcmpi(string({plan.MemberPlans.Name}), "Furina"));
    yelanPlan = plan.MemberPlans(strcmpi(string({plan.MemberPlans.Name}), "Yelan"));
    xianyunPlan = plan.MemberPlans(strcmpi(string({plan.MemberPlans.Name}), "Xianyun"));
    jeanPlan = plan.MemberPlans(strcmpi(string({plan.MemberPlans.Name}), "Jean"));
    assert(~isempty(furinaPlan), ...
        'Auto-plan regression should expose a Furina member plan.');
    assert(~strcmpi(char(string(furinaPlan.PlanningSource)), 'reference-carry'), ...
        'Low-confidence auto-plan should not fall back to Furina''s full solo carry reference rotation.');
    assert(~contains(string(furinaPlan.RotationText), "Heavy"), ...
        'Low-confidence auto-plan should trim Furina''s support-lean fallback away from the old heavy solo loop.');
    assert(~any(contains(string(furinaPlan.RotationTokens), "Normal")), ...
        'Auto-plan regression should standardize Furina fallback tokens into executable normal strings rather than abstract Normal placeholders.');
    assert(sum(startsWith(string(furinaPlan.RotationTokens), "N")) <= 16, ...
        'Low-confidence Furina carry fallback should keep the foreground normal tail bounded instead of drifting back into the repeated solo seed.');
    assert(~isempty(yelanPlan) && contains(string(yelanPlan.RotationText), "Throw"), ...
        'Support-side template refinement should keep Yelan''s short follow-up in the low-confidence mixed-support sample.');
    assert(~isempty(xianyunPlan) ...
            && sum(contains(string(xianyunPlan.RotationTokens), "Plunge")) <= 1 ...
            && ~contains(string(xianyunPlan.RotationText), "Starwicker"), ...
        'Low-confidence support fallback should no longer drag Xianyun''s autonomous burst ticks into the scheduled foreground window.');
    assert(~isempty(xianyunPlan) && double(xianyunPlan.EstimatedDuration) <= 2.6, ...
        'Support fallback should keep Xianyun near a short setup window rather than a stretched solo fragment.');
    assert(~isempty(jeanPlan) ...
            && sum(startsWith(string(jeanPlan.RotationTokens), "N")) <= 3 ...
            && sum(contains(string(jeanPlan.RotationTokens), "N1")) <= 1, ...
        'Low-confidence support fallback should keep Jean to a single short normal tail instead of repeating the old solo string.');
    assert(~isempty(jeanPlan) && double(jeanPlan.EstimatedDuration) <= 2.8, ...
        'Support fallback should keep Jean within a realistic quickswap sustain window.');

    warnings = string(getFieldOrDefault(teamResult, 'PlanningWarnings', strings(0, 1)));
    assert(~isempty(warnings), ...
        'Team regression should still surface planning warnings when loop energy is missing.');
    assert(double(getFieldOrDefault(teamResult.TimelineSummary, 'IdleTime', inf)) < 3.0, ...
        'Timeline-ranked auto-plan should keep idle time within a realistic low-idle quickswap window after trimming away the old solo-style support tails.');

    disp('validateTeamAutoPlanCarryFallbackRegression passed');
end
