function validateXianglingRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cfg0 = getDefaultCharacterConfig('Xiangling', struct('Constellation', 0, 'TalentLevel', 10));
    cfg4 = getDefaultCharacterConfig('Xiangling', struct('Constellation', 4, 'TalentLevel', 10));
    ctx0 = buildTeamContext({cfg0}, 20, struct('ReactionMode', "Realistic"), enemy);
    ctx4 = buildTeamContext({cfg4}, 20, struct('ReactionMode', "Realistic"), enemy);

    [damage0, ~, breakdown0, rotationTime0, audit0] = simulateXianglingDPS( ...
        cfg0.Build, enemy, cfg0.RotationFile, cfg0.TalentLevel, cfg0.Constellation, ctx0);
    [damage4, ~, breakdown4, rotationTime4, audit4] = simulateXianglingDPS( ...
        cfg4.Build, enemy, cfg4.RotationFile, cfg4.TalentLevel, cfg4.Constellation, ctx4);

    actions0 = string(breakdown0.Action);
    actions4 = string(breakdown4.Action);
    pyronadoEarly0 = breakdown0(actions0 == "PyronadoEarly", :);
    pyronado0 = breakdown0(actions0 == "Pyronado", :);
    chiliRows0 = breakdown0(actions0 == "Chili", :);
    pyronadoEarly4 = breakdown4(actions4 == "PyronadoEarly", :);
    pyronado4 = breakdown4(actions4 == "Pyronado", :);

    assert(damage0 > 0 && rotationTime0 > 0 && damage4 > 0 && rotationTime4 > 0, ...
        'Xiangling regression should produce positive damage and rotation time for both C0 and C4.');
    assert(isequal(actions0', ["E", "QSlash1", "QSlash2", "QSlash3", "PyronadoEarly", "Chili", "Pyronado", "N5Explode"]), ...
        'Xiangling regression should preserve the Guoba -> Pyronado -> chili -> C2 implode order.');
    assert(height(pyronadoEarly0) == 1 && contains(string(pyronadoEarly0.Note), "x5"), ...
        'Xiangling C0 regression should split the opening Pyronado segment into 5 hits.');
    assert(height(pyronado0) == 1 && contains(string(pyronado0.Note), "x5"), ...
        'Xiangling C0 regression should keep the 10-hit Pyronado note.');
    assert(height(chiliRows0) == 1 && strcmp(string(chiliRows0.Note), "Guoba chili pickup"), ...
        'Xiangling regression should expose the chili pickup as an explicit zero-damage row.');
    assert(height(pyronadoEarly4) == 1 && contains(string(pyronadoEarly4.Note), "x5"), ...
        'Xiangling C4 regression should split the opening Pyronado segment into 5 hits.');
    assert(height(pyronado4) == 1 && contains(string(pyronado4.Note), "x9"), ...
        'Xiangling C4 regression should keep the extended 14-hit Pyronado note.');
    assert(~any(audit0.Rows.ApplyGaugeFallback | audit0.Rows.ICDFallback) ...
        && ~any(audit4.Rows.ApplyGaugeFallback | audit4.Rows.ICDFallback), ...
        'Xiangling regression should keep explicit gauge and ICD metadata for the scripted rotation.');

    disp('validateXianglingRegression passed');
end
