function validateTeamAutoPlanRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    furina = getDefaultCharacterConfig('Furina', struct('Constellation', 0, 'TalentLevel', 10));
    barbara = getDefaultCharacterConfig('Barbara');
    lisa = getDefaultCharacterConfig('Lisa');

    baselineSpec = struct( ...
        'Members', {{furina, barbara, lisa}}, ...
        'RotationDuration', 20, ...
        'SharedBuffs', struct());
    baselineResult = simulateTeamDPS(baselineSpec, enemy);
    baselinePlan = baselineResult.PlannedRotation;
    baselinePlans = baselineResult.PlannedRotation.MemberPlans;
    baselineTimeline = baselineResult.TimelineTable;
    baselineReactionRows = baselineTimeline(strlength(strtrim(string(baselineTimeline.Reaction))) > 0, :);
    expectedReactionDensity = min(1, height(baselineReactionRows) / max(height(baselineTimeline), 1));

    assert(all(~[baselinePlans.SeedIsExplicit]), ...
        'Default team auto-plan should treat default single-character rotations as reference data instead of explicit manual seeds.');
    assert(~any(contains(string({baselinePlans.PlanningSource}), "seed-")), ...
        'Default team auto-plan should no longer collapse back to seed-derived member rotations when no manual override is present.');
    assert(~isempty(baselineReactionRows), ...
        'Furina/Barbara/Lisa baseline auto-plan should surface at least one elemental reaction on the selected timeline.');
    assert(isfield(baselinePlan, 'SelectionMetrics') ...
            && isstruct(baselinePlan.SelectionMetrics) ...
            && isfield(baselinePlan.SelectionMetrics, 'ReactionDensity') ...
            && abs(double(baselinePlan.SelectionMetrics.ReactionDensity) - expectedReactionDensity) < 1e-9, ...
        'Auto-plan selection metrics should compute reaction density from the real team timeline Reaction column.');
    assert(contains(string(baselinePlan.SelectionSummary), "react="), ...
        'Auto-plan selection summary should expose reaction density for timeline-ranked candidate debugging.');

    tempDir = tempname;
    mkdir(tempDir);
    cleanup = onCleanup(@() rmdir(tempDir, 's')); %#ok<NASGU>

    customLisa = lisa;
    customLisa.RotationFile = writeTempRotationFile(tempDir, 'Lisa', 2, sprintf('Q\nN1\nN2\n'));
    customLisa.HasExplicitRotationSeed = true;

    customSpec = struct( ...
        'Members', {{furina, barbara, customLisa}}, ...
        'RotationDuration', 20, ...
        'SharedBuffs', struct());
    customResult = simulateTeamDPS(customSpec, enemy);
    customPlans = customResult.PlannedRotation.MemberPlans;
    lisaIndex = find(strcmpi(string({customPlans.Name}), "Lisa"), 1, 'first');

    assert(~isempty(lisaIndex) && customPlans(lisaIndex).SeedIsExplicit, ...
        'Explicit team rotation overrides should still be preserved as manual seeds.');
    assert(contains(string(customPlans(lisaIndex).PlanningSource), "seed-"), ...
        'Explicit team rotation overrides should continue to flow into seed-based planning branches.');

    disp('validateTeamAutoPlanRegression passed');
end
