function validateDahliaRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    cfgC5 = getDefaultCharacterConfig('Dahlia', struct('Constellation', 5));
    cfgC6 = getDefaultCharacterConfig('Dahlia', struct('Constellation', 6));

    [damageC5, ~, breakdownC5, rotationTimeC5] = simulateDahliaDPS( ...
        cfgC5.Build, enemy, cfgC5.RotationFile, cfgC5.TalentLevel, cfgC5.Constellation, ...
        buildTeamContext({cfgC5}, 20, struct('ReactionMode', "Realistic"), enemy));
    [damageC6, ~, breakdownC6, rotationTimeC6] = simulateDahliaDPS( ...
        cfgC6.Build, enemy, cfgC6.RotationFile, cfgC6.TalentLevel, cfgC6.Constellation, ...
        buildTeamContext({cfgC6}, 20, struct('ReactionMode', "Realistic"), enemy));

    normalRowsC6 = breakdownC6(contains(string(breakdownC6.Action), ["N1", "N2", "N3", "N4"]), :);

    assert(rotationTimeC6 < rotationTimeC5, ...
        'Dahlia C6 should shorten the default rotation via the extra Favonian Favor ATK SPD.');
    assert(abs(damageC6 - damageC5) < 1e-6 * max(1, abs(damageC5)), ...
        'Dahlia C6 should not directly inflate damage in the current self-DPS model.');
    assert(any(contains(string(breakdownC6.Note), "detonation")), ...
        'Dahlia E notes should reflect the delayed Shower detonation model.');
    assert(all(contains(string(normalRowsC6.Note), "Favonian Favor SPD")), ...
        'Dahlia normal actions under burst should annotate the Favonian Favor ATK SPD window.');

    disp('validateDahliaRegression passed');
end
