function validateWriothesleyAutoRegression()
    initProjectPaths();

    c0 = auditCharacterReactionMetadata('Wriothesley');
    c6 = auditCharacterReactionMetadata('Wriothesley', struct('Constellation', 6));

    assert(isempty(c0.Rows(c0.Rows.ApplyGaugeFallback | c0.Rows.ICDFallback, :)), ...
        'Wriothesley C0 AUTO rotation should resolve ApplyGauge and ICD metadata without fallback rows.');
    assert(isequal(string(c0.Rows.Action), ...
        ["E"; "N1"; "N2"; "N3"; "N4"; "N5"; "Rebuke"; "N1"; "N2"; "N3"; "N4"; "N5"; "Rebuke"; "Q"; "Blade"]), ...
        'Wriothesley C0 AUTO rotation should expand to the expected standard loop.');

    assert(isempty(c6.Rows(c6.Rows.ApplyGaugeFallback | c6.Rows.ICDFallback, :)), ...
        'Wriothesley C6 AUTO rotation should resolve ApplyGauge and ICD metadata without fallback rows.');
    assert(isequal(string(c6.Rows.Action), ...
        ["E"; "N1"; "N2"; "N3"; "N4"; "N5"; "RebukeC2"; "C6Icicle"; ...
         "N1C2"; "N2C2"; "N3C2"; "N4C2"; "N5C2"; "RebukeC2"; "C6Icicle"; "Q"; "Blade"]), ...
        'Wriothesley C6 AUTO rotation should expand to the expected icicle loop.');

    disp('validateWriothesleyAutoRegression passed');
end
