function validateNicoleRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    nicole = getDefaultCharacterConfig('Nicole', struct('Constellation', 2));
    teamContext = buildTeamContext({nicole}, 20, struct('ReactionMode', "Realistic"), enemy);

    sharedNicoleDMGBonus = getFieldOrDefault(teamContext, 'NicoleApproxSharedAllDMGBonus', 0);
    assert(sharedNicoleDMGBonus > 0, ...
        'Nicole support context should expose a shared weapon-driven DMG bonus.');
    assert(abs(getFieldOrDefault(teamContext, 'NicoleWeaponActiveDMGBonus', 0) - sharedNicoleDMGBonus) < 1e-9, ...
        'Nicole shared DMG bonus should match the active weapon bonus approximation.');
    assert(getFieldOrDefault(teamContext, 'AllDMGBonus', 0) >= sharedNicoleDMGBonus, ...
        'Nicole shared weapon bonus should flow into teamContext.AllDMGBonus.');

    noWeaponContext = teamContext;
    noWeaponContext.AllDMGBonus = getFieldOrDefault(noWeaponContext, 'AllDMGBonus', 0) - sharedNicoleDMGBonus;
    noWeaponContext.NicoleApproxSharedAllDMGBonus = 0;

    [nicoleDamageWith, ~] = simulateNicoleDPS( ...
        nicole.Build, enemy, nicole.RotationFile, nicole.TalentLevel, nicole.Constellation, teamContext);
    [nicoleDamageWithout, ~] = simulateNicoleDPS( ...
        nicole.Build, enemy, nicole.RotationFile, nicole.TalentLevel, nicole.Constellation, noWeaponContext);
    assert(abs(nicoleDamageWith - nicoleDamageWithout) < 1e-6 * max(1, abs(nicoleDamageWith)), ...
        'Nicole self simulation should strip the shared approximation to avoid double-counting weapon DMG bonus.');

    projectionRotation = [tempname, '.txt'];
    cleanupObj = onCleanup(@() localDeleteIfExists(projectionRotation)); %#ok<NASGU>
    fid = fopen(projectionRotation, 'w');
    assert(fid > 0, 'Failed to create temporary Nicole projection regression rotation file.');
    fprintf(fid, 'Q\nProjection\n');
    fclose(fid);

    ownerBuild = struct( ...
        'WeaponATK', 0, ...
        'AtkBonus', 0, ...
        'FlatATK', 0, ...
        'CritRate', 0, ...
        'CritDMG', 0, ...
        'PyroDMGBonus', 0, ...
        'ResShred', 0);
    projectionContext = struct( ...
        'ReactionMode', "Realistic", ...
        'RotationDuration', 20, ...
        'NicoleProjectionOwnerName', "Jean", ...
        'NicoleProjectionOwnerElement', "Pyro", ...
        'NicoleProjectionOwnerIsHexerei', false, ...
        'NicoleProjectionOwnerConfig', struct('Name', "Jean", 'Build', ownerBuild), ...
        'NicoleProjectionMultiplier', 1.0, ...
        'NicoleProjectionMaxCount', 4, ...
        'NicoleWeaponActiveDMGBonus', 0, ...
        'AllDMGBonus', 0, ...
        'ATKBonus', 0, ...
        'FlatATK', 0, ...
        'PyroResShred', 0);

    [~, ~, projectionBreakdown] = simulateNicoleDPS( ...
        nicole.Build, enemy, projectionRotation, nicole.TalentLevel, nicole.Constellation, projectionContext);
    projectionRows = projectionBreakdown(strcmpi(string(projectionBreakdown.Action), "Projection"), :);
    assert(height(projectionRows) == 1, ...
        'Nicole projection regression should isolate exactly one Projection row.');

    jeanChars = readtable(char(resolveCharacterDataFile('Jean', 'characters')), 'TextType', 'string');
    expectedProjectionDamage = double(getFieldOrDefault(jeanChars, 'BaseATK', 0)) ...
        * calcDamageMultiplier(90, enemy, 0);
    assert(abs(projectionRows.Damage - expectedProjectionDamage) < 1e-6 * max(1, expectedProjectionDamage), ...
        'Nicole projection owner ATK should be sourced from the owner''s character data when available.');

    disp('validateNicoleRegression passed');
end

function localDeleteIfExists(path)
    if exist(path, 'file') == 2
        delete(path);
    end
end
