function validateAinoTimelineAuraRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Approximate", ...
        'AutoSupportAura', true, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    aino = getDefaultCharacterConfig('Aino', struct('Constellation', 0));
    amber = getDefaultCharacterConfig('Amber');
    kaeya = getDefaultCharacterConfig('Kaeya');
    members = {aino, amber, kaeya};

    pyroTimeline = localBuildAinoTimeline([ ...
        localAinoTimelineRow(1, 0.50, "Kaeya", "E", "Cryo", 1, "Cryo:1.00U"), ...
        localAinoTimelineRow(2, 1.40, "Amber", "E", "Pyro", 1, "Pyro:1.00U"), ...
        localAinoTimelineRow(3, 2.00, "Aino", "E1", "Hydro", 1, "Pyro:1.00U")]);
    cryoTimeline = localBuildAinoTimeline([ ...
        localAinoTimelineRow(1, 0.50, "Amber", "E", "Pyro", 1, "Pyro:1.00U"), ...
        localAinoTimelineRow(2, 1.40, "Kaeya", "E", "Cryo", 1, "Cryo:1.00U"), ...
        localAinoTimelineRow(3, 2.00, "Aino", "E1", "Hydro", 1, "Cryo:1.00U")]);

    pyroContext = buildTeamContext(members, 20, struct( ...
        'ReactionMode', "Approximate", ...
        'TimelineTable', pyroTimeline), enemy);
    cryoContext = buildTeamContext(members, 20, struct( ...
        'ReactionMode', "Approximate", ...
        'TimelineTable', cryoTimeline), enemy);

    [~, ~, pyroBreakdown] = simulateAinoDPS( ...
        aino.Build, enemy, aino.RotationFile, aino.TalentLevel, aino.Constellation, pyroContext);
    [~, ~, cryoBreakdown] = simulateAinoDPS( ...
        aino.Build, enemy, aino.RotationFile, aino.TalentLevel, aino.Constellation, cryoContext);

    pyroRows = pyroBreakdown(strcmp(string(pyroBreakdown.Action), "E1"), :);
    cryoRows = cryoBreakdown(strcmp(string(cryoBreakdown.Action), "E1"), :);

    assert(height(pyroRows) == 1 && height(cryoRows) == 1 ...
        && pyroRows.Damage(1) > cryoRows.Damage(1), ...
        'Aino approximate support-aura selection should follow the timeline-derived Pyro/Cryo state.');

    disp('validateAinoTimelineAuraRegression passed');
end

function row = localAinoTimelineRow(order, startTime, character, action, hitElement, applyGauge, auraState)
    row = struct( ...
        'Order', double(order), ...
        'StartTime', double(startTime), ...
        'Character', string(character), ...
        'Action', string(action), ...
        'HitElement', string(hitElement), ...
        'ApplyGauge', double(applyGauge), ...
        'AuraState', string(auraState));
end

function timelineTable = localBuildAinoTimeline(rows)
    order = reshape([rows.Order], [], 1);
    startTime = reshape([rows.StartTime], [], 1);
    character = reshape(string({rows.Character}), [], 1);
    action = reshape(string({rows.Action}), [], 1);
    hitElement = reshape(string({rows.HitElement}), [], 1);
    applyGauge = reshape([rows.ApplyGauge], [], 1);
    auraState = reshape(string({rows.AuraState}), [], 1);

    timelineTable = table(order, startTime, character, action, hitElement, applyGauge, auraState, ...
        'VariableNames', {'Order', 'StartTime', 'Character', 'Action', 'HitElement', 'ApplyGauge', 'AuraState'});
end
