function validateTeamTimedReactionTimelineRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    barbara = getDefaultCharacterConfig('Barbara');
    collei = getDefaultCharacterConfig('Collei');
    teamContext = buildTeamContext({barbara, collei}, 10, struct('ReactionMode', "Realistic"), enemy);

    rotationPlan = struct( ...
        'RotationDuration', 10, ...
        'MemberPlans', [ ...
            struct('Role', "Support", 'RotationTokens', {{'E'}}, 'StartTime', 0.00), ...
            struct('Role', "Support", 'RotationTokens', {{'E'}}, 'StartTime', 0.60)]);

    result = simulateTeamTimeline({barbara, collei}, rotationPlan, teamContext, enemy, struct());
    timeline = result.TimelineTable;

    timedReactionRows = timeline(string(timeline.SourceType) == "TimedReaction", :);
    tailRows = timeline(string(timeline.Character) == "Team" & string(timeline.Action) == "Tail", :);

    assert(~isempty(timedReactionRows), ...
        'Bloom timeout should surface as an explicit timed reaction event in the team timeline.');
    assert(any(string(timedReactionRows.Action) == "Bloom"), ...
        'Timed reaction rows should preserve the Bloom timeout reaction name.');
    assert(any(string(timedReactionRows.TriggerPacketSource) == "DendroCore"), ...
        'Timed reaction rows should expose the originating packet source for expired Dendro Cores.');
    assert(any(string(timedReactionRows.TriggerSourceCharacter) == "Collei"), ...
        'Timed reaction rows should preserve the original reaction owner for Bloom-core timeout damage.');
    assert(~isempty(tailRows) && all(strlength(string(tailRows.Reaction)) == 0), ...
        'Tail summary rows should no longer hide timed reactions inside the aggregate Reaction column.');
    assert(height(tailRows) == 2 ...
        && abs(tailRows.StartTime(1) - 1.3) < 1e-9 ...
        && abs(tailRows.EndTime(1) - 6.6) < 1e-9 ...
        && abs(tailRows.StartTime(2) - 6.6) < 1e-9, ...
        'Tail windows should be split around the timed Bloom event instead of spanning across it.');

    disp('validateTeamTimedReactionTimelineRegression passed');
end
