function validateRazorRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    cfg = getDefaultCharacterConfig('Razor', struct('Constellation', 6));
    teamContext = buildTeamContext({cfg}, 20, struct('ReactionMode', "Realistic"), enemy);
    [damage, ~, breakdown, ~, audit] = simulateRazorDPS( ...
        cfg.Build, enemy, [], cfg.TalentLevel, cfg.Constellation, teamContext);

    rows = audit.Rows;
    qRows = rows(string(rows.ActionKey) == "Q", :);
    fallbackRows = rows(rows.ApplyGaugeFallback | rows.ICDFallback, :);

    assert(damage > 0, 'Razor default simulation should produce positive damage.');
    assert(~isempty(qRows), 'Razor audit should include the burst-cast action row.');
    assert(all(strcmp(string(qRows.ApplyGaugeSource), "explicit")), ...
        'Razor burst cast should resolve ApplyGauge from explicit metadata.');
    assert(all(strcmp(string(qRows.ICDSource), "explicit")), ...
        'Razor burst cast should resolve ICD metadata from the handcrafted action spec.');
    assert(isempty(fallbackRows), ...
        'Razor audit should resolve ApplyGauge and ICD metadata without fallback rows.');
    assert(any(strcmp(string(breakdown.Action), "Wolf")), ...
        'Razor default rotation should still include the wolf-companion follow-up action.');

    disp('validateRazorRegression passed');
end
