function validateOroronRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 2, ...
        'TargetCount', 2);

    cfgC5 = getDefaultCharacterConfig('Ororon', struct('Constellation', 5));
    cfgC6 = getDefaultCharacterConfig('Ororon', struct('Constellation', 6));
    teamContext = buildTeamContext({cfgC6}, 20, struct('ReactionMode', "Realistic"), enemy);

    [damageC5, ~, breakdownC5] = simulateOroronDPS( ...
        cfgC5.Build, enemy, cfgC5.RotationFile, cfgC5.TalentLevel, cfgC5.Constellation, teamContext);
    [damageC6, ~, breakdownC6] = simulateOroronDPS( ...
        cfgC6.Build, enemy, cfgC6.RotationFile, cfgC6.TalentLevel, cfgC6.Constellation, teamContext);
    [damageC1, ~, breakdownC1] = simulateOroronDPS( ...
        cfgC5.Build, enemy, cfgC5.RotationFile, cfgC5.TalentLevel, 1, teamContext);

    ororonEC = getDefaultCharacterConfig('Ororon', struct('Constellation', 1));
    xingqiu = getDefaultCharacterConfig('Xingqiu');
    fischl = getDefaultCharacterConfig('Fischl');
    noelle = getDefaultCharacterConfig('Noelle');
    ifa = getDefaultCharacterConfig('Ifa');

    teamContextEC = buildTeamContext({ororonEC, xingqiu, fischl, noelle}, 20, struct('ReactionMode', "Realistic"), enemy);
    teamContextNatlanEC = buildTeamContext({ororonEC, xingqiu, fischl, ifa}, 20, struct('ReactionMode', "Realistic"), enemy);

    [damageEC, ~, breakdownEC] = simulateOroronDPS( ...
        ororonEC.Build, enemy, ororonEC.RotationFile, ororonEC.TalentLevel, ororonEC.Constellation, teamContextEC);
    [damageNatlanEC, ~, breakdownNatlanEC] = simulateOroronDPS( ...
        ororonEC.Build, enemy, ororonEC.RotationFile, ororonEC.TalentLevel, ororonEC.Constellation, teamContextNatlanEC);

    hypersenseNoteEC = string(breakdownEC.Note(strcmp(string(breakdownEC.Action), "Hypersense")));
    hypersenseNoteNatlanEC = string(breakdownNatlanEC.Note(strcmp(string(breakdownNatlanEC.Action), "Hypersense")));

    assert(damageC6 >= damageC5, ...
        'Ororon C6 should not underperform C5 in the default multi-target rotation.');
    assert(any(contains(string(breakdownC6.Note), "C6 burst-triggered Hypersense")), ...
        'Ororon C6 should expose the burst-triggered Hypersense note.');
    assert(any(contains(string(breakdownC6.Action), "C6Echo")), ...
        'Ororon C6 rotation should include the C6 echo action.');
    assert(any(contains(string(breakdownC1.Note), "Nighttide")), ...
        'Ororon C1 should expose the Nighttide note on Spirit Orb hits.');
    assert(isfield(teamContextEC, 'ArchetypeInfo') && isstruct(teamContextEC.ArchetypeInfo) ...
        && ~isempty(fieldnames(teamContextEC.ArchetypeInfo)), ...
        'buildTeamContext should expose ArchetypeInfo for direct character sims.');
    assert(any(contains(hypersenseNoteEC, "est. 5 procs")), ...
        'Ororon plain Electro-Charged comp should expose the 5-proc Hypersense estimate.');
    assert(any(contains(hypersenseNoteNatlanEC, "est. 7 procs")), ...
        'Ororon Natlan + Electro-Charged comp should expose the higher 7-proc Hypersense estimate.');
    assert(damageNatlanEC > damageEC, ...
        'Natlan-backed Electro-Charged setup should outperform plain Electro-Charged via extra Hypersense pressure.');

    disp('validateOroronRegression passed');
end
