function validateTeamEnergyCatchRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    xingqiu = getDefaultCharacterConfig('Xingqiu');
    xiangling = getDefaultCharacterConfig('Xiangling');
    xingqiu.StartEnergy = 0;
    xiangling.StartEnergy = 0;
    teamContext = buildTeamContext({xingqiu, xiangling}, 20, struct('ReactionMode', "Realistic"), enemy);

    stayPlan = struct( ...
        'RotationDuration', 20, ...
        'MemberPlans', [ ...
            struct('Role', "Driver", 'RotationTokens', {{'E', 'N1', 'N1'}}, 'StartTime', 0.0), ...
            struct('Role', "OffField", 'RotationTokens', {{'Q'}}, 'StartTime', 3.5)]);

    funnelPlan = struct( ...
        'RotationDuration', 20, ...
        'MemberPlans', [ ...
            struct('Role', "Driver", 'RotationTokens', {{'E'}}, 'StartTime', 0.0), ...
            struct('Role', "OffField", 'RotationTokens', {{'Q', 'N1'}}, 'StartTime', 1.05)]);

    stayResult = simulateTeamTimeline({xingqiu, xiangling}, stayPlan, teamContext, enemy, struct());
    funnelResult = simulateTeamTimeline({xingqiu, xiangling}, funnelPlan, teamContext, enemy, struct());

    stayEnergyTimeline = stayResult.EnergyTimeline;
    funnelEnergyTimeline = funnelResult.EnergyTimeline;
    stayEnergySummary = stayResult.EnergySummary;
    funnelEnergySummary = funnelResult.EnergySummary;

    assert(istable(stayEnergyTimeline) && istable(funnelEnergyTimeline), ...
        'Team timeline should expose a structured energy timeline table.');
    assert(any(string(stayEnergyTimeline.EventType) == "ParticleCatch"), ...
        'Energy timeline should now record delayed particle catch events.');
    assert(any(string(funnelEnergyTimeline.EventType) == "ParticleCatch"), ...
        'Funnel timeline should also record delayed particle catch events.');

    stayCatchRows = stayEnergyTimeline(string(stayEnergyTimeline.SourceCharacter) == "Xingqiu" ...
        & string(stayEnergyTimeline.Action) == "E" ...
        & string(stayEnergyTimeline.EventType) == "ParticleCatch", :);
    funnelCatchRows = funnelEnergyTimeline(string(funnelEnergyTimeline.SourceCharacter) == "Xingqiu" ...
        & string(funnelEnergyTimeline.Action) == "E" ...
        & string(funnelEnergyTimeline.EventType) == "ParticleCatch", :);

    assert(~isempty(stayCatchRows) && ~isempty(funnelCatchRows), ...
        'Xingqiu skill should emit delayed catch rows in both timelines.');
    assert(any(string(stayCatchRows.Recipient) == "Xingqiu") ...
            && any(string(stayCatchRows.Recipient) == "Xiangling"), ...
        'Delayed particle catch should still distribute some energy to off-field teammates.');
    assert(any(string(funnelCatchRows.Recipient) == "Xiangling"), ...
        'After a pre-catch swap, the foreground teammate should receive a catch row.');

    stayXiangling = stayEnergySummary(string(stayEnergySummary.Character) == "Xiangling", :);
    funnelXiangling = funnelEnergySummary(string(funnelEnergySummary.Character) == "Xiangling", :);
    stayXingqiu = stayEnergySummary(string(stayEnergySummary.Character) == "Xingqiu", :);
    funnelXingqiu = funnelEnergySummary(string(funnelEnergySummary.Character) == "Xingqiu", :);

    assert(~isempty(stayXiangling) && ~isempty(funnelXiangling) && ~isempty(stayXingqiu) && ~isempty(funnelXingqiu), ...
        'Energy summary should keep both members.');
    assert(funnelXiangling.EndEnergy > stayXiangling.EndEnergy, ...
        'Front-loading a swap before particle arrival should increase the funnel target''s ending energy.');
    assert(funnelXingqiu.EndEnergy < stayXingqiu.EndEnergy, ...
        'Handing particles to a teammate should reduce the original owner''s ending energy.');
    assert(sum(stayCatchRows.DeltaEnergy(string(stayCatchRows.Recipient) == "Xingqiu")) ...
            > sum(stayCatchRows.DeltaEnergy(string(stayCatchRows.Recipient) == "Xiangling")), ...
        'Without a pre-catch swap, the original on-field owner should receive the larger share of same-element particles.');
    assert(sum(funnelCatchRows.DeltaEnergy(string(funnelCatchRows.Recipient) == "Xiangling")) ...
            > sum(funnelCatchRows.DeltaEnergy(string(funnelCatchRows.Recipient) == "Xingqiu")), ...
        'After a pre-catch swap, the new foreground teammate should receive the larger share of the caught particles.');
    assert(stayResult.LoopReadiness < 1 && funnelResult.LoopReadiness < 1, ...
        'Zero-start energy timelines should not be misreported as fully loop-ready.');

    disp('validateTeamEnergyCatchRegression passed');
end
