function validateDefaultSoloContextReactionModeRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cases = { ...
        struct('Name', "Sethos", 'Cfg', getDefaultCharacterConfig('Sethos', struct('Constellation', 0)), ...
            'SimFn', @simulateSethosDPS), ...
        struct('Name', "Ororon", 'Cfg', getDefaultCharacterConfig('Ororon', struct('Constellation', 1)), ...
            'SimFn', @simulateOroronDPS), ...
        struct('Name', "Ifa", 'Cfg', getDefaultCharacterConfig('Ifa', struct('Constellation', 0)), ...
            'SimFn', @simulateIfaDPS)};

    for caseIndex = 1:numel(cases)
        current = cases{caseIndex};
        cfg = current.Cfg;
        [~, ~, ~, ~, audit] = current.SimFn( ...
            cfg.Build, enemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, []);
        assert(strcmp(string(getFieldOrDefault(audit, 'TeamContextReactionMode', "")), "Realistic"), ...
            sprintf('%s default simulator context should inherit the explicit Realistic enemy reaction mode.', current.Name));
        assert(~logical(getFieldOrDefault(audit, 'EnemyStateAutoSupportAura', true)), ...
            sprintf('%s default simulator context should not silently re-enable support-aura fallback in Realistic mode.', current.Name));
    end

    disp('validateDefaultSoloContextReactionModeRegression passed');
end
