function validateVarkaRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnableElementalAura', true, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    varka = getDefaultCharacterConfig('Varka', struct('Constellation', 2));
    tempDir = tempname;
    mkdir(tempDir);
    cleanupObj = onCleanup(@() rmdir(tempDir, 's')); %#ok<NASGU>

    pyrosupports = { ...
        varka, ...
        struct('Name', 'Jean', 'Constellation', 0, 'Build', struct()), ...
        struct('Name', 'Bennett', 'Constellation', 0, 'Build', struct()), ...
        struct('Name', 'Xiangling', 'Constellation', 0, 'Build', struct())};
    pyroContext = buildTeamContext(pyrosupports, 20, struct('ReactionMode', "Realistic"), enemy);
    pyroRotation = writeTempRotationFile(tempDir, 'Varka', 1, sprintf('E\nN1\nN2\nAscend\nDevour\nQ\n'));

    [~, ~, pyroBreakdown] = simulateVarkaDPS( ...
        varka.Build, enemy, pyroRotation, varka.TalentLevel, varka.Constellation, pyroContext);
    pyroActions = string(pyroBreakdown.Action);
    pyroNotes = string(pyroBreakdown.Note);

    assert(any(contains(pyroNotes, "right=Pyro")), ...
        'Varka should prioritize Pyro as the right-hand infused element.');
    assert(any(contains(pyroNotes, "Oath+1")) || any(contains(pyroNotes, "Oath x1")), ...
        'Varka should gain Azure Fang''s Oath after self-triggered Swirl in Sturm und Drang.');
    assert(any(contains(pyroNotes, "Lyrical")), ...
        'C1 Lyrical Libation should be consumed by the first special action.');
    assert(any(pyroActions == "FourWindsC2"), ...
        'C2 should add an extra Four Winds follow-up strike row.');
    assert(any(pyroActions == "AzureDevourC2"), ...
        'C2 should add an extra Azure Devour follow-up strike row.');
    assert(any(contains(pyroNotes, "slash1=Pyro")), ...
        'Burst first slash should convert to the chosen right-hand element.');

    hydroSupports = { ...
        varka, ...
        struct('Name', 'Jean', 'Constellation', 0, 'Build', struct()), ...
        struct('Name', 'Xingqiu', 'Constellation', 0, 'Build', struct()), ...
        struct('Name', 'Fischl', 'Constellation', 0, 'Build', struct())};
    hydroContext = buildTeamContext(hydroSupports, 20, struct('ReactionMode', "Realistic"), enemy);
    hydroRotation = writeTempRotationFile(tempDir, 'Varka', 2, sprintf('E\nN1\n'));

    [~, ~, hydroBreakdown] = simulateVarkaDPS( ...
        varka.Build, enemy, hydroRotation, varka.TalentLevel, varka.Constellation, hydroContext);
    hydroNotes = string(hydroBreakdown.Note);

    assert(any(contains(hydroNotes, "right=Hydro")), ...
        'Hydro should outrank Electro when Pyro is absent.');
    assert(~any(contains(hydroNotes, "right=Electro")), ...
        'Electro should not be selected over Hydro in the right-hand priority rule.');

    varkaC6 = getDefaultCharacterConfig('Varka', struct('Constellation', 6));
    pyroSupportsC6 = { ...
        varkaC6, ...
        struct('Name', 'Jean', 'Constellation', 0, 'Build', struct()), ...
        struct('Name', 'Bennett', 'Constellation', 0, 'Build', struct()), ...
        struct('Name', 'Xiangling', 'Constellation', 0, 'Build', struct())};
    pyroContextC6 = buildTeamContext(pyroSupportsC6, 20, struct('ReactionMode', "Realistic"), enemy);
    chainedRotation = writeTempRotationFile(tempDir, 'Varka', 3, sprintf('E\nAscend\nDevour\nAscend\nDevour\nAscend\nDevour\n'));
    gappedRotation = writeTempRotationFile(tempDir, 'Varka', 4, sprintf('E\nAscend\nN1\nDevour\nAscend\nDevour\nAscend\nDevour\n'));

    [damageChained, ~, breakdownChained] = simulateVarkaDPS( ...
        varkaC6.Build, enemy, chainedRotation, varkaC6.TalentLevel, varkaC6.Constellation, pyroContextC6);
    [damageGapped, ~, breakdownGapped] = simulateVarkaDPS( ...
        varkaC6.Build, enemy, gappedRotation, varkaC6.TalentLevel, varkaC6.Constellation, pyroContextC6);
    chainedDevourStarts = breakdownChained(strcmp(string(breakdownChained.Action), "AzureDevourRight1"), :);
    gappedDevourStarts = breakdownGapped(strcmp(string(breakdownGapped.Action), "AzureDevourRight1"), :);

    assert(height(chainedDevourStarts) == 3 && height(gappedDevourStarts) == 3, ...
        'Expanded Varka C6 regressions should expose all three Azure Devour group starts.');
    assert(all(contains(string(chainedDevourStarts.Note), "C6 free")), ...
        'Fully chained Varka C6 Devour groups should consume the stored free-link state.');
    assert(all(contains(string(gappedDevourStarts.Note), "C6 free")), ...
        'Varka C6 free-link state should survive filler actions until the matching Devour consumes it.');
    assert(~any(contains(string(gappedDevourStarts.Note), "no Four Winds use")), ...
        'Varka C6 gap-linked Devour starts should not fail the Four Winds charge gate.');
    assert(damageGapped > damageChained, ...
        'A filler normal should add damage without breaking the preserved Varka C6 Devour link.');

    disp('validateVarkaRegression passed');
end
