function validateVentiRegression()
    initProjectPaths();

    baseEnemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cfg = getDefaultCharacterConfig('Venti', struct('TalentLevel', 10, 'Constellation', 0));
    amber = getDefaultCharacterConfig('Amber');
    barbara = getDefaultCharacterConfig('Barbara');
    build = cfg.Build;
    build.PyroDMGBonus = 0.80;
    build.HydroDMGBonus = 0.00;

    priorityContext = buildTeamContext({cfg, amber, barbara}, 20, struct('ReactionMode', "Realistic"), baseEnemy);
    overrideEnemy = baseEnemy;
    overrideEnemy.InitialAuraElement = "Hydro";
    overrideContext = buildTeamContext({cfg, amber, barbara}, 20, struct('ReactionMode', "Realistic"), overrideEnemy);

    [priorityDamage, ~, priorityBreakdown, priorityTime, priorityAudit] = simulateVentiDPS( ...
        build, baseEnemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, priorityContext);
    [overrideDamage, ~, overrideBreakdown, overrideTime, overrideAudit] = simulateVentiDPS( ...
        build, overrideEnemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, overrideContext);

    priorityActions = string(priorityBreakdown.Action);
    priorityInfuse = priorityBreakdown(priorityActions == "QInfuse", :);
    overrideInfuse = overrideBreakdown(string(overrideBreakdown.Action) == "QInfuse", :);

    assert(priorityDamage > 0 && priorityTime > 0 && overrideDamage > 0 && overrideTime > 0, ...
        'Venti regression should produce positive damage and rotation time.');
    assert(isequal(priorityActions', ["EHold", "QDot", "QInfuse", "E"]), ...
        'Venti regression should preserve the hold E -> burst -> infuse -> tap E order.');
    assert(height(priorityInfuse) == 1 && height(overrideInfuse) == 1, ...
        'Venti regression should isolate one absorbed-element row per scripted rotation.');
    assert(priorityInfuse.Damage > overrideInfuse.Damage, ...
        'Venti regression should prefer Pyro over Hydro when no initial aura override is present.');
    assert(~any(priorityAudit.Rows.ApplyGaugeFallback | priorityAudit.Rows.ICDFallback) ...
        && ~any(overrideAudit.Rows.ApplyGaugeFallback | overrideAudit.Rows.ICDFallback), ...
        'Venti regression should keep explicit gauge and ICD metadata for the scripted rotation.');

    disp('validateVentiRegression passed');
end
