function validateTeamContextTimelineAttachmentRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    furina = getDefaultCharacterConfig('Furina', struct('Constellation', 0, 'TalentLevel', 10));
    barbara = getDefaultCharacterConfig('Barbara');
    lisa = getDefaultCharacterConfig('Lisa');
    teamSpec = struct( ...
        'Members', {{furina, barbara, lisa}}, ...
        'RotationDuration', 20, ...
        'SharedBuffs', struct());

    teamResult = simulateTeamDPS(teamSpec, enemy);
    teamContext = teamResult.TeamContext;

    assert(isfield(teamContext, 'TimelineTable') ...
        && istable(teamContext.TimelineTable) ...
        && height(teamContext.TimelineTable) == height(teamResult.TimelineTable), ...
        'simulateTeamDPS should carry the resolved TimelineTable into TeamContext.');
    assert(isfield(teamContext, 'EnergyTimeline') ...
        && istable(teamContext.EnergyTimeline) ...
        && height(teamContext.EnergyTimeline) == height(teamResult.EnergyTimeline), ...
        'simulateTeamDPS should carry the resolved EnergyTimeline into TeamContext.');
    assert(isfield(teamContext, 'ActiveEffectsTable') ...
        && istable(teamContext.ActiveEffectsTable) ...
        && height(teamContext.ActiveEffectsTable) == height(teamResult.ActiveEffectsTable), ...
        'simulateTeamDPS should carry the resolved ActiveEffectsTable into TeamContext.');
    assert(isfield(teamContext, 'HealthEventTable') ...
        && istable(teamContext.HealthEventTable) ...
        && height(teamContext.HealthEventTable) == height(teamResult.HealthEventTable), ...
        'simulateTeamDPS should carry the resolved HealthEventTable into TeamContext.');
    assert(isfield(teamContext, 'CanLoopNextCycle') ...
        && logical(teamContext.CanLoopNextCycle) == logical(teamResult.CanLoopNextCycle), ...
        'simulateTeamDPS should carry loop readiness booleans into TeamContext.');
    assert(isfield(teamContext, 'LoopReadiness') ...
        && abs(double(teamContext.LoopReadiness) - double(teamResult.LoopReadiness)) < 1e-9, ...
        'simulateTeamDPS should carry loop readiness scalars into TeamContext.');

    disp('validateTeamContextTimelineAttachmentRegression passed');
end
