function validateAinoJahodaTimelineRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 2, ...
        'TargetCount', 2);

    aino = getDefaultCharacterConfig('Aino', struct('Constellation', 4));
    jahoda = getDefaultCharacterConfig('Jahoda', struct('Constellation', 2));
    teamContext = buildTeamContext({aino, jahoda}, 20, struct('ReactionMode', "Realistic"), enemy);

    [~, ~, breakdownAino] = simulateAinoDPS(aino.Build, enemy, aino.RotationFile, aino.TalentLevel, aino.Constellation, teamContext);
    [~, ~, breakdownJahoda] = simulateJahodaDPS(jahoda.Build, enemy, jahoda.RotationFile, jahoda.TalentLevel, jahoda.Constellation, teamContext);
    soloJahoda = getDefaultCharacterConfig('Jahoda', struct('Constellation', 0));
    soloJahodaContext = buildTeamContext({soloJahoda}, 20, struct('ReactionMode', "Realistic"), enemy);
    [~, ~, soloJahodaBreakdown] = simulateJahodaDPS( ...
        soloJahoda.Build, enemy, soloJahoda.RotationFile, soloJahoda.TalentLevel, soloJahoda.Constellation, soloJahodaContext);

    assert(any(contains(string(breakdownAino.Action), "C2Ball")) || ...
        any(contains(string(breakdownAino.Action), "Q")), ...
        'Aino breakdown should expose the burst follow-up path.');
    assert(any(contains(string(breakdownJahoda.Action), "Robot")) || ...
        any(contains(string(breakdownJahoda.Action), "Meowball")), ...
        'Jahoda breakdown should expose the converted follow-up path.');
    assert(any(strcmp(string(soloJahodaBreakdown.Action), "Smoke")) ...
        && any(strcmp(string(soloJahodaBreakdown.Action), "FlaskPartial")), ...
        'Solo Jahoda fallback should keep the smoke-bomb and unfilled flask path.');
    assert(~any(strcmp(string(soloJahodaBreakdown.Action), "Meowball")) ...
        && ~any(strcmp(string(soloJahodaBreakdown.Action), "Robot")), ...
        'Solo Jahoda fallback should not emit zero-damage converted follow-up rows without an element conversion.');

    tempDir = tempname;
    mkdir(tempDir);
    cleanup = onCleanup(@() rmdir(tempDir, 's')); %#ok<NASGU>
    aino.RotationFile = writeTempRotationFile(tempDir, 'Aino', 1, "Q");
    jahoda.RotationFile = writeTempRotationFile(tempDir, 'Jahoda', 2, sprintf('FlaskFull\nQ\n'));

    teamSpec = struct('Members', { {aino, jahoda} }, 'RotationDuration', 20, ...
        'SharedBuffs', struct('ReactionMode', "Realistic"), ...
        'PlanOptions', struct('DisableAutoPlan', true));
    teamResult = simulateTeamDPS(teamSpec, enemy);
    timeline = teamResult.TimelineTable;
    assert(any(contains(string(timeline.Action), "DuckyWaterBall")) || ...
        any(contains(string(timeline.EffectTag), "CoolYourJetsDucky")), ...
        'Team timeline should include Aino background driver metadata.');
    assert(any(contains(string(timeline.Action), "RobotStrike")) || ...
        any(contains(string(timeline.EffectTag), "PurrsonalCoordinatedAssistanceRobots")), ...
        'Team timeline should include Jahoda background driver metadata.');
    assert(any(strlength(string(timeline.HitElement)) > 0), ...
        'Timeline hits should keep a resolved element for background actions.');
    ainoBurstRows = timeline(string(timeline.Character) == "Aino" ...
        & string(timeline.Action) == "Q", :);
    assert(~isempty(ainoBurstRows) && all(ainoBurstRows.ApplyGauge == 0), ...
        'Aino Q should hand off Hydro application to the ducky ticks.');
    jahodaFlaskRows = timeline(string(timeline.Character) == "Jahoda" ...
        & string(timeline.Action) == "FlaskFull", :);
    assert(~isempty(jahodaFlaskRows) && all(jahodaFlaskRows.ApplyGauge == 0), ...
        'Jahoda FlaskFull under Moonsign should store the flask and defer gauge to Meowball.');

    jahodaC5 = getDefaultCharacterConfig('Jahoda', struct('Constellation', 5));
    jahodaC6 = getDefaultCharacterConfig('Jahoda', struct('Constellation', 6));
    jahodaContextC5 = buildTeamContext({aino, jahodaC5}, 20, struct('ReactionMode', "Realistic"), enemy);
    jahodaContextC6 = buildTeamContext({aino, jahodaC6}, 20, struct('ReactionMode', "Realistic"), enemy);
    [damageC5, ~] = simulateJahodaDPS( ...
        jahodaC5.Build, enemy, jahodaC5.RotationFile, jahodaC5.TalentLevel, jahodaC5.Constellation, jahodaContextC5);
    [damageC6, ~] = simulateJahodaDPS( ...
        jahodaC6.Build, enemy, jahodaC6.RotationFile, jahodaC6.TalentLevel, jahodaC6.Constellation, jahodaContextC6);
    assert(damageC6 > damageC5, ...
        'Jahoda C6 should outdamage C5 once the Moonsign crit window is applied.');

    varka = getDefaultCharacterConfig('Varka', struct('Constellation', 2));
    jean = getDefaultCharacterConfig('Jean');
    bennett = getDefaultCharacterConfig('Bennett');
    xiangling = getDefaultCharacterConfig('Xiangling');
    varka.RotationFile = writeTempRotationFile(tempDir, 'Varka', 3, sprintf('E\nAscend\nDevour\nQ\n'));
    varkaPlan = struct('Members', { {varka, jean, bennett, xiangling} }, 'RotationDuration', 20, ...
        'SharedBuffs', struct('ReactionMode', "Realistic"), ...
        'PlanOptions', struct('DisableAutoPlan', true));
    varkaTimeline = simulateTeamDPS(varkaPlan, enemy).TimelineTable;
    varkaActions = string(varkaTimeline.Action);
    varkaRows = varkaTimeline(string(varkaTimeline.Character) == "Varka", :);

    assert(any(varkaActions == "FourWindsRight") && any(varkaActions == "FourWindsAnemo") ...
        && any(varkaActions == "AzureDevourRight1") && any(varkaActions == "Q1") && any(varkaActions == "Q2"), ...
        'Varka team timeline should expand public special tokens into the internal multi-hit action rows.');
    assert(any(varkaRows.Action == "FourWindsRight" & varkaRows.HitElement == "Pyro" & varkaRows.ApplyGauge == 1), ...
        'Varka Four Winds right-hand row should retain Pyro application in the team timeline.');
    assert(any(varkaRows.Action == "FourWindsAnemo" & varkaRows.HitElement == "Anemo" & varkaRows.ApplyGauge == 1), ...
        'Varka Four Winds anemo row should retain its Anemo follow-up hit in the team timeline.');
    assert(any(varkaRows.Action == "Q2" & varkaRows.HitElement == "Anemo" & varkaRows.SourceType == "MemberAction"), ...
        'Varka burst follow-up slash should be scheduled as an explicit timeline action row.');

    disp('validateAinoJahodaTimelineRegression passed');
end
