function validateReactionEngineRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);
    teamContext = struct('ReactionMode', "Realistic");
    build = struct('EM', 0, 'ReactionDMGBonus', 0);

    state = createEnemyState(enemy, teamContext, "");
    state = localApplyAuraOnly(state, "Pyro", 1.0, build, teamContext, enemy);
    forwardVape = resolveReactionForHit(state, localMakeHit("Hydro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(forwardVape.PrimaryReaction), 'Vaporize'), ...
        'Expected Vaporize to trigger from Hydro on Pyro.');
    assert(localAuraGauge(forwardVape.EnemyState, "Pyro") == 0, ...
        'Forward Vaporize should fully consume a 1U Pyro aura with a 1U Hydro trigger.');
    assert(localAuraGauge(forwardVape.EnemyState, "Hydro") > 0, ...
        'Forward Vaporize should leave a residual Hydro aura when the trigger over-consumes the aura.');

    state = createEnemyState(enemy, teamContext, "");
    state = localApplyAuraOnly(state, "Hydro", 1.0, build, teamContext, enemy);
    reverseVape = resolveReactionForHit(state, localMakeHit("Pyro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(reverseVape.PrimaryReaction), 'Vaporize'), ...
        'Expected Vaporize to trigger from Pyro on Hydro.');
    assert(localAuraGauge(reverseVape.EnemyState, "Hydro") > 0, ...
        'Reverse Vaporize should leave Hydro aura behind after the weaker aura tax.');
    assert(localAuraGauge(reverseVape.EnemyState, "Pyro") == 0, ...
        'Reverse Vaporize should not fabricate a residual Pyro aura when Hydro remains dominant.');

    state = createEnemyState(enemy, teamContext, "");
    state = localApplyAuraOnly(state, "Hydro", 1.0, build, teamContext, enemy);
    electroCharged = resolveReactionForHit(state, localMakeHit("Electro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(electroCharged.PrimaryReaction), 'ElectroCharged'), ...
        'Expected Electro-Charged to trigger from Electro on Hydro.');
    assert(localAuraGauge(electroCharged.EnemyState, "Hydro") > 0, ...
        'Hydro aura should remain after Electro-Charged.');
    assert(localAuraGauge(electroCharged.EnemyState, "Electro") > 0, ...
        'Electro aura should coexist after Electro-Charged.');

    ecPyro = resolveReactionForHit(electroCharged.EnemyState, localMakeHit("Pyro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(ecPyro.PrimaryReaction), 'Vaporize'), ...
        'Hydro-first Electro-Charged should prioritize Hydro as the primary aura for a Pyro follow-up.');
    assert(any(strcmpi(cellstr(string(ecPyro.TriggeredReactions)), 'overload')), ...
        'Pyro on coexisting Hydro and Electro should also trigger Overload from the secondary Electro aura.');
    assert(ecPyro.AmplifyMultiplier > 1 && ecPyro.ReactionDamage > 0, ...
        'Pyro on Hydro-first Electro-Charged should preserve both Vaporize amplification and Overload damage.');

    reverseECState = createEnemyState(enemy, teamContext, "");
    reverseECState = localApplyAuraOnly(reverseECState, "Electro", 1.0, build, teamContext, enemy);
    reverseElectroCharged = resolveReactionForHit(reverseECState, localMakeHit("Hydro", 1.0), build, teamContext, enemy, 0);
    reverseEcPyro = resolveReactionForHit(reverseElectroCharged.EnemyState, localMakeHit("Pyro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(reverseEcPyro.PrimaryReaction), 'Overload'), ...
        'Electro-first Electro-Charged should prioritize Electro as the primary aura for a Pyro follow-up.');
    assert(any(strcmpi(cellstr(string(reverseEcPyro.TriggeredReactions)), 'vaporize')), ...
        'Pyro on Electro-first Electro-Charged should still trigger Vaporize from the secondary Hydro aura.');
    assert(reverseEcPyro.AmplifyMultiplier > 1 && reverseEcPyro.ReactionDamage > 0, ...
        'Pyro on Electro-first Electro-Charged should preserve both Overload damage and Vaporize amplification.');

    ecCryo = resolveReactionForHit(electroCharged.EnemyState, localMakeHit("Cryo", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(ecCryo.PrimaryReaction), 'Frozen'), ...
        'Cryo on Hydro-first Electro-Charged should prioritize Frozen from the Hydro aura.');
    assert(any(strcmpi(cellstr(string(ecCryo.TriggeredReactions)), 'superconduct')), ...
        'Cryo on coexisting Hydro and Electro should also trigger Superconduct from the secondary Electro aura.');
    assert(logical(ecCryo.EnemyState.Frozen.Active) && ecCryo.ReactionDamage > 0, ...
        'Cryo on Electro-Charged should leave Frozen active and deal Superconduct reaction damage.');

    ecDendro = resolveReactionForHit(electroCharged.EnemyState, localMakeHit("Dendro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(ecDendro.PrimaryReaction), 'Bloom'), ...
        'Dendro on Hydro-first Electro-Charged should prioritize Bloom from the Hydro aura.');
    assert(any(strcmpi(cellstr(string(ecDendro.TriggeredReactions)), 'quicken')), ...
        'Dendro on coexisting Hydro and Electro should also trigger Quicken from the secondary Electro aura.');
    assert(numel(ecDendro.EnemyState.DendroCores) == 1 && logical(ecDendro.EnemyState.Quicken.Active), ...
        'Dendro on Electro-Charged should leave both a Bloom core and a Quicken state.');
    assert(localAuraGauge(ecDendro.EnemyState, "Electro") > 0 && localAuraGauge(ecDendro.EnemyState, "Electro") < 1.0, ...
        'The secondary Quicken trigger should consume part of the existing Electro aura instead of leaving it untouched.');

    state = createEnemyState(enemy, teamContext, "");
    state = localApplyAuraOnly(state, "Hydro", 1.0, build, teamContext, enemy);
    frozen = resolveReactionForHit(state, localMakeHit("Cryo", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(frozen.PrimaryReaction), 'Frozen'), ...
        'Expected Frozen to trigger from Cryo on Hydro.');
    assert(logical(frozen.EnemyState.Frozen.Active), 'Frozen state should become active.');
    assert(localAuraGauge(frozen.EnemyState, "Hydro") > 0 && localAuraGauge(frozen.EnemyState, "Hydro") < 1.0, ...
        'Frozen should consume part of the existing Hydro aura instead of leaving it untouched.');
    assert(localAuraGauge(frozen.EnemyState, "Cryo") > 0, ...
        'Frozen should leave residual Cryo aura after the trigger is applied.');
    frozenGaugeBefore = double(frozen.EnemyState.Frozen.Gauge);

    secondFrozen = resolveReactionForHit(frozen.EnemyState, localMakeHit("Cryo", 1.0), build, teamContext, enemy, 0);
    assert(~strcmpi(char(secondFrozen.PrimaryReaction), 'Frozen'), ...
        'A second Cryo hit should not repeatedly refreeze from the original 1U Hydro aura after the first Frozen already consumed it.');
    assert(localAuraGauge(secondFrozen.EnemyState, "Hydro") <= localAuraGauge(frozen.EnemyState, "Hydro"), ...
        'Follow-up Cryo hits should not restore Hydro aura after Frozen has already consumed it.');

    thirdFrozen = resolveReactionForHit(secondFrozen.EnemyState, localMakeHit("Cryo", 1.0), build, teamContext, enemy, 0);
    assert(~strcmpi(char(thirdFrozen.PrimaryReaction), 'Frozen'), ...
        'Frozen should not keep retriggering from a single original 1U Hydro aura.');

    shatterHit = localMakeHit("Geo", 0);
    shatterHit.CanApplyAura = false;
    shatterHit.CanShatter = true;
    shatterHit.StrikeType = "Blunt";
    shatter = resolveReactionForHit(frozen.EnemyState, shatterHit, build, teamContext, enemy, 0);
    assert(any(strcmpi(cellstr(string(shatter.TriggeredReactions)), 'shatter')) ...
        || strcmpi(char(shatter.PrimaryReaction), 'Shatter'), ...
        'Expected Shatter to trigger on a Frozen target.');
    assert(double(shatter.EnemyState.Frozen.Gauge) < frozenGaugeBefore, ...
        'Shatter should consume Frozen gauge.');

    state = createEnemyState(enemy, teamContext, "");
    state = localApplyAuraOnly(state, "Dendro", 1.0, build, teamContext, enemy);
    bloom = resolveReactionForHit(state, localMakeHit("Hydro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(bloom.PrimaryReaction), 'Bloom'), ...
        'Expected Bloom to trigger from Hydro on Dendro.');
    assert(numel(bloom.EnemyState.DendroCores) == 1, ...
        'Bloom should create one Dendro Core.');
    assert(localAuraGauge(bloom.EnemyState, "Dendro") > 0 && localAuraGauge(bloom.EnemyState, "Dendro") < 1.0, ...
        'Bloom should consume part of the existing Dendro aura instead of leaving it untouched.');

    secondBloom = resolveReactionForHit(bloom.EnemyState, localMakeHit("Hydro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(secondBloom.PrimaryReaction), 'Bloom'), ...
        'A second Hydro hit should still trigger Bloom while enough Dendro aura remains.');
    assert(numel(secondBloom.EnemyState.DendroCores) == 2, ...
        'A second Bloom should add a second Dendro Core while aura remains.');
    assert(localAuraGauge(secondBloom.EnemyState, "Dendro") < localAuraGauge(bloom.EnemyState, "Dendro"), ...
        'Repeated Bloom triggers should continue consuming the remaining Dendro aura.');

    thirdBloom = resolveReactionForHit(secondBloom.EnemyState, localMakeHit("Hydro", 1.0), build, teamContext, enemy, 0);
    assert(~strcmpi(char(thirdBloom.PrimaryReaction), 'Bloom'), ...
        'Bloom should stop triggering once the original 1U Dendro aura has been consumed.');
    assert(numel(thirdBloom.EnemyState.DendroCores) == 2, ...
        'Bloom should not fabricate extra Dendro Cores after the Dendro aura is exhausted.');

    hyperbloom = resolveReactionForHit(bloom.EnemyState, localMakeHit("Electro", 1.0), build, teamContext, enemy, 0);
    assert(any(strcmpi(cellstr(string(hyperbloom.TriggeredReactions)), 'hyperbloom')) ...
        || strcmpi(char(hyperbloom.PrimaryReaction), 'Hyperbloom'), ...
        'Expected Hyperbloom to trigger from Electro on a Bloom core.');
    assert(isempty(hyperbloom.EnemyState.DendroCores), ...
        'Hyperbloom should consume the available Dendro Core.');

    burgeonState = createEnemyState(enemy, teamContext, "");
    burgeonState = localApplyAuraOnly(burgeonState, "Dendro", 1.0, build, teamContext, enemy);
    burgeonBloom = resolveReactionForHit(burgeonState, localMakeHit("Hydro", 1.0), build, teamContext, enemy, 0);
    burgeon = resolveReactionForHit(burgeonBloom.EnemyState, localMakeHit("Pyro", 1.0), build, teamContext, enemy, 0);
    assert(any(strcmpi(cellstr(string(burgeon.TriggeredReactions)), 'burgeon')) ...
        || strcmpi(char(burgeon.PrimaryReaction), 'Burgeon'), ...
        'Expected Burgeon to trigger from Pyro on a Bloom core.');
    assert(isempty(burgeon.EnemyState.DendroCores), ...
        'Burgeon should consume the available Dendro Core.');

    burningState = createEnemyState(enemy, teamContext, "");
    burningState = localApplyAuraOnly(burningState, "Dendro", 1.0, build, teamContext, enemy);
    firstBurning = resolveReactionForHit(burningState, localMakeHit("Pyro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(firstBurning.PrimaryReaction), 'Burning'), ...
        'Expected Burning to trigger from Pyro on Dendro.');
    assert(logical(firstBurning.EnemyState.Burning.Active), ...
        'Burning should activate its timed state.');
    assert(localAuraGauge(firstBurning.EnemyState, "Dendro") > 0 && localAuraGauge(firstBurning.EnemyState, "Dendro") < 1.0, ...
        'Burning should consume part of the existing Dendro aura instead of leaving it untouched.');

    secondBurning = resolveReactionForHit(firstBurning.EnemyState, localMakeHit("Pyro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(secondBurning.PrimaryReaction), 'Burning'), ...
        'A second Pyro hit should still refresh Burning while enough Dendro aura remains.');
    assert(localAuraGauge(secondBurning.EnemyState, "Dendro") < localAuraGauge(firstBurning.EnemyState, "Dendro"), ...
        'Repeated Burning refreshes should continue consuming the remaining Dendro aura.');

    thirdBurning = resolveReactionForHit(secondBurning.EnemyState, localMakeHit("Pyro", 1.0), build, teamContext, enemy, 0);
    assert(~strcmpi(char(thirdBurning.PrimaryReaction), 'Burning'), ...
        'Burning should stop retriggering once the original 1U Dendro aura has been consumed.');

    quickenState = createEnemyState(enemy, teamContext, "");
    quickenState = localApplyAuraOnly(quickenState, "Dendro", 1.0, build, teamContext, enemy);
    firstQuicken = resolveReactionForHit(quickenState, localMakeHit("Electro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(firstQuicken.PrimaryReaction), 'Quicken'), ...
        'Expected Quicken to trigger from Electro on Dendro.');
    assert(logical(firstQuicken.EnemyState.Quicken.Active), ...
        'Quicken should activate its lingering catalyze state.');
    assert(localAuraGauge(firstQuicken.EnemyState, "Dendro") > 0 && localAuraGauge(firstQuicken.EnemyState, "Dendro") < 1.0, ...
        'Quicken should consume part of the existing Dendro aura instead of leaving it untouched.');
    assert(localAuraGauge(firstQuicken.EnemyState, "Electro") == 0, ...
        'Equal-gauge Quicken should not fabricate a residual Electro aura when the trigger is fully consumed into the catalyze state.');
    assert(double(firstQuicken.EnemyState.Quicken.Gauge) > 0 && double(firstQuicken.EnemyState.Quicken.Gauge) < 1.0, ...
        'Quicken should snapshot only the reacted portion of the original gauges.');
    quickenGaugeBeforeAggravate = double(firstQuicken.EnemyState.Quicken.Gauge);

    aggravate = resolveReactionForHit(firstQuicken.EnemyState, localMakeHit("Electro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(aggravate.PrimaryReaction), 'Aggravate'), ...
        'Electro on an active Quicken state should trigger Aggravate.');
    assert(abs(double(aggravate.EnemyState.Quicken.Gauge) - quickenGaugeBeforeAggravate) < 1e-9, ...
        'Aggravate should not consume the lingering Quicken gauge in the unified state model.');

    spread = resolveReactionForHit(firstQuicken.EnemyState, localMakeHit("Dendro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(spread.PrimaryReaction), 'Spread'), ...
        'Dendro on an active Quicken state should trigger Spread.');
    assert(abs(double(spread.EnemyState.Quicken.Gauge) - quickenGaugeBeforeAggravate) < 1e-9, ...
        'Spread should not consume the lingering Quicken gauge in the unified state model.');

    pureQuickenState = firstQuicken.EnemyState;
    pureQuickenState.Auras = pureQuickenState.Auras([]);

    quickenBloom = resolveReactionForHit(pureQuickenState, localMakeHit("Hydro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(quickenBloom.PrimaryReaction), 'Bloom'), ...
        'Hydro should still trigger Bloom when only the lingering Quicken state remains.');
    assert(numel(quickenBloom.EnemyState.DendroCores) == 1, ...
        'Pure Quicken -> Hydro should still create a Dendro Core.');
    assert(double(quickenBloom.EnemyState.Quicken.Gauge) < quickenGaugeBeforeAggravate, ...
        'Hydro-triggered Bloom should consume part of the lingering Quicken gauge.');

    quickenBurning = resolveReactionForHit(pureQuickenState, localMakeHit("Pyro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(quickenBurning.PrimaryReaction), 'Burning'), ...
        'Pyro should still trigger Burning when only the lingering Quicken state remains.');
    assert(logical(quickenBurning.EnemyState.Burning.Active), ...
        'Pure Quicken -> Pyro should activate Burning.');
    assert(double(quickenBurning.EnemyState.Quicken.Gauge) < quickenGaugeBeforeAggravate, ...
        'Pyro-triggered Burning should consume part of the lingering Quicken gauge.');

    quickenElectroState = firstQuicken.EnemyState;
    quickenElectroState = localApplyAuraOnly(quickenElectroState, "Electro", 0.4, build, teamContext, enemy);
    quickenElectroDendroGauge = localAuraGauge(quickenElectroState, "Dendro");

    quickenElectroHydro = resolveReactionForHit(quickenElectroState, localMakeHit("Hydro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(quickenElectroHydro.PrimaryReaction), 'ElectroCharged'), ...
        'Hydro on coexisting Electro + Quicken should still prioritize Electro-Charged from the explicit Electro aura.');
    assert(any(strcmpi(cellstr(string(quickenElectroHydro.TriggeredReactions)), 'bloom')), ...
        'Hydro on coexisting Electro + Quicken should also trigger Bloom from the lingering Dendro-side state.');
    assert(numel(quickenElectroHydro.EnemyState.DendroCores) == 1, ...
        'Hydro on coexisting Electro + Quicken should create one Dendro Core from the Dendro-side follow-up.');
    assert(localAuraGauge(quickenElectroHydro.EnemyState, "Dendro") < quickenElectroDendroGauge, ...
        'Hydro on coexisting Electro + Quicken should consume the explicit residual Dendro aura before it can keep triggering Bloom for free.');

    quickenElectroPyro = resolveReactionForHit(quickenElectroState, localMakeHit("Pyro", 1.0), build, teamContext, enemy, 0);
    assert(strcmpi(char(quickenElectroPyro.PrimaryReaction), 'Overload'), ...
        'Pyro on coexisting Electro + Quicken should still prioritize Overload from the explicit Electro aura.');
    assert(any(strcmpi(cellstr(string(quickenElectroPyro.TriggeredReactions)), 'burning')), ...
        'Pyro on coexisting Electro + Quicken should also trigger Burning from the lingering Dendro-side state.');
    assert(logical(quickenElectroPyro.EnemyState.Burning.Active), ...
        'Pyro on coexisting Electro + Quicken should activate Burning.');
    assert(localAuraGauge(quickenElectroPyro.EnemyState, "Dendro") < quickenElectroDendroGauge, ...
        'Pyro on coexisting Electro + Quicken should consume the explicit residual Dendro aura before it can keep refreshing Burning for free.');

    frozenElectroState = createEnemyState(enemy, teamContext, "");
    frozenElectroState = localApplyAuraOnly(frozenElectroState, "Hydro", 1.0, build, teamContext, enemy);
    frozenElectroState = resolveReactionForHit(frozenElectroState, localMakeHit("Cryo", 1.0), build, teamContext, enemy, 0).EnemyState;
    frozenElectroState = localApplyAuraOnly(frozenElectroState, "Electro", 1.0, build, teamContext, enemy);
    frozenElectroDendro = resolveReactionForHit(frozenElectroState, localMakeHit("Dendro", 1.0), build, teamContext, enemy, 0);
    assert(any(strcmpi(cellstr(string(frozenElectroDendro.TriggeredReactions)), 'bloom')), ...
        'Dendro on Frozen + Electro should still trigger Bloom from the Hydro side.');
    assert(any(strcmpi(cellstr(string(frozenElectroDendro.TriggeredReactions)), 'quicken')), ...
        'Dendro on Frozen + Electro should still trigger Quicken from the secondary Electro aura even when the primary aura pick falls through.');
    assert(logical(frozenElectroDendro.EnemyState.Quicken.Active), ...
        'Frozen + Electro -> Dendro should leave the Quicken state active after the secondary reaction.');

    [expiredState, packets] = advanceEnemyStateTime(bloom.EnemyState, 6.1, "", teamContext);
    packetNames = strings(0, 1);
    if ~isempty(packets)
        packetNames = string({packets.ReactionName}).';
    end
    assert(any(strcmpi(cellstr(packetNames), 'Bloom')), ...
        'A Dendro Core should explode into Bloom damage on timeout.');
    assert(isempty(expiredState.DendroCores), ...
        'Expired Dendro Cores should be removed from enemy state.');

    [timedECState, ecPackets] = advanceEnemyStateTime(electroCharged.EnemyState, 12.0, "", teamContext);
    ecPacketNames = strings(0, 1);
    if ~isempty(ecPackets)
        ecPacketNames = string({ecPackets.ReactionName}).';
    end
    assert(sum(strcmpi(cellstr(ecPacketNames), 'ElectroCharged')) == 9, ...
        'Electro-Charged should emit all intermediate timed ticks during a long advance window.');
    assert(~timedECState.ElectroCharged.Active, ...
        'Electro-Charged should expire after its gauge is fully advanced out.');

    disp('validateReactionEngineRegression passed');
end

function state = localApplyAuraOnly(state, element, gauge, build, teamContext, enemy)
    hit = localMakeHit(element, gauge);
    hit.CanTriggerReaction = false;
    result = resolveReactionForHit(state, hit, build, teamContext, enemy, 0);
    state = result.EnemyState;
end

function hit = localMakeHit(element, gauge)
    hit = struct( ...
        'HitElement', string(element), ...
        'ApplyElement', string(element), ...
        'ApplyGauge', double(gauge), ...
        'CanApplyAura', double(gauge) > 0, ...
        'CanTriggerReaction', true, ...
        'AllowAmplify', true, ...
        'AllowCatalyze', true);
end

function gauge = localAuraGauge(enemyState, auraElement)
    gauge = 0;
    if ~isfield(enemyState, 'Auras') || isempty(enemyState.Auras)
        return;
    end

    for i = 1:numel(enemyState.Auras)
        if strcmpi(char(enemyState.Auras(i).Element), char(string(auraElement)))
            gauge = max(gauge, double(enemyState.Auras(i).Gauge));
        end
    end
end
