function validateTeamCoreConversionTimelineRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    barbara = getDefaultCharacterConfig('Barbara');
    collei = getDefaultCharacterConfig('Collei');

    kuki = getDefaultCharacterConfig('KukiShinobu');
    hyperContext = buildTeamContext({barbara, collei, kuki}, 18, struct('ReactionMode', "Realistic"), enemy);
    hyperPlan = struct( ...
        'RotationDuration', 18, ...
        'MemberPlans', [ ...
            struct('Role', "Support", 'RotationTokens', {{'E'}}, 'StartTime', 0.00), ...
            struct('Role', "Support", 'RotationTokens', {{'E'}}, 'StartTime', 0.60), ...
            struct('Role', "Driver", 'RotationTokens', {{'E', 'N1', 'N2', 'N3'}}, 'StartTime', 1.20)]);

    hyperResult = simulateTeamTimeline({barbara, collei, kuki}, hyperPlan, hyperContext, enemy, struct());
    hyperTimeline = hyperResult.TimelineTable;
    hyperRows = hyperTimeline(contains(string(hyperTimeline.Reaction), "Hyperbloom", 'IgnoreCase', true), :);

    assert(~isempty(hyperRows), ...
        'Barbara -> Collei -> Kuki should surface Hyperbloom in the team timeline.');
    assert(any(string(hyperRows.Character) == "KukiShinobu" & string(hyperRows.Action) == "E"), ...
        'Kuki skill hit should be able to convert the Bloom core into Hyperbloom on the timeline.');
    assert(all(hyperRows.DendroCoreCount == 0), ...
        'Hyperbloom conversion rows should leave no lingering Dendro Cores after the conversion hit.');

    thoma = getDefaultCharacterConfig('Thoma');
    burgeonContext = buildTeamContext({barbara, collei, thoma}, 18, struct('ReactionMode', "Realistic"), enemy);
    burgeonPlan = struct( ...
        'RotationDuration', 18, ...
        'MemberPlans', [ ...
            struct('Role', "Support", 'RotationTokens', {{'E'}}, 'StartTime', 0.00), ...
            struct('Role', "Support", 'RotationTokens', {{'E'}}, 'StartTime', 0.60), ...
            struct('Role', "Driver", 'RotationTokens', {{'E', 'N1', 'N2'}}, 'StartTime', 1.20)]);

    burgeonResult = simulateTeamTimeline({barbara, collei, thoma}, burgeonPlan, burgeonContext, enemy, struct());
    burgeonTimeline = burgeonResult.TimelineTable;
    burgeonRows = burgeonTimeline(contains(string(burgeonTimeline.Reaction), "Burgeon", 'IgnoreCase', true), :);

    assert(~isempty(burgeonRows), ...
        'Barbara -> Collei -> Thoma should surface Burgeon in the team timeline.');
    assert(any(string(burgeonRows.Character) == "Thoma" & string(burgeonRows.Action) == "E"), ...
        'Thoma skill hit should be able to convert the Bloom core into Burgeon on the timeline.');
    assert(all(burgeonRows.DendroCoreCount == 0), ...
        'Burgeon conversion rows should leave no lingering Dendro Cores after the conversion hit.');

    disp('validateTeamCoreConversionTimelineRegression passed');
end
