function validateBarbaraRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cfg = getDefaultCharacterConfig('Barbara', struct('Constellation', 2));
    teamContext = buildTeamContext({cfg}, 20, struct('ReactionMode', "Realistic"), enemy);
    [~, ~, breakdown, ~, audit] = simulateBarbaraDPS( ...
        cfg.Build, enemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, teamContext);

    caRows = audit.Rows(strcmp(string(audit.Rows.Action), "CA"), :);
    assert(~isempty(caRows), 'Barbara audit should include a charged-attack row.');
    assert(any(strcmp(string(caRows.ApplyGaugeSource), "explicit") | strcmp(string(caRows.ApplyGaugeSource), "inferred")), ...
        'Barbara charged attack should resolve ApplyGauge from explicit or inferred metadata.');
    assert(any(strcmp(string(caRows.ICDSource), "explicit") | strcmp(string(caRows.ICDSource), "inferred")), ...
        'Barbara charged attack should resolve ICD metadata from explicit or inferred data.');
    assert(any(strcmp(string(breakdown.Action), "CA")), ...
        'Barbara baseline rotation should still include a charged attack action.');

    disp('validateBarbaraRegression passed');
end
