function validateTeamTimelineAuraICDRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    aino = getDefaultCharacterConfig('Aino', struct('Constellation', 2));
    fischl = getDefaultCharacterConfig('Fischl', struct('Constellation', 6));
    teamContext = buildTeamContext({aino, fischl}, 20, struct('ReactionMode', "Realistic"), enemy);

    rotationPlan = struct( ...
        'RotationDuration', 20, ...
        'MemberPlans', [ ...
            struct('Role', "Driver", 'RotationTokens', {{'Q'}}, 'StartTime', 0), ...
            struct('Role', "OffField", 'RotationTokens', {{'E', 'Oz'}}, 'StartTime', 0)]);

    result = simulateTeamTimeline({aino, fischl}, rotationPlan, teamContext, enemy, struct());
    timeline = result.TimelineTable;

    ainoRows = timeline(string(timeline.Character) == "Aino", :);
    ozRows = timeline(contains(string(timeline.Action), "Oz", 'IgnoreCase', true), :);

    assert(~isempty(ainoRows), 'Team timeline should include Aino rows.');
    assert(~isempty(ozRows), 'Team timeline should include Oz background rows.');
    assert(all(ismember(["CanApplyAura", "ApplyGaugeSource", "ICDRule", "ICDGroup", "ICDSource"], string(timeline.Properties.VariableNames))), ...
        'Team timeline should expose aura and ICD columns.');
    assert(all(strcmp(string(ozRows.ApplyGaugeSource), "metadata") | strcmp(string(ozRows.ApplyGaugeSource), "inferred")), ...
        'Oz background rows should resolve ApplyGauge from metadata or inference.');
    assert(any(strcmp(string(ozRows.ICDRule), "4 hits / 5s")), ...
        'Oz background rows should carry the resolved ICD rule.');
    assert(any(strcmp(string(ainoRows.Action), "Q")) && any(ainoRows.ApplyGauge == 0 | ainoRows.ApplyGauge == 1), ...
        'Aino team timeline should retain explicit gauge information on the burst row.');
    assert(~any(strcmp(string(timeline.Action), "OzA4Retribution")), ...
        'Fischl A4 retribution should not trigger from background-only reaction packets.');

    barbara = getDefaultCharacterConfig('Barbara');
    barbaraContext = buildTeamContext({barbara, fischl}, 20, struct('ReactionMode', "Realistic"), enemy);
    barbaraPlan = struct( ...
        'RotationDuration', 20, ...
        'MemberPlans', [ ...
            struct('Role', "Driver", 'RotationTokens', {{'N1'}}, 'StartTime', 0.80), ...
            struct('Role', "OffField", 'RotationTokens', {{'E'}}, 'StartTime', 0.00)]);

    barbaraResult = simulateTeamTimeline({barbara, fischl}, barbaraPlan, barbaraContext, enemy, struct());
    barbaraTimeline = barbaraResult.TimelineTable;
    jointRows = barbaraTimeline(strcmp(string(barbaraTimeline.Action), "OzJointAttack"), :);
    a4Rows = barbaraTimeline(strcmp(string(barbaraTimeline.Action), "OzA4Retribution"), :);

    assert(~isempty(jointRows), ...
        'Fischl C6 should schedule an Oz joint attack for a foreground normal hit while Oz is active.');
    assert(~isempty(a4Rows), ...
        'Fischl A4 should schedule a retribution follow-up after a foreground Electro-related reaction.');
    assert(height(a4Rows) == 1, ...
        'Fischl A4 should only schedule one retribution follow-up for a single foreground direct-hit reaction.');
    assert(any(string(jointRows.ICDRule) == "4 hits / 5s" & string(jointRows.ApplyGaugeSource) == "metadata"), ...
        'Fischl C6 joint attacks should inherit explicit Oz metadata.');
    assert(any(string(a4Rows.BackgroundDriverMode) == "ReactionEventTrigger" ...
            & string(a4Rows.TriggerPacketSource) == "DirectHitReaction" ...
            & string(a4Rows.TriggerSourceCharacter) == "Barbara"), ...
        'Fischl A4 should be sourced from a foreground direct-hit reaction packet.');

    disp('validateTeamTimelineAuraICDRegression passed');
end
