function validateTeamTimelineSummaryRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    barbara = getDefaultCharacterConfig('Barbara');
    lisa = getDefaultCharacterConfig('Lisa');
    barbara.StartTime = 0;
    lisa.StartTime = 5;

    teamSpec = struct( ...
        'Members', {{barbara, lisa}}, ...
        'RotationDuration', 20, ...
        'SharedBuffs', struct('ReactionMode', "Realistic"), ...
        'PlanOptions', struct('DisableAutoPlan', true));

    teamResult = simulateTeamDPS(teamSpec, enemy);
    summary = teamResult.TimelineSummary;
    energy = teamResult.EnergySummary;
    memberSummary = teamResult.Summary;

    assert(isfield(summary, 'SwapCount') && summary.SwapCount >= 1, ...
        'Team timeline summary should count swap windows.');
    assert(isfield(summary, 'IdleTime') && summary.IdleTime > 0, ...
        'Team timeline summary should expose non-zero idle time for staggered manual entry.');
    assert(isfield(summary, 'OverlapTime') && summary.OverlapTime == 0, ...
        'Team timeline summary should keep overlap at zero for non-overlapping manual entry.');
    assert(isfield(teamResult, 'CanLoopNextCycle') && ~teamResult.CanLoopNextCycle, ...
        'Manual two-member sample should not loop the next cycle.');
    assert(isfield(teamResult, 'LoopReadiness') && teamResult.LoopReadiness == 0, ...
        'Manual two-member sample should expose zero loop readiness when bursts are missing energy.');
    assert(istable(energy) && all(ismember(["Character", "CanBurstNextCycle", "MissingEnergy"], string(energy.Properties.VariableNames))), ...
        'Energy summary should keep the loop-check columns.');
    assert(any(strcmp(string(memberSummary.Character), "Barbara")) && any(strcmp(string(memberSummary.Character), "Lisa")), ...
        'Member summary should contain both manual team members.');
    assert(all(~isnan(memberSummary.ReservedTime)), ...
        'Manual passthrough plans should still populate reserved time.');
    assert(all(memberSummary.PlannedEndTime > memberSummary.PlannedStartTime), ...
        'Manual passthrough plans should populate end times from token duration estimates.');

    disp('validateTeamTimelineSummaryRegression passed');
end
