function validateTeamSameTimestampMemberActionPlanOrderingRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    barbara = getDefaultCharacterConfig('Barbara');
    lisa = getDefaultCharacterConfig('Lisa');
    teamContext = buildTeamContext({barbara, lisa}, 20, struct('ReactionMode', "Realistic"), enemy);

    rotationPlan = struct( ...
        'RotationDuration', 20, ...
        'ExecutionOrder', [2, 1], ...
        'ExecutionTable', table( ...
            [1; 2], ...
            ["Lisa"; "Barbara"], ...
            ["Driver"; "Support"], ...
            ["", ""].', ...
            [0; 0], ...
            [0.60; 0.60], ...
            [0.60; 0.60], ...
            ["N1"; "N1"], ...
            'VariableNames', {'Order', 'Character', 'Role', 'Job', 'StartTime', 'EndTime', 'ReservedTime', 'RotationPreview'}), ...
        'MemberPlans', [ ...
            struct('Role', "Support", 'Order', 2, 'RotationTokens', {{'N1'}}, 'StartTime', 0.0), ...
            struct('Role', "Driver", 'Order', 1, 'RotationTokens', {{'N1'}}, 'StartTime', 0.0)]);

    result = simulateTeamTimeline({barbara, lisa}, rotationPlan, teamContext, enemy, struct());
    timeline = result.TimelineTable;
    sharedTimeRows = timeline(abs(double(timeline.StartTime)) <= 1e-9 ...
        & string(timeline.SourceType) == "MemberAction", :);

    assert(height(sharedTimeRows) == 2, ...
        'Regression should surface both same-timestamp member actions.');
    assert(string(sharedTimeRows.Character(1)) == "Lisa" ...
            && string(sharedTimeRows.Character(2)) == "Barbara", ...
        'Same-timestamp foreground member actions should follow the planned execution order rather than member-index order.');
    assert(strlength(strtrim(string(sharedTimeRows.Reaction(1)))) == 0, ...
        'The first same-timestamp applicator should establish aura instead of consuming a reaction immediately.');
    assert(string(sharedTimeRows.Reaction(2)) == "ElectroCharged", ...
        'The later same-timestamp member action should inherit the newly-established aura and own the resulting reaction.');
    assert(sum(string(sharedTimeRows.Reaction) == "ElectroCharged") == 1, ...
        'Same-timestamp member ordering should still produce exactly one reaction event.');

    disp('validateTeamSameTimestampMemberActionPlanOrderingRegression passed');
end
