function validateNicoleRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    nicole = getDefaultCharacterConfig('Nicole', struct('Constellation', 2));
    teamContext = buildTeamContext({nicole}, 20, struct('ReactionMode', "Realistic"), enemy);

    sharedNicoleDMGBonus = getFieldOrDefault(teamContext, 'NicoleSharedAllDMGBonus', 0);
    assert(sharedNicoleDMGBonus > 0, ...
        'Nicole support context should expose a shared weapon-driven DMG bonus.');
    assert(abs(getFieldOrDefault(teamContext, 'NicoleWeaponActiveDMGBonus', 0) - sharedNicoleDMGBonus) < 1e-9, ...
        'Nicole shared DMG bonus should match the active weapon bonus snapshot.');
    assert(getFieldOrDefault(teamContext, 'AllDMGBonus', 0) >= sharedNicoleDMGBonus, ...
        'Nicole shared weapon bonus should flow into teamContext.AllDMGBonus.');
    assert(abs(getFieldOrDefault(teamContext, 'NicoleApproxSharedAllDMGBonus', 0) - sharedNicoleDMGBonus) < 1e-9, ...
        'Nicole legacy shared DMG bonus alias should stay aligned with the formal field.');

    noWeaponContext = teamContext;
    noWeaponContext.AllDMGBonus = getFieldOrDefault(noWeaponContext, 'AllDMGBonus', 0) - sharedNicoleDMGBonus;
    noWeaponContext.NicoleSharedAllDMGBonus = 0;
    noWeaponContext.NicoleApproxSharedAllDMGBonus = 0;

    [nicoleDamageWith, ~] = simulateNicoleDPS( ...
        nicole.Build, enemy, nicole.RotationFile, nicole.TalentLevel, nicole.Constellation, teamContext);
    [nicoleDamageWithout, ~] = simulateNicoleDPS( ...
        nicole.Build, enemy, nicole.RotationFile, nicole.TalentLevel, nicole.Constellation, noWeaponContext);
    assert(abs(nicoleDamageWith - nicoleDamageWithout) < 1e-6 * max(1, abs(nicoleDamageWith)), ...
        'Nicole self simulation should strip the shared approximation to avoid double-counting weapon DMG bonus.');

    projectionRotation = [tempname, '.txt'];
    cleanupObj = onCleanup(@() localDeleteIfExists(projectionRotation)); %#ok<NASGU>
    fid = fopen(projectionRotation, 'w');
    assert(fid > 0, 'Failed to create temporary Nicole projection regression rotation file.');
    fprintf(fid, 'Q\nProjection\n');
    fclose(fid);

    ownerBuild = struct( ...
        'WeaponATK', 0, ...
        'AtkBonus', 0, ...
        'FlatATK', 0, ...
        'CritRate', 0, ...
        'CritDMG', 0, ...
        'PyroDMGBonus', 0, ...
        'ResShred', 0);
    projectionContext = struct( ...
        'ReactionMode', "Realistic", ...
        'RotationDuration', 20, ...
        'NicoleProjectionOwnerName', "Jean", ...
        'NicoleProjectionOwnerElement', "Pyro", ...
        'NicoleProjectionOwnerIsHexerei', false, ...
        'NicoleProjectionOwnerConfig', struct('Name', "Jean", 'Build', ownerBuild), ...
        'NicoleProjectionOwnerBaseATK', 0, ...
        'NicoleProjectionMultiplier', 1.0, ...
        'NicoleProjectionMaxCount', 4, ...
        'NicoleWeaponActiveDMGBonus', 0, ...
        'AllDMGBonus', 0, ...
        'ATKBonus', 0, ...
        'FlatATK', 0, ...
        'NicoleSharedAllDMGBonus', 0, ...
        'NicoleSharedFlatATK', 0, ...
        'PyroResShred', 0);

    [~, ~, projectionBreakdown] = simulateNicoleDPS( ...
        nicole.Build, enemy, projectionRotation, nicole.TalentLevel, nicole.Constellation, projectionContext);
    projectionRows = projectionBreakdown(strcmpi(string(projectionBreakdown.Action), "Projection"), :);
    assert(height(projectionRows) == 1, ...
        'Nicole projection regression should isolate exactly one Projection row.');

    jeanChars = readtable(char(resolveCharacterDataFile('Jean', 'characters')), 'TextType', 'string');
    expectedProjectionDamage = double(getFieldOrDefault(jeanChars, 'BaseATK', 0)) ...
        * calcDamageMultiplier(90, enemy, 0);
    assert(abs(projectionRows.Damage - expectedProjectionDamage) < 1e-6 * max(1, expectedProjectionDamage), ...
        'Nicole projection owner ATK should be sourced from the owner''s character data when available.');

    customProjectionContext = projectionContext;
    customProjectionContext.NicoleProjectionOwnerName = "CustomOwner";
    customProjectionContext.NicoleProjectionOwnerConfig = struct('Name', "CustomOwner", 'Build', ownerBuild);
    customProjectionContext.NicoleProjectionOwnerBaseATK = 456;
    [~, ~, customProjectionBreakdown] = simulateNicoleDPS( ...
        nicole.Build, enemy, projectionRotation, nicole.TalentLevel, nicole.Constellation, customProjectionContext);
    customProjectionRows = customProjectionBreakdown(strcmpi(string(customProjectionBreakdown.Action), "Projection"), :);
    expectedCustomProjectionDamage = 456 * calcDamageMultiplier(90, enemy, 0);
    assert(abs(customProjectionRows.Damage - expectedCustomProjectionDamage) < 1e-6 * max(1, expectedCustomProjectionDamage), ...
        'Nicole projection regression should honor an explicit owner base ATK override.');

    implicitOwnerContext = projectionContext;
    implicitOwnerContext = rmfield(implicitOwnerContext, 'NicoleProjectionOwnerConfig');
    [~, ~, implicitOwnerBreakdown] = simulateNicoleDPS( ...
        nicole.Build, enemy, projectionRotation, nicole.TalentLevel, nicole.Constellation, implicitOwnerContext);
    implicitOwnerRows = implicitOwnerBreakdown(strcmpi(string(implicitOwnerBreakdown.Action), "Projection"), :);
    jeanCfg = getDefaultCharacterConfig('Jean');
    jeanBaseATK = double(getFieldOrDefault(jeanChars, 'BaseATK', 0));
    jeanTotalATK = (jeanBaseATK + getFieldOrDefault(jeanCfg.Build, 'WeaponATK', 0)) ...
        * (1 + getFieldOrDefault(jeanCfg.Build, 'AtkBonus', 0)) ...
        + getFieldOrDefault(jeanCfg.Build, 'FlatATK', 0);
    jeanExpectedCrit = calcExpectedCritMultiplier( ...
        getFieldOrDefault(jeanCfg.Build, 'CritRate', 0), getFieldOrDefault(jeanCfg.Build, 'CritDMG', 0));
    jeanExpectedProjectionDamage = jeanTotalATK * (1 + getFieldOrDefault(jeanCfg.Build, 'PyroDMGBonus', 0)) ...
        * jeanExpectedCrit * calcDamageMultiplier(90, enemy, 0);
    assert(abs(implicitOwnerRows.Damage - jeanExpectedProjectionDamage) < 1e-6 * max(1, jeanExpectedProjectionDamage), ...
        'Nicole projection regression should restore the default owner build when only the owner name is available.');

    disp('validateNicoleRegression passed');
end

function localDeleteIfExists(path)
    if exist(path, 'file') == 2
        delete(path);
    end
end
