function validateImportedAuditCompatibilityRegression()
    initProjectPaths();

    requiredColumns = [ ...
        "Action", "ActionKey", "ApplyGauge", "ApplyGaugeSource", "ICDRule", "ICDSource", ...
        "LunarisAttackName", "LunarisDamageParam", "ApplyGaugeFallback", "ICDFallback"];

    furina = auditCharacterReactionMetadata('Furina');
    assert(istable(furina.Rows), ...
        'Furina audit should always return a table for Rows.');
    assert(all(ismember(requiredColumns, string(furina.Rows.Properties.VariableNames))), ...
        'Furina audit rows should expose the standard compatibility columns even when empty.');
    assert(height(furina.Rows) == 0, ...
        'Furina bespoke simulator should surface an empty standardized audit table until action-level metadata is wired.');

    nicole = auditCharacterReactionMetadata('Nicole');
    assert(~isempty(nicole.Rows), ...
        'Nicole audit should no longer fail through imported-normal parameter fallback.');
    assert(all(ismember(requiredColumns, string(nicole.Rows.Properties.VariableNames))), ...
        'Nicole audit rows should expose the standard compatibility columns.');
    assert(any(strcmp(string(nicole.Rows.Action), "N1")), ...
        'Nicole imported audit should resolve catalyst normal parameters instead of hard-coded x1HitDMG.');

    durin = auditCharacterReactionMetadata('Durin');
    assert(~isempty(durin.Rows), ...
        'Durin audit should no longer fail through imported-normal parameter fallback.');
    assert(all(ismember(requiredColumns, string(durin.Rows.Properties.VariableNames))), ...
        'Durin audit rows should expose the standard compatibility columns.');
    assert(~any(strcmp(string(durin.Rows.Action), "N1")), ...
        'Durin imported audit should skip nonexistent normal-string placeholders.');

    disp('validateImportedAuditCompatibilityRegression passed');
end
