function validateVarkaRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnableElementalAura', true, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    varka = getDefaultCharacterConfig('Varka', struct('Constellation', 2));
    tempDir = tempname;
    mkdir(tempDir);
    cleanupObj = onCleanup(@() rmdir(tempDir, 's')); %#ok<NASGU>

    pyrosupports = { ...
        varka, ...
        struct('Name', 'Jean', 'Constellation', 0, 'Build', struct()), ...
        struct('Name', 'Bennett', 'Constellation', 0, 'Build', struct()), ...
        struct('Name', 'Xiangling', 'Constellation', 0, 'Build', struct())};
    pyroContext = buildTeamContext(pyrosupports, 20, struct('ReactionMode', "Realistic"), enemy);
    pyroRotation = writeTempRotationFile(tempDir, 'Varka', 1, sprintf('E\nN1\nN2\nAscend\nDevour\nQ\n'));

    [~, ~, pyroBreakdown] = simulateVarkaDPS( ...
        varka.Build, enemy, pyroRotation, varka.TalentLevel, varka.Constellation, pyroContext);
    pyroActions = string(pyroBreakdown.Action);
    pyroNotes = string(pyroBreakdown.Note);

    assert(any(contains(pyroNotes, "right=Pyro")), ...
        'Varka should prioritize Pyro as the right-hand infused element.');
    assert(any(contains(pyroNotes, "Oath+1")) || any(contains(pyroNotes, "Oath x1")), ...
        'Varka should gain Azure Fang''s Oath after self-triggered Swirl in Sturm und Drang.');
    assert(any(contains(pyroNotes, "Lyrical")), ...
        'C1 Lyrical Libation should be consumed by the first special action.');
    assert(any(pyroActions == "FourWindsC2"), ...
        'C2 should add an extra Four Winds follow-up strike row.');
    assert(any(pyroActions == "AzureDevourC2"), ...
        'C2 should add an extra Azure Devour follow-up strike row.');
    assert(any(contains(pyroNotes, "slash1=Pyro")), ...
        'Burst first slash should convert to the chosen right-hand element.');

    hydroSupports = { ...
        varka, ...
        struct('Name', 'Jean', 'Constellation', 0, 'Build', struct()), ...
        struct('Name', 'Xingqiu', 'Constellation', 0, 'Build', struct()), ...
        struct('Name', 'Fischl', 'Constellation', 0, 'Build', struct())};
    hydroContext = buildTeamContext(hydroSupports, 20, struct('ReactionMode', "Realistic"), enemy);
    hydroRotation = writeTempRotationFile(tempDir, 'Varka', 2, sprintf('E\nN1\n'));

    [~, ~, hydroBreakdown] = simulateVarkaDPS( ...
        varka.Build, enemy, hydroRotation, varka.TalentLevel, varka.Constellation, hydroContext);
    hydroNotes = string(hydroBreakdown.Note);

    assert(any(contains(hydroNotes, "right=Hydro")), ...
        'Hydro should outrank Electro when Pyro is absent.');
    assert(~any(contains(hydroNotes, "right=Electro")), ...
        'Electro should not be selected over Hydro in the right-hand priority rule.');

    varkaC6 = getDefaultCharacterConfig('Varka', struct('Constellation', 6));
    pyroSupportsC6 = { ...
        varkaC6, ...
        struct('Name', 'Jean', 'Constellation', 0, 'Build', struct()), ...
        struct('Name', 'Bennett', 'Constellation', 0, 'Build', struct()), ...
        struct('Name', 'Xiangling', 'Constellation', 0, 'Build', struct())};
    pyroContextC6 = buildTeamContext(pyroSupportsC6, 20, struct('ReactionMode', "Realistic"), enemy);
    chainedRotation = writeTempRotationFile(tempDir, 'Varka', 3, sprintf('E\nAscend\nDevour\nAscend\nDevour\nAscend\nDevour\n'));
    gappedRotation = writeTempRotationFile(tempDir, 'Varka', 4, sprintf('E\nAscend\nN1\nDevour\nAscend\nDevour\nAscend\nDevour\n'));

    [damageChained, ~, breakdownChained] = simulateVarkaDPS( ...
        varkaC6.Build, enemy, chainedRotation, varkaC6.TalentLevel, varkaC6.Constellation, pyroContextC6);
    [damageGapped, ~, breakdownGapped] = simulateVarkaDPS( ...
        varkaC6.Build, enemy, gappedRotation, varkaC6.TalentLevel, varkaC6.Constellation, pyroContextC6);
    chainedDevourStarts = breakdownChained(strcmp(string(breakdownChained.Action), "AzureDevourRight1"), :);
    gappedDevourStarts = breakdownGapped(strcmp(string(breakdownGapped.Action), "AzureDevourRight1"), :);

    assert(height(chainedDevourStarts) == 3 && height(gappedDevourStarts) == 3, ...
        'Expanded Varka C6 regressions should expose all three Azure Devour group starts.');
    assert(all(contains(string(chainedDevourStarts.Note), "C6 free")), ...
        'Fully chained Varka C6 Devour groups should consume the stored free-link state.');
    assert(all(contains(string(gappedDevourStarts.Note), "C6 free")), ...
        'Varka C6 free-link state should survive filler actions until the matching Devour consumes it.');
    assert(~any(contains(string(gappedDevourStarts.Note), "no Four Winds use")), ...
        'Varka C6 gap-linked Devour starts should not fail the Four Winds charge gate.');
    assert(damageGapped > damageChained, ...
        'A filler normal should add damage without breaking the preserved Varka C6 Devour link.');

    auditRotation = writeTempRotationFile(tempDir, 'Varka', 5, sprintf('E\nAscend\nDevour\nQ\n'));
    [~, ~, ~, ~, audit] = simulateVarkaDPS( ...
        varka.Build, enemy, auditRotation, varka.TalentLevel, varka.Constellation, pyroContext);
    auditRows = audit.Rows;

    fourWindsRows = auditRows(ismember(string(auditRows.Action), ["FourWindsRight", "FourWindsAnemo"]), :);
    fourWindsC2Rows = auditRows(string(auditRows.Action) == "FourWindsC2", :);
    devourRows = auditRows(ismember(string(auditRows.Action), ...
        ["AzureDevourRight1", "AzureDevourAnemo1", "AzureDevourRight2", "AzureDevourAnemo2"]), :);
    devourC2Rows = auditRows(string(auditRows.Action) == "AzureDevourC2", :);
    burstRows = auditRows(ismember(string(auditRows.Action), ["Q1", "Q2"]), :);
    normalAuditRotation = writeTempRotationFile(tempDir, 'Varka', 6, sprintf('E\nN1\n'));
    [~, ~, ~, ~, normalAudit] = simulateVarkaDPS( ...
        varka.Build, enemy, normalAuditRotation, varka.TalentLevel, varka.Constellation, pyroContext);
    leftRows = normalAudit.Rows(endsWith(string(normalAudit.Rows.Action), "Left"), :);
    rightRows = normalAudit.Rows(endsWith(string(normalAudit.Rows.Action), "Right"), :);

    assert(~isempty(fourWindsRows) && all(string(fourWindsRows.LunarisAttackName) == "Special_ElementalArt"), ...
        'Varka Four Winds audit rows should bind to the special Lunaris elemental-art entries.');
    assert(~isempty(devourRows) && all(string(devourRows.LunarisAttackName) == "Special_ElementalArt"), ...
        'Varka Azure Devour audit rows should bind to the special Lunaris elemental-art entries.');
    assert(~isempty(fourWindsC2Rows) && all(string(fourWindsC2Rows.LunarisAttackName) == ""), ...
        'Varka Four Winds C2 extra slash should stay as an explicit non-Lunaris bonus row.');
    assert(~isempty(devourC2Rows) && all(string(devourC2Rows.LunarisAttackName) == ""), ...
        'Varka Azure Devour C2 extra slash should stay as an explicit non-Lunaris bonus row.');
    assert(~isempty(burstRows) && all(string(burstRows.LunarisAttackName) == "ElementalBurst"), ...
        'Varka burst audit rows should bind to the Lunaris burst entries.');
    assert(~isempty(leftRows) && all(leftRows.ApplyGauge == 1) ...
        && all(string(leftRows.ApplyGaugeSource) == "explicit") ...
        && all(string(leftRows.LunarisAttackName) == ""), ...
        'Varka left-hand audit rows should expose explicit 1U aura metadata without borrowing an unrelated Lunaris attack.');
    assert(~isempty(rightRows) && all(rightRows.ApplyGauge == 1) ...
        && all(string(rightRows.ApplyGaugeSource) == "explicit") ...
        && all(string(rightRows.LunarisAttackName) == ""), ...
        'Varka right-hand audit rows should expose explicit 1U aura metadata without borrowing an unrelated Lunaris attack.');

    publicAscend = inferActionCombatMetadata(varka, 'Ascend', struct(), pyroContext);
    publicDevour = inferActionCombatMetadata(varka, 'Devour', struct(), pyroContext);
    publicBurst = inferActionCombatMetadata(varka, 'Q', struct(), pyroContext);
    internalBurstFollow = inferActionCombatMetadata(varka, 'Q2', struct(), pyroContext);

    assert(publicAscend.ActionClass == "Skill" && publicAscend.HitElement == "Pyro" ...
        && publicAscend.ApplyGauge == 1 && publicAscend.ICDSource == "metadata", ...
        'Varka Ascend should resolve to a Pyro 1U skill hit in the inference layer.');
    assert(publicDevour.ActionClass == "Charged" && publicDevour.HitElement == "Pyro" ...
        && publicDevour.ApplyGauge == 1 && publicDevour.ICDSource == "metadata", ...
        'Varka Devour should resolve to a Pyro 1U charged hit in the inference layer.');
    assert(publicBurst.HitElement == "Pyro" && publicBurst.TriggeredFollowUpAction == "Q2", ...
        'Varka public burst metadata should route the leading slash element and schedule the second slash.');
    assert(internalBurstFollow.ActionClass == "FollowUp" && internalBurstFollow.HitElement == "Anemo", ...
        'Varka Q2 should resolve as the anemo follow-up slash.');

    disp('validateVarkaRegression passed');
end
