function validateJeanDilucRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Approximate", ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    jean = getDefaultCharacterConfig('Jean', struct('Constellation', 1));
    diluc = getDefaultCharacterConfig('Diluc', struct('Constellation', 6));

    [jeanDamage, ~, jeanBreakdown] = simulateJeanDPS( ...
        jean.Build, enemy, [], jean.TalentLevel, jean.Constellation, []);
    [dilucDamage, ~, dilucBreakdown] = simulateDilucDPS( ...
        diluc.Build, enemy, [], diluc.TalentLevel, diluc.Constellation, []);

    assert(jeanDamage > 0, 'Jean default simulation should produce positive damage.');
    assert(isequal(string(jeanBreakdown.Action(1:3)), ["E"; "QCast"; "QField"]), ...
        'Jean default rotation should keep the expected baseline E/Q sequence.');

    assert(dilucDamage > 0, 'Diluc default simulation should produce positive damage.');
    assert(any(strcmp(string(dilucBreakdown.Action), "E2Rhythm")), ...
        'Diluc default rotation should preserve the rhythm-tagged second skill cast.');

    disp('validateJeanDilucRegression passed');
end
