function validateXianglingRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cfg0 = getDefaultCharacterConfig('Xiangling', struct('Constellation', 0, 'TalentLevel', 10));
    cfg4 = getDefaultCharacterConfig('Xiangling', struct('Constellation', 4, 'TalentLevel', 10));
    ctx0 = buildTeamContext({cfg0}, 20, struct('ReactionMode', "Realistic"), enemy);
    ctx4 = buildTeamContext({cfg4}, 20, struct('ReactionMode', "Realistic"), enemy);

    [damage0, ~, breakdown0, rotationTime0, audit0] = simulateXianglingDPS( ...
        cfg0.Build, enemy, cfg0.RotationFile, cfg0.TalentLevel, cfg0.Constellation, ctx0);
    [damage4, ~, breakdown4, rotationTime4, audit4] = simulateXianglingDPS( ...
        cfg4.Build, enemy, cfg4.RotationFile, cfg4.TalentLevel, cfg4.Constellation, ctx4);
    pickupEvents = table( ...
        5.05, ...
        "Xiangling", ...
        "Pickup", ...
        "GuobaChili", ...
        "Chili", ...
        1.0, ...
        'VariableNames', {'Time', 'Character', 'EventKind', 'EventName', 'SourceAction', 'Value'});
    explicitPickupCtx = buildTeamContext({cfg0}, 20, struct('ReactionMode', "Realistic", 'CombatEventTable', pickupEvents), enemy);
    [damagePickup, ~, breakdownPickup, rotationTimePickup] = simulateXianglingDPS( ...
        cfg0.Build, enemy, cfg0.RotationFile, cfg0.TalentLevel, cfg0.Constellation, explicitPickupCtx);

    actions0 = string(breakdown0.Action);
    actions4 = string(breakdown4.Action);
    pickupActions = string(breakdownPickup.Action);
    pyronadoEarly0 = breakdown0(actions0 == "PyronadoEarly", :);
    pyronado0 = breakdown0(actions0 == "Pyronado", :);
    chiliRows0 = breakdown0(actions0 == "Chili", :);
    pyronadoEarly4 = breakdown4(actions4 == "PyronadoEarly", :);
    pyronado4 = breakdown4(actions4 == "Pyronado", :);
    pyronadoEarlyPickup = breakdownPickup(pickupActions == "PyronadoEarly", :);
    pyronadoPickup = breakdownPickup(pickupActions == "Pyronado", :);
    chiliPickupRows = breakdownPickup(pickupActions == "Chili", :);

    assert(damage0 > 0 && rotationTime0 > 0 && damage4 > 0 && rotationTime4 > 0, ...
        'Xiangling regression should produce positive damage and rotation time for both C0 and C4.');
    assert(isequal(actions0', ["E", "QSlash1", "QSlash2", "QSlash3", "PyronadoEarly", "Chili", "Pyronado", "N5Explode"]), ...
        'Xiangling regression should preserve the Guoba -> Pyronado -> chili -> C2 implode order.');
    assert(height(pyronadoEarly0) == 1 && contains(string(pyronadoEarly0.Note), "x5"), ...
        'Xiangling C0 regression should split the opening Pyronado segment into 5 hits.');
    assert(height(pyronado0) == 1 && contains(string(pyronado0.Note), "x5"), ...
        'Xiangling C0 regression should keep the 10-hit Pyronado note.');
    assert(height(chiliRows0) == 1 && strcmp(string(chiliRows0.Note), "Guoba chili pickup"), ...
        'Xiangling regression should expose the chili pickup as an explicit zero-damage row.');
    assert(height(pyronadoEarly4) == 1 && contains(string(pyronadoEarly4.Note), "x5"), ...
        'Xiangling C4 regression should split the opening Pyronado segment into 5 hits.');
    assert(height(pyronado4) == 1 && contains(string(pyronado4.Note), "x9"), ...
        'Xiangling C4 regression should keep the extended 14-hit Pyronado note.');
    assert(damagePickup > damage0 && abs(rotationTimePickup - rotationTime0) < 1e-9, ...
        'Explicit Guoba chili pickup timing should rebalance Pyronado damage without changing the total scripted rotation time.');
    assert(height(pyronadoEarlyPickup) == 1 && contains(string(pyronadoEarlyPickup.Note), "pickup@5.05s") ...
            && contains(string(pyronadoEarlyPickup.Note), "x4"), ...
        'Explicit chili-timing regression should pull one Pyronado spin into the post-pickup window when the pickup event lands earlier than the legacy split.');
    assert(height(pyronadoPickup) == 1 && contains(string(pyronadoPickup.Note), "pickup@5.05s") ...
            && contains(string(pyronadoPickup.Note), "x6"), ...
        'Explicit chili-timing regression should increase the buffed late-spin count when the pickup event lands earlier than the legacy split.');
    assert(height(chiliPickupRows) == 1 && contains(string(chiliPickupRows.Note), "pickup@5.05s"), ...
        'Xiangling explicit pickup regression should annotate the Chili row with the resolved pickup timestamp.');
    assert(~any(audit0.Rows.ApplyGaugeFallback | audit0.Rows.ICDFallback) ...
        && ~any(audit4.Rows.ApplyGaugeFallback | audit4.Rows.ICDFallback), ...
        'Xiangling regression should keep explicit gauge and ICD metadata for the scripted rotation.');

    disp('validateXianglingRegression passed');
end
