function validateImportedAuditCompatibilityRegression()
    initProjectPaths();

    requiredColumns = [ ...
        "Action", "ActionKey", "ApplyGauge", "ApplyGaugeSource", "ICDRule", "ICDSource", ...
        "LunarisAttackName", "LunarisDamageParam", "ApplyGaugeFallback", "ICDFallback"];

    furina = auditCharacterReactionMetadata('Furina');
    assert(istable(furina.Rows), ...
        'Furina audit should always return a table for Rows.');
    assert(all(ismember(requiredColumns, string(furina.Rows.Properties.VariableNames))), ...
        'Furina audit rows should expose the standard compatibility columns.');
    assert(~isempty(furina.Rows), ...
        'Furina bespoke simulator should now expose standardized action metadata rows.');
    assert(~any(furina.Rows.ApplyGaugeFallback | furina.Rows.ICDFallback), ...
        'Furina bespoke audit should avoid generic fallback rows.');
    assert(any(strcmp(string(furina.Rows.Action), "E")) && any(strcmp(string(furina.Rows.Action), "Q")), ...
        'Furina bespoke audit should include its baseline skill and burst actions.');

    nicole = auditCharacterReactionMetadata('Nicole');
    assert(~isempty(nicole.Rows), ...
        'Nicole audit should no longer fail through imported-normal parameter fallback.');
    assert(all(ismember(requiredColumns, string(nicole.Rows.Properties.VariableNames))), ...
        'Nicole audit rows should expose the standard compatibility columns.');
    assert(~any(nicole.Rows.ApplyGaugeFallback | nicole.Rows.ICDFallback), ...
        'Nicole bespoke audit should avoid generic fallback rows.');
    assert(any(strcmp(string(nicole.Rows.Action), "Projection")), ...
        'Nicole bespoke audit should resolve projection and unity actions directly.');
    assert(any(strcmp(string(nicole.Rows.Action), "Unity")), ...
        'Nicole bespoke audit should include the Unity follow-up action.');

    durin = auditCharacterReactionMetadata('Durin');
    assert(~isempty(durin.Rows), ...
        'Durin audit should no longer fail through imported-normal parameter fallback.');
    assert(all(ismember(requiredColumns, string(durin.Rows.Properties.VariableNames))), ...
        'Durin audit rows should expose the standard compatibility columns.');
    assert(~any(durin.Rows.ApplyGaugeFallback | durin.Rows.ICDFallback), ...
        'Durin bespoke audit should avoid generic fallback rows.');
    assert(any(strcmp(string(durin.Rows.Action), "Confirm")) || any(strcmp(string(durin.Rows.Action), "Deny")), ...
        'Durin bespoke audit should expose its true transmutation actions.');

    disp('validateImportedAuditCompatibilityRegression passed');
end
