function validateFischlRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cfg = getDefaultCharacterConfig('Fischl', struct('Constellation', 6, 'TalentLevel', 10));
    ctx = buildTeamContext({cfg}, 20, struct('ReactionMode', "Realistic"), enemy);

    [damage, ~, breakdown, rotationTime, audit] = simulateFischlDPS( ...
        cfg.Build, enemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, ctx);

    actions = string(breakdown.Action);
    ozRows = breakdown(actions == "Oz", :);
    qOzRows = breakdown(actions == "QOz", :);

    assert(damage > 0 && rotationTime > 0, ...
        'Fischl regression should produce positive damage and rotation time.');
    assert(isequal(actions', ["E", "Oz", "Q", "QOz"]), ...
        'Fischl regression should preserve the summon -> Oz -> burst -> Oz refresh order.');
    assert(height(ozRows) == 1 && contains(string(ozRows.Note), "x10"), ...
        'Fischl regression should keep the 10-shot Oz turret note.');
    assert(height(qOzRows) == 1 && contains(string(qOzRows.Note), "x10"), ...
        'Fischl regression should keep the 10-shot Oz refresh note.');
    assert(~any(audit.Rows.ApplyGaugeFallback | audit.Rows.ICDFallback), ...
        'Fischl regression should keep explicit gauge and ICD metadata for the scripted rotation.');

    disp('validateFischlRegression passed');
end
