function validateTeamRotationOptimizerRegression()
    initProjectPaths();

    enemy = struct('Level', 90, 'Res', 0.10, 'DefReduct', 0, ...
        'ReactionMode', "Realistic", 'AutoSupportAura', false);
    amber = getDefaultCharacterConfig('Amber');
    amber.Build.ER = 5.0;
    teamContext = buildTeamContext({amber}, 20, struct(), enemy);

    cooldownPlan = struct( ...
        'RotationDuration', 5, ...
        'MemberPlans', struct('Role', "Carry", 'RotationTokens', {{'E', 'E'}}, 'StartTime', 0));
    cooldownReport = validateTeamRotationLoop({amber}, cooldownPlan, teamContext, enemy, struct());
    assert(~cooldownReport.IsFeasible && any(cooldownReport.Violations.Type == "Cooldown"), ...
        'Loop validator should reject skill casts whose shared cooldown crosses the cycle boundary.');

    basePlan = struct( ...
        'RotationDuration', 20, ...
        'CarryIndex', 1, ...
        'ExecutionOrder', 1, ...
        'ArchetypeInfo', identifyTeamArchetype({amber}, struct()), ...
        'MemberPlans', struct('Role', "Carry", 'Job', "Damage", ...
            'RotationTokens', {{'Q', 'E', 'Q'}}, 'RotationText', "Q" + newline + "E" + newline + "Q", ...
            'StartTime', 0, 'EndTime', 2.95, 'EstimatedDuration', 2.95));
    optimized = optimizeTeamRotation({amber}, basePlan, 20, enemy, struct(), struct( ...
        'OptimizerMaxCandidates', 6, 'ValidationCycles', 4, 'WarmupCycles', 1));

    assert(optimized.Enabled && optimized.CandidateCount >= 2, ...
        'Rotation optimizer should evaluate the baseline and at least one constrained mutation.');
    assert(optimized.FeasibleCandidateCount >= 1 && optimized.BestIndex > 0 && isfinite(optimized.BestDPS), ...
        'Rotation optimizer should retain a feasible DPS-scored candidate after rejecting invalid burst timing.');
    bestTokens = string(optimized.BestPlan.MemberPlans(1).RotationTokens);
    assert(sum(strcmpi(bestTokens, "Q")) == 1, ...
        'Optimizer should remove one of two unsustainable Amber bursts from the best feasible cycle.');

    teamSpec = struct( ...
        'Members', {{amber}}, ...
        'RotationDuration', 20, ...
        'SharedBuffs', struct(), ...
        'PlanOptions', struct('EnableDPSOptimizer', true, 'OptimizerMaxCandidates', 6, ...
            'ValidationCycles', 4, 'WarmupCycles', 1));
    teamResult = simulateTeamDPS(teamSpec, enemy);
    assert(teamResult.Optimization.Enabled && isfield(teamResult.PlannedRotation, 'SelectionMode'), ...
        'Unified team simulation should expose the optimized rotation when the option is enabled.');

    disp('validateTeamRotationOptimizerRegression passed');
end
