function validateIfaRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Approximate");

    cfgC0 = getDefaultCharacterConfig('Ifa', struct('Constellation', 0));
    cfgC2 = getDefaultCharacterConfig('Ifa', struct('Constellation', 2));
    bennett = struct('Name', 'Bennett', 'Constellation', 0, 'Build', customArtifact_Bennett());

    contextC0 = buildTeamContext( ...
        {cfgC0, bennett}, 20, struct('ReactionMode', "Approximate"), enemy);
    contextC2 = buildTeamContext( ...
        {cfgC2, bennett}, 20, struct('ReactionMode', "Approximate", 'NightsoulPointPool', 40), enemy);

    [damageC0, ~, breakdownC0] = simulateIfaDPS( ...
        cfgC0.Build, enemy, cfgC0.RotationFile, cfgC0.TalentLevel, cfgC0.Constellation, contextC0);
    [damageC2, ~, breakdownC2] = simulateIfaDPS( ...
        cfgC2.Build, enemy, cfgC2.RotationFile, cfgC2.TalentLevel, cfgC2.Constellation, contextC2);

    supportRowsC0 = breakdownC0(contains(string(breakdownC0.Action), "Support"), :);
    supportRowsC2 = breakdownC2(contains(string(breakdownC2.Action), "Support"), :);

    assert(damageC2 > damageC0, ...
        'Ifa C2 with an explicit extra Nightsoul pool should outdamage the baseline Rescue rotation.');
    assert(all(contains(string(supportRowsC0.Note), "Rescue")), ...
        'Ifa support actions should annotate their Rescue Essentials state.');
    assert(all(contains(string(supportRowsC2.Note), "Rescue")), ...
        'Ifa C2 support actions should annotate their enlarged Rescue Essentials state.');
    assert(sum(supportRowsC2.Damage) > sum(supportRowsC0.Damage), ...
        'Ifa Support damage should increase when Rescue Essentials and C2 are both strengthened.');

    disp('validateIfaRegression passed');
end
