function validateVentiRegression()
    initProjectPaths();

    baseEnemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cfg = getDefaultCharacterConfig('Venti', struct('TalentLevel', 10, 'Constellation', 0));
    amber = getDefaultCharacterConfig('Amber');
    barbara = getDefaultCharacterConfig('Barbara');
    build = cfg.Build;
    build.PyroDMGBonus = 0.80;
    build.HydroDMGBonus = 0.00;

    pyroEnemy = baseEnemy;
    pyroEnemy.InitialAuraElement = "Pyro";
    pyroEnemy.InitialAuraGauge = 1.0;
    priorityContext = buildTeamContext({cfg, amber, barbara}, 20, struct('ReactionMode', "Realistic"), pyroEnemy);
    hydroOnlyContext = buildTeamContext({cfg, barbara}, 20, struct('ReactionMode', "Realistic"), baseEnemy);
    overrideEnemy = baseEnemy;
    overrideEnemy.InitialAuraElement = "Hydro";
    overrideContext = buildTeamContext({cfg, amber, barbara}, 20, struct('ReactionMode', "Realistic"), overrideEnemy);
    approximateEnemy = baseEnemy;
    approximateEnemy.ReactionMode = "Approximate";
    approximateEnemy.AutoSupportAura = true;
    approximateContext = buildTeamContext({cfg, amber, barbara}, 20, struct('ReactionMode', "Approximate"), approximateEnemy);

    [priorityDamage, ~, priorityBreakdown, priorityTime, priorityAudit] = simulateVentiDPS( ...
        build, pyroEnemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, priorityContext);
    [hydroOnlyDamage, ~, hydroOnlyBreakdown, hydroOnlyTime] = simulateVentiDPS( ...
        build, baseEnemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, hydroOnlyContext);
    [overrideDamage, ~, overrideBreakdown, overrideTime, overrideAudit] = simulateVentiDPS( ...
        build, overrideEnemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, overrideContext);
    [approximateDamage, ~, approximateBreakdown, approximateTime] = simulateVentiDPS( ...
        build, approximateEnemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, approximateContext);

    priorityActions = string(priorityBreakdown.Action);
    priorityInfuse = priorityBreakdown(priorityActions == "QInfuse", :);
    hydroOnlyInfuse = hydroOnlyBreakdown(string(hydroOnlyBreakdown.Action) == "QInfuse", :);
    overrideInfuse = overrideBreakdown(string(overrideBreakdown.Action) == "QInfuse", :);
    approximateInfuse = approximateBreakdown(string(approximateBreakdown.Action) == "QInfuse", :);

    assert(priorityDamage > 0 && priorityTime > 0 && hydroOnlyDamage > 0 && hydroOnlyTime > 0 ...
        && overrideDamage > 0 && overrideTime > 0 && approximateDamage > 0 && approximateTime > 0, ...
        'Venti regression should produce positive damage and rotation time.');
    assert(isequal(priorityActions', ["EHold", "QDot", "QInfuse", "E"]), ...
        'Venti regression should preserve the hold E -> burst -> infuse -> tap E order.');
    assert(height(priorityInfuse) == 1 && height(hydroOnlyInfuse) == 1 ...
        && height(overrideInfuse) == 1 && height(approximateInfuse) == 1, ...
        'Venti regression should isolate one absorbed-element row per scripted rotation.');
    assert(hydroOnlyInfuse.Damage == 0, ...
        'Venti realistic Hydro-only regression should not absorb an element without an explicit enemy aura.');
    assert(priorityInfuse.Damage > overrideInfuse.Damage, ...
        'Venti regression should prefer Pyro over Hydro when no initial aura override is present.');
    assert(overrideInfuse.Damage > hydroOnlyInfuse.Damage, ...
        'Venti explicit Hydro-aura regression should outdamage the realistic Hydro-only team context.');
    assert(approximateInfuse.Damage > priorityInfuse.Damage, ...
        'Venti approximate-mode regression should preserve the team-priority absorption fallback and its support-aura damage upside.');
    assert(~any(priorityAudit.Rows.ApplyGaugeFallback | priorityAudit.Rows.ICDFallback) ...
        && ~any(overrideAudit.Rows.ApplyGaugeFallback | overrideAudit.Rows.ICDFallback), ...
        'Venti regression should keep explicit gauge and ICD metadata for the scripted rotation.');

    disp('validateVentiRegression passed');
end
