function validateDefaultSoloContextReactionModeRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cases = { ...
        struct('Name', "Sethos", 'Cfg', getDefaultCharacterConfig('Sethos', struct('Constellation', 0)), ...
            'SimFn', @simulateSethosDPS), ...
        struct('Name', "Ororon", 'Cfg', getDefaultCharacterConfig('Ororon', struct('Constellation', 1)), ...
            'SimFn', @simulateOroronDPS), ...
        struct('Name', "Ifa", 'Cfg', getDefaultCharacterConfig('Ifa', struct('Constellation', 0)), ...
            'SimFn', @simulateIfaDPS), ...
        struct('Name', "Dahlia", 'Cfg', getDefaultCharacterConfig('Dahlia', struct('Constellation', 5)), ...
            'SimFn', @simulateDahliaDPS), ...
        struct('Name', "Aino", 'Cfg', getDefaultCharacterConfig('Aino', struct('Constellation', 4)), ...
            'SimFn', @simulateAinoDPS), ...
        struct('Name', "Jahoda", 'Cfg', getDefaultCharacterConfig('Jahoda', struct('Constellation', 2)), ...
            'SimFn', @simulateJahodaDPS), ...
        struct('Name', "Illuga", 'Cfg', getDefaultCharacterConfig('Illuga', struct('Constellation', 2)), ...
            'SimFn', @simulateIllugaDPS), ...
        struct('Name', "LanYan", 'Cfg', getDefaultCharacterConfig('LanYan', struct('Constellation', 4)), ...
            'SimFn', @simulateLanYanDPS), ...
        struct('Name', "Varka", 'Cfg', getDefaultCharacterConfig('Varka', struct('Constellation', 2)), ...
            'SimFn', @simulateVarkaDPS), ...
        struct('Name', "Amber", 'Cfg', getDefaultCharacterConfig('Amber', struct('Constellation', 6)), ...
            'SimFn', @simulateAmberDPS), ...
        struct('Name', "Barbara", 'Cfg', getDefaultCharacterConfig('Barbara', struct('Constellation', 6)), ...
            'SimFn', @simulateBarbaraDPS), ...
        struct('Name', "Chevreuse", 'Cfg', getDefaultCharacterConfig('Chevreuse', struct('Constellation', 6)), ...
            'SimFn', @simulateChevreuseDPS), ...
        struct('Name', "Diluc", 'Cfg', getDefaultCharacterConfig('Diluc', struct('Constellation', 2)), ...
            'SimFn', @simulateDilucDPS), ...
        struct('Name', "Jean", 'Cfg', getDefaultCharacterConfig('Jean', struct('Constellation', 2)), ...
            'SimFn', @simulateJeanDPS), ...
        struct('Name', "Kaeya", 'Cfg', getDefaultCharacterConfig('Kaeya', struct('Constellation', 6)), ...
            'SimFn', @simulateKaeyaDPS), ...
        struct('Name', "Durin", 'Cfg', getDefaultCharacterConfig('Durin', struct('Constellation', 0, 'TalentLevel', 10)), ...
            'SimFn', @simulateDurinDPS), ...
        struct('Name', "Fischl", 'Cfg', getDefaultCharacterConfig('Fischl', struct('Constellation', 6, 'TalentLevel', 10)), ...
            'SimFn', @simulateFischlDPS), ...
        struct('Name', "Furina", 'Cfg', getDefaultCharacterConfig('Furina', struct('Constellation', 0, 'TalentLevel', 10)), ...
            'SimFn', @simulateFurinaDPS), ...
        struct('Name', "Iansan", 'Cfg', getDefaultCharacterConfig('Iansan', struct('Constellation', 1, 'TalentLevel', 10)), ...
            'SimFn', @simulateIansanDPS), ...
        struct('Name', "KamisatoAyaka", 'Cfg', getDefaultCharacterConfig('KamisatoAyaka', struct('Constellation', 2, 'TalentLevel', 10)), ...
            'SimFn', @simulateKamisatoAyakaDPS), ...
        struct('Name', "Lisa", 'Cfg', getDefaultCharacterConfig('Lisa', struct('Constellation', 4, 'TalentLevel', 10)), ...
            'SimFn', @simulateLisaDPS), ...
        struct('Name', "Nicole", 'Cfg', getDefaultCharacterConfig('Nicole', struct('Constellation', 2)), ...
            'SimFn', @simulateNicoleDPS), ...
        struct('Name', "Razor", 'Cfg', getDefaultCharacterConfig('Razor', struct('Constellation', 6)), ...
            'SimFn', @simulateRazorDPS), ...
        struct('Name', "Varesa", 'Cfg', getDefaultCharacterConfig('Varesa', struct('Constellation', 0, 'TalentLevel', 10)), ...
            'SimFn', @simulateVaresaDPS), ...
        struct('Name', "Venti", 'Cfg', getDefaultCharacterConfig('Venti', struct('Constellation', 0, 'TalentLevel', 10)), ...
            'SimFn', @simulateVentiDPS), ...
        struct('Name', "Xiangling", 'Cfg', getDefaultCharacterConfig('Xiangling', struct('Constellation', 4, 'TalentLevel', 10)), ...
            'SimFn', @simulateXianglingDPS), ...
        struct('Name', "Xianyun", 'Cfg', getDefaultCharacterConfig('Xianyun', struct('Constellation', 6)), ...
            'SimFn', @simulateXianyunDPS)};

    for caseIndex = 1:numel(cases)
        current = cases{caseIndex};
        cfg = current.Cfg;
        [~, ~, ~, ~, audit] = current.SimFn( ...
            cfg.Build, enemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, []);
        assert(strcmp(string(getFieldOrDefault(audit, 'TeamContextReactionMode', "")), "Realistic"), ...
            sprintf('%s default simulator context should inherit the explicit Realistic enemy reaction mode.', current.Name));
        assert(~logical(getFieldOrDefault(audit, 'EnemyStateAutoSupportAura', true)), ...
            sprintf('%s default simulator context should not silently re-enable support-aura fallback in Realistic mode.', current.Name));
    end

    disp('validateDefaultSoloContextReactionModeRegression passed');
end
