function validateOroronTimelineRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 2, ...
        'TargetCount', 2);

    ororon = getDefaultCharacterConfig('Ororon', struct('Constellation', 1));
    xingqiu = getDefaultCharacterConfig('Xingqiu');
    fischl = getDefaultCharacterConfig('Fischl');
    ifa = getDefaultCharacterConfig('Ifa');
    members = {ororon, xingqiu, fischl, ifa};

    denseTimeline = localBuildOroronTimeline([ ...
        localOroronTimelineRow(1, 0.00, "Ororon", "E", "MemberAction", "Skill", "Electro", 1, ""), ...
        localOroronTimelineRow(2, 0.10, "Ifa", "SupportTap", "MemberAction", "Skill", "Anemo", 1, ""), ...
        localOroronTimelineRow(3, 2.00, "Xingqiu", "RainSword", "TriggeredFollowUp", "FollowUp", "Hydro", 1, "Electro-Charged"), ...
        localOroronTimelineRow(4, 4.10, "Ifa", "SupportTap", "MemberAction", "Skill", "Anemo", 1, ""), ...
        localOroronTimelineRow(5, 6.20, "Fischl", "Oz", "EffectTick", "FollowUp", "Electro", 1, "Electro-Charged"), ...
        localOroronTimelineRow(6, 8.30, "Ifa", "SupportTap", "MemberAction", "Skill", "Anemo", 1, ""), ...
        localOroronTimelineRow(7, 10.40, "Xingqiu", "RainSword", "TriggeredFollowUp", "FollowUp", "Hydro", 1, "Electro-Charged")]);
    sparseTimeline = localBuildOroronTimeline([ ...
        localOroronTimelineRow(1, 0.00, "Ororon", "E", "MemberAction", "Skill", "Electro", 1, ""), ...
        localOroronTimelineRow(2, 0.10, "Ifa", "SupportTap", "MemberAction", "Skill", "Anemo", 1, ""), ...
        localOroronTimelineRow(3, 2.00, "Xingqiu", "RainSword", "TriggeredFollowUp", "FollowUp", "Hydro", 1, "Electro-Charged")]);

    denseContext = buildTeamContext(members, 20, struct( ...
        'ReactionMode', "Realistic", ...
        'TimelineTable', denseTimeline), enemy);
    sparseContext = buildTeamContext(members, 20, struct( ...
        'ReactionMode', "Realistic", ...
        'TimelineTable', sparseTimeline), enemy);

    [denseDamage, ~, denseBreakdown] = simulateOroronDPS( ...
        ororon.Build, enemy, ororon.RotationFile, ororon.TalentLevel, ororon.Constellation, denseContext);
    [sparseDamage, ~, sparseBreakdown] = simulateOroronDPS( ...
        ororon.Build, enemy, ororon.RotationFile, ororon.TalentLevel, ororon.Constellation, sparseContext);

    denseNote = string(denseBreakdown.Note(strcmp(string(denseBreakdown.Action), "Hypersense")));
    sparseNote = string(sparseBreakdown.Note(strcmp(string(sparseBreakdown.Action), "Hypersense")));

    diluc = getDefaultCharacterConfig('Diluc');
    kachina = getDefaultCharacterConfig('Kachina');
    supportPlan = planTeamRotation({diluc, ororon, kachina}, 20, enemy, struct('ReactionMode', "Realistic"), struct());
    supportNames = string({supportPlan.MemberPlans.Name});
    ororonPlan = supportPlan.MemberPlans(find(strcmpi(supportNames, "Ororon"), 1, 'first'));
    ororonTokens = string(ororonPlan.RotationTokens);

    runtimeMembers = {ororon, kachina};
    runtimeContext = buildTeamContext(runtimeMembers, 20, struct('ReactionMode', "Realistic"), enemy);
    runtimePlan = struct( ...
        'RotationDuration', 20, ...
        'ArchetypeInfo', identifyTeamArchetype(runtimeMembers, struct('ReactionMode', "Realistic")), ...
        'MemberPlans', [ ...
            struct('Role', "Support", 'RotationTokens', {{'E', 'Q'}}, 'StartTime', 0.00), ...
            struct('Role', "Support", 'RotationTokens', {{'E'}}, 'StartTime', 0.10)]);
    runtimeTimeline = simulateTeamTimeline(runtimeMembers, runtimePlan, runtimeContext, enemy, struct());
    runtimeRows = runtimeTimeline.TimelineTable;
    bounceRows = runtimeRows(strcmp(string(runtimeRows.Character), "Ororon") ...
        & strcmp(string(runtimeRows.Action), "Bounce"), :);
    waveRows = runtimeRows(strcmp(string(runtimeRows.Character), "Ororon") ...
        & startsWith(string(runtimeRows.Action), "Wave#"), :);
    hypersenseRows = runtimeRows(strcmp(string(runtimeRows.Character), "Ororon") ...
        & strcmp(string(runtimeRows.Action), "Hypersense"), :);

    assert(isfield(denseContext, 'TimelineTable') ...
        && height(denseContext.TimelineTable) == height(denseTimeline), ...
        'buildTeamContext should preserve caller-provided TimelineTable data.');
    assert(any(contains(denseNote, "est. 5 procs")), ...
        'Dense real-timeline Electro-Charged windows should lift Ororon to a 5-proc Hypersense estimate.');
    assert(any(contains(sparseNote, "est. 2 procs")), ...
        'Sparse real-timeline trigger windows should reduce Ororon to a 2-proc Hypersense estimate.');
    assert(denseDamage > sparseDamage, ...
        'Denser real timeline trigger windows should increase Ororon damage.');
    assert(isequal(ororonTokens(:)', ["E", "Q"]), ...
        'Ororon support auto-plan should stay on public E/Q tokens while deferring pulses and Hypersense to runtime expansion.');
    assert(~isempty(bounceRows), ...
        'Ororon team timeline should expand the public skill token into an explicit Spirit Orb bounce row.');
    assert(height(waveRows) >= 6 ...
        && all(string(waveRows.SourceType) == "EffectTick") ...
        && all(string(waveRows.BackgroundDriverMode) == "AutonomousTick"), ...
        'Ororon team timeline should expand the public burst token into autonomous Supersonic Oculus wave ticks.');
    assert(~isempty(hypersenseRows) ...
        && any(string(hypersenseRows.TriggerSourceCharacter) == "Kachina") ...
        && any(string(hypersenseRows.BackgroundDriverMode) == "ForegroundAnyActionTrigger"), ...
        'Ororon team timeline should trigger runtime Hypersense follow-ups from allied Nightsoul elemental actions.');

    disp('validateOroronTimelineRegression passed');
end

function row = localOroronTimelineRow(order, startTime, character, action, sourceType, actionClass, hitElement, applyGauge, reaction)
    row = struct( ...
        'Order', double(order), ...
        'StartTime', double(startTime), ...
        'Character', string(character), ...
        'Action', string(action), ...
        'SourceType', string(sourceType), ...
        'ActionClass', string(actionClass), ...
        'HitElement', string(hitElement), ...
        'ApplyGauge', double(applyGauge), ...
        'Reaction', string(reaction));
end

function timelineTable = localBuildOroronTimeline(rows)
    order = reshape([rows.Order], [], 1);
    startTime = reshape([rows.StartTime], [], 1);
    character = reshape(string({rows.Character}), [], 1);
    action = reshape(string({rows.Action}), [], 1);
    sourceType = reshape(string({rows.SourceType}), [], 1);
    actionClass = reshape(string({rows.ActionClass}), [], 1);
    hitElement = reshape(string({rows.HitElement}), [], 1);
    applyGauge = reshape([rows.ApplyGauge], [], 1);
    reaction = reshape(string({rows.Reaction}), [], 1);

    timelineTable = table(order, startTime, character, action, sourceType, actionClass, hitElement, applyGauge, reaction, ...
        'VariableNames', {'Order', 'StartTime', 'Character', 'Action', 'SourceType', 'ActionClass', 'HitElement', 'ApplyGauge', 'Reaction'});
end
