function validateTeamEnergyCatchRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    xingqiu = getDefaultCharacterConfig('Xingqiu');
    xiangling = getDefaultCharacterConfig('Xiangling');
    xingqiu.StartEnergy = 0;
    xiangling.StartEnergy = 0;
    teamContext = buildTeamContext({xingqiu, xiangling}, 20, struct('ReactionMode', "Realistic"), enemy);

    stayPlan = struct( ...
        'RotationDuration', 20, ...
        'MemberPlans', [ ...
            struct('Role', "Driver", 'RotationTokens', {{'E', 'N1', 'N1'}}, 'StartTime', 0.0), ...
            struct('Role', "OffField", 'RotationTokens', {{'Q'}}, 'StartTime', 3.5)]);

    funnelPlan = struct( ...
        'RotationDuration', 20, ...
        'MemberPlans', [ ...
            struct('Role', "Driver", 'RotationTokens', {{'E'}}, 'StartTime', 0.0), ...
            struct('Role', "OffField", 'RotationTokens', {{'Q', 'N1'}}, 'StartTime', 1.05)]);

    stayResult = simulateTeamTimeline({xingqiu, xiangling}, stayPlan, teamContext, enemy, struct());
    stayEnergyTimeline = stayResult.EnergyTimeline;

    stayCatchRows = stayEnergyTimeline(string(stayEnergyTimeline.SourceCharacter) == "Xingqiu" ...
        & string(stayEnergyTimeline.Action) == "E" ...
        & string(stayEnergyTimeline.EventType) == "ParticleCatch", :);
    assert(~isempty(stayCatchRows), ...
        'Xingqiu skill should emit delayed catch rows in the stay timeline.');

    boundarySwapTime = min(stayCatchRows.Time);
    boundaryPlan = struct( ...
        'RotationDuration', 20, ...
        'MemberPlans', [ ...
            struct('Role', "Driver", 'RotationTokens', {{'E'}}, 'StartTime', 0.0), ...
            struct('Role', "OffField", 'RotationTokens', {{'Q', 'N1'}}, 'StartTime', boundarySwapTime)]);

    funnelResult = simulateTeamTimeline({xingqiu, xiangling}, funnelPlan, teamContext, enemy, struct());
    boundaryResult = simulateTeamTimeline({xingqiu, xiangling}, boundaryPlan, teamContext, enemy, struct());

    funnelEnergyTimeline = funnelResult.EnergyTimeline;
    boundaryEnergyTimeline = boundaryResult.EnergyTimeline;
    stayEnergySummary = stayResult.EnergySummary;
    funnelEnergySummary = funnelResult.EnergySummary;
    boundaryEnergySummary = boundaryResult.EnergySummary;

    assert(istable(stayEnergyTimeline) && istable(funnelEnergyTimeline) && istable(boundaryEnergyTimeline), ...
        'Team timeline should expose a structured energy timeline table.');
    assert(any(string(stayEnergyTimeline.EventType) == "ParticleCatch"), ...
        'Energy timeline should now record delayed particle catch events.');
    assert(any(string(funnelEnergyTimeline.EventType) == "ParticleCatch"), ...
        'Funnel timeline should also record delayed particle catch events.');
    assert(any(string(boundaryEnergyTimeline.EventType) == "ParticleCatch"), ...
        'Boundary funnel timeline should also record delayed particle catch events.');
    assert(any(string(stayEnergyTimeline.EventType) == "ParticleSpawn"), ...
        'Energy timeline should now expose particle spawn timing separately from catch timing.');
    assert(any(string(funnelEnergyTimeline.EventType) == "ParticleSpawn"), ...
        'Funnel timeline should also expose particle spawn timing separately from catch timing.');
    assert(any(string(boundaryEnergyTimeline.EventType) == "ParticleSpawn"), ...
        'Boundary funnel timeline should also expose particle spawn timing separately from catch timing.');

    funnelCatchRows = funnelEnergyTimeline(string(funnelEnergyTimeline.SourceCharacter) == "Xingqiu" ...
        & string(funnelEnergyTimeline.Action) == "E" ...
        & string(funnelEnergyTimeline.EventType) == "ParticleCatch", :);
    boundaryCatchRows = boundaryEnergyTimeline(string(boundaryEnergyTimeline.SourceCharacter) == "Xingqiu" ...
        & string(boundaryEnergyTimeline.Action) == "E" ...
        & string(boundaryEnergyTimeline.EventType) == "ParticleCatch", :);

    assert(~isempty(funnelCatchRows) && ~isempty(boundaryCatchRows), ...
        'Xingqiu skill should emit delayed catch rows in funnel and boundary-swap timelines.');
    staySpawnRows = stayEnergyTimeline(string(stayEnergyTimeline.SourceCharacter) == "Xingqiu" ...
        & string(stayEnergyTimeline.Action) == "E" ...
        & string(stayEnergyTimeline.EventType) == "ParticleSpawn", :);
    funnelSpawnRows = funnelEnergyTimeline(string(funnelEnergyTimeline.SourceCharacter) == "Xingqiu" ...
        & string(funnelEnergyTimeline.Action) == "E" ...
        & string(funnelEnergyTimeline.EventType) == "ParticleSpawn", :);
    boundarySpawnRows = boundaryEnergyTimeline(string(boundaryEnergyTimeline.SourceCharacter) == "Xingqiu" ...
        & string(boundaryEnergyTimeline.Action) == "E" ...
        & string(boundaryEnergyTimeline.EventType) == "ParticleSpawn", :);
    assert(~isempty(staySpawnRows) && ~isempty(funnelSpawnRows) && ~isempty(boundarySpawnRows), ...
        'Xingqiu skill should emit explicit spawn rows before the catch rows in every energy timeline sample.');
    assert(all(staySpawnRows.Time < stayCatchRows.Time) ...
        && all(funnelSpawnRows.Time < funnelCatchRows.Time) ...
        && all(boundarySpawnRows.Time < boundaryCatchRows.Time), ...
        'Energy packets should spawn before they can be caught.');
    assert(any(string(stayCatchRows.Recipient) == "Xingqiu") ...
            && any(string(stayCatchRows.Recipient) == "Xiangling"), ...
        'Delayed particle catch should still distribute some energy to off-field teammates.');
    assert(any(string(funnelCatchRows.Recipient) == "Xiangling"), ...
        'After a pre-catch swap, the foreground teammate should receive a catch row.');
    assert(any(string(boundaryCatchRows.Recipient) == "Xiangling"), ...
        'A swap that lands exactly on particle arrival should still credit the incoming foreground teammate.');

    stayXiangling = stayEnergySummary(string(stayEnergySummary.Character) == "Xiangling", :);
    funnelXiangling = funnelEnergySummary(string(funnelEnergySummary.Character) == "Xiangling", :);
    boundaryXiangling = boundaryEnergySummary(string(boundaryEnergySummary.Character) == "Xiangling", :);
    stayXingqiu = stayEnergySummary(string(stayEnergySummary.Character) == "Xingqiu", :);
    funnelXingqiu = funnelEnergySummary(string(funnelEnergySummary.Character) == "Xingqiu", :);
    boundaryXingqiu = boundaryEnergySummary(string(boundaryEnergySummary.Character) == "Xingqiu", :);

    assert(~isempty(stayXiangling) && ~isempty(funnelXiangling) && ~isempty(boundaryXiangling) ...
        && ~isempty(stayXingqiu) && ~isempty(funnelXingqiu) && ~isempty(boundaryXingqiu), ...
        'Energy summary should keep both members across all energy timing samples.');
    assert(funnelXiangling.EndEnergy > stayXiangling.EndEnergy, ...
        'Front-loading a swap before particle arrival should increase the funnel target''s ending energy.');
    assert(funnelXingqiu.EndEnergy < stayXingqiu.EndEnergy, ...
        'Handing particles to a teammate should reduce the original owner''s ending energy.');
    assert(sum(stayCatchRows.DeltaEnergy(string(stayCatchRows.Recipient) == "Xingqiu")) ...
            > sum(stayCatchRows.DeltaEnergy(string(stayCatchRows.Recipient) == "Xiangling")), ...
        'Without a pre-catch swap, the original on-field owner should receive the larger share of same-element particles.');
    assert(sum(funnelCatchRows.DeltaEnergy(string(funnelCatchRows.Recipient) == "Xiangling")) ...
            > sum(funnelCatchRows.DeltaEnergy(string(funnelCatchRows.Recipient) == "Xingqiu")), ...
        'After a pre-catch swap, the new foreground teammate should receive the larger share of the caught particles.');
    assert(sum(boundaryCatchRows.DeltaEnergy(string(boundaryCatchRows.Recipient) == "Xiangling")) ...
            > sum(boundaryCatchRows.DeltaEnergy(string(boundaryCatchRows.Recipient) == "Xingqiu")), ...
        'Particles that arrive exactly on the swap boundary should now funnel to the incoming foreground teammate.');
    boundaryXianglingCatch = sum(boundaryCatchRows.DeltaEnergy(string(boundaryCatchRows.Recipient) == "Xiangling"));
    funnelXianglingCatch = sum(funnelCatchRows.DeltaEnergy(string(funnelCatchRows.Recipient) == "Xiangling"));
    boundaryXingqiuCatch = sum(boundaryCatchRows.DeltaEnergy(string(boundaryCatchRows.Recipient) == "Xingqiu"));
    funnelXingqiuCatch = sum(funnelCatchRows.DeltaEnergy(string(funnelCatchRows.Recipient) == "Xingqiu"));
    assert(abs(boundaryXianglingCatch - funnelXianglingCatch) < 1e-9 ...
        && abs(boundaryXingqiuCatch - funnelXingqiuCatch) < 1e-9 ...
        && boundaryXingqiu.EndEnergy < stayXingqiu.EndEnergy, ...
        'Boundary-time swaps should now funnel the same catch shares as an already-established front-loaded swap.');
    assert(stayResult.LoopReadiness < 1 && funnelResult.LoopReadiness < 1, ...
        'Zero-start energy timelines should not be misreported as fully loop-ready.');
    assert(all(ismember(["NextBurstWindowTime", "EarliestBurstReadyTime", "CanBurstOnNextWindow", "NextWindowReadiness"], ...
        string(funnelEnergySummary.Properties.VariableNames))), ...
        'Energy summary should expose next-window burst readiness columns for timeline-level loop checks.');
    assert(~funnelResult.CanLoopNextCycle && ~funnelXiangling.CanBurstOnNextWindow, ...
        'Loop readiness should now fail when the next planned burst window arrives before the burst energy is actually restored.');
    assert(isfinite(funnelXiangling.NextBurstWindowTime) && funnelXiangling.NextBurstWindowTime > 20, ...
        'Next burst window should be projected into the following cycle rather than staying pinned to the current rotation horizon.');
    assert(funnelXiangling.EarliestBurstReadyTime > funnelXiangling.NextBurstWindowTime, ...
        'The timeline-level loop check should record when energy becomes ready after the next burst window has already passed.');

    disp('validateTeamEnergyCatchRegression passed');
end
