function validateNahidaTriggeredTimelineRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    nahida = getDefaultCharacterConfig('Nahida');
    barbara = getDefaultCharacterConfig('Barbara');
    teamContext = buildTeamContext({nahida, barbara}, 10, struct('ReactionMode', "Realistic"), enemy);

    rotationPlan = struct( ...
        'RotationDuration', 10, ...
        'MemberPlans', [ ...
            struct('Role', "Support", 'RotationTokens', {{'E'}}, 'StartTime', 0.00), ...
            struct('Role', "Driver", 'RotationTokens', {{'N1', 'N1', 'N1'}}, 'StartTime', 0.80)]);

    result = simulateTeamTimeline({nahida, barbara}, rotationPlan, teamContext, enemy, struct());
    timeline = result.TimelineTable;

    nahidaERows = timeline(string(timeline.Character) == "Nahida" & string(timeline.Action) == "E", :);
    triKarmaRows = timeline(strcmp(string(timeline.Action), "TriKarmaTick"), :);
    triKarmaEffectRows = timeline(contains(string(timeline.Action), "TriKarmaTick#") ...
        | (string(timeline.Character) == "Nahida" & string(timeline.SourceType) == "EffectTick"), :);
    timedBloomRows = timeline(strcmp(string(timeline.SourceType), "TimedReaction") ...
        & strcmp(string(timeline.Action), "Bloom") ...
        & strcmp(string(timeline.TriggerPacketSource), "DendroCore"), :);

    assert(height(nahidaERows) == 1 ...
        && all(string(nahidaERows.BackgroundDriverMode) == "ReactionEventTrigger"), ...
        'Nahida Seed of Skandha should expose a pure reaction-triggered background window.');
    assert(isempty(triKarmaEffectRows), ...
        'Nahida team timeline should not pre-expand Tri-Karma as autonomous periodic EffectTick rows.');
    assert(any(strcmp(string(triKarmaRows.TriggerPacketSource), "DirectHitReaction") ...
            & strcmp(string(triKarmaRows.TriggerSourceCharacter), "Barbara")), ...
        'Direct Bloom reactions should still trigger one explicit Tri-Karma follow-up.');
    assert(~isempty(timedBloomRows), ...
        'Barbara Bloom cores should still surface as timed reaction rows in the shared team timeline.');

    timedTriKarmaRows = triKarmaRows(strcmp(string(triKarmaRows.TriggerPacketSource), "DendroCore"), :);
    assert(height(timedTriKarmaRows) == 1 ...
        && timedTriKarmaRows.StartTime(1) > timedBloomRows.StartTime(1) ...
        && strcmp(string(timedTriKarmaRows.TriggerSourceCharacter(1)), "Barbara"), ...
        'Timed Bloom core damage should feed back into the Nahida reaction-triggered follow-up window.');

    disp('validateNahidaTriggeredTimelineRegression passed');
end
