function validateNicoleRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    nicole = getDefaultCharacterConfig('Nicole', struct('Constellation', 2));
    teamContext = buildTeamContext({nicole}, 20, struct('ReactionMode', "Realistic"), enemy);

    sharedNicoleDMGBonus = getFieldOrDefault(teamContext, 'NicoleApproxSharedAllDMGBonus', 0);
    assert(sharedNicoleDMGBonus > 0, ...
        'Nicole support context should expose a shared weapon-driven DMG bonus.');
    assert(abs(getFieldOrDefault(teamContext, 'NicoleWeaponActiveDMGBonus', 0) - sharedNicoleDMGBonus) < 1e-9, ...
        'Nicole shared DMG bonus should match the active weapon bonus approximation.');
    assert(getFieldOrDefault(teamContext, 'AllDMGBonus', 0) >= sharedNicoleDMGBonus, ...
        'Nicole shared weapon bonus should flow into teamContext.AllDMGBonus.');

    noWeaponContext = teamContext;
    noWeaponContext.AllDMGBonus = getFieldOrDefault(noWeaponContext, 'AllDMGBonus', 0) - sharedNicoleDMGBonus;
    noWeaponContext.NicoleApproxSharedAllDMGBonus = 0;

    [nicoleDamageWith, ~] = simulateNicoleDPS( ...
        nicole.Build, enemy, nicole.RotationFile, nicole.TalentLevel, nicole.Constellation, teamContext);
    [nicoleDamageWithout, ~] = simulateNicoleDPS( ...
        nicole.Build, enemy, nicole.RotationFile, nicole.TalentLevel, nicole.Constellation, noWeaponContext);
    assert(abs(nicoleDamageWith - nicoleDamageWithout) < 1e-6 * max(1, abs(nicoleDamageWith)), ...
        'Nicole self simulation should strip the shared approximation to avoid double-counting weapon DMG bonus.');

    disp('validateNicoleRegression passed');
end
