function validateTeamPostCycleEnergyProjectionRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    amber = getDefaultCharacterConfig('Amber');
    amber.StartEnergy = 40;
    amber.Build.ER = 5.0;

    teamContext = buildTeamContext({amber}, 20, struct('ReactionMode', "Realistic"), enemy);
    rotationPlan = struct( ...
        'RotationDuration', 20, ...
        'MemberPlans', struct( ...
            'Role', "Driver", ...
            'RotationTokens', {{'Q', 'E'}}, ...
            'StartTime', 18.60));

    result = simulateTeamTimeline({amber}, rotationPlan, teamContext, enemy, struct());
    energySummary = result.EnergySummary;
    energyTimeline = result.EnergyTimeline;

    amberSummary = energySummary(string(energySummary.Character) == "Amber", :);
    projectedCatchRows = energyTimeline(string(energyTimeline.SourceCharacter) == "Amber" ...
        & string(energyTimeline.Action) == "E" ...
        & string(energyTimeline.EventType) == "ParticleCatch", :);

    assert(~isempty(amberSummary), ...
        'Single-member late-energy regression should keep Amber in the energy summary.');
    assert(~isempty(projectedCatchRows), ...
        'Late Amber particles should now remain visible as projected catch rows after the rotation end.');
    assert(all(projectedCatchRows.Time > 20), ...
        'Projected post-cycle catch rows should land strictly after the original rotation horizon.');
    assert(amberSummary.EndEnergy == 0, ...
        'EndEnergy should continue to represent the actual energy at the original rotation end, before projected late catches.');
    assert(isfinite(amberSummary.EarliestBurstReadyTime) ...
        && amberSummary.EarliestBurstReadyTime >= min(projectedCatchRows.Time) - 1e-9, ...
        'Loop readiness should now account for the first post-cycle particle catch when computing burst-ready timing.');
    assert(amberSummary.CanBurstOnNextWindow && result.CanLoopNextCycle ...
        && amberSummary.NextWindowReadiness == 1, ...
        'A late self-caught skill should now allow Amber to loop the next burst window.');
    assert(amberSummary.NextBurstWindowTime > 20 ...
        && amberSummary.EarliestBurstReadyTime < amberSummary.NextBurstWindowTime, ...
        'Projected late particles should refill energy before Amber''s next repeated burst window.');

    disp('validateTeamPostCycleEnergyProjectionRegression passed');
end
