function validateLisaRegression()
    initProjectPaths();

    singleEnemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);
    multiEnemy = singleEnemy;
    multiEnemy.EnemyCount = 3;
    multiEnemy.TargetCount = 3;

    cfg4 = getDefaultCharacterConfig('Lisa', struct('Constellation', 4, 'TalentLevel', 10));
    cfg6 = getDefaultCharacterConfig('Lisa', struct('Constellation', 6, 'TalentLevel', 10));
    ctx4 = buildTeamContext({cfg4}, 20, struct('ReactionMode', "Realistic"), singleEnemy);
    ctx4Multi = buildTeamContext({cfg4}, 20, struct('ReactionMode', "Realistic"), multiEnemy);
    ctx6 = buildTeamContext({cfg6}, 20, struct('ReactionMode', "Realistic"), singleEnemy);

    [damage4, ~, breakdown4, rotationTime4, audit4] = simulateLisaDPS( ...
        cfg4.Build, singleEnemy, "", cfg4.TalentLevel, cfg4.Constellation, ctx4);
    [damage4Multi, ~, breakdown4Multi] = simulateLisaDPS( ...
        cfg4.Build, multiEnemy, "", cfg4.TalentLevel, cfg4.Constellation, ctx4Multi);
    [damage6, ~, breakdown6, rotationTime6, audit6] = simulateLisaDPS( ...
        cfg6.Build, singleEnemy, "", cfg6.TalentLevel, cfg6.Constellation, ctx6);

    actions4 = string(breakdown4.Action);
    actions4Multi = string(breakdown4Multi.Action);
    actions6 = string(breakdown6.Action);
    q4 = breakdown4(actions4 == "Q", :);
    q4Multi = breakdown4Multi(actions4Multi == "Q", :);
    holdRows6 = breakdown6(actions6 == "EHold", :);
    c6EntryRows = breakdown6(actions6 == "C6Entry", :);

    assert(damage4 > 0 && damage4Multi > 0 && rotationTime4 > 0 && damage6 > 0 && rotationTime6 > 0, ...
        'Lisa regression should produce positive damage and rotation time for both C4 and C6.');
    assert(height(q4) == 1 && contains(string(q4.Note), "x12"), ...
        'Lisa single-target C4 regression should keep one Lightning Rose bolt per tick.');
    assert(height(q4Multi) == 1 && contains(string(q4Multi.Note), "x36"), ...
        'Lisa multi-target C4 regression should scale Lightning Rose to three bolts per tick.');
    assert(isequal(actions6', ["C6Entry", "EHold", "Q", "CA", "ETap", "EHold"]), ...
        'Lisa C6 regression should preserve the explicit field-entry setup and dynamic hold-E routing.');
    assert(height(c6EntryRows) == 1 && contains(string(c6EntryRows.Note), "conductive x3"), ...
        'Lisa C6 regression should expose the explicit field-entry conductive setup row.');
    assert(height(holdRows6) == 2 ...
        && contains(string(holdRows6.Note(1)), "3 stack") ...
        && contains(string(holdRows6.Note(2)), "2 stack"), ...
        'Lisa C6 regression should route hold-E damage through the current conductive stack state.');
    assert(~any(audit4.Rows.ApplyGaugeFallback | audit4.Rows.ICDFallback) ...
        && ~any(audit6.Rows.ApplyGaugeFallback | audit6.Rows.ICDFallback), ...
        'Lisa regression should keep explicit gauge and ICD metadata for the scripted rotation.');

    disp('validateLisaRegression passed');
end
