function validateTeamSameTimestampTimedReactionOrderingRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    lisa = getDefaultCharacterConfig('Lisa');
    barbara = getDefaultCharacterConfig('Barbara');
    kaeya = getDefaultCharacterConfig('Kaeya');
    teamContext = buildTeamContext({lisa, barbara, kaeya}, 20, struct('ReactionMode', "Realistic"), enemy);

    rotationPlan = struct( ...
        'RotationDuration', 20, ...
        'MemberPlans', [ ...
            struct('Role', "Support", 'RotationTokens', {{'N1'}}, 'StartTime', 0.0), ...
            struct('Role', "Driver", 'RotationTokens', {{'N1'}}, 'StartTime', 0.0), ...
            struct('Role', "Driver", 'RotationTokens', {{'N1'}}, 'StartTime', 1.0)]);

    result = simulateTeamTimeline({lisa, barbara, kaeya}, rotationPlan, teamContext, enemy, struct());
    timeline = result.TimelineTable;
    sharedTimeRows = timeline(abs(double(timeline.StartTime) - 1.0) <= 1e-9, :);

    assert(height(sharedTimeRows) >= 2, ...
        'Regression should surface both the timed Electro-Charged tick and the incoming foreground action on the same timestamp.');
    assert(string(sharedTimeRows.SourceType(1)) == "TimedReaction" ...
            && string(sharedTimeRows.Action(1)) == "ElectroCharged", ...
        'A timed reaction that resolves at the frame boundary should stay ahead of the member action it was processed before.');
    assert(string(sharedTimeRows.SourceType(2)) == "MemberAction" ...
            && string(sharedTimeRows.Character(2)) == "Kaeya" ...
            && string(sharedTimeRows.Action(2)) == "N1", ...
        'The foreground action should remain immediately after the already-resolved timed reaction on the shared timestamp.');

    disp('validateTeamSameTimestampTimedReactionOrderingRegression passed');
end
