function validateTeamSameTimestampEffectTickOrderingRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    kuki = getDefaultCharacterConfig('KukiShinobu');
    barbara = getDefaultCharacterConfig('Barbara');
    teamContext = buildTeamContext({kuki, barbara}, 20, struct('ReactionMode', "Realistic"), enemy);

    rotationPlan = struct( ...
        'RotationDuration', 20, ...
        'MemberPlans', [ ...
            struct('Role', "Support", 'RotationTokens', {{'E'}}, 'StartTime', 0.0), ...
            struct('Role', "Driver", 'RotationTokens', {{'N1'}}, 'StartTime', 1.5)]);

    result = simulateTeamTimeline({kuki, barbara}, rotationPlan, teamContext, enemy, struct());
    timeline = result.TimelineTable;
    sharedTimeRows = timeline(abs(double(timeline.StartTime) - 1.5) <= 1e-9, :);

    assert(height(sharedTimeRows) >= 2, ...
        'Same-timestamp regression should surface both the pre-existing ring tick and the incoming foreground normal.');
    assert(string(sharedTimeRows.SourceType(1)) == "EffectTick" ...
            && startsWith(string(sharedTimeRows.Action(1)), "RingTick"), ...
        'An already-scheduled autonomous tick should resolve before a newly-started foreground action at the same timestamp.');
    assert(string(sharedTimeRows.SourceType(2)) == "MemberAction" ...
            && string(sharedTimeRows.Character(2)) == "Barbara" ...
            && string(sharedTimeRows.Action(2)) == "N1", ...
        'The foreground normal should still resolve immediately after the autonomous tick on the shared timestamp.');
    assert(sum(string(sharedTimeRows.Reaction) == "ElectroCharged") == 1, ...
        'Same-timestamp ordering should avoid double-counting Electro-Charged from a pre-existing tick and the incoming Hydro normal on the same frame.');

    disp('validateTeamSameTimestampEffectTickOrderingRegression passed');
end
