function validateKaeyaRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cfg0 = getDefaultCharacterConfig('Kaeya', struct('Constellation', 0, 'TalentLevel', 10));
    cfg6 = getDefaultCharacterConfig('Kaeya', struct('Constellation', 6, 'TalentLevel', 10));
    ctx0 = buildTeamContext({cfg0}, 20, struct('ReactionMode', "Realistic"), enemy);
    ctx6 = buildTeamContext({cfg6}, 20, struct('ReactionMode', "Realistic"), enemy);

    [damage0, ~, breakdown0, rotationTime0, audit0] = simulateKaeyaDPS( ...
        cfg0.Build, enemy, cfg0.RotationFile, cfg0.TalentLevel, cfg0.Constellation, ctx0);
    [damage6, ~, breakdown6, rotationTime6, audit6] = simulateKaeyaDPS( ...
        cfg6.Build, enemy, cfg6.RotationFile, cfg6.TalentLevel, cfg6.Constellation, ctx6);

    actions0 = string(breakdown0.Action);
    q0 = breakdown0(actions0 == "Q", :);
    q6 = breakdown6(string(breakdown6.Action) == "Q", :);
    ca0 = breakdown0(actions0 == "CA", :);

    assert(damage0 > 0 && rotationTime0 > 0 && damage6 > 0 && rotationTime6 > 0, ...
        'Kaeya regression should produce positive damage and rotation time for both C0 and C6.');
    assert(isequal(actions0', ["E", "Q", "N1", "N2", "N3", "CA"]), ...
        'Kaeya regression should preserve the Frostgnaw -> Glacial Waltz -> physical string order.');
    assert(height(q0) == 1 && contains(string(q0.Note), "x8"), ...
        'Kaeya C0 burst regression should keep the 8-tick Glacial Waltz note.');
    assert(height(q6) == 1 && contains(string(q6.Note), "x9"), ...
        'Kaeya C6 burst regression should keep the extra Glacial Waltz tick.');
    assert(height(ca0) == 1 && contains(string(ca0.Note), "x2"), ...
        'Kaeya charged attack regression should keep the 2-hit physical note.');
    assert(damage6 > damage0, ...
        'Kaeya C6 regression should outdamage the C0 script through the extra burst tick.');
    assert(~any(audit0.Rows.ApplyGaugeFallback | audit0.Rows.ICDFallback) ...
        && ~any(audit6.Rows.ApplyGaugeFallback | audit6.Rows.ICDFallback), ...
        'Kaeya regression should keep explicit gauge and ICD metadata for the scripted rotation.');

    disp('validateKaeyaRegression passed');
end
