function validateTeamTimelineFrozenShatterRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false);

    barbara = getDefaultCharacterConfig('Barbara');
    kaeya = getDefaultCharacterConfig('Kaeya');
    razor = getDefaultCharacterConfig('Razor');
    teamContext = buildTeamContext({barbara, kaeya, razor}, 18, struct('ReactionMode', "Realistic"), enemy);

    rotationPlan = struct( ...
        'RotationDuration', 18, ...
        'MemberPlans', [ ...
            struct('Role', "Support", 'RotationTokens', {{'E'}}, 'StartTime', 0.00), ...
            struct('Role', "Support", 'RotationTokens', {{'Q'}}, 'StartTime', 0.60), ...
            struct('Role', "Driver", 'RotationTokens', {{'N1', 'N2', 'N3'}}, 'StartTime', 1.60)]);

    result = simulateTeamTimeline({barbara, kaeya, razor}, rotationPlan, teamContext, enemy, struct());
    timeline = result.TimelineTable;

    frozenRows = timeline(contains(string(timeline.Reaction), "Frozen", 'IgnoreCase', true), :);
    shatterRows = timeline(contains(string(timeline.Reaction), "Shatter", 'IgnoreCase', true), :);
    razorRows = timeline(string(timeline.Character) == "Razor", :);

    assert(~isempty(frozenRows), ...
        'Barbara -> Kaeya setup should create a Frozen state in the team timeline.');
    assert(~isempty(shatterRows), ...
        'A claymore foreground combo should shatter an existing Frozen target in the team timeline.');
    assert(any(string(shatterRows.Character) == "Razor" & string(shatterRows.Action) == "N1"), ...
        'Razor N1 should be able to trigger the first Shatter after Kaeya freezes the target.');
    assert(any(contains(string(razorRows.Reaction), "Shatter", 'IgnoreCase', true)), ...
        'Razor foreground rows should surface Shatter instead of silently consuming Frozen state.');

    firstFrozenGauge = frozenRows.FrozenGauge(1);
    firstShatterGauge = shatterRows.FrozenGauge(1);
    assert(firstFrozenGauge > firstShatterGauge, ...
        'Frozen gauge should decrease after the first Shatter trigger.');

    disp('validateTeamTimelineFrozenShatterRegression passed');
end
