function validateVentiRegression()
    initProjectPaths();

    baseEnemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cfg = getDefaultCharacterConfig('Venti', struct('TalentLevel', 10, 'Constellation', 0));
    amber = getDefaultCharacterConfig('Amber');
    barbara = getDefaultCharacterConfig('Barbara');
    build = cfg.Build;
    build.PyroDMGBonus = 0.80;
    build.HydroDMGBonus = 0.00;

    pyroEnemy = baseEnemy;
    pyroEnemy.InitialAuraElement = "Pyro";
    pyroEnemy.InitialAuraGauge = 1.0;
    priorityContext = buildTeamContext({cfg, amber, barbara}, 20, struct('ReactionMode', "Realistic"), pyroEnemy);
    hydroOnlyContext = buildTeamContext({cfg, barbara}, 20, struct('ReactionMode', "Realistic"), baseEnemy);
    overrideEnemy = baseEnemy;
    overrideEnemy.InitialAuraElement = "Hydro";
    overrideContext = buildTeamContext({cfg, amber, barbara}, 20, struct('ReactionMode', "Realistic"), overrideEnemy);
    approximateEnemy = baseEnemy;
    approximateEnemy.ReactionMode = "Approximate";
    approximateEnemy.AutoSupportAura = true;
    approximateContext = buildTeamContext({cfg, amber, barbara}, 20, struct('ReactionMode', "Approximate"), approximateEnemy);

    [priorityDamage, ~, priorityBreakdown, priorityTime, priorityAudit] = simulateVentiDPS( ...
        build, pyroEnemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, priorityContext);
    [hydroOnlyDamage, ~, hydroOnlyBreakdown, hydroOnlyTime] = simulateVentiDPS( ...
        build, baseEnemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, hydroOnlyContext);
    [overrideDamage, ~, overrideBreakdown, overrideTime, overrideAudit] = simulateVentiDPS( ...
        build, overrideEnemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, overrideContext);
    [approximateDamage, ~, approximateBreakdown, approximateTime] = simulateVentiDPS( ...
        build, approximateEnemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, approximateContext);

    priorityActions = string(priorityBreakdown.Action);
    priorityInfuse = priorityBreakdown(priorityActions == "QInfuse", :);
    hydroOnlyInfuse = hydroOnlyBreakdown(string(hydroOnlyBreakdown.Action) == "QInfuse", :);
    overrideInfuse = overrideBreakdown(string(overrideBreakdown.Action) == "QInfuse", :);
    approximateInfuse = approximateBreakdown(string(approximateBreakdown.Action) == "QInfuse", :);

    assert(priorityDamage > 0 && priorityTime > 0 && hydroOnlyDamage > 0 && hydroOnlyTime > 0 ...
        && overrideDamage > 0 && overrideTime > 0 && approximateDamage > 0 && approximateTime > 0, ...
        'Venti regression should produce positive damage and rotation time.');
    assert(isequal(priorityActions', ["EHold", "QDot", "QInfuse", "E"]), ...
        'Venti regression should preserve the hold E -> burst -> infuse -> tap E order.');
    assert(height(priorityInfuse) == 1 && height(hydroOnlyInfuse) == 1 ...
        && height(overrideInfuse) == 1 && height(approximateInfuse) == 1, ...
        'Venti regression should isolate one absorbed-element row per scripted rotation.');
    assert(hydroOnlyInfuse.Damage == 0, ...
        'Venti realistic Hydro-only regression should not absorb an element without an explicit enemy aura.');
    assert(priorityInfuse.Damage > overrideInfuse.Damage, ...
        'Venti regression should prefer Pyro over Hydro when no initial aura override is present.');
    assert(overrideInfuse.Damage > hydroOnlyInfuse.Damage, ...
        'Venti explicit Hydro-aura regression should outdamage the realistic Hydro-only team context.');
    assert(approximateInfuse.Damage > priorityInfuse.Damage, ...
        'Venti approximate-mode regression should preserve the team-priority absorption fallback and its support-aura damage upside.');
    assert(~any(priorityAudit.Rows.ApplyGaugeFallback | priorityAudit.Rows.ICDFallback) ...
        && ~any(overrideAudit.Rows.ApplyGaugeFallback | overrideAudit.Rows.ICDFallback), ...
        'Venti regression should keep explicit gauge and ICD metadata for the scripted rotation.');

    diluc = getDefaultCharacterConfig('Diluc');
    hydroTimelineContext = buildTeamContext({cfg, diluc, barbara}, 20, struct('ReactionMode', "Approximate"), approximateEnemy);
    [hydroTimelineDamage, ~, hydroTimelineBreakdown] = simulateVentiDPS( ...
        build, approximateEnemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, hydroTimelineContext);
    hydroTimelineInfuse = hydroTimelineBreakdown(string(hydroTimelineBreakdown.Action) == "QInfuse", :);
    hydroTimelinePlan = planTeamRotation({cfg, diluc, barbara}, 20, baseEnemy, struct('ReactionMode', "Realistic"), struct());
    hydroTimelineRealContext = buildTeamContext({cfg, diluc, barbara}, 20, struct('ReactionMode', "Realistic"), baseEnemy);
    hydroTimelineResult = simulateTeamTimeline({cfg, diluc, barbara}, hydroTimelinePlan, hydroTimelineRealContext, baseEnemy, struct());
    hydroTimelineRows = hydroTimelineResult.TimelineTable;
    hydroTimelineBurstRows = hydroTimelineRows(string(hydroTimelineRows.Character) == "Venti" ...
        & string(hydroTimelineRows.SourceType) == "MemberAction" ...
        & string(hydroTimelineRows.Action) == "Q", :);
    hydroTimelineTickRows = hydroTimelineRows(string(hydroTimelineRows.Character) == "Venti" ...
        & string(hydroTimelineRows.SourceType) == "EffectTick" ...
        & startsWith(string(hydroTimelineRows.Action), "QDot"), :);
    hydroTimelineOrder = string(hydroTimelinePlan.ExecutionTable.Character);
    hydroTimelineVentiTokens = string(hydroTimelinePlan.MemberPlans(1).RotationTokens);
    hydroDilucEnemy = baseEnemy;
    hydroDilucEnemy.InitialAuraElement = "Hydro";
    hydroDilucEnemy.InitialAuraGauge = 1.0;
    hydroDilucContext = buildTeamContext({cfg, diluc, barbara}, 20, struct('ReactionMode', "Realistic"), hydroDilucEnemy);
    [~, ~, hydroDilucBreakdown] = simulateVentiDPS( ...
        build, hydroDilucEnemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, hydroDilucContext);
    hydroDilucInfuse = hydroDilucBreakdown(string(hydroDilucBreakdown.Action) == "QInfuse", :);
    pyroDilucEnemy = baseEnemy;
    pyroDilucEnemy.InitialAuraElement = "Pyro";
    pyroDilucEnemy.InitialAuraGauge = 1.0;
    pyroDilucContext = buildTeamContext({cfg, diluc, barbara}, 20, struct('ReactionMode', "Realistic"), pyroDilucEnemy);
    [~, ~, pyroDilucBreakdown] = simulateVentiDPS( ...
        build, pyroDilucEnemy, cfg.RotationFile, cfg.TalentLevel, cfg.Constellation, pyroDilucContext);
    pyroDilucInfuse = pyroDilucBreakdown(string(pyroDilucBreakdown.Action) == "QInfuse", :);

    assert(hydroTimelineDamage > 0 && height(hydroTimelineInfuse) == 1, ...
        'Venti timeline-derived approximate regression should keep one positive absorbed-element burst row.');
    assert(find(hydroTimelineOrder == "Barbara", 1, 'first') < find(hydroTimelineOrder == "Venti", 1, 'first'), ...
        'Team auto-planning should place a practical aura applicator before Venti when burst absorption depends on pre-existing aura.');
    assert(numel(hydroTimelineVentiTokens) == 2 ...
        && isequal(hydroTimelineVentiTokens(:)', ["EHold", "Q"]) ...
        && ~any(ismember(hydroTimelineVentiTokens, ["QDot", "QInfuse"])), ...
        'Venti team auto-planning should now use only the public hold skill and burst tokens in the foreground plan.');
    assert(~isempty(hydroTimelineBurstRows) && hydroTimelineBurstRows.Order(1) > 1 ...
        && contains(string(hydroTimelineRows.AuraState(hydroTimelineBurstRows.Order(1) - 1)), "Hydro:", 'IgnoreCase', true), ...
        'The realistic team timeline should preserve a Hydro aura immediately before Venti''s first burst row.');
    assert(height(hydroTimelineTickRows) >= 18 ...
        && all(string(hydroTimelineTickRows.ActionClass) == "FollowUp") ...
        && all(string(hydroTimelineTickRows.BackgroundDriverMode) == "AutonomousTick") ...
        && hydroTimelineTickRows.StartTime(1) > hydroTimelineBurstRows.StartTime(1), ...
        'Venti team timeline should expand the public burst token into autonomous QDot follow-up ticks.');
    assert(hydroTimelineInfuse.Damage < approximateInfuse.Damage, ...
        'Venti approximate absorption should now react to the planned team timeline instead of treating every mixed Hydro/Pyro team as the same static priority case.');
    assert(height(hydroDilucInfuse) == 1 && height(pyroDilucInfuse) == 1 ...
        && hydroTimelineInfuse.Damage < pyroDilucInfuse.Damage ...
        && abs(hydroTimelineInfuse.Damage - hydroDilucInfuse.Damage) ...
            < abs(hydroTimelineInfuse.Damage - pyroDilucInfuse.Damage), ...
        ['Timeline-derived approximate absorption should follow the Hydro aura preserved at the burst boundary ' ...
         'instead of collapsing back to the static Pyro team-priority fallback.']);

    disp('validateVentiRegression passed');
end
