function validateIllugaRegression()
    initProjectPaths();

    enemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 2, ...
        'TargetCount', 2);

    cfgC1 = getDefaultCharacterConfig('Illuga', struct('Constellation', 1));
    cfgC2 = getDefaultCharacterConfig('Illuga', struct('Constellation', 2));
    teamContextC1 = buildTeamContext({cfgC1}, 20, struct('ReactionMode', "Realistic"), enemy);
    teamContextC2 = buildTeamContext({cfgC2}, 20, struct('ReactionMode', "Realistic"), enemy);

    [damageC1, ~, breakdownC1] = simulateIllugaDPS( ...
        cfgC1.Build, enemy, cfgC1.RotationFile, cfgC1.TalentLevel, cfgC1.Constellation, teamContextC1);
    [damageC2, ~, breakdownC2] = simulateIllugaDPS( ...
        cfgC2.Build, enemy, cfgC2.RotationFile, cfgC2.TalentLevel, cfgC2.Constellation, teamContextC2);

    assert(damageC2 > damageC1, ...
        'Illuga C2 should outperform C1 in the default burst rotation.');
    assert(any(contains(string(breakdownC2.Action), "SongBoost")), ...
        'Illuga breakdown should include the Nightingale''s Song proxy action.');
    assert(any(contains(string(breakdownC2.Action), "C2Aedon")), ...
        'Illuga C2 breakdown should include the Aedon follow-up action.');

    disp('validateIllugaRegression passed');
end
