function validateSethosRegression()
    initProjectPaths();

    baseEnemy = struct( ...
        'Level', 90, ...
        'Res', 0.10, ...
        'DefReduct', 0, ...
        'ReactionMode', "Realistic", ...
        'AutoSupportAura', false, ...
        'EnemyCount', 1, ...
        'TargetCount', 1);

    cfg = getDefaultCharacterConfig('Sethos', struct('Constellation', 0));

    [damageC0, ~, breakdownC0] = simulateSethosDPS( ...
        cfg.Build, baseEnemy, cfg.RotationFile, cfg.TalentLevel, 0, []);
    [damageC1, ~, breakdownC1] = simulateSethosDPS( ...
        cfg.Build, baseEnemy, cfg.RotationFile, cfg.TalentLevel, 1, []);

    assert(damageC1 > damageC0, ...
        'Sethos C1 should increase damage relative to C0 for the default rotation.');
    assert(any(contains(string(breakdownC1.Note), "C1 x")), ...
        'Sethos C1 rotation should expose the Electro DMG stack note.');
    assert(~any(contains(string(breakdownC0.Note), "C1 x")), ...
        'Sethos C0 rotation should not expose the C1 stack note.');

    multiTargetEnemy = baseEnemy;
    multiTargetEnemy.EnemyCount = 2;
    multiTargetEnemy.TargetCount = 2;
    [damageC3, ~] = simulateSethosDPS( ...
        cfg.Build, multiTargetEnemy, cfg.RotationFile, cfg.TalentLevel, 3, []);
    [damageC4, ~, breakdownC4] = simulateSethosDPS( ...
        cfg.Build, multiTargetEnemy, cfg.RotationFile, cfg.TalentLevel, 4, []);

    assert(damageC4 > damageC3, ...
        'Sethos C4 should increase damage on multi-target rotations via the EM share window.');
    assert(any(contains(string(breakdownC4.Note), "C4 team EM")), ...
        'Sethos C4 rotation should expose the EM-share note on qualifying hits.');

    disp('validateSethosRegression passed');
end
