function [totalDMG, dps, breakdown, rotationTime, audit] = simulateDilucDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % 迪卢克高精度近似模拟�?    % 建模要点�?    % 1. E 三段分开建模，并显式处理 C4“节奏释放”额�?40%�?    % 2. Q 拆为起手斩、凤凰路径持续伤、终点爆炸，并开启火附魔窗；
    % 3. 附魔期间普攻视为火伤，A4 额外火伤加成始终写入该窗口；
    % 4. C6 �?E 后两次普攻增伤单独拆成动作，避免直接粗暴平均�?    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Diluc', 'rotation_Diluc.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Diluc', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    vapeReady = getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1 || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1;
    burstInfuseBonus = 0.20;
    c1DamageBonus = 0.15 * double(constellation >= 1);
    c2AtkBonus = 0.30 * double(constellation >= 2);
    c6NormalBonus = 0.30 * double(constellation >= 6);

    actions = struct();
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BurstWindowDamageBonus', burstInfuseBonus, ...
        'BaseActionDamageBonus', c1DamageBonus + c6NormalBonus, 'ATKWeight', c2AtkBonus, 'Note', "Infused normal 1");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BurstWindowDamageBonus', burstInfuseBonus, ...
        'BaseActionDamageBonus', c1DamageBonus + c6NormalBonus, 'ATKWeight', c2AtkBonus, 'Note', "Infused normal 2");
    actions.N3 = struct('TalentGroup', "Normal", 'Param', "x3HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BurstWindowDamageBonus', burstInfuseBonus, ...
        'BaseActionDamageBonus', c1DamageBonus + c6NormalBonus, 'ATKWeight', c2AtkBonus, 'Note', "Infused normal 3");
    actions.N4 = struct('TalentGroup', "Normal", 'Param', "x4HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BurstWindowDamageBonus', burstInfuseBonus, ...
        'BaseActionDamageBonus', c1DamageBonus + c6NormalBonus, 'ATKWeight', c2AtkBonus, 'Note', "Infused normal 4");
    actions.NA6A = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BurstWindowDamageBonus', burstInfuseBonus, ...
        'BaseActionDamageBonus', c1DamageBonus + c6NormalBonus, 'ATKWeight', c2AtkBonus, ...
        'Note', "C6 empowered normal after E");
    actions.NA6B = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BurstWindowDamageBonus', burstInfuseBonus, ...
        'BaseActionDamageBonus', c1DamageBonus + c6NormalBonus, 'ATKWeight', c2AtkBonus, ...
        'Note', "C6 empowered normal after E");
    actions.E1 = struct('TalentGroup', "Skill", 'Param', "x1HitDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', c1DamageBonus, ...
        'ATKWeight', c2AtkBonus, 'AllowAmplify', double(vapeReady), ...
        'LunarisAttackName', "FireCross_Strike", 'LunarisDamageParam', "Damage", 'ICDGroup', "Diluc_E", 'ICDRule', "5 hits / 5s", 'ApplyGauge', 2.0, 'Note', "Searing Onslaught 1");
    actions.E2 = struct('TalentGroup', "Skill", 'Param', "x2HitDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', c1DamageBonus, ...
        'ATKWeight', c2AtkBonus, 'AllowAmplify', double(vapeReady), ...
        'LunarisAttackName', "FireCross_Strike", 'LunarisDamageParam', "Damage", 'ICDGroup', "Diluc_E", 'ICDRule', "5 hits / 5s", 'ApplyGauge', 2.0, 'Note', "Searing Onslaught 2");
    actions.E2Rhythm = struct('TalentGroup', "Skill", 'Param', "x2HitDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', c1DamageBonus + 0.40, ...
        'ATKWeight', c2AtkBonus, 'AllowAmplify', double(vapeReady), ...
        'LunarisAttackName', "FireCross_Strike", 'LunarisDamageParam', "Damage", 'ICDGroup', "Diluc_E", 'ICDRule', "5 hits / 5s", 'ApplyGauge', 2.0, 'Note', "C4 rhythm E2");
    actions.E3 = struct('TalentGroup', "Skill", 'Param', "x3HitDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', c1DamageBonus, ...
        'ATKWeight', c2AtkBonus, 'AllowAmplify', double(vapeReady), ...
        'LunarisAttackName', "FireCross_Strike", 'LunarisDamageParam', "Damage", 'ICDGroup', "Diluc_E", 'ICDRule', "5 hits / 5s", 'ApplyGauge', 2.0, 'Note', "Searing Onslaught 3");
    actions.E3Rhythm = struct('TalentGroup', "Skill", 'Param', "x3HitDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', c1DamageBonus + 0.40, ...
        'ATKWeight', c2AtkBonus, 'AllowAmplify', double(vapeReady), ...
        'LunarisAttackName', "FireCross_Strike", 'LunarisDamageParam', "Damage", 'ICDGroup', "Diluc_E", 'ICDRule', "5 hits / 5s", 'ApplyGauge', 2.0, 'Note', "C4 rhythm E3");
    actions.Q1 = struct('TalentGroup', "Burst", 'Param', "SlashingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', c1DamageBonus, ...
        'ATKWeight', c2AtkBonus, 'AllowAmplify', double(vapeReady), ...
        'LunarisAttackName', "FireCross_Strike", 'LunarisDamageParam', "Damage", 'ICDGroup', "Diluc_Q", 'ICDRule', "5 hits / 5s", 'ApplyGauge', 2.0, ...
        'PostSetBurstActiveTime', 8.0, 'Note', "Dawn slash");
    actions.QPhoenix = struct('TalentGroup', "Burst", 'Param', "DoT", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'HitCount', 4, ...
        'BaseActionDamageBonus', c1DamageBonus, 'ATKWeight', c2AtkBonus, ...
        'AllowAmplify', double(vapeReady), 'LunarisAttackName', "FireCross_Material", 'LunarisDamageParam', "Damage|TalentRate|MUL", 'ICDGroup', "Diluc_Q", 'ICDRule', "5 hits / 5s", 'ApplyGauge', 2.0, 'Note', "Phoenix travel");
    actions.Q2 = struct('TalentGroup', "Burst", 'Param', "ExplosionDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', c1DamageBonus, ...
        'ATKWeight', c2AtkBonus, 'AllowAmplify', double(vapeReady), ...
        'LunarisAttackName', "FireCross_Explode", 'LunarisDamageParam', "Damage|TalentRate|MUL", 'ICDGroup', "Diluc_Q", 'ICDRule', "5 hits / 5s", 'ApplyGauge', 2.0, 'Note', "Dawn explosion");

    spec = struct( ...
        'Element', "Pyro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.78, ...
        'DefaultRotation', {{'Q1', 'QPhoenix', 'Q2', 'E1', 'N1', 'E2', 'N2', 'E3', 'N3', 'N4'}}, ...
        'ActionTimeMap', struct( ...
            'N1', 0.38, 'N2', 0.42, 'N3', 0.48, 'N4', 0.58, ...
            'NA6A', 0.38, 'NA6B', 0.42, 'E1', 0.48, 'E2', 0.50, 'E2Rhythm', 0.50, 'E3', 0.54, 'E3Rhythm', 0.54, ...
            'Q1', 0.90, 'QPhoenix', 0.70, 'Q2', 0.20), ...
        'Actions', actions);

    if constellation >= 4
        spec.DefaultRotation = {{'Q1', 'QPhoenix', 'Q2', 'E1', 'N1', 'E2Rhythm', 'N2', 'E3Rhythm', 'N3', 'N4'}};
    end
    if constellation >= 6
        spec.DefaultRotation = {{'Q1', 'QPhoenix', 'Q2', 'E1', 'NA6A', 'E2Rhythm', 'NA6B', 'E3Rhythm', 'N3', 'N4'}};
    end

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Diluc', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

