function build = customArtifact_Neuvillette()
    % 那维莱特默认构筑。
    % 默认面板以生命值、双暴和重击增伤为主，适配水柱输出核心玩法。
    build = struct( ...
        'Weapon', 'TomeOfTheEternalFlow', ...
        'WeaponATK', 542, ...
        'HPBonus', 1.74, ...
        'FlatHP', 4780, ...
        'CritRate', 0.68, ...
        'CritDMG', 2.28, ...
        'HydroDMGBonus', 0.466, ...
        'ChargeDMGBonus', 0.42, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'MarechausseeHunter', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1 ...
    );

    % 回写 CSV，作为默认面板的可视化落盘版本。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Neuvillette', 'artifacts_Neuvillette.csv');
    writetable(struct2table(build), outputPath);
end
