function build = customArtifact_Neuvillette()
    % Default HP/crit Hydro build for Neuvillette beam-focused damage.
    build = struct( ...
        'Weapon', 'TomeOfTheEternalFlow', ...
        'WeaponATK', 542, ...
        'HPBonus', 1.74, ...
        'FlatHP', 4780, ...
        'CritRate', 0.68, ...
        'CritDMG', 2.28, ...
        'HydroDMGBonus', 0.466, ...
        'ChargeDMGBonus', 0.42, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Neuvillette', 'artifacts_Neuvillette.csv');
    writetable(struct2table(build), outputPath);
end
