function build = customArtifact_Illuga()
    % Default Illuga build emphasizing EM-scaled geo damage.
    build = struct( ...
        'Weapon', 'Ballad of the Fjords', ...
        'WeaponATK', 510, ...
        'WeaponSubStatType', 'EM', ...
        'WeaponSubStatValue', 120, ...
        'WeaponRefinement', 1, ...
        'EM', 640, ...
        'AtkBonus', 0.24, ...
        'FlatATK', 180, ...
        'DEFBonus', 0.58, ...
        'FlatDEF', 300, ...
        'CritRate', 0.70, ...
        'CritDMG', 1.82, ...
        'GeoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.22, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'HuskOfOpulentDreams', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Illuga', 'artifacts_Illuga.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
