function build = customArtifact_Xianyun()
    % 闲云默认构筑。
    % 这里以“爆发稳定覆盖 + 较高攻击力支撑下落辅助 + 一定本人输出”为目标，
    % 采用 4 宗室的近似通用支援模板，便于单人/队伍入口统一复用。
    build = struct( ...
        'Weapon', 'Crane''s Echoing Call', ...
        'WeaponATK', 740.5801544, ...
        'WeaponSubStatType', 'ATK%', ...
        'WeaponSubStatValue', 0.165384, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 1.72, ...
        'FlatATK', 410, ...
        'ER', 1.72, ...
        'CritRate', 0.42, ...
        'CritDMG', 1.02, ...
        'AnemoDMGBonus', 0.466, ...
        'PlungeDMGBonus', 0.00, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.20, ...
        'HealingBonus', 0.15, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'NoblesseOblige', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Xianyun', 'artifacts_Xianyun.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
