function build = customArtifact_Layla()
    % Default Layla build emphasizing shield-backed Cryo off-field damage.
    build = struct( ...
        'Weapon', 'KeyOfKhajNisut', ...
        'WeaponATK', 542, ...
        'HPBonus', 1.20, ...
        'FlatHP', 4780, ...
        'CritRate', 0.55, ...
        'CritDMG', 1.30, ...
        'CryoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'TenacityOfTheMillelith', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Layla', 'artifacts_Layla.csv');
    writetable(struct2table(build), outputPath);
end
