function [totalDMG, dps, breakdown, rotationTime] = simulateLaylaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Layla simulator for shield hit, shooting stars, and burst slugs.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Layla', 'rotation_Layla.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Layla', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    starHits = 4 + 2 * double(constellation >= 6);
    slugHits = 8 + 2 * double(constellation >= 6);

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'Note', "Nights of Formal Focus");
    actions.Stars = struct('TalentGroup', "Skill", 'Param', "ShootingStarDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', starHits, ...
        'C6DamageBonus', 0.40, 'Note', "Shooting stars");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "StarlightSlugDMG", 'MVOverride', 0, ...
        'DamageField', "BurstDMGBonus", 'PostSetBurstActiveTime', 12.0, 'Note', "Dream of the Star-Stream Shaker");
    actions.Slug = struct('TalentGroup', "Burst", 'Param', "StarlightSlugDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", 'ActionScalingMode', "HP", 'BaseMultiplier', 1.00, ...
        'HitCount', slugHits, 'C6DamageBonus', 0.40, 'Note', "Starlight slugs");

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.85, ...
        'DefaultRotation', {{'E', 'Stars', 'Q', 'Slug'}}, ...
        'ActionTimeMap', struct('E', 0.65, 'Stars', 8.00, 'Q', 0.95, 'Slug', 12.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Layla', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
