function build = customArtifact_Gorou()
    % Default Gorou build for defense support and geo burst field.
    build = struct( ...
        'Weapon', 'FavoniusWarbow', ...
        'WeaponATK', 565, ...
        'WeaponSubStatType', 'ER', ...
        'WeaponSubStatValue', 0.306, ...
        'WeaponRefinement', 1, ...
        'DEFBonus', 0.46, ...
        'FlatDEF', 180, ...
        'ER', 1.85, ...
        'CritRate', 0.55, ...
        'CritDMG', 1.20, ...
        'GeoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'NoblesseOblige', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Gorou', 'artifacts_Gorou.csv');
    writetable(struct2table(build), outputPath);
end
