function build = customArtifact_Gaming()
    % Default Gaming build focused on plunge-centric pyro damage.
    build = struct( ...
        'Weapon', 'BeaconOfTheReedSea', ...
        'WeaponATK', 608, ...
        'AtkBonus', 0.96, ...
        'FlatATK', 311, ...
        'EM', 120, ...
        'CritRate', 0.69, ...
        'CritDMG', 1.96, ...
        'PyroDMGBonus', 0.466, ...
        'PlungeDMGBonus', 0.36, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.15, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'CrimsonWitchOfFlames', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Gaming', 'artifacts_Gaming.csv');
    writetable(struct2table(build), outputPath);
end
