function [totalDMG, dps, breakdown, rotationTime] = simulateGamingDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Gaming medium-detail simulator using plunge-oriented action modeling.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Gaming', 'rotation_Gaming.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Gaming', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillATK", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetSkillActiveTime', 6.0, 'PostSetStacks', 1, ...
        'C1DamageBonus', 0.10, 'Note', "Bestial skill leap");
    actions.Plunge = struct('TalentGroup', "Plunge", 'Param', "HighPlungeATK", 'DamageField', "PlungeDMGBonus", ...
        'BaseMultiplier', 1.00, 'PerStackMultiplier', 0.20, 'SkillWindowMultiplier', 0.10, ...
        'AllowAmplify', 1, 'ReactionBonus', 0.15, 'PostAddStacks', 1, 'PostMaxStacks', 3, ...
        'C6CritDMGBonus', 0.40, 'Note', "Pyro plunge");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "BurstATK", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetBurstActiveTime', 12.0, 'PostSetStacks', 2, ...
        'C2CritRateBonus', 0.10, 'Note', "Burst summon");
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "N1ATK", 'DamageField', "NormalDMGBonus", ...
        'BaseMultiplier', 1.00, 'Note', "Normal attack");

    spec = struct( ...
        'Element', "Pyro", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Hydro", ...
        'DefaultActionTime', 0.8, ...
        'ActionTimeMap', struct('E', 0.70, 'Plunge', 0.95, 'Q', 1.15, 'N1', 0.45), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Gaming', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
