function [totalDMG, dps, breakdown, rotationTime, audit] = simulateGamingDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Gaming simulator centered on Lion Dance plunge loops.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Gaming', 'rotation_Gaming.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Gaming', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SuanniManChaiSmashDMG", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetBurstActiveTime', 12.0, 'C2CritRateBonus', 0.10, ...
        'LunarisAttackName', "ElementalBurst_Bullet_03", 'Note', "Burst smash");
    actions.E = struct('TalentGroup', "Skill", 'Param', "PlungingAttackCharmedCloudstriderDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'AllowAmplify', 1, 'ReactionBonus', 0.15, 'SkillWindowMultiplier', 0.10, ...
        'C1DamageBonus', 0.10, 'C6CritDMGBonus', 0.40, ...
        'LunarisDamageParam', "Gaming_SpecialFallingAttack_Damage", 'StrikeType', "Blunt", 'CanShatter', true, ...
        'Note', "Cloudstrider plunge");

    spec = struct( ...
        'Element', "Pyro", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Hydro", ...
        'DefaultActionTime', 0.85, ...
        'DefaultRotation', {{'Q', 'E', 'E', 'E', 'E'}}, ...
        'ActionTimeMap', struct('E', 0.95, 'Q', 1.10), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Gaming', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

