function [totalDMG, dps, breakdown, rotationTime, audit] = simulateAloyDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Aloy simulator with Frozen Wilds bomb / bomblet split, Coil-driven
    % Rushing Ice normal conversion, and explicit Cryo burst mapping.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Aloy', 'rotation_Aloy.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Aloy', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talent = readtable(char(resolveCharacterDataFile('Aloy', 'talents')));
    coilBonus = getTalentValue(talent, 'Skill', 'CoilNormalAttackDMGBonus', talentLevel);
    rushingIceBonus = getTalentValue(talent, 'Skill', 'RushingIceNormalAttackDMGBonus', talentLevel);
    teamAtkBuff = 0.08;
    selfAtkBuff = 0.16;

    workBuild = build;
    workBuild.AtkBonus = getFieldOrDefault(workBuild, 'AtkBonus', 0) + selfAtkBuff + teamAtkBuff;
    workBuild.CryoDMGBonus = getFieldOrDefault(workBuild, 'CryoDMGBonus', 0) + 0.35;

    meltReady = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1;

    actions = struct();
    actions.EBomb = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "FreezeBombDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Avatar_AloyGadgetSkill_ElementalArt_Bullet", ...
        'LunarisDamageParam', "ElementalArt_Damage1", ...
        'Note', "Frozen Wilds bomb");
    actions.EBomblets = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "ChillwaterBombletDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', 4, ...
        'HitTimeline', [0.25, 0.25, 0.25, 0.25], ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'PostSetStacks', 4, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Avatar_AloyGadgetSkill_ElementalArt_Mine", ...
        'LunarisDamageParam', "ElementalArt_Damage2", ...
        'Note', "Chillwater bomblets");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Avatar_AloyGadgetSkill_ElementalBurst", ...
        'LunarisDamageParam', "ElementalBurst_Damage", ...
        'Note', "Prophecies of Dawn");
    actions.N1 = localMakeAloyNormalAction("x1HitDMG", 1.00 + coilBonus + rushingIceBonus, "Cryo", double(meltReady), "NormalAttack_01_01_DamagePercentage", "Aloy infused normal 1");
    actions.N2 = localMakeAloyNormalAction("x2HitDMG", 1.00 + coilBonus + rushingIceBonus, "Cryo", double(meltReady), "NormalAttack_02_DamagePercentage", "Aloy infused normal 2");
    actions.N3 = localMakeAloyNormalAction("x3HitDMG", 1.00 + coilBonus + rushingIceBonus, "Cryo", double(meltReady), "NormalAttack_03_DamagePercentage", "Aloy infused normal 3");
    actions.N4 = localMakeAloyNormalAction("x4HitDMG", 1.00 + coilBonus + rushingIceBonus, "Cryo", double(meltReady), "NormalAttack_04_DamagePercentage", "Aloy infused normal 4");
    actions.Aimed = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "FullyChargedAimedShot", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Avatar_AloyGadgetSkill_ExtraAttack_Ice", ...
        'LunarisDamageParam', "DamageWithIce", ...
        'Note', "Fully charged shot");

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Pyro", ...
        'DefaultActionTime', 0.65, ...
        'DefaultRotation', {{'EBomb', 'EBomblets', 'N1', 'N2', 'N3', 'N4', 'Q', 'Aimed'}}, ...
        'ActionTimeMap', struct( ...
            'EBomb', 0.55, ...
            'EBomblets', 1.00, ...
            'N1', 0.30, ...
            'N2', 0.34, ...
            'N3', 0.38, ...
            'N4', 0.46, ...
            'Q', 0.90, ...
            'Aimed', 1.05), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Aloy', workBuild, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function action = localMakeAloyNormalAction(paramName, baseMultiplier, actionElement, allowAmplify, lunarisParam, note)
    action = struct( ...
        'TalentGroup', "Normal", ...
        'Param', string(paramName), ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', string(actionElement), ...
        'BaseMultiplier', baseMultiplier, ...
        'AllowAmplify', allowAmplify, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Avatar_AloyGadgetSkill_NormalAttack_01_01_Damage", ...
        'LunarisDamageParam', string(lunarisParam), ...
        'Note', string(note));
end
