function build = customArtifact_Hutao()
    % Default Hu Tao build for low-HP charged-attack focused vaporize play.
    build = struct( ...
        'Weapon', '护摩之杖', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CD', ...
        'WeaponSubStatValue', 0.662, ...
        'WeaponRefinement', 1, ...
        'HPBonus', 0.86, ...
        'FlatHP', 4780, ...
        'AtkBonus', 0.12, ...
        'FlatATK', 220, ...
        'EM', 220, ...
        'ER', 1.10, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.20, ...
        'PyroDMGBonus', 0.466, ...
        'ChargedDMGBonus', 0.18, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.18, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'CrimsonWitchOfFlames', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Hutao', 'artifacts_Hutao.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
