function build = customArtifact_Venti()
    % Default Venti build for burst swirl support and skill damage.
    build = struct( ...
        'Weapon', 'ElegyForTheEnd', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'ER', ...
        'WeaponSubStatValue', 0.551, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.46, ...
        'FlatATK', 120, ...
        'ER', 1.80, ...
        'EM', 220, ...
        'CritRate', 0.55, ...
        'CritDMG', 1.40, ...
        'AnemoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.00, ...
        'BurstDMGBonus', 0.00, ...
        'ArtifactSet1', 'ViridescentVenerer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Venti', 'artifacts_Venti.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
