function [totalDMG, dps, breakdown, rotationTime, audit] = simulateXiaoDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Xiao simulator with dash spam, burst-enhanced anemo plunge loop, and
    % explicit burst window damage conversion.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Xiao', 'rotation_Xiao.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Xiao', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talent = readtable(char(resolveCharacterDataFile('Xiao', 'talents')));
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    burstPlungeBonus = getTalentValue(talent, 'Burst', 'NormalChargedPlungingAttackDMGBonus', burstLevel);
    burstDuration = getTalentValue(talent, 'Burst', 'Duration', burstLevel);
    c1DashCount = 2 + double(constellation >= 1);
    c4AtkBonus = 0.20 * double(constellation >= 4);
    c6BurstBonus = 0.15 * double(constellation >= 6);

    workBuild = build;
    if c4AtkBonus > 0
        workBuild.AtkBonus = getFieldOrDefault(workBuild, 'AtkBonus', 0) + c4AtkBonus;
    end

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Xiao_Dash", ...
        'ICDRule', "7 hits / 0.1s", ...
        'StrikeType', "Slash", ...
        'LunarisAttackName', "DevilDash_Bullet", ...
        'LunarisDamageParam', "DevilDash_Damage", ...
        'Note', "Lemniscatic Wind Cycling");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "Duration", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'MVOverride', 0, ...
        'PostSetBurstActiveTime', burstDuration, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Bane of All Evil");
    actions.PlungSlash = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "PlungeDMG", ...
        'DamageField', "PlungeDMGBonus", ...
        'ActionElement', "Anemo", ...
        'ActionScalingMode', "ATK", ...
        'BaseMultiplier', 1.00 + burstPlungeBonus + c6BurstBonus, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Slash", ...
        'LunarisAttackName', "FallingAnthem", ...
        'LunarisDamageParam', "FallingAnthem_HowlingSoul_Loop_Damage", ...
        'Note', "Burst plunge slash");
    actions.PlungImpact = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "LowHighPlungeDMG", ...
        'DamageField', "PlungeDMGBonus", ...
        'ActionElement', "Anemo", ...
        'ActionScalingMode', "ATK", ...
        'BaseMultiplier', 1.00 + burstPlungeBonus + c6BurstBonus, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'LunarisAttackName', "FallingAnthem", ...
        'LunarisDamageParam', "FallingAnthem_HowlingSoul_Rank_2_Damage", ...
        'Note', "Burst plunge impact");
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Normal 1");
    actions.CA = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Slash", ...
        'Note', "Charged attack");

    defaultRotation = {};
    for i = 1:c1DashCount
        defaultRotation{end + 1} = 'E'; %#ok<AGROW>
    end
    defaultRotation = [defaultRotation, {'Q', 'PlungSlash', 'PlungImpact', 'PlungSlash', 'PlungImpact', 'PlungSlash', 'PlungImpact'}]; %#ok<AGROW>
    if constellation >= 6
        defaultRotation = [defaultRotation, {'E', 'E'}]; %#ok<AGROW>
    end

    spec = struct( ...
        'Element', "Anemo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.55, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct( ...
            'E', 0.42, ...
            'Q', 0.95, ...
            'PlungSlash', 0.20, ...
            'PlungImpact', 0.72, ...
            'N1', 0.34, ...
            'CA', 0.78), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Xiao', workBuild, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
