function build = customArtifact_Iansan()
    % 伊安珊默认构筑。
    % 默认面板侧重攻击、充能与适量元素精通，
    % 用于兼顾爆发辅助、站场穿插动作和雷伤副C段。
    build = struct( ...
        'Weapon', 'FavoniusLance', ...
        'WeaponATK', 565, ...
        'AtkBonus', 1.18, ...
        'FlatATK', 280, ...
        'ER', 2.00, ...
        'EM', 160, ...
        'CritRate', 0.58, ...
        'CritDMG', 1.16, ...
        'ElectroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.20, ...
        'NormalDMGBonus', 0.12, ...
        'ResShred', 0.00 ...
    );

    % 回写默认构筑数据。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Iansan', 'artifacts_Iansan.csv');
    writetable(struct2table(build), outputPath);
end
