function build = customArtifact_Sandrone()
    % Sandrone default build.
    % Keep artifact totals free of 2pc bonuses so the unified artifact
    % compiler can safely add set effects without double counting.
    build = struct( ...
        'Weapon', 'Beacon of the Reed Sea', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.331, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.66, ...
        'FlatATK', 311, ...
        'HPBonus', 0.12, ...
        'FlatHP', 1200, ...
        'CritRate', 0.75, ...
        'CritDMG', 1.88, ...
        'CryoDMGBonus', 0.466, ...
        'ChargedDMGBonus', 0.18, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'BlizzardStrayer', ...
        'ArtifactSet1Pieces', 2, ...
        'ArtifactSet2', 'GladiatorsFinale', ...
        'ArtifactSet2Pieces', 2, ...
        'ArtifactSet4Active', 0);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Sandrone', 'artifacts_Sandrone.csv');
    writetable(struct2table(build), outputPath);
end
