function [totalDMG, dps, breakdown, rotationTime, audit] = simulateSandroneDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Sandrone high-detail simulator.
    % This implementation keeps the character-specific state machine for:
    % 1. Fagio Decoding / Power Overdrive transitions;
    % 2. Decoding Power gain, natural decay, and skill-side repair loss;
    % 3. Refined Tactics accumulation and burst-ray consumption;
    % 4. Stellar-Conduct-tagged direct damage branches and C4 / C6 details.
    %
    % At the same time, every damage instance now goes through the unified
    % aura / ICD / reaction entry so that:
    % - Cryo hits can actually trigger Melt / Stellar-Conduct / Shatter;
    % - Stellar-tagged direct hits use 0U and do not trigger a second reaction;
    % - the enemy state is shared continuously across the full rotation.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Sandrone', 'rotation_Sandrone.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Sandrone', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    dataFolder = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Sandrone');
    base = readtable(fullfile(dataFolder, 'characters_Sandrone.csv'));
    talent = readtable(fullfile(dataFolder, 'talents_Sandrone.csv'));
    actions = localResolveRotation(seqFile);

    normalLevel = talentLevel + 3 * double(constellation >= 3);
    skillLevel = talentLevel;
    burstLevel = talentLevel + 3 * double(constellation >= 5);

    atk = localResolveATK(base, build, teamContext);
    workBuild = build;
    workBuild.EM = getFieldOrDefault(workBuild, 'EM', 0) + min(160, 0.08 * atk);
    preferredAura = localResolvePreferredAura(teamContext);
    enemyState = getFieldOrDefault(teamContext, 'EnemyState', createEnemyState(enemy, teamContext, "Cryo"));

    state = struct( ...
        'FagioPower', 0, ...
        'DecodingActive', false, ...
        'OverdriveActive', false, ...
        'BeamCountInMode', 0, ...
        'RefinedTactics', 0, ...
        'StellarConductActive', false, ...
        'PolestarFieldTime', 0, ...
        'C4Cooldown', 0, ...
        'ICDStates', struct());

    totalDMG = 0;
    rotationTime = 0;
    breakdown = table('Size', [0 3], 'VariableTypes', {'string', 'double', 'string'}, ...
        'VariableNames', {'Action', 'Damage', 'Note'});
    auditRows = {};

    for i = 1:numel(actions)
        action = string(actions{i});
        actionTime = localActionTime(action);
        dmg = 0;
        resolvedTime = 0;
        note = "";
        reactionTags = strings(0, 1);
        idleTriggerElement = "";
        extraRows = table('Size', [0 3], 'VariableTypes', {'string', 'double', 'string'}, ...
            'VariableNames', {'Action', 'Damage', 'Note'});

        switch char(action)
            case 'CAStart'
                idleTriggerElement = "Cryo";
                if state.OverdriveActive
                    note = "Power Overdrive active";
                else
                    state.DecodingActive = true;
                    state.BeamCountInMode = 0;
                    sweepSpec = struct( ...
                        'Label', "ChargedSweep", ...
                        'Element', "Cryo", ...
                        'DamageField', "ChargedDMGBonus", ...
                        'Multiplier', getTalentValue(talent, 'Normal', 'ChargedSweepDMG', normalLevel), ...
                        'ActionDamageBonus', 0, ...
                        'ApplyGauge', 1.0, ...
                        'CanApplyAura', true, ...
                        'CanTriggerReaction', true, ...
                        'AllowAmplify', true, ...
                        'PreferredAura', preferredAura, ...
                        'ICDRule', "Independent", ...
                        'ICDGroup', "SandroneSweep", ...
                        'StrikeType', "Blunt", ...
                        'StellarTagged', false, ...
                        'GainBeamPowerOnHit', false, ...
                        'PostHitPowerLoss', 0);
                    [hitDMG, state, enemyState, hitTags, auditRows] = localResolveStructuredHit( ...
                        action, sweepSpec, actionTime, atk, workBuild, teamContext, enemy, ...
                        state, enemyState, constellation, talent, auditRows);
                    dmg = dmg + hitDMG;
                    resolvedTime = resolvedTime + actionTime;
                    reactionTags = [reactionTags; hitTags(:)]; %#ok<AGROW>
                    note = sprintf('Decoding enter, power=%.1f', state.FagioPower);
                end

            case 'Beam'
                idleTriggerElement = "Cryo";
                if ~state.DecodingActive
                    note = "Decoding inactive";
                else
                    state.BeamCountInMode = state.BeamCountInMode + 1;
                    useStellarBeam = state.StellarConductActive;
                    beamMV = getTalentValue(talent, 'Normal', localBeamParamName(useStellarBeam), normalLevel);
                    if constellation >= 2 && useStellarBeam
                        c2Stacks = min(getTalentValue(talent, 'Constellation', 'C2BeamMaxStacks', normalLevel), state.BeamCountInMode - 1);
                        beamMV = beamMV ...
                            + getTalentValue(talent, 'Constellation', 'C2BeamFlatATK', normalLevel) ...
                            + c2Stacks * getTalentValue(talent, 'Constellation', 'C2BeamStackATK', normalLevel);
                    end

                    beamSpec = struct( ...
                        'Label', "CondensedBeam", ...
                        'Element', "Cryo", ...
                        'DamageField', "ChargedDMGBonus", ...
                        'Multiplier', beamMV, ...
                        'ActionDamageBonus', 0, ...
                        'ApplyGauge', 1.0 * double(~useStellarBeam), ...
                        'CanApplyAura', ~useStellarBeam, ...
                        'CanTriggerReaction', ~useStellarBeam, ...
                        'AllowAmplify', ~useStellarBeam, ...
                        'PreferredAura', preferredAura, ...
                        'ICDRule', "2 hits / 1.4s", ...
                        'ICDGroup', "SandroneMachineGun", ...
                        'StrikeType', "", ...
                        'StellarTagged', useStellarBeam, ...
                        'GainBeamPowerOnHit', true, ...
                        'PostHitPowerLoss', 0);
                    [beamDMG, state, enemyState, beamTags, auditRows] = localResolveStructuredHit( ...
                        action, beamSpec, actionTime, atk, workBuild, teamContext, enemy, ...
                        state, enemyState, constellation, talent, auditRows);
                    dmg = dmg + beamDMG;
                    resolvedTime = resolvedTime + actionTime;
                    reactionTags = [reactionTags; beamTags(:)]; %#ok<AGROW>

                    if constellation >= 6 && state.BeamCountInMode >= 3
                        clusterMV = getTalentValue(talent, 'Constellation', localClusterParamName(useStellarBeam), normalLevel);
                        clusterCount = round(getTalentValue(talent, 'Constellation', 'C6ClusterHitCount', normalLevel));
                        clusterDMG = 0;
                        for hitIndex = 1:clusterCount
                            clusterSpec = struct( ...
                                'Label', "C6Cluster" + hitIndex, ...
                                'Element', "Cryo", ...
                                'DamageField', "ChargedDMGBonus", ...
                                'Multiplier', clusterMV, ...
                                'ActionDamageBonus', 0, ...
                                'ApplyGauge', 1.0 * double(~useStellarBeam), ...
                                'CanApplyAura', ~useStellarBeam, ...
                                'CanTriggerReaction', ~useStellarBeam, ...
                                'AllowAmplify', ~useStellarBeam, ...
                                'PreferredAura', preferredAura, ...
                                'ICDRule', "2 hits / 1.4s", ...
                                'ICDGroup', "SandroneMachineGun", ...
                                'StrikeType', "", ...
                                'StellarTagged', useStellarBeam, ...
                                'GainBeamPowerOnHit', false, ...
                                'PostHitPowerLoss', 0);
                            [thisClusterDMG, state, enemyState, clusterTags, auditRows] = localResolveStructuredHit( ...
                                action, clusterSpec, 0, atk, workBuild, teamContext, enemy, ...
                                state, enemyState, constellation, talent, auditRows);
                            clusterDMG = clusterDMG + thisClusterDMG;
                            reactionTags = [reactionTags; clusterTags(:)]; %#ok<AGROW>
                        end
                        dmg = dmg + clusterDMG;
                        extraRows = [extraRows; {string("C6Cluster"), clusterDMG, sprintf('C6 cluster x%d', clusterCount)}]; %#ok<AGROW>
                    end

                    if useStellarBeam
                        [c4DMG, state, enemyState, c4Tags, auditRows] = localResolveC4FollowUp( ...
                            action, 0, atk, workBuild, teamContext, enemy, state, enemyState, ...
                            constellation, talent, normalLevel, auditRows);
                        if c4DMG > 0
                            dmg = dmg + c4DMG;
                            reactionTags = [reactionTags; c4Tags(:)]; %#ok<AGROW>
                            extraRows = [extraRows; {string("C4Beam"), c4DMG, "C4 coordinated Stellar-Conduct shot"}]; %#ok<AGROW>
                        end
                    end

                    note = sprintf('Condensed beam #%d, power %.1f', state.BeamCountInMode, state.FagioPower);
                end

            case 'BeamOD'
                idleTriggerElement = "Cryo";
                if ~state.OverdriveActive
                    note = "Power Overdrive inactive";
                else
                    overdriveSpec = struct( ...
                        'Label', "OverdriveBeam", ...
                        'Element', "Cryo", ...
                        'DamageField', "ChargedDMGBonus", ...
                        'Multiplier', getTalentValue(talent, 'Normal', 'OverdriveDMG', normalLevel), ...
                        'ActionDamageBonus', 0, ...
                        'ApplyGauge', 1.0, ...
                        'CanApplyAura', true, ...
                        'CanTriggerReaction', true, ...
                        'AllowAmplify', true, ...
                        'PreferredAura', preferredAura, ...
                        'ICDRule', "2 hits / 1.4s", ...
                        'ICDGroup', "SandroneMachineGun", ...
                        'StrikeType', "", ...
                        'StellarTagged', false, ...
                        'GainBeamPowerOnHit', false, ...
                        'PostHitPowerLoss', getTalentValue(talent, 'Passive', 'OverdriveShotPowerLoss', normalLevel));
                    [beamDMG, state, enemyState, beamTags, auditRows] = localResolveStructuredHit( ...
                        action, overdriveSpec, actionTime, atk, workBuild, teamContext, enemy, ...
                        state, enemyState, constellation, talent, auditRows);
                    dmg = dmg + beamDMG;
                    resolvedTime = resolvedTime + actionTime;
                    reactionTags = [reactionTags; beamTags(:)]; %#ok<AGROW>
                    note = sprintf('Overdrive beam, power -> %.1f', state.FagioPower);
                end

            case 'E'
                idleTriggerElement = "Cryo";
                powerBefore = state.FagioPower;
                powerLoss = min(powerBefore, ...
                    getTalentValue(talent, 'Passive', 'SkillPowerLossStart', skillLevel) ...
                    + getTalentValue(talent, 'Passive', 'SkillPowerLossPerSecond', skillLevel) * actionTime);
                enhancedThreshold = getTalentValue(talent, 'Passive', 'PrismPowerThreshold', skillLevel);

                state.DecodingActive = false;
                state.OverdriveActive = false;
                state.BeamCountInMode = 0;

                prism1Spec = struct( ...
                    'Label', "Prism1", ...
                    'Element', "Cryo", ...
                    'DamageField', "SkillDMGBonus", ...
                    'Multiplier', getTalentValue(talent, 'Skill', 'PrismShotDMG', skillLevel), ...
                    'ActionDamageBonus', 0, ...
                    'ApplyGauge', 1.0, ...
                    'CanApplyAura', true, ...
                    'CanTriggerReaction', true, ...
                    'AllowAmplify', true, ...
                    'PreferredAura', preferredAura, ...
                    'ICDRule', "Independent", ...
                    'ICDGroup', "SandroneSkillPrism", ...
                    'StrikeType', "", ...
                    'StellarTagged', false, ...
                    'GainBeamPowerOnHit', false, ...
                    'PostHitPowerLoss', 0);
                [prism1DMG, state, enemyState, prism1Tags, auditRows] = localResolveStructuredHit( ...
                    action, prism1Spec, 0.20, atk, workBuild, teamContext, enemy, ...
                    state, enemyState, constellation, talent, auditRows);
                dmg = dmg + prism1DMG;
                resolvedTime = resolvedTime + 0.20;
                reactionTags = [reactionTags; prism1Tags(:)]; %#ok<AGROW>
                extraRows = [extraRows; {string("Prism1"), prism1DMG, "First prism shot"}]; %#ok<AGROW>

                useStellarShot = state.StellarConductActive;
                prism2MV = getTalentValue(talent, 'Skill', localSkillPrismParamName(useStellarShot), skillLevel);
                if powerBefore > enhancedThreshold
                    prism2MV = prism2MV * getTalentValue(talent, 'Passive', 'PrismEnhancedMultiplier', skillLevel);
                end
                prism2Spec = struct( ...
                    'Label', "Prism2", ...
                    'Element', "Cryo", ...
                    'DamageField', "SkillDMGBonus", ...
                    'Multiplier', prism2MV, ...
                    'ActionDamageBonus', 0, ...
                    'ApplyGauge', 1.0 * double(~useStellarShot), ...
                    'CanApplyAura', ~useStellarShot, ...
                    'CanTriggerReaction', ~useStellarShot, ...
                    'AllowAmplify', ~useStellarShot, ...
                    'PreferredAura', preferredAura, ...
                    'ICDRule', "Independent", ...
                    'ICDGroup', "SandroneSkillPrism", ...
                    'StrikeType', "", ...
                    'StellarTagged', useStellarShot, ...
                    'GainBeamPowerOnHit', false, ...
                    'PostHitPowerLoss', 0);
                [prism2DMG, state, enemyState, prism2Tags, auditRows] = localResolveStructuredHit( ...
                    action, prism2Spec, 0.20, atk, workBuild, teamContext, enemy, ...
                    state, enemyState, constellation, talent, auditRows);
                dmg = dmg + prism2DMG;
                resolvedTime = resolvedTime + 0.20;
                reactionTags = [reactionTags; prism2Tags(:)]; %#ok<AGROW>
                extraRows = [extraRows; {string("Prism2"), prism2DMG, "Second prism shot"}]; %#ok<AGROW>

                if useStellarShot
                    [c4DMG, state, enemyState, c4Tags, auditRows] = localResolveC4FollowUp( ...
                        action, 0, atk, workBuild, teamContext, enemy, state, enemyState, ...
                        constellation, talent, skillLevel, auditRows);
                    if c4DMG > 0
                        dmg = dmg + c4DMG;
                        reactionTags = [reactionTags; c4Tags(:)]; %#ok<AGROW>
                        extraRows = [extraRows; {string("C4Prism"), c4DMG, "C4 coordinated Stellar-Conduct shot"}]; %#ok<AGROW>
                    end
                end

                state.FagioPower = max(0, powerBefore - powerLoss);
                tacticsGain = floor(powerLoss / 10) * getTalentValue(talent, 'Passive', 'RefinedTacticsPer10Power', skillLevel);
                state.RefinedTactics = min(getTalentValue(talent, 'Passive', 'RefinedTacticsMaxStacks', skillLevel), ...
                    state.RefinedTactics + tacticsGain);
                if state.OverdriveActive && state.FagioPower < getTalentValue(talent, 'Passive', 'OverdriveExitThreshold', skillLevel)
                    state.OverdriveActive = false;
                end
                note = sprintf('Prism x2, power %.1f -> %.1f, tactics=%d', powerBefore, state.FagioPower, state.RefinedTactics);

            case 'Q'
                idleTriggerElement = "Cryo";
                bombardMV = getTalentValue(talent, 'Burst', 'BombardmentDMG', burstLevel);
                bombardHits = round(getTalentValue(talent, 'Burst', 'BombardmentHitCount', burstLevel));
                bombardIntervals = 0.15 * ones(1, bombardHits);
                for hitIndex = 1:bombardHits
                    bombardSpec = struct( ...
                        'Label', "Bombardment" + hitIndex, ...
                        'Element', "Cryo", ...
                        'DamageField', "BurstDMGBonus", ...
                        'Multiplier', bombardMV, ...
                        'ActionDamageBonus', 0, ...
                        'ApplyGauge', 1.0, ...
                        'CanApplyAura', true, ...
                        'CanTriggerReaction', true, ...
                        'AllowAmplify', true, ...
                        'PreferredAura', preferredAura, ...
                        'ICDRule', "Independent", ...
                        'ICDGroup', "SandroneBurstBombardment", ...
                        'StrikeType', "", ...
                        'StellarTagged', false, ...
                        'GainBeamPowerOnHit', false, ...
                        'PostHitPowerLoss', 0);
                    [thisBombardDMG, state, enemyState, bombardTags, auditRows] = localResolveStructuredHit( ...
                        action, bombardSpec, bombardIntervals(hitIndex), atk, workBuild, teamContext, enemy, ...
                        state, enemyState, constellation, talent, auditRows);
                    dmg = dmg + thisBombardDMG;
                    resolvedTime = resolvedTime + bombardIntervals(hitIndex);
                    reactionTags = [reactionTags; bombardTags(:)]; %#ok<AGROW>
                    extraRows = [extraRows; {string("Bombardment" + hitIndex), thisBombardDMG, "Burst bombardment hit"}]; %#ok<AGROW>
                end

                useStellarRay = state.StellarConductActive;
                rayMV = getTalentValue(talent, 'Burst', localBurstRayParamName(useStellarRay), burstLevel);
                tacticsConsumed = state.RefinedTactics;
                if useStellarRay
                    rayMV = rayMV * (1 + getTalentValue(talent, 'Passive', 'RayBonusPerTacticsStack', burstLevel) * tacticsConsumed);
                end
                raySpec = struct( ...
                    'Label', "ConvectiveRay", ...
                    'Element', "Cryo", ...
                    'DamageField', "BurstDMGBonus", ...
                    'Multiplier', rayMV, ...
                    'ActionDamageBonus', 0, ...
                    'ApplyGauge', 1.0 * double(~useStellarRay), ...
                    'CanApplyAura', ~useStellarRay, ...
                    'CanTriggerReaction', ~useStellarRay, ...
                    'AllowAmplify', ~useStellarRay, ...
                    'PreferredAura', preferredAura, ...
                    'ICDRule', "Independent", ...
                    'ICDGroup', "SandroneBurstRay", ...
                    'StrikeType', "Blunt", ...
                    'StellarTagged', useStellarRay, ...
                    'GainBeamPowerOnHit', false, ...
                    'PostHitPowerLoss', 0);
                [rayDMG, state, enemyState, rayTags, auditRows] = localResolveStructuredHit( ...
                    action, raySpec, 0.25, atk, workBuild, teamContext, enemy, ...
                    state, enemyState, constellation, talent, auditRows);
                dmg = dmg + rayDMG;
                resolvedTime = resolvedTime + 0.25;
                reactionTags = [reactionTags; rayTags(:)]; %#ok<AGROW>
                extraRows = [extraRows; {string("ConvectiveRay"), rayDMG, "Burst finisher"}]; %#ok<AGROW>

                if useStellarRay
                    [c4DMG, state, enemyState, c4Tags, auditRows] = localResolveC4FollowUp( ...
                        action, 0, atk, workBuild, teamContext, enemy, state, enemyState, ...
                        constellation, talent, burstLevel, auditRows);
                    if c4DMG > 0
                        dmg = dmg + c4DMG;
                        reactionTags = [reactionTags; c4Tags(:)]; %#ok<AGROW>
                        extraRows = [extraRows; {string("C4Ray"), c4DMG, "C4 coordinated Stellar-Conduct shot"}]; %#ok<AGROW>
                    end
                end

                state.RefinedTactics = 0;
                note = sprintf('Bombardment x%d, tactics consumed=%d', bombardHits, tacticsConsumed);

            case 'N1'
                idleTriggerElement = "Physical";
                normalSpec = struct( ...
                    'Label', "Normal1", ...
                    'Element', "Physical", ...
                    'DamageField', "NormalDMGBonus", ...
                    'Multiplier', getTalentValue(talent, 'Normal', 'N1DMG', normalLevel), ...
                    'ActionDamageBonus', 0, ...
                    'ApplyGauge', 0.0, ...
                    'CanApplyAura', false, ...
                    'CanTriggerReaction', true, ...
                    'AllowAmplify', false, ...
                    'PreferredAura', "", ...
                    'ICDRule', "Independent", ...
                    'ICDGroup', "SandroneNormal", ...
                    'StrikeType', "Blunt", ...
                    'StellarTagged', false, ...
                    'GainBeamPowerOnHit', false, ...
                    'PostHitPowerLoss', 0);
                [dmg, state, enemyState, reactionTags, auditRows] = localResolveStructuredHit( ...
                    action, normalSpec, actionTime, atk, workBuild, teamContext, enemy, ...
                    state, enemyState, constellation, talent, auditRows);
                resolvedTime = actionTime;
                note = "Normal 1";

            case 'N2'
                idleTriggerElement = "Physical";
                normalSpec = struct( ...
                    'Label', "Normal2", ...
                    'Element', "Physical", ...
                    'DamageField', "NormalDMGBonus", ...
                    'Multiplier', getTalentValue(talent, 'Normal', 'N2DMG', normalLevel), ...
                    'ActionDamageBonus', 0, ...
                    'ApplyGauge', 0.0, ...
                    'CanApplyAura', false, ...
                    'CanTriggerReaction', true, ...
                    'AllowAmplify', false, ...
                    'PreferredAura', "", ...
                    'ICDRule', "Independent", ...
                    'ICDGroup', "SandroneNormal", ...
                    'StrikeType', "Blunt", ...
                    'StellarTagged', false, ...
                    'GainBeamPowerOnHit', false, ...
                    'PostHitPowerLoss', 0);
                [dmg, state, enemyState, reactionTags, auditRows] = localResolveStructuredHit( ...
                    action, normalSpec, actionTime, atk, workBuild, teamContext, enemy, ...
                    state, enemyState, constellation, talent, auditRows);
                resolvedTime = actionTime;
                note = "Normal 2";

            case 'N3'
                idleTriggerElement = "Physical";
                normalSpec = struct( ...
                    'Label', "Normal3", ...
                    'Element', "Physical", ...
                    'DamageField', "NormalDMGBonus", ...
                    'Multiplier', getTalentValue(talent, 'Normal', 'N3DMG', normalLevel), ...
                    'ActionDamageBonus', 0, ...
                    'ApplyGauge', 0.0, ...
                    'CanApplyAura', false, ...
                    'CanTriggerReaction', true, ...
                    'AllowAmplify', false, ...
                    'PreferredAura', "", ...
                    'ICDRule', "Independent", ...
                    'ICDGroup', "SandroneNormal", ...
                    'StrikeType', "Blunt", ...
                    'StellarTagged', false, ...
                    'GainBeamPowerOnHit', false, ...
                    'PostHitPowerLoss', 0);
                [dmg, state, enemyState, reactionTags, auditRows] = localResolveStructuredHit( ...
                    action, normalSpec, actionTime, atk, workBuild, teamContext, enemy, ...
                    state, enemyState, constellation, talent, auditRows);
                resolvedTime = actionTime;
                note = "Normal 3";

            otherwise
                note = "Unknown action";
        end

        remainingTime = max(0, actionTime - resolvedTime);
        if remainingTime > 1e-9
            state = localAdvanceStateWindow(state, action, remainingTime, talent, constellation);
            [idleDMG, enemyState, idleTags] = localAdvanceIdleWindow( ...
                remainingTime, idleTriggerElement, workBuild, teamContext, enemy, enemyState);
            dmg = dmg + idleDMG;
            reactionTags = [reactionTags; idleTags(:)]; %#ok<AGROW>
        end

        reactionTags = unique(reactionTags(strlength(reactionTags) > 0), 'stable');
        note = localAppendReactionTags(note, reactionTags);
        totalDMG = totalDMG + dmg;
        if ~isempty(extraRows)
            breakdown = [breakdown; extraRows]; %#ok<AGROW>
        end
        breakdown = [breakdown; {action, dmg, note}]; %#ok<AGROW>
        rotationTime = rotationTime + actionTime;
    end

    if rotationTime <= 0
        rotationTime = getFieldOrDefault(teamContext, 'RotationDuration', 20);
    end
    dps = totalDMG / rotationTime;

    if nargout > 4
        audit = struct();
        if ~isempty(auditRows)
            audit.Rows = cell2table(auditRows, 'VariableNames', { ...
                'Action', 'Hit', 'ApplyGauge', 'CanApplyAura', 'ICDRule', 'ICDGroup', ...
                'PrimaryReaction', 'TriggeredReactions', 'StellarTagged'});
        else
            audit.Rows = table();
        end
        audit.FinalState = state;
        audit.FinalEnemyState = enemyState;
    else
        audit = struct();
    end
end

function actions = localResolveRotation(seqFile)
    tokens = readRotationTokens(seqFile);
    if isempty(tokens)
        tokens = {'AUTO'};
    end
    if numel(tokens) == 1 && strcmpi(tokens{1}, 'AUTO')
        actions = {'CAStart', 'Beam', 'Beam', 'Beam', 'BeamOD', 'E', 'Q'};
    else
        actions = tokens;
    end
end

function atk = localResolveATK(base, build, teamContext)
    atk = (base.BaseATK(1) + getFieldOrDefault(build, 'WeaponATK', 0)) ...
        * (1 + getFieldOrDefault(build, 'AtkBonus', 0) + getFieldOrDefault(teamContext, 'ATKBonus', 0)) ...
        + getFieldOrDefault(build, 'FlatATK', 0) + getFieldOrDefault(teamContext, 'FlatATK', 0);
end

function preferredAura = localResolvePreferredAura(teamContext)
    if logical(getFieldOrDefault(teamContext, 'StellarConductEnabled', false)) ...
            && getFieldOrDefault(teamContext, 'ElectroCount', 0) >= 1
        preferredAura = "Electro";
    elseif getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1
        preferredAura = "Pyro";
    elseif getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1
        preferredAura = "Hydro";
    else
        preferredAura = "";
    end
end

function [damage, state, enemyState, reactionTags, auditRows] = localResolveStructuredHit( ...
        actionName, hitSpec, deltaTime, atk, build, teamContext, enemy, state, enemyState, constellation, talent, auditRows)
    state = localAdvanceStateWindow(state, actionName, deltaTime, talent, constellation);
    [canApplyAura, state.ICDStates, icdSnapshot] = localResolveHitICD(state.ICDStates, hitSpec, deltaTime);

    directDamage = localDirectDamage( ...
        hitSpec.Element, atk, hitSpec.Multiplier, build, teamContext, enemy, ...
        localResolveDamageFieldBonus(build, hitSpec.DamageField) + getFieldOrDefault(hitSpec, 'ActionDamageBonus', 0), ...
        getFieldOrDefault(hitSpec, 'ExtraResShred', 0));

    hitDescriptor = struct( ...
        'HitElement', string(hitSpec.Element), ...
        'ApplyElement', string(hitSpec.Element), ...
        'ApplyGauge', getFieldOrDefault(hitSpec, 'ApplyGauge', 0), ...
        'CanApplyAura', canApplyAura, ...
        'CanTriggerReaction', logical(getFieldOrDefault(hitSpec, 'CanTriggerReaction', true)), ...
        'AllowAmplify', logical(getFieldOrDefault(hitSpec, 'AllowAmplify', false)), ...
        'AllowCatalyze', false, ...
        'PreferredAura', string(getFieldOrDefault(hitSpec, 'PreferredAura', "")), ...
        'ForceReactionName', "", ...
        'ReactionElement', string(hitSpec.Element), ...
        'ReactionBonus', 0, ...
        'StrikeType', string(getFieldOrDefault(icdSnapshot, 'StrikeType', getFieldOrDefault(hitSpec, 'StrikeType', ""))), ...
        'ICDGroup', string(getFieldOrDefault(icdSnapshot, 'ICDGroup', "")), ...
        'ICDRule', string(getFieldOrDefault(icdSnapshot, 'ICDRule', "")), ...
        'ICDSource', "explicit");

    if any(strcmpi(char(string(hitSpec.Element)), {'physical', 'none'}))
        hitDescriptor.CanApplyAura = false;
        hitDescriptor.ApplyElement = "";
    end
    if isfield(hitSpec, 'StrikeType')
        hitDescriptor.StrikeType = string(hitSpec.StrikeType);
    end

    reactionResult = resolveReactionForHit(enemyState, hitDescriptor, build, teamContext, enemy, deltaTime);
    enemyState = reactionResult.EnemyState;

    directDamage = directDamage * reactionResult.AmplifyMultiplier;
    if reactionResult.CatalyzeFlatDamage > 0
        directDamage = directDamage + localDirectDamage( ...
            hitSpec.Element, 1, reactionResult.CatalyzeFlatDamage, build, teamContext, enemy, ...
            localResolveDamageFieldBonus(build, hitSpec.DamageField) + getFieldOrDefault(hitSpec, 'ActionDamageBonus', 0), ...
            getFieldOrDefault(hitSpec, 'ExtraResShred', 0));
    end

    if logical(getFieldOrDefault(hitSpec, 'StellarTagged', false))
        directDamage = directDamage * localStellarDamageMultiplier(talent, constellation, teamContext);
    end

    damage = directDamage + reactionResult.ReactionDamage;
    reactionTags = unique(reactionResult.TriggeredReactions(strlength(reactionResult.TriggeredReactions) > 0), 'stable');

    if logical(getFieldOrDefault(hitSpec, 'GainBeamPowerOnHit', false)) && state.DecodingActive
        state.FagioPower = min(100, state.FagioPower + getTalentValue(talent, 'Passive', 'BeamPowerGainOnHit', 10));
        if state.FagioPower >= 100
            state.DecodingActive = false;
            state.OverdriveActive = true;
        end
    end

    state.FagioPower = max(0, state.FagioPower - getFieldOrDefault(hitSpec, 'PostHitPowerLoss', 0));
    if state.OverdriveActive && state.FagioPower < getTalentValue(talent, 'Passive', 'OverdriveExitThreshold', 10)
        state.OverdriveActive = false;
    end

    if any(strcmpi(cellstr(reactionTags), 'stellarconduct')) ...
            || strcmpi(char(string(reactionResult.PrimaryReaction)), 'stellarconduct')
        state.PolestarFieldTime = max(state.PolestarFieldTime, 6.0);
    end
    state = localRefreshStellarConductFromField(state);

    auditRows = [auditRows; { ...
        string(actionName), ...
        string(getFieldOrDefault(hitSpec, 'Label', "")), ...
        double(getFieldOrDefault(hitSpec, 'ApplyGauge', 0)), ...
        logical(canApplyAura), ...
        string(getFieldOrDefault(icdSnapshot, 'ICDRule', "")), ...
        string(getFieldOrDefault(icdSnapshot, 'ICDGroup', "")), ...
        string(getFieldOrDefault(reactionResult, 'PrimaryReaction', "")), ...
        strjoin(cellstr(reactionTags), '|'), ...
        logical(getFieldOrDefault(hitSpec, 'StellarTagged', false))}]; %#ok<AGROW>
end

function [c4DMG, state, enemyState, reactionTags, auditRows] = localResolveC4FollowUp( ...
        actionName, deltaTime, atk, build, teamContext, enemy, state, enemyState, constellation, talent, talentLevel, auditRows)
    c4DMG = 0;
    reactionTags = strings(0, 1);
    if constellation < 4 || state.C4Cooldown > 1e-6
        return;
    end

    c4Spec = struct( ...
        'Label', "C4PrismaticCannon", ...
        'Element', "Cryo", ...
        'DamageField', "SkillDMGBonus", ...
        'Multiplier', getTalentValue(talent, 'Constellation', 'C4FollowUpATK', talentLevel), ...
        'ActionDamageBonus', 0, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'AllowAmplify', false, ...
        'PreferredAura', "", ...
        'ICDRule', "Independent", ...
        'ICDGroup', "SandroneC4", ...
        'StrikeType', "", ...
        'StellarTagged', true, ...
        'GainBeamPowerOnHit', false, ...
        'PostHitPowerLoss', 0);
    [c4DMG, state, enemyState, reactionTags, auditRows] = localResolveStructuredHit( ...
        actionName, c4Spec, deltaTime, atk, build, teamContext, enemy, ...
        state, enemyState, constellation, talent, auditRows);
    state.C4Cooldown = getTalentValue(talent, 'Constellation', 'C4Cooldown', talentLevel);
end

function state = localAdvanceStateWindow(state, actionName, deltaTime, talent, constellation)
    deltaTime = max(0, double(deltaTime));
    if deltaTime <= 1e-9
        return;
    end

    state.C4Cooldown = max(0, state.C4Cooldown - deltaTime);
    state.PolestarFieldTime = max(0, state.PolestarFieldTime - deltaTime);

    if state.DecodingActive
        powerGain = getTalentValue(talent, 'Passive', 'BeamPowerGainPerSecond', 10) * deltaTime;
        if constellation >= 1
            powerGain = powerGain * (1 - getTalentValue(talent, 'Constellation', 'C1PowerGainReduction', 10));
        end
        state.FagioPower = min(100, state.FagioPower + powerGain);
        if state.FagioPower >= 100
            state.DecodingActive = false;
            state.OverdriveActive = true;
        end
    elseif ~strcmpi(char(string(actionName)), 'E')
        powerDecay = getTalentValue(talent, 'Passive', 'NonDecodingPowerDecayPerSecond', 10) * deltaTime;
        state.FagioPower = max(0, state.FagioPower - powerDecay);
    end

    if state.OverdriveActive && state.FagioPower < getTalentValue(talent, 'Passive', 'OverdriveExitThreshold', 10)
        state.OverdriveActive = false;
    end
    state = localRefreshStellarConductFromField(state);
end

function state = localRefreshStellarConductFromField(state)
    state.StellarConductActive = state.PolestarFieldTime > 1e-6;
end

function [idleDMG, enemyState, reactionTags] = localAdvanceIdleWindow(deltaTime, triggerElement, build, teamContext, enemy, enemyState)
    idleDMG = 0;
    reactionTags = strings(0, 1);
    if deltaTime <= 1e-9
        return;
    end

    idleDescriptor = struct( ...
        'HitElement', string(triggerElement), ...
        'ApplyElement', "", ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false);
    idleResult = resolveReactionForHit(enemyState, idleDescriptor, build, teamContext, enemy, deltaTime);
    enemyState = idleResult.EnemyState;
    idleDMG = idleResult.ReactionDamage;
    reactionTags = unique(idleResult.TriggeredReactions(strlength(idleResult.TriggeredReactions) > 0), 'stable');
end

function [canApplyAura, icdStates, snapshot] = localResolveHitICD(icdStates, hitSpec, deltaTime)
    snapshot = struct( ...
        'ICDGroup', string(getFieldOrDefault(hitSpec, 'ICDGroup', "")), ...
        'ICDRule', string(getFieldOrDefault(hitSpec, 'ICDRule', "Independent")), ...
        'StrikeType', string(getFieldOrDefault(hitSpec, 'StrikeType', "")));
    canApplyAura = logical(getFieldOrDefault(hitSpec, 'CanApplyAura', false)) ...
        && double(getFieldOrDefault(hitSpec, 'ApplyGauge', 0)) > 0;
    if ~canApplyAura
        return;
    end

    icdConfig = localParseICDRule(snapshot.ICDRule);
    if strcmpi(char(string(getFieldOrDefault(icdConfig, 'Kind', "Independent"))), 'Independent')
        return;
    end
    if strlength(snapshot.ICDGroup) == 0
        return;
    end

    fieldName = matlab.lang.makeValidName(char(snapshot.ICDGroup));
    if ~isfield(icdStates, fieldName)
        icdStates.(fieldName) = struct( ...
            'HitsSinceApply', max(0, double(icdConfig.Hits) - 1), ...
            'Elapsed', max(0, double(icdConfig.Window)), ...
            'HitsThreshold', max(1, double(icdConfig.Hits)), ...
            'Window', max(0, double(icdConfig.Window)));
    end

    state = icdStates.(fieldName);
    state.Elapsed = state.Elapsed + max(0, double(deltaTime));
    if state.Window > 0 && state.Elapsed >= state.Window
        state.HitsSinceApply = max(0, state.HitsThreshold - 1);
        state.Elapsed = 0;
    end

    if state.HitsSinceApply >= max(0, state.HitsThreshold - 1)
        canApplyAura = true;
        state.HitsSinceApply = 0;
        state.Elapsed = 0;
    else
        canApplyAura = false;
        state.HitsSinceApply = state.HitsSinceApply + 1;
    end

    icdStates.(fieldName) = state;
end

function config = localParseICDRule(ruleText)
    ruleText = string(ruleText);
    config = struct('Kind', "Independent", 'Hits', 1, 'Window', 0);
    if strlength(ruleText) == 0 || strcmpi(char(ruleText), 'Independent')
        return;
    end
    tokens = regexp(lower(char(ruleText)), '(\d+)\s*hits?\s*/\s*([\d\.]+)\s*s', 'tokens', 'once');
    if isempty(tokens)
        return;
    end
    config.Kind = "Windowed";
    config.Hits = max(1, str2double(tokens{1}));
    config.Window = max(0, str2double(tokens{2}));
end

function multiplier = localStellarDamageMultiplier(talent, constellation, teamContext)
    multiplier = 1 ...
        + getFieldOrDefault(teamContext, 'StellarConductBonus', 0) ...
        + getFieldOrDefault(teamContext, 'SandroneStellarConductBonus', 0) ...
        + getFieldOrDefault(teamContext, 'SandroneStellarConductC1Bonus', 0) ...
        + getFieldOrDefault(teamContext, 'StellarGlimmerBonus', 0);
    if constellation >= 6
        multiplier = multiplier * (1 + getTalentValue(talent, 'Constellation', 'C6StellarConductElevate', 10));
    end
end

function damage = localDirectDamage(element, atk, mv, build, teamContext, enemy, extraBonus, extraResShred)
    if nargin < 8
        extraResShred = 0;
    end
    critRate = getFieldOrDefault(build, 'CritRate', 0) + localElementCritRateBonus(element, teamContext);
    critDMG = getFieldOrDefault(build, 'CritDMG', 0) + localElementCritDMGBonus(element, teamContext);
    critMult = calcExpectedCritMultiplier(critRate, critDMG);
    dmgBonus = 1 + localElementBonus(element, build, teamContext) + getFieldOrDefault(teamContext, 'AllDMGBonus', 0) + extraBonus;
    resShred = getFieldOrDefault(build, 'ResShred', 0) + localElementResShred(element, teamContext) + extraResShred;
    damage = atk * mv * dmgBonus * critMult * calcDamageMultiplier(90, enemy, resShred);
end

function bonus = localResolveDamageFieldBonus(build, damageField)
    damageField = string(damageField);
    bonus = getFieldOrDefault(build, char(damageField), 0);
    switch lower(char(damageField))
        case 'chargeddmgbonus'
            bonus = bonus + getFieldOrDefault(build, 'ChargeDMGBonus', 0);
        case 'chargedmgbonus'
            bonus = bonus + getFieldOrDefault(build, 'ChargedDMGBonus', 0);
    end
end

function bonus = localElementBonus(element, build, teamContext)
    switch lower(char(string(element)))
        case 'cryo'
            bonus = getFieldOrDefault(build, 'CryoDMGBonus', 0) + getFieldOrDefault(teamContext, 'CryoDMGBonus', 0);
        case 'physical'
            bonus = getFieldOrDefault(build, 'PhysicalDMGBonus', 0) + getFieldOrDefault(teamContext, 'PhysicalDMGBonus', 0);
        otherwise
            bonus = 0;
    end
end

function shred = localElementResShred(element, teamContext)
    switch lower(char(string(element)))
        case 'cryo'
            shred = getFieldOrDefault(teamContext, 'CryoResShred', 0);
        case 'physical'
            shred = getFieldOrDefault(teamContext, 'PhysicalResShred', 0);
        otherwise
            shred = 0;
    end
end

function bonus = localElementCritRateBonus(element, teamContext)
    switch lower(char(string(element)))
        case 'physical'
            bonus = getFieldOrDefault(teamContext, 'PhysicalCritRateBonus', 0);
        otherwise
            bonus = 0;
    end
end

function bonus = localElementCritDMGBonus(element, teamContext)
    switch lower(char(string(element)))
        case 'cryo'
            bonus = getFieldOrDefault(teamContext, 'CryoCritDMGBonus', 0);
        case 'physical'
            bonus = getFieldOrDefault(teamContext, 'PhysicalCritDMGBonus', 0);
        otherwise
            bonus = 0;
    end
end

function paramName = localBeamParamName(useStellarBeam)
    if useStellarBeam
        paramName = 'CondensedBeamStellarDMG';
    else
        paramName = 'CondensedBeamDMG';
    end
end

function paramName = localClusterParamName(useStellarBeam)
    if useStellarBeam
        paramName = 'C6ClusterHitStellarATK';
    else
        paramName = 'C6ClusterHitATK';
    end
end

function paramName = localSkillPrismParamName(useStellarShot)
    if useStellarShot
        paramName = 'PrismShotStellarDMG';
    else
        paramName = 'PrismShotDMG';
    end
end

function paramName = localBurstRayParamName(useStellarRay)
    if useStellarRay
        paramName = 'RayStellarDMG';
    else
        paramName = 'RayDMG';
    end
end

function note = localAppendReactionTags(baseNote, reactionTags)
    note = string(baseNote);
    if isempty(reactionTags)
        return;
    end
    for i = 1:numel(reactionTags)
        if strlength(reactionTags(i)) == 0
            continue;
        end
        if strlength(note) == 0
            note = string(reactionTags(i));
        else
            note = note + ", " + string(reactionTags(i));
        end
    end
end

function actionTime = localActionTime(action)
    switch char(string(action))
        case 'CAStart'
            actionTime = 0.75;
        case 'Beam'
            actionTime = 0.90;
        case 'BeamOD'
            actionTime = 1.10;
        case 'E'
            actionTime = 0.60;
        case 'Q'
            actionTime = 1.25;
        case 'N1'
            actionTime = 0.38;
        case 'N2'
            actionTime = 0.42;
        case 'N3'
            actionTime = 0.56;
        otherwise
            actionTime = 0.50;
    end
end
