function build = customArtifact_Mualani()
    % 玛拉妮默认构筑。
    % 默认面板以生命值与双暴为主，适配咬击与导弹终结段的轮转输出。
    build = struct( ...
        'Weapon', 'SurfingTome', ...
        'WeaponATK', 542, ...
        'HPBonus', 1.72, ...
        'FlatHP', 4780, ...
        'CritRate', 0.76, ...
        'CritDMG', 1.92, ...
        'HydroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 180, ...
        'ResShred', 0.00 ...
    );

    % 回写 CSV，作为后续脚本和表格的统一基线。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Mualani', 'artifacts_Mualani.csv');
    writetable(struct2table(build), outputPath);
end
