function build = customArtifact_Mualani()
    % Default HP/crit build for Mualani's surf-bite burst profile.
    build = struct( ...
        'Weapon', 'SurfingTome', ...
        'WeaponATK', 542, ...
        'HPBonus', 1.72, ...
        'FlatHP', 4780, ...
        'CritRate', 0.76, ...
        'CritDMG', 1.92, ...
        'HydroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 180, ...
        'ResShred', 0.00 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Mualani', 'artifacts_Mualani.csv');
    writetable(struct2table(build), outputPath);
end
