function build = customArtifact_Jean()
    % Default Jean build for quickswap Anemo burst and healing support.
    build = struct( ...
        'Weapon', 'AquilaFavonia', ...
        'WeaponATK', 674, ...
        'WeaponSubStatType', 'Phys', ...
        'WeaponSubStatValue', 0.413, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.72, ...
        'FlatATK', 311, ...
        'ER', 1.35, ...
        'CritRate', 0.60, ...
        'CritDMG', 1.45, ...
        'AnemoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'HealingBonus', 0.359, ...
        'ArtifactSet1', 'ViridescentVenerer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Jean', 'artifacts_Jean.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
