function build = customArtifact_Ororon()
    % Default Ororon build focused on electro off-field and burst damage.
    build = struct( ...
        'Weapon', 'The Stringless', ...
        'WeaponATK', 510, ...
        'WeaponSubStatType', 'EM', ...
        'WeaponSubStatValue', 165, ...
        'WeaponRefinement', 5, ...
        'AtkBonus', 0.70, ...
        'FlatATK', 311, ...
        'EM', 200, ...
        'ER', 1.35, ...
        'CritRate', 0.72, ...
        'CritDMG', 1.88, ...
        'ElectroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.30, ...
        'BurstDMGBonus', 0.30, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'GoldenTroupe', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Ororon', 'artifacts_Ororon.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
