function build = customArtifact_Tighnari()
    % Default Tighnari build for spread-focused charged shots and burst.
    build = struct( ...
        'Weapon', 'HuntersPath', ...
        'WeaponATK', 542, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.44, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.46, ...
        'FlatATK', 120, ...
        'EM', 320, ...
        'CritRate', 0.72, ...
        'CritDMG', 1.90, ...
        'DendroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.22, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'DeepwoodMemories', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Tighnari', 'artifacts_Tighnari.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
