function [totalDMG, dps, breakdown, rotationTime, audit] = simulateBeidouDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Beidou high-detail simulator.
    % Focus:
    % - hold counter damage bonus scaling
    % - full-counter / burst chain lightning with real ICD and gauge
    % - C6 Electro RES shred and Radiance Stellar-Conduct Cryo RES shred / EM
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Beidou', 'rotation_Beidou.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Beidou', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    workTeamContext = teamContext;
    talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Beidou', 'talents_Beidou.csv');
    talent = readtable(talentPath);
    skillLevel = talentLevel + 3 * double(constellation >= 3);
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    aggravateReady = getFieldOrDefault(workTeamContext, 'DendroCount', 0) >= 1;
    burstExtraResShred = 0.15 * double(constellation >= 6);
    burstReactionEM = getFieldOrDefault(build, 'EM', 0) + getFieldOrDefault(workTeamContext, 'EMBonus', 0);
    if burstExtraResShred > 0
        workTeamContext.ElectroResShred = getFieldOrDefault(workTeamContext, 'ElectroResShred', 0) - burstExtraResShred;
    end
    if constellation >= 6 && logical(getFieldOrDefault(workTeamContext, 'StellarConductEnabled', false))
        workTeamContext.EMBonus = getFieldOrDefault(workTeamContext, 'EMBonus', 0) - 200;
        burstReactionEM = burstReactionEM + 200;
    end

    counterBase = getTalentValue(talent, 'Skill', 'BaseDMG', skillLevel);
    counterBonus = getTalentValue(talent, 'Skill', 'DMGBonusOnHitTaken', skillLevel);
    holdCounterMV = counterBase + 2 * counterBonus;
    burstArcHits = 12;
    burstArcTimeline = ones(1, burstArcHits);

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "BaseDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'MVOverride', holdCounterMV, ...
        'AllowCatalyze', double(aggravateReady), ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ThunderCounter_Strike", ...
        'LunarisDamageParam', "Damage_PerStage|2.000000|MUL|Damage_Stage1|ADD", ...
        'Note', "Tidecaller counter");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), ...
        'ApplyGauge', 4.0, ...
        'PostSetBurstActiveTime', 15.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ThunderShield", ...
        'LunarisDamageParam', "BurstDamage", ...
        'Note', "Stormbreaker cast");
    actions.Chain = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "LightningDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', burstArcHits, ...
        'HitTimeline', burstArcTimeline, ...
        'AllowCatalyze', double(aggravateReady), ...
        'ExtraResShred', burstExtraResShred, ...
        'ReactionEMOverride', burstReactionEM, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Beidou_Stormbreaker", ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ThunderShield_Gadget", ...
        'LunarisDamageParam', "ChainDamage", ...
        'Note', "Stormbreaker chain lightning");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.85, ...
        'DefaultRotation', {{'E', 'Q', 'Chain'}}, ...
        'ActionTimeMap', struct('E', 0.85, 'Q', 1.00, 'Chain', 15.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Beidou', build, enemy, seqFile, talentLevel, constellation, workTeamContext, spec);
end
