function [totalDMG, dps, breakdown, rotationTime, audit] = simulateSucroseDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Sucrose simulator with explicit skill charges, burst wind spirit
    % ticks, and absorbed-element follow-up damage.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Sucrose', 'rotation_Sucrose.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Sucrose', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    absorbedElement = localResolveAbsorbedElement(teamContext, enemy);
    absorbedReady = double(strlength(absorbedElement) > 0);
    burstDuration = 6.0 + 2.0 * double(constellation >= 2);
    burstTickCount = 4 + double(constellation >= 2);
    burstTickTimeline = (burstDuration / burstTickCount) * ones(1, burstTickCount);
    c6InfuseBonus = 0.20 * double(constellation >= 6);

    actions = struct();
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Attack01", ...
        'LunarisDamageParam', "Sucrose_NormalAttack_01_Damage", ...
        'Note', "Normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Attack02", ...
        'LunarisDamageParam', "Sucrose_NormalAttack_02_Damage", ...
        'Note', "Normal 2");
    actions.N3 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Attack03", ...
        'LunarisDamageParam', "Sucrose_NormalAttack_03_Damage", ...
        'Note', "Normal 3");
    actions.N4 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x4HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Attack04_Gadget", ...
        'LunarisDamageParam', "Sucrose_NormalAttack_04_Damage", ...
        'Note', "Normal 4");
    actions.CA = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'Note', "Charged attack");
    actions.PlungeSlash = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "PlungeDMG", ...
        'DamageField', "PlungeDMGBonus", ...
        'ActionElement', "Anemo", ...
        'ActionScalingMode', "ATK", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "FallingAnthem", ...
        'LunarisDamageParam', "FallingAnthem_Normal_Loop_Damage", ...
        'Note', "Plunge slash");
    actions.PlungeImpact = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "LowHighPlungeDMG", ...
        'DamageField', "PlungeDMGBonus", ...
        'ActionElement', "Anemo", ...
        'ActionScalingMode', "ATK", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "FallingAnthem", ...
        'LunarisDamageParam', "FallingAnthem_Normal_Rank_2_Damage", ...
        'Note', "Plunge impact");
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'Note', "Astable Anemohypostasis Creation - 6308");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "Duration", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'MVOverride', 0, ...
        'PostSetBurstActiveTime', burstDuration, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Forbidden Creation cast");
    actions.QDoT = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "DoT", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', burstTickCount, ...
        'HitTimeline', burstTickTimeline, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "DemiHurricane_Damage", ...
        'LunarisDamageParam', "Sucrose_DemiHurricane_Gadget_Damage", ...
        'Note', "Large Wind Spirit Anemo ticks");
    actions.QInfuse = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "AdditionalElementalDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', absorbedElement, ...
        'BaseMultiplier', absorbedReady, ...
        'FlatDamageBonus', c6InfuseBonus * absorbedReady, ...
        'HitCount', burstTickCount, ...
        'HitTimeline', burstTickTimeline, ...
        'AllowAmplify', localElementAllowsAmplify(absorbedElement, teamContext), ...
        'AllowCatalyze', localElementAllowsCatalyze(absorbedElement, teamContext), ...
        'PreferredAmplifyAura', localElementPreferredAura(absorbedElement, teamContext), ...
        'ApplyGauge', 1.0 * absorbedReady, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "DemiHurricane_Damage", ...
        'LunarisDamageParam', "Sucrose_DemiHurricane_Gadget_Mix_Damage", ...
        'Note', "Large Wind Spirit absorbed ticks");

    defaultRotation = {'E'};
    if constellation >= 1
        defaultRotation{end + 1} = 'E'; %#ok<AGROW>
    end
    defaultRotation = [defaultRotation, {'Q', 'QDoT'}]; %#ok<AGROW>
    if absorbedReady > 0
        defaultRotation{end + 1} = 'QInfuse'; %#ok<AGROW>
    end
    defaultRotation = [defaultRotation, {'CA'}]; %#ok<AGROW>

    spec = struct( ...
        'Element', "Anemo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.55, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct( ...
            'N1', 0.33, ...
            'N2', 0.33, ...
            'N3', 0.36, ...
            'N4', 0.48, ...
            'CA', 0.88, ...
            'PlungeSlash', 0.20, ...
            'PlungeImpact', 0.62, ...
            'E', 0.68, ...
            'Q', 0.95, ...
            'QDoT', burstDuration, ...
            'QInfuse', burstDuration), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Sucrose', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function element = localResolveAbsorbedElement(teamContext, enemy)
    if nargin >= 2 && isstruct(enemy)
        initialAura = string(getFieldOrDefault(enemy, 'InitialAuraElement', ""));
        if any(strcmpi(initialAura, ["Pyro", "Hydro", "Electro", "Cryo"]))
            element = string(initialAura);
            return;
        end
    end

    priority = ["Pyro", "Hydro", "Electro", "Cryo"];
    for i = 1:numel(priority)
        if getFieldOrDefault(teamContext, char(priority(i) + "Count"), 0) >= 1
            element = priority(i);
            return;
        end
    end
    element = "";
end

function tf = localElementAllowsAmplify(element, teamContext)
    switch lower(char(string(element)))
        case 'pyro'
            tf = double(getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1 || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1);
        case 'hydro'
            tf = double(getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1);
        case 'cryo'
            tf = double(getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1);
        otherwise
            tf = 0;
    end
end

function tf = localElementAllowsCatalyze(element, teamContext)
    switch lower(char(string(element)))
        case 'electro'
            tf = double(getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1);
        case 'dendro'
            tf = double(getFieldOrDefault(teamContext, 'ElectroCount', 0) >= 1);
        otherwise
            tf = 0;
    end
end

function aura = localElementPreferredAura(element, teamContext)
    switch lower(char(string(element)))
        case 'pyro'
            if getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1
                aura = "Hydro";
            elseif getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1
                aura = "Cryo";
            else
                aura = "";
            end
        case 'hydro'
            aura = "Pyro";
        case 'cryo'
            aura = "Pyro";
        otherwise
            aura = "";
    end
end
