function [totalDMG, dps, breakdown, rotationTime, audit] = simulateTartagliaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Tartaglia simulator with ranged shot opener, melee stance conversion,
    % Riptide Slash follow-up, and ranged / melee burst split.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Tartaglia', 'rotation_Tartaglia.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Tartaglia', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    vapeReady = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1;
    meleeLoopCount = 2 + double(constellation >= 1);

    actions = struct();
    actions.RangeAim = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "FullyChargedAimedShot", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vapeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ShootArrow_Enchanted_Water", ...
        'LunarisDamageParam', "DamageWithWater", ...
        'Note', "Ranged charged shot");
    actions.RangeBurst = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMGRanged", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vapeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "AquariaBlade_Range_Gadget", ...
        'LunarisDamageParam', "AquariaBlade_Range_Damage", ...
        'Note', "Havoc: Obliteration ranged");
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "StanceChangeDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'PostSetSkillActiveTime', 9.0, ...
        'AllowAmplify', double(vapeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Gandalfr", ...
        'LunarisDamageParam', "Gandalfr_StartDamage", ...
        'Note', "Foul Legacy: Raging Tide");
    actions.M1 = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vapeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Tartaglia_Melee", ...
        'ICDRule', "3 hits / 2.5s", ...
        'LunarisAttackName', "AquariaBlade_Melee", ...
        'LunarisDamageParam', "AquariaBlade_Melee_Damage", ...
        'Note', "Melee normal 1");
    actions.M2 = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vapeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Tartaglia_Melee", ...
        'ICDRule', "3 hits / 2.5s", ...
        'LunarisAttackName', "AquariaBlade_Melee", ...
        'LunarisDamageParam', "AquariaBlade_Melee_Damage", ...
        'Note', "Melee normal 2");
    actions.M3 = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vapeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Tartaglia_Melee", ...
        'ICDRule', "3 hits / 2.5s", ...
        'LunarisAttackName', "AquariaBlade_Melee", ...
        'LunarisDamageParam', "AquariaBlade_Melee_Damage", ...
        'Note', "Melee normal 3");
    actions.M4 = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "x4HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vapeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Tartaglia_Melee", ...
        'ICDRule', "3 hits / 2.5s", ...
        'LunarisAttackName', "AquariaBlade_Melee", ...
        'LunarisDamageParam', "AquariaBlade_Melee_Damage", ...
        'Note', "Melee normal 4");
    actions.M5 = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "x5HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vapeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Tartaglia_Melee", ...
        'ICDRule', "3 hits / 2.5s", ...
        'LunarisAttackName', "AquariaBlade_Melee", ...
        'LunarisDamageParam', "AquariaBlade_Melee_Damage", ...
        'Note', "Melee normal 5");
    actions.Riptide = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "RiptideSlash", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', meleeLoopCount, ...
        'AllowAmplify', double(vapeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Tartaglia_Riptide", ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "WaterFlower_Handler", ...
        'LunarisDamageParam', "AquaFlower_Melee_Damage", ...
        'Note', "Riptide slash");
    actions.MeleeBurst = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMGMelee", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vapeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "AquariaBlade_Melee", ...
        'LunarisDamageParam', "AquariaBlade_Melee_Damage", ...
        'Note', "Havoc: Obliteration melee");

    spec = struct( ...
        'Element', "Hydro", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Pyro", ...
        'DefaultActionTime', 0.60, ...
        'DefaultRotation', {{'RangeAim', 'E', 'M1', 'M2', 'M3', 'M4', 'M5', 'Riptide', 'M1', 'M2', 'M3', 'M4', 'M5', 'Riptide', 'MeleeBurst'}}, ...
        'ActionTimeMap', struct( ...
            'RangeAim', 1.10, ...
            'RangeBurst', 1.00, ...
            'E', 0.60, ...
            'M1', 0.28, ...
            'M2', 0.30, ...
            'M3', 0.36, ...
            'M4', 0.38, ...
            'M5', 0.42, ...
            'Riptide', 0.40, ...
            'MeleeBurst', 1.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Tartaglia', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
