function [totalDMG, dps, breakdown, rotationTime] = simulateRazorDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % 雷泽高精度近似模拟。
    % 建模要点：
    % 1. E 点按积攒雷之印，长按按层数清空并结算；
    % 2. Q 开启后普攻与狼魂追击拆开，按常见站场节奏估算段数；
    % 3. C4 点按减防、C6 落雷与暴击强化窗口显式处理；
    % 4. 物伤主轴下保留超导减抗由 teamContext 统一提供。
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Razor', 'rotation_Razor.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Razor', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    wolfHitCount = 10;
    c4DefReduct = 0.15 * double(constellation >= 4);
    c6CritRateBonus = 0.10 * double(constellation >= 6);
    c6CritDMGBonus = 0.50 * double(constellation >= 6);

    actions = struct();
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", 'BaseMultiplier', 1.00, 'CritRateBonus', c6CritRateBonus, 'CritDMGBonus', c6CritDMGBonus, 'Note', "Normal 1");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", 'BaseMultiplier', 1.00, 'CritRateBonus', c6CritRateBonus, 'CritDMGBonus', c6CritDMGBonus, 'Note', "Normal 2");
    actions.N3 = struct('TalentGroup', "Normal", 'Param', "x3HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", 'BaseMultiplier', 1.00, 'CritRateBonus', c6CritRateBonus, 'CritDMGBonus', c6CritDMGBonus, 'Note', "Normal 3");
    actions.N4 = struct('TalentGroup', "Normal", 'Param', "x4HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", 'BaseMultiplier', 1.00, 'CritRateBonus', c6CritRateBonus, 'CritDMGBonus', c6CritDMGBonus, 'Note', "Normal 4");
    actions.ETap = struct('TalentGroup', "Skill", 'Param', "PressSkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1), ...
        'PostAddMarks', 1, 'PostMaxMarks', 3, 'PostSetSkillActiveTime', 7.0, 'Note', "Claw and Thunder tap");
    actions.EHold = struct('TalentGroup', "Skill", 'Param', "HoldSkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1), ...
        'PostSetMarks', 0, 'SkillWindowEnemyDefReduct', c4DefReduct, 'Note', "Claw and Thunder hold");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "BurstDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1), ...
        'PostSetBurstActiveTime', 15.0, 'PostSetMarks', 0, 'SkillWindowEnemyDefReduct', c4DefReduct, 'Note', "Lightning Fang cast");
    actions.Wolf = struct('TalentGroup', "Burst", 'Param', "SoulCompanionDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'HitCount', wolfHitCount, ...
        'AllowCatalyze', double(getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1), ...
        'SkillWindowEnemyDefReduct', c4DefReduct, 'Note', "Soul companion");
    actions.C6Strike = struct('TalentGroup', "Burst", 'Param', "BurstDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'MVOverride', 1.00 * double(constellation >= 6), 'AllowCatalyze', double(getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1), ...
        'SkillWindowEnemyDefReduct', c4DefReduct, 'Note', "C6 lightning strike");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.80, ...
        'DefaultRotation', {{'ETap', 'ETap', 'EHold', 'Q', 'N1', 'N2', 'N3', 'N4', 'Wolf', 'C6Strike'}}, ...
        'ActionTimeMap', struct('N1', 0.35, 'N2', 0.40, 'N3', 0.50, 'N4', 0.60, 'ETap', 0.55, 'EHold', 1.00, 'Q', 1.05, 'Wolf', 0.20, 'C6Strike', 0.10), ...
        'Actions', actions);

    if constellation < 6
        spec.DefaultRotation = {{'ETap', 'ETap', 'EHold', 'Q', 'N1', 'N2', 'N3', 'N4', 'Wolf'}};
    end

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Razor', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
