function build = customArtifact_Kaeya()
    % Default Kaeya build for cryo quickswap and burst orbit hits.
    build = struct( ...
        'Weapon', 'PrimordialJadeCutter', ...
        'WeaponATK', 542, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.441, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.78, ...
        'FlatATK', 220, ...
        'ER', 1.35, ...
        'CritRate', 0.70, ...
        'CritDMG', 1.95, ...
        'CryoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.22, ...
        'ArtifactSet1', 'BlizzardStrayer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Kaeya', 'artifacts_Kaeya.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
