function build = customArtifact_Ifa()
    % Default Ifa build oriented around anemo personal damage.
    build = struct( ...
        'Weapon', 'Lost Prayer to the Sacred Winds', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.331, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.88, ...
        'FlatATK', 311, ...
        'EM', 120, ...
        'ER', 1.20, ...
        'CritRate', 0.78, ...
        'CritDMG', 1.96, ...
        'AnemoDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.15, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'ViridescentVenerer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Ifa', 'artifacts_Ifa.csv');
    if exist(fileparts(outputPath), 'dir') ~= 7
        mkdir(fileparts(outputPath));
    end
    writetable(struct2table(build), outputPath);
end
