function [totalDMG, dps, breakdown, rotationTime, audit] = simulateIfaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Ifa simulator with Nightsoul hover window, tap/hold Supporting Fire,
    % burst field marks, and constellation-aware extra tonic shots.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Ifa', 'rotation_Ifa.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Ifa', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    pyroCount = getFieldOrDefault(teamContext, 'PyroCount', 0);
    hydroCount = getFieldOrDefault(teamContext, 'HydroCount', 0);
    cryoCount = getFieldOrDefault(teamContext, 'CryoCount', 0);
    electroCount = getFieldOrDefault(teamContext, 'ElectroCount', 0);
    swirlReady = pyroCount + hydroCount + cryoCount + electroCount >= 1;

    rescuePoints = max(0, getFieldOrDefault(teamContext, 'MemberCount', 1) * 20);
    rescueBonus = 0.015 * min(rescuePoints, 150);
    if constellation >= 2
        rescueBonus = rescueBonus + 0.015 * min(50, max(0, rescuePoints - 60) * 4);
    end

    absorbedElement = localResolveIfaBurstElement(teamContext);
    burstReactionReady = strcmpi(absorbedElement, 'electro') || strcmpi(absorbedElement, 'pyro') ...
        || strcmpi(absorbedElement, 'hydro') || strcmpi(absorbedElement, 'cryo');

    holdShotCount = 4 + double(constellation >= 6);
    holdTimeline = [0.00, 0.40, 0.40, 0.40, 0.40];
    holdTimeline = holdTimeline(1:holdShotCount);
    if numel(holdTimeline) < holdShotCount
        holdTimeline(end + 1:holdShotCount) = 0.40; %#ok<AGROW>
    end
    markHitCount = 4;
    markTimeline = [1.60, 2.00, 2.00, 2.00];

    actions = struct();
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_Bullet_01", ...
        'LunarisDamageParam', "NormalAttack_01_Damage", ...
        'AllowTransformative', double(swirlReady), ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_Bullet_02", ...
        'LunarisDamageParam', "NormalAttack_02_Damage", ...
        'AllowTransformative', double(swirlReady), ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Normal 2");
    actions.N3 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_Bullet_03", ...
        'LunarisDamageParam', "NormalAttack_03_Damage", ...
        'AllowTransformative', double(swirlReady), ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Normal 3");
    actions.CA = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ExtraAttack_Bullet", ...
        'LunarisDamageParam', "ExtraAttack_Damage", ...
        'AllowTransformative', double(swirlReady), ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Charged shot");
    actions.ECast = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "TonicshotDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 0.00, ...
        'PostSetSkillActiveTime', 7.5, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'Note', "Airborne Disease Prevention");
    actions.SupportTap = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "TonicshotDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'SkillWindowDamageBonus', 0.00, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Ifa_SupportingFire", ...
        'ICDRule', "2 hits / 12s", ...
        'LunarisAttackName', "HoverAttack_Bullet_01", ...
        'LunarisDamageParam', "ElementalArt_Bullet_Damage", ...
        'AllowTransformative', double(swirlReady), ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Supporting Fire tap");
    actions.SupportHold = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "TonicshotDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', holdShotCount, ...
        'HitTimeline', holdTimeline, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Ifa_SupportingFire", ...
        'ICDRule', "2 hits / 12s", ...
        'LunarisAttackName', "HoverAttack_Bullet_01", ...
        'LunarisDamageParam', "ElementalArt_Bullet_Damage", ...
        'AllowTransformative', double(swirlReady), ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'C6FlatDirectATKWeight', 0.60 / holdShotCount, ...
        'Note', "Supporting Fire hold");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Bullet", ...
        'LunarisDamageParam', "ElementalBurst_Damage", ...
        'AllowTransformative', double(swirlReady), ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'PostSetBurstActiveTime', 15.0, ...
        'Note', "Compound Sedation Field");
    actions.Mark = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SedationMarkDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', absorbedElement, ...
        'BaseMultiplier', 1.00, ...
        'HitCount', markHitCount, ...
        'HitTimeline', markTimeline, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Ifa_SedationMark", ...
        'ICDRule', "2 hits / 2s", ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "ElementalBurst_ExtraHit_Damage", ...
        'AllowAmplify', double(any(strcmpi(absorbedElement, {'Hydro', 'Pyro', 'Cryo'})) && (pyroCount + hydroCount + cryoCount) >= 1), ...
        'AllowTransformative', double(burstReactionReady), ...
        'PreferredAmplifyAura', localResolvePreferredAura(absorbedElement, teamContext), ...
        'ReactionBonus', rescueBonus * double(any(strcmpi(absorbedElement, {'Hydro', 'Pyro', 'Cryo', 'Electro'}))), ...
        'Note', "Sedation field extra hits");

    spec = struct( ...
        'Element', "Anemo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.8, ...
        'DefaultRotation', {{'Q', 'Mark', 'ECast', 'SupportTap', 'SupportHold', 'CA'}}, ...
        'ActionTimeMap', struct('N1', 0.34, 'N2', 0.34, 'N3', 0.42, 'CA', 0.80, ...
            'ECast', 0.55, 'SupportTap', 0.50, 'SupportHold', 1.90, 'Q', 0.95, 'Mark', 7.60), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Ifa', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function element = localResolveIfaBurstElement(teamContext)
    priority = ["Hydro", "Pyro", "Electro", "Cryo"];
    counts = [ ...
        getFieldOrDefault(teamContext, 'HydroCount', 0), ...
        getFieldOrDefault(teamContext, 'PyroCount', 0), ...
        getFieldOrDefault(teamContext, 'ElectroCount', 0), ...
        getFieldOrDefault(teamContext, 'CryoCount', 0)];

    element = "Anemo";
    bestCount = 0;
    for i = 1:numel(priority)
        if counts(i) > bestCount
            bestCount = counts(i);
            element = priority(i);
        end
    end
end

function aura = localResolvePreferredAura(element, teamContext)
    element = string(element);
    switch lower(char(element))
        case 'hydro'
            if getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1
                aura = "Pyro";
            else
                aura = "";
            end
        case 'pyro'
            if getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1
                aura = "Hydro";
            elseif getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1
                aura = "Cryo";
            else
                aura = "";
            end
        case 'cryo'
            if getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1
                aura = "Pyro";
            else
                aura = "";
            end
        otherwise
            aura = "";
    end
end
