function build = customArtifact_Yaoyao()
    % Default Yaoyao build balancing healing uptime and some Dendro damage.
    build = struct( ...
        'Weapon', 'FavoniusLance', ...
        'WeaponATK', 565, ...
        'HPBonus', 0.96, ...
        'FlatHP', 4780, ...
        'ER', 1.80, ...
        'CritRate', 0.45, ...
        'CritDMG', 1.10, ...
        'DendroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.15, ...
        'BurstDMGBonus', 0.15, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'DeepwoodMemories', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Yaoyao', 'artifacts_Yaoyao.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
