function build = customArtifact_Mika()
    % Default Mika build for physical support, healing, and burst consistency.
    build = struct( ...
        'Weapon', '西风长枪', ...
        'WeaponATK', 565, ...
        'WeaponSubStatType', 'ER', ...
        'WeaponSubStatValue', 0.306268198, ...
        'WeaponRefinement', 5, ...
        'HPBonus', 0.84, ...
        'FlatHP', 4780, ...
        'AtkBonus', 0.22, ...
        'FlatATK', 180, ...
        'ER', 1.95, ...
        'EM', 40, ...
        'CritRate', 0.42, ...
        'CritDMG', 0.80, ...
        'CryoDMGBonus', 0.18, ...
        'SkillDMGBonus', 0.15, ...
        'BurstDMGBonus', 0.15, ...
        'HealingBonus', 0.359, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'NoblesseOblige', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Mika', 'artifacts_Mika.csv');
    writetable(struct2table(build), outputPath);
end
