function [totalDMG, dps, breakdown, rotationTime] = simulateMikaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Mika simulator for direct skill damage contribution in physical support rotations.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Mika', 'rotation_Mika.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Mika', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.EArrow = struct('TalentGroup', "Skill", 'Param', "FlowfrostArrowDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'Note', "Flowfrost Arrow");
    actions.Flare = struct('TalentGroup', "Skill", 'Param', "RimestarFlareDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'Note', "Rimestar Flare");
    actions.Shard = struct('TalentGroup', "Skill", 'Param', "RimestarShardDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 1 + double(constellation >= 2), 'Note', "Rimestar Shard");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "CastHealing", 'MVOverride', 0, ...
        'DamageField', "BurstDMGBonus", 'PostSetBurstActiveTime', 15.0, 'Note', "Skyfeather Song");

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.70, ...
        'DefaultRotation', {{'EArrow', 'Flare', 'Shard', 'Q'}}, ...
        'ActionTimeMap', struct('EArrow', 0.55, 'Flare', 0.25, 'Shard', 0.20, 'Q', 0.90), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Mika', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
