function build = customArtifact_Nilou()
    % 妮露默认构筑。
    % 默认面板以生命值为核心，同时兼顾一定精通，用于模拟水伤和
    % 丰穰之核两部分贡献。
    build = struct( ...
        'Weapon', 'KeyOfKhajNisut', ...
        'WeaponATK', 542, ...
        'HPBonus', 1.86, ...
        'FlatHP', 4780, ...
        'CritRate', 0.36, ...
        'CritDMG', 1.18, ...
        'HydroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 320, ...
        'ResShred', 0.00 ...
    );

    % 回写 CSV，便于和脚本内默认值保持一致。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Nilou', 'artifacts_Nilou.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
