function build = customArtifact_Faruzan()
    % Default Faruzan build favoring burst uptime and personal Anemo damage.
    build = struct( ...
        'Weapon', 'ElegyForTheEnd', ...
        'WeaponATK', 608, ...
        'AtkBonus', 0.46, ...
        'FlatATK', 120, ...
        'ER', 1.85, ...
        'CritRate', 0.55, ...
        'CritDMG', 1.55, ...
        'AnemoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'ViridescentVenerer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Faruzan', 'artifacts_Faruzan.csv');
    writetable(struct2table(build), outputPath);
end
