function [totalDMG, dps, breakdown, rotationTime, audit] = simulateSayuDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Sayu simulator with tap / hold roll split, absorbed roll segment, and
    % Muji-Muji Daruma attack ticks including C6 EM scaling.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Sayu', 'rotation_Sayu.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Sayu', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    absorbedElement = localResolveSayuAbsorbedElement(teamContext, enemy);
    absorbedReady = double(strlength(absorbedElement) > 0);
    emValue = getFieldOrDefault(build, 'EM', 0) + getFieldOrDefault(teamContext, 'EMBonus', 0);
    c6DarumaAtkBonus = min(4.0, 0.002 * emValue) * double(constellation >= 6);

    actions = struct();
    actions.EPress = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "xFuufuuWhirlwindKickPressDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Click", ...
        'LunarisDamageParam', "Click_StrikeDamage", ...
        'Note', "Fuuin Dash press");
    actions.Roll = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "FuufuuWindwheelDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', 8, ...
        'HitTimeline', 0.55 * ones(1, 8), ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Roll_Bullet", ...
        'LunarisDamageParam', "Roll_Damage", ...
        'Note', "Windwheel roll");
    actions.RollMix = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "FuufuuWindwheelElementalDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', absorbedElement, ...
        'BaseMultiplier', absorbedReady, ...
        'HitCount', 8, ...
        'HitTimeline', 0.55 * ones(1, 8), ...
        'AllowAmplify', localSayuAllowsAmplify(absorbedElement, teamContext), ...
        'AllowCatalyze', localSayuAllowsCatalyze(absorbedElement, teamContext), ...
        'PreferredAmplifyAura', localSayuPreferredAura(absorbedElement, teamContext), ...
        'ApplyGauge', 1.0 * absorbedReady, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Roll_Bullet", ...
        'LunarisDamageParam', "MixRoll_Damage", ...
        'Note', "Absorbed roll damage");
    actions.EHoldEnd = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "FuufuuWhirlwindKickHoldDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Hold", ...
        'LunarisDamageParam', "Hold_StrikeDamage", ...
        'Note', "Hold finisher");
    actions.EHoldMix = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "FuufuuWhirlwindKickElementalDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', absorbedElement, ...
        'BaseMultiplier', absorbedReady, ...
        'AllowAmplify', localSayuAllowsAmplify(absorbedElement, teamContext), ...
        'AllowCatalyze', localSayuAllowsCatalyze(absorbedElement, teamContext), ...
        'PreferredAmplifyAura', localSayuPreferredAura(absorbedElement, teamContext), ...
        'ApplyGauge', 1.0 * absorbedReady, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Hold", ...
        'LunarisDamageParam', "Hold_Mix_StrikeDamage", ...
        'Note', "Absorbed hold finisher");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillActivationDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "Damage_Ratio", ...
        'Note', "Mujina Flurry cast");
    actions.Daruma = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "MujiMujiDarumaDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00 + c6DarumaAtkBonus, ...
        'AllowTransformative', 1, ...
        'HitCount', 6, ...
        'HitTimeline', 2.0 * ones(1, 6), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Phantom", ...
        'LunarisDamageParam', "Damage_Ratio|Constellation_6_Damage|ADD", ...
        'Note', "Daruma attacks");

    defaultRotation = {'EPress', 'Roll', 'RollMix', 'EHoldEnd', 'EHoldMix', 'Q', 'Daruma'};
    spec = struct( ...
        'Element', "Anemo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.70, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct( ...
            'EPress', 0.42, ...
            'Roll', 4.40, ...
            'RollMix', 4.40, ...
            'EHoldEnd', 0.35, ...
            'EHoldMix', 0.10, ...
            'Q', 0.95, ...
            'Daruma', 12.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Sayu', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function element = localResolveSayuAbsorbedElement(teamContext, enemy)
    if nargin >= 2 && isstruct(enemy)
        initialAura = string(getFieldOrDefault(enemy, 'InitialAuraElement', ""));
        if any(strcmpi(initialAura, ["Pyro", "Hydro", "Electro", "Cryo"]))
            element = string(initialAura);
            return;
        end
    end

    priority = ["Pyro", "Hydro", "Electro", "Cryo"];
    for i = 1:numel(priority)
        if getFieldOrDefault(teamContext, char(priority(i) + "Count"), 0) >= 1
            element = priority(i);
            return;
        end
    end
    element = "";
end

function tf = localSayuAllowsAmplify(element, teamContext)
    switch lower(char(string(element)))
        case 'pyro'
            tf = double(getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1 || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1);
        case 'hydro'
            tf = double(getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1);
        case 'cryo'
            tf = double(getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1);
        otherwise
            tf = 0;
    end
end

function tf = localSayuAllowsCatalyze(element, teamContext)
    switch lower(char(string(element)))
        case 'electro'
            tf = double(getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1);
        otherwise
            tf = 0;
    end
end

function aura = localSayuPreferredAura(element, teamContext)
    switch lower(char(string(element)))
        case 'pyro'
            if getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1
                aura = "Hydro";
            elseif getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1
                aura = "Cryo";
            else
                aura = "";
            end
        case 'hydro'
            aura = "Pyro";
        case 'cryo'
            aura = "Pyro";
        otherwise
            aura = "";
    end
end
