function [totalDMG, dps, breakdown, rotationTime, audit] = simulateRosariaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Rosaria simulator with double-hit skill, burst lance deployment, and
    % periodic cryo ticks.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Rosaria', 'rotation_Rosaria.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Rosaria', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    meltReady = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1;
    burstTickCount = 6 + 2 * double(constellation >= 2);
    burstTimeline = 1.0 * ones(1, burstTickCount);
    c6ResShred = 0.20 * double(constellation >= 6);

    actions = struct();
    actions.E1 = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Spear", ...
        'LunarisAttackName', "ElementalArt_Strike_01", ...
        'LunarisDamageParam', "Damage_01", ...
        'Note', "Ravaging Confession first hit");
    actions.E2 = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Slash", ...
        'LunarisAttackName', "ElementalArt_Strike_02", ...
        'LunarisDamageParam', "Damage_02", ...
        'Note', "Ravaging Confession second hit");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'PostSetBurstActiveTime', 8.0, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Slash", ...
        'LunarisAttackName', "ElementalBurst_Strike_01", ...
        'LunarisDamageParam', "Damage_01", ...
        'Note', "Rites of Termination impact");
    actions.QTick = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "IceLanceDoT", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', burstTickCount, ...
        'HitTimeline', burstTimeline, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ExtraResShred', c6ResShred, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Gadget_Material", ...
        'LunarisDamageParam', "Interval_Damage", ...
        'Note', "Ice Lance ticks");
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Normal 1");

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Pyro", ...
        'DefaultActionTime', 0.60, ...
        'DefaultRotation', {{'E1', 'E2', 'Q', 'QTick', 'N1'}}, ...
        'ActionTimeMap', struct( ...
            'E1', 0.18, ...
            'E2', 0.48, ...
            'Q', 0.92, ...
            'QTick', 8.00, ...
            'N1', 0.34), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Rosaria', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
