function [totalDMG, dps, breakdown, rotationTime, audit] = simulateAlbedoDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Albedo simulator with solar isotoma placement, transient blossom
    % ticks, and burst fatal blossom handling.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Albedo', 'rotation_Albedo.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Albedo', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talent = readtable(char(resolveCharacterDataFile('Albedo', 'talents')));
    skillLevel = talentLevel + 3 * double(constellation >= 3);
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    blossomCount = 7;

    workBuild = build;
    workBuild.DEFBonus = getFieldOrDefault(workBuild, 'DEFBonus', 0);

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Geo", ...
        'ActionScalingMode', "ATK", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "SkillObj_FuriousMonolith", ...
        'LunarisDamageParam', "OpeningDamage", ...
        'Note', "Abiogenesis: Solar Isotoma cast");
    actions.Field = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "TransientBlossomDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Geo", ...
        'ActionScalingMode', "DEF", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', blossomCount, ...
        'HitTimeline', 1.80 * ones(1, blossomCount), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "SkillObj_FuriousMonolith_Field", ...
        'LunarisDamageParam', "-", ...
        'Note', "Transient Blossom field ticks");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "BurstDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Geo", ...
        'ActionScalingMode', "ATK", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "AlchemicalBreakOut", ...
        'LunarisDamageParam', "OpeningDamage", ...
        'Note', "Rite of Progeniture: Tectonic Tide");
    actions.Fatal = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "FatalBlossomDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Geo", ...
        'ActionScalingMode', "ATK", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', blossomCount, ...
        'HitTimeline', 0.15 * ones(1, blossomCount), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "SkillObj_FuriousMonolith_FullBloom", ...
        'LunarisDamageParam', "Damage_Burst", ...
        'Note', "Fatal Blossom follow-up");
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'ICDRule', "Independent", ...
        'Note', "Filler normal attack");

    if constellation >= 2
        workBuild.GeoDMGBonus = getFieldOrDefault(workBuild, 'GeoDMGBonus', 0) + 0.15;
    end
    if constellation >= 4
        workBuild.SkillDMGBonus = getFieldOrDefault(workBuild, 'SkillDMGBonus', 0) + 0.30;
    end

    spec = struct( ...
        'Element', "Geo", ...
        'ScalingMode', "DEF", ...
        'DefaultActionTime', 0.60, ...
        'DefaultRotation', {{'E', 'Field', 'Field', 'Q', 'Fatal', 'Field', 'Field', 'N1'}}, ...
        'ActionTimeMap', struct( ...
            'E', 0.68, ...
            'Field', 1.80, ...
            'Q', 1.00, ...
            'Fatal', 0.18, ...
            'N1', 0.42), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Albedo', workBuild, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
