function build = customArtifact_Barbara()
    % Default Barbara build for healing support with some burst contribution.
    build = struct( ...
        'Weapon', 'ThrillingTalesOfDragonSlayers', ...
        'WeaponATK', 401, ...
        'WeaponSubStatType', 'HP', ...
        'WeaponSubStatValue', 0.352, ...
        'WeaponRefinement', 5, ...
        'HPBonus', 0.92, ...
        'FlatHP', 4780, ...
        'ER', 1.60, ...
        'HealingBonus', 0.359, ...
        'HydroDMGBonus', 0.00, ...
        'BurstDMGBonus', 0.10, ...
        'ArtifactSet1', 'OceanHuedClam', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Barbara', 'artifacts_Barbara.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
