function build = customArtifact_YunJin()
    % Default Yun Jin build for DEF-based burst support and quickswap damage.
    build = struct( ...
        'Weapon', 'FavoniusLance', ...
        'WeaponATK', 565, ...
        'WeaponSubStatType', 'ER', ...
        'WeaponSubStatValue', 0.306, ...
        'WeaponRefinement', 1, ...
        'DEFBonus', 0.58, ...
        'FlatDEF', 120, ...
        'ER', 1.95, ...
        'CritRate', 0.45, ...
        'CritDMG', 1.10, ...
        'GeoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.18, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'HuskOfOpulentDreams', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'YunJin', 'artifacts_YunJin.csv');
    writetable(struct2table(build), outputPath);
end
