function build = customArtifact_LanYan()
    % Default Lan Yan build for catalyst anemo damage and burst cadence.
    build = struct( ...
        'Weapon', 'Sacrificial Jade', ...
        'WeaponATK', 454, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.368, ...
        'WeaponRefinement', 5, ...
        'AtkBonus', 0.82, ...
        'FlatATK', 311, ...
        'EM', 140, ...
        'ER', 1.25, ...
        'CritRate', 0.78, ...
        'CritDMG', 1.92, ...
        'AnemoDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.16, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'ViridescentVenerer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'LanYan', 'artifacts_LanYan.csv');
    if exist(fileparts(outputPath), 'dir') ~= 7
        mkdir(fileparts(outputPath));
    end
    writetable(struct2table(build), outputPath);
end
