function [totalDMG, dps, breakdown, rotationTime, audit] = simulateLanYanDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Lan Yan simulator with dash hit, ring bounces, absorbed bonus hits,
    % EM conversion on skill/burst, and C1/C6 extra ring support.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'LanYan', 'rotation_LanYan.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'LanYan', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    absorbedElement = localResolveLanYanElement(teamContext);
    absorbedReady = absorbedElement ~= "";
    hitElement = "Anemo";
    if ~absorbedReady
        absorbedElement = "Anemo";
    end

    burstHitCount = 3;
    burstTimeline = [0.00, 0.08, 0.08];
    ringCount = 3;
    ringTimeline = [0.00, 0.24, 0.24];
    burstFlatEMWeight = 7.74 / burstHitCount;
    baseRingAttack = localResolveLanYanRingAttack(absorbedReady, absorbedElement, false);
    extraRingAttack = localResolveLanYanRingAttack(absorbedReady, absorbedElement, true);

    allowAbsorbAmplify = any(strcmpi(absorbedElement, {'Hydro', 'Pyro', 'Cryo'}));
    allowAbsorbCatalyze = strcmpi(absorbedElement, 'Electro');
    allowAbsorbTransformative = any(strcmpi(absorbedElement, {'Hydro', 'Pyro', 'Cryo', 'Electro'}));

    actions = struct();
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Normal 2");
    actions.N3 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Normal 3");
    actions.N4 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x4HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Normal 4");
    actions.Charged = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Charged ring throw");
    actions.EDash = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "FeathermoonRingDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', hitElement, ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectEMWeight', 3.09, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "LanYan_Skill", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'LunarisAttackName', "ElementalArt_Bullet_Wind", ...
        'LunarisDamageParam', "Lanyan_ElementalArt_Base_Damage", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Swallow-Wisp dash");
    actions.ERing = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "FeathermoonRingDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', hitElement, ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectEMWeight', 3.09, ...
        'HitCount', ringCount, ...
        'HitTimeline', ringTimeline, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "LanYan_Skill", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'LunarisAttackName', baseRingAttack, ...
        'LunarisDamageParam', "Lanyan_ElementalArt_Base_Damage", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Feathermoon ring bounces");
    if absorbedReady
        actions.EAbsorb = struct( ...
            'TalentGroup', "Skill", ...
            'Param', "FeathermoonRingDMG", ...
            'DamageField', "SkillDMGBonus", ...
            'ActionElement', absorbedElement, ...
            'BaseMultiplier', 0.50, ...
            'FlatDirectEMWeight', 3.09 * 0.50, ...
            'HitCount', ringCount, ...
            'HitTimeline', ringTimeline, ...
            'ApplyGauge', 1.0, ...
            'ICDGroup', "LanYan_Skill_Mix", ...
            'ICDRule', "Standard (3h/2.5s)", ...
            'LunarisAttackName', baseRingAttack, ...
            'LunarisDamageParam', "Lanyan_ElementalArt_Base_Damage|Lanyan_ElementalArt_Ratio_Damage|MUL", ...
            'AllowAmplify', double(allowAbsorbAmplify), ...
            'AllowCatalyze', double(allowAbsorbCatalyze), ...
            'AllowTransformative', double(allowAbsorbTransformative), ...
            'PreferredAmplifyAura', localResolveLanYanAura(absorbedElement, teamContext), ...
            'Note', "Absorbed ring damage");

        if constellation >= 1
            actions.ERingExtra = struct( ...
                'TalentGroup', "Skill", ...
                'Param', "FeathermoonRingDMG", ...
                'DamageField', "SkillDMGBonus", ...
                'ActionElement', hitElement, ...
                'BaseMultiplier', 1.00, ...
                'FlatDirectEMWeight', 3.09, ...
                'HitCount', ringCount, ...
                'HitTimeline', ringTimeline, ...
                'ApplyGauge', 1.0, ...
                'ICDGroup', "LanYan_Skill", ...
                'ICDRule', "Standard (3h/2.5s)", ...
                'LunarisAttackName', extraRingAttack, ...
                'LunarisDamageParam', "Lanyan_ElementalArt_Base_Damage", ...
                'AllowTransformative', 1, ...
                'ReactionElement', "Anemo", ...
                'ReactionBaseDamage', 723.0, ...
                'Note', "C1 extra Feathermoon ring");
            actions.EAbsorbExtra = struct( ...
                'TalentGroup', "Skill", ...
                'Param', "FeathermoonRingDMG", ...
                'DamageField', "SkillDMGBonus", ...
                'ActionElement', absorbedElement, ...
                'BaseMultiplier', 0.50, ...
                'FlatDirectEMWeight', 3.09 * 0.50, ...
                'HitCount', ringCount, ...
                'HitTimeline', ringTimeline, ...
                'ApplyGauge', 1.0, ...
                'ICDGroup', "LanYan_Skill_Mix", ...
                'ICDRule', "Standard (3h/2.5s)", ...
                'LunarisAttackName', extraRingAttack, ...
                'LunarisDamageParam', "Lanyan_ElementalArt_Base_Damage|Lanyan_ElementalArt_Ratio_Damage|MUL", ...
                'AllowAmplify', double(allowAbsorbAmplify), ...
                'AllowCatalyze', double(allowAbsorbCatalyze), ...
                'AllowTransformative', double(allowAbsorbTransformative), ...
                'PreferredAmplifyAura', localResolveLanYanAura(absorbedElement, teamContext), ...
                'Note', "C1 absorbed extra ring");
        end
    end
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectEMWeight', burstFlatEMWeight, ...
        'HitCount', burstHitCount, ...
        'HitTimeline', burstTimeline, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'PostSetBurstActiveTime', 12.0, ...
        'LunarisAttackName', "ElementalBurst_Bullet_2", ...
        'LunarisDamageParam', "Lanyan_ElementalBurst_Base_Damage", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Lustrous Moonrise");

    defaultRotation = {'EDash', 'ERing'};
    if absorbedReady
        defaultRotation{end + 1} = 'EAbsorb'; %#ok<AGROW>
        if constellation >= 1
            defaultRotation{end + 1} = 'ERingExtra'; %#ok<AGROW>
            defaultRotation{end + 1} = 'EAbsorbExtra'; %#ok<AGROW>
        end
    end
    defaultRotation{end + 1} = 'Q'; %#ok<AGROW>
    defaultRotation{end + 1} = 'Charged'; %#ok<AGROW>

    spec = struct( ...
        'Element', "Anemo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.8, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct('N1', 0.34, 'N2', 0.38, 'N3', 0.40, 'N4', 0.48, ...
            'Charged', 0.72, 'EDash', 0.45, 'ERing', 0.85, 'EAbsorb', 0.01, ...
            'ERingExtra', 0.01, 'EAbsorbExtra', 0.01, 'Q', 1.00), ...
        'InitializeStateFn', @localInitializeLanYanState, ...
        'AfterActionFn', @localAfterLanYanAction, ...
        'AdvanceStateFn', @localAdvanceLanYanState, ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'LanYan', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function state = localInitializeLanYanState(state, hookContext) %#ok<INUSD>
    state.TempEMBonus = 0;
    state.TempEMWindow = 0;
end

function [state, note] = localAfterLanYanAction(state, actionKey, actionSpec, actionDamage, reactionTags, note, hookContext) %#ok<INUSD>
    if actionKey == "Q" && getFieldOrDefault(hookContext, 'Constellation', 0) >= 4
        state.TempEMBonus = 60;
        state.TempEMWindow = 12.0;
        note = localAppendLanYanNote(note, "C4 EM");
    end
end

function state = localAdvanceLanYanState(state, actionTime, hookContext) %#ok<INUSD>
    if isfield(state, 'TempEMWindow') && state.TempEMWindow > 0
        state.TempEMWindow = max(0, state.TempEMWindow - actionTime);
        if state.TempEMWindow <= 1e-9
            state.TempEMBonus = 0;
        end
    end
end

function note = localAppendLanYanNote(baseNote, suffix)
    if strlength(string(baseNote)) == 0
        note = string(suffix);
    else
        note = string(baseNote) + ", " + string(suffix);
    end
end

function attackName = localResolveLanYanRingAttack(absorbedReady, element, useExtra)
    if absorbedReady
        attackName = localResolveLanYanAbsorbAttack(element, useExtra);
    else
        attackName = "ElementalArt_Bullet_Wind";
    end
end

function element = localResolveLanYanElement(teamContext)
    priority = ["Pyro", "Hydro", "Electro", "Cryo"];
    counts = [ ...
        getFieldOrDefault(teamContext, 'PyroCount', 0), ...
        getFieldOrDefault(teamContext, 'HydroCount', 0), ...
        getFieldOrDefault(teamContext, 'ElectroCount', 0), ...
        getFieldOrDefault(teamContext, 'CryoCount', 0)];
    bestCount = 0;
    element = "";
    for i = 1:numel(priority)
        if counts(i) > bestCount
            bestCount = counts(i);
            element = priority(i);
        end
    end
end

function attackName = localResolveLanYanAbsorbAttack(element, useExtra)
    suffix = lower(char(string(element)));
    switch suffix
        case 'pyro'
            base = "ElementalArt_Bullet_Fire";
        case 'hydro'
            base = "ElementalArt_Bullet_Water";
        case 'electro'
            base = "ElementalArt_Bullet_Electric";
        case 'cryo'
            base = "ElementalArt_Bullet_Ice";
        otherwise
            base = "ElementalArt_Bullet_Wind";
    end
    if useExtra && base ~= "ElementalArt_Bullet_Wind"
        attackName = base + "_Extra";
    else
        attackName = base;
    end
end

function aura = localResolveLanYanAura(element, teamContext)
    switch lower(char(string(element)))
        case 'hydro'
            aura = "Pyro";
            if getFieldOrDefault(teamContext, 'PyroCount', 0) <= 0
                aura = "";
            end
        case 'pyro'
            if getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1
                aura = "Hydro";
            elseif getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1
                aura = "Cryo";
            else
                aura = "";
            end
        case 'cryo'
            if getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1
                aura = "Pyro";
            else
                aura = "";
            end
        otherwise
            aura = "";
    end
end
