function [totalDMG, dps, breakdown, rotationTime, audit] = simulateLanYanDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Lan Yan simulator with dash hit, ring bounces, absorbed bonus hits,
    % EM conversion on skill/burst, and C1/C6 extra ring support.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'LanYan', 'rotation_LanYan.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'LanYan', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    absorbedElement = localResolveLanYanElement(teamContext);
    absorbedReady = absorbedElement ~= "";
    hitElement = "Anemo";
    if ~absorbedReady
        absorbedElement = "Anemo";
    end

    burstHitCount = 4;
    burstTimeline = [0.00, 0.08, 0.08, 0.08];
    ringCount = 3 + double(constellation >= 1);
    ringTimeline = [0.00, 0.24, 0.24];
    ringTimeline = ringTimeline(1:ringCount);
    if numel(ringTimeline) < ringCount
        ringTimeline(end + 1:ringCount) = 0.24; %#ok<AGROW>
    end

    allowAbsorbAmplify = any(strcmpi(absorbedElement, {'Hydro', 'Pyro', 'Cryo'}));
    allowAbsorbCatalyze = strcmpi(absorbedElement, 'Electro');
    allowAbsorbTransformative = any(strcmpi(absorbedElement, {'Hydro', 'Pyro', 'Cryo', 'Electro'}));

    actions = struct();
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 0.50, ...
        'HitCount', 2, ...
        'HitTimeline', [0.00, 0.08], ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "LanYan_Normal", ...
        'ICDRule', "Independent", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Normal 2");
    actions.N3 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 0.50, ...
        'HitCount', 2, ...
        'HitTimeline', [0.00, 0.10], ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "LanYan_Normal", ...
        'ICDRule', "Independent", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Normal 3");
    actions.N4 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x4HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Normal 4");
    actions.Charged = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', 3, ...
        'HitTimeline', [0.00, 0.08, 0.08], ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "LanYan_Charged", ...
        'ICDRule', "Independent", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Charged ring throw");
    actions.EDash = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "FeathermoonRingDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', hitElement, ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectEMWeight', 3.09, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "LanYan_Skill", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'LunarisAttackName', "ElementalArt_Bullet_Wind", ...
        'LunarisDamageParam', "Lanyan_ElementalArt_Base_Damage", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Swallow-Wisp dash");
    actions.ERing = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "FeathermoonRingDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', hitElement, ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectEMWeight', 3.09, ...
        'HitCount', ringCount, ...
        'HitTimeline', ringTimeline, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "LanYan_Skill", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'LunarisAttackName', "ElementalArt_Bullet_Wind", ...
        'LunarisDamageParam', "Lanyan_ElementalArt_Base_Damage", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Feathermoon ring bounces");
    actions.EAbsorb = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "FeathermoonRingDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', absorbedElement, ...
        'BaseMultiplier', 0.50, ...
        'FlatDirectEMWeight', 3.09 * 0.50, ...
        'HitCount', ringCount, ...
        'HitTimeline', ringTimeline, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "LanYan_Skill_Mix", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'LunarisAttackName', localResolveLanYanAbsorbAttack(absorbedElement, constellation >= 1), ...
        'LunarisDamageParam', "Lanyan_ElementalArt_Base_Damage|Lanyan_ElementalArt_Ratio_Damage|MUL", ...
        'AllowAmplify', double(allowAbsorbAmplify), ...
        'AllowCatalyze', double(allowAbsorbCatalyze), ...
        'AllowTransformative', double(allowAbsorbTransformative), ...
        'PreferredAmplifyAura', localResolveLanYanAura(absorbedElement, teamContext), ...
        'Note', "Absorbed ring damage");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectEMWeight', 7.74, ...
        'HitCount', burstHitCount, ...
        'HitTimeline', burstTimeline, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Bullet_2", ...
        'LunarisDamageParam', "Lanyan_ElementalBurst_Base_Damage", ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Anemo", ...
        'ReactionBaseDamage', 723.0, ...
        'Note', "Lustrous Moonrise");

    defaultRotation = {'EDash', 'ERing'};
    if absorbedReady
        defaultRotation{end + 1} = 'EAbsorb'; %#ok<AGROW>
    end
    defaultRotation{end + 1} = 'Q'; %#ok<AGROW>
    defaultRotation{end + 1} = 'Charged'; %#ok<AGROW>

    spec = struct( ...
        'Element', "Anemo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.8, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct('N1', 0.34, 'N2', 0.38, 'N3', 0.40, 'N4', 0.48, ...
            'Charged', 0.72, 'EDash', 0.45, 'ERing', 0.85, 'EAbsorb', 0.01, 'Q', 1.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'LanYan', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function element = localResolveLanYanElement(teamContext)
    priority = ["Pyro", "Hydro", "Electro", "Cryo"];
    counts = [ ...
        getFieldOrDefault(teamContext, 'PyroCount', 0), ...
        getFieldOrDefault(teamContext, 'HydroCount', 0), ...
        getFieldOrDefault(teamContext, 'ElectroCount', 0), ...
        getFieldOrDefault(teamContext, 'CryoCount', 0)];
    bestCount = 0;
    element = "";
    for i = 1:numel(priority)
        if counts(i) > bestCount
            bestCount = counts(i);
            element = priority(i);
        end
    end
end

function attackName = localResolveLanYanAbsorbAttack(element, useExtra)
    suffix = lower(char(string(element)));
    switch suffix
        case 'pyro'
            base = "ElementalArt_Bullet_Fire";
        case 'hydro'
            base = "ElementalArt_Bullet_Water";
        case 'electro'
            base = "ElementalArt_Bullet_Electric";
        case 'cryo'
            base = "ElementalArt_Bullet_Ice";
        otherwise
            base = "ElementalArt_Bullet_Wind";
    end
    if useExtra && base ~= "ElementalArt_Bullet_Wind"
        attackName = base + "_Extra";
    else
        attackName = base;
    end
end

function aura = localResolveLanYanAura(element, teamContext)
    switch lower(char(string(element)))
        case 'hydro'
            aura = "Pyro";
            if getFieldOrDefault(teamContext, 'PyroCount', 0) <= 0
                aura = "";
            end
        case 'pyro'
            if getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1
                aura = "Hydro";
            elseif getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1
                aura = "Cryo";
            else
                aura = "";
            end
        case 'cryo'
            if getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1
                aura = "Pyro";
            else
                aura = "";
            end
        otherwise
            aura = "";
    end
end
