function build = customArtifact_Kaveh()
    % Default Kaveh build targeting bloom ownership and burst-empowered Dendro core damage.
    build = struct( ...
        'Weapon', '饰铁之花', ...
        'WeaponATK', 565, ...
        'WeaponSubStatType', 'EM', ...
        'WeaponSubStatValue', 110.26, ...
        'WeaponRefinement', 5, ...
        'AtkBonus', 0.46, ...
        'FlatATK', 220, ...
        'ER', 1.60, ...
        'EM', 860, ...
        'CritRate', 0.35, ...
        'CritDMG', 0.85, ...
        'DendroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.18, ...
        'ReactionDMGBonus', 0.25, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'FlowerOfParadiseLost', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Kaveh', 'artifacts_Kaveh.csv');
    writetable(struct2table(build), outputPath);
end
