function [totalDMG, dps, breakdown, rotationTime] = simulateKavehDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Kaveh simulator covering burst-infused Dendro normals plus owned Bloom explosions in Hydro teams.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Kaveh', 'rotation_Kaveh.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Kaveh', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Kaveh', 'talents_Kaveh.csv');
    talent = readtable(talentPath);
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    coreBonus = getTalentValue(talent, 'Burst', 'DendroCoreBurstDMGBonus', burstLevel) ...
        + getFieldOrDefault(teamContext, 'NilouBloomBonus', 0) ...
        + getFieldOrDefault(teamContext, 'LunarBloomBonus', 0);
    bloomReady = getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1;
    spreadReady = getFieldOrDefault(teamContext, 'ElectroCount', 0) >= 1;

    actions = struct();
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'PostSetBurstActiveTime', 12.0, ...
        'LunarisAttackName', "ElementalBurst", 'LunarisDamageParam', "Kaveh_ElementalBurst_Damage", 'Note', "Painted Dome");
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(spreadReady), 'Note', "Burst normal 1");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(spreadReady), 'Note', "Burst normal 2");
    actions.N3 = struct('TalentGroup', "Normal", 'Param', "x3HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(spreadReady), 'Note', "Burst normal 3");
    actions.N4 = struct('TalentGroup', "Normal", 'Param', "x4HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(spreadReady), 'Note', "Burst normal 4");
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(spreadReady), ...
        'LunarisAttackName', "ElementalArt", 'LunarisDamageParam', "Kaveh_ElementalArt_Damage", 'Note', "Artistic Ingenuity");
    actions.Core = struct('TalentGroup', "Burst", 'Param', "DendroCoreBurstDMGBonus", 'MVOverride', 0, ...
        'DamageField', "BurstDMGBonus", 'AllowTransformative', 1, 'ReactionElement', "Dendro", ...
        'ReactionBaseDamage', 2893, 'ReactionBonus', coreBonus, ...
        'ReactionCritRate', getFieldOrDefault(teamContext, 'ReactionCritRate', []), ...
        'ReactionCritDMG', getFieldOrDefault(teamContext, 'ReactionCritDMG', []), ...
        'Note', "Bloom detonation");

    if bloomReady
        defaultRotation = {'Q', 'N1', 'N2', 'Core', 'N3', 'Core', 'E', 'Core', 'N4', 'Core', 'Core', 'Core'};
    else
        defaultRotation = {'Q', 'N1', 'N2', 'N3', 'E', 'N4'};
    end

    spec = struct( ...
        'Element', "Dendro", ...
        'ScalingMode', "ATK", ...
        'ReactionBonusField', "ReactionDMGBonus", ...
        'DefaultActionTime', 0.80, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct('Q', 1.00, 'N1', 0.45, 'N2', 0.45, 'N3', 0.50, 'N4', 0.60, 'E', 0.80, 'Core', 0.40), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Kaveh', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
