function [totalDMG, dps, breakdown, rotationTime, audit] = simulateDionaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Diona simulator with tap / hold Icy Paws and burst field ticks.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Diona', 'rotation_Diona.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Diona', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    workTeamContext = teamContext;
    skillLevel = talentLevel + 3 * double(constellation >= 5);
    burstLevel = talentLevel + 3 * double(constellation >= 3);
    burstTickCount = 8;
    holdPawCount = 5;
    pawDamageBonus = 0.15 * double(constellation >= 2);
    if constellation >= 6
        workTeamContext.EMBonus = getFieldOrDefault(workTeamContext, 'EMBonus', 0) - 200;
    end
    fieldReactionEM = getFieldOrDefault(build, 'EM', 0) + getFieldOrDefault(workTeamContext, 'EMBonus', 0) ...
        + 200 * double(constellation >= 6);
    reactionProcReady = logical(getFieldOrDefault(workTeamContext, 'StellarConductEnabled', false)) ...
        || (getFieldOrDefault(workTeamContext, 'CryoCount', 0) >= 1 && getFieldOrDefault(workTeamContext, 'ElectroCount', 0) >= 1) ...
        || (getFieldOrDefault(workTeamContext, 'CryoCount', 0) >= 1 && getFieldOrDefault(workTeamContext, 'AnemoCount', 0) >= 1);
    p4ProcCount = 3 * double(reactionProcReady);
    p4Timeline = localBuildP4Timeline(p4ProcCount);

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "IcyPawDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', pawDamageBonus, ...
        'HitCount', 2, ...
        'HitTimeline', [0.00, 0.10], ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Diona_Paw", ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Bullet_Material", ...
        'LunarisDamageParam', "ElementalArt_Damage", ...
        'Note', "Icy Paws tap");
    actions.EHold = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "IcyPawDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', pawDamageBonus, ...
        'HitCount', holdPawCount, ...
        'HitTimeline', [0.00, 0.06, 0.06, 0.06, 0.06], ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Diona_Paw", ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Bullet_Material", ...
        'LunarisDamageParam', "ElementalArt_Damage", ...
        'Note', "Icy Paws hold");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Elemental_Art_Flask", ...
        'LunarisDamageParam', "Elemental_Burst_Damage", ...
        'Note', "Signature Mix cast");
    actions.QTick = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "ContinuousFieldDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', burstTickCount, ...
        'HitTimeline', [1.50 * ones(1, burstTickCount - 1), 1.50], ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ReactionEMOverride', fieldReactionEM, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Diona_Burst", ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "IceWine_Fog", ...
        'LunarisDamageParam', "Elemental_Burst_Damage", ...
        'Note', "Signature Mix field ticks");
    if p4ProcCount > 0
        actions.P4Paw = struct( ...
            'TalentGroup', "Skill", ...
            'TalentLevelOverride', skillLevel, ...
            'Param', "IcyPawDMG", ...
            'DamageField', "SkillDMGBonus", ...
            'ActionElement', "Cryo", ...
            'BaseMultiplier', 1.00, ...
            'HitCount', numel(p4Timeline), ...
            'HitTimeline', p4Timeline, ...
            'AllowAmplify', 1, ...
            'PreferredAmplifyAura', "Pyro", ...
            'ReactionEMOverride', fieldReactionEM, ...
            'ApplyGauge', 1.0, ...
            'ICDGroup', "Diona_P4Paw", ...
            'ICDRule', "1 hits / 3.5s", ...
            'LunarisAttackName', "ElementalArt_Bullet_Material", ...
            'LunarisDamageParam', "ElementalArt_Damage", ...
            'Note', "P4 reaction-triggered extra paws");
    end

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.70, ...
        'DefaultRotation', {{'EHold', 'Q', 'QTick'}}, ...
        'ActionTimeMap', struct( ...
            'E', 0.42, ...
            'EHold', 0.64, ...
            'Q', 0.95, ...
            'QTick', 12.00), ...
        'Actions', actions);

    if reactionProcReady
        spec.DefaultRotation = {{'EHold', 'Q', 'QTick', 'P4Paw'}};
    end

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Diona', build, enemy, seqFile, talentLevel, constellation, workTeamContext, spec);
end

function timeline = localBuildP4Timeline(procCount)
    timeline = [];
    if procCount <= 0
        return;
    end

    for procIndex = 1:procCount
        if procIndex == 1
            timeline = [timeline, 2.0, 0.05, 0.05]; %#ok<AGROW>
        else
            timeline = [timeline, 3.5, 0.05, 0.05]; %#ok<AGROW>
        end
    end
end
