function [totalDMG, dps, breakdown, rotationTime, audit] = simulateDionaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Diona simulator with tap / hold Icy Paws and burst field ticks.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Diona', 'rotation_Diona.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Diona', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    burstTickCount = 8;
    holdPawCount = 5;

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "IcyPawDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', 2, ...
        'HitTimeline', [0.00, 0.10], ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Diona_Paw", ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Bullet_Material", ...
        'LunarisDamageParam', "ElementalArt_Damage", ...
        'Note', "Icy Paws tap");
    actions.EHold = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "IcyPawDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', holdPawCount, ...
        'HitTimeline', [0.00, 0.06, 0.06, 0.06, 0.06], ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Diona_Paw", ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Bullet_Material", ...
        'LunarisDamageParam', "ElementalArt_Damage", ...
        'Note', "Icy Paws hold");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Elemental_Art_Flask", ...
        'LunarisDamageParam', "Elemental_Burst_Damage", ...
        'Note', "Signature Mix cast");
    actions.QTick = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "ContinuousFieldDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', burstTickCount, ...
        'HitTimeline', [1.50 * ones(1, burstTickCount - 1), 1.50], ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Diona_Burst", ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "IceWine_Fog", ...
        'LunarisDamageParam', "Elemental_Burst_Damage", ...
        'Note', "Signature Mix field ticks");

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.70, ...
        'DefaultRotation', {{'EHold', 'Q', 'QTick'}}, ...
        'ActionTimeMap', struct( ...
            'E', 0.42, ...
            'EHold', 0.64, ...
            'Q', 0.95, ...
            'QTick', 12.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Diona', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
