function build = customArtifact_Arlecchino()
    % Default baseline build used by standalone and unified-entry runs.
    build = struct( ...
        'Weapon', 'CrimsonMoon', ...
        'WeaponATK', 674, ...
        'AtkBonus', 1.05, ...
        'FlatATK', 311, ...
        'CritRate', 0.78, ...
        'CritDMG', 2.10, ...
        'PyroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.35, ...
        'SkillDMGBonus', 0.15, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 40, ...
        'ResShred', 0.00 ...
    );

    % Persist the baseline so analysis scripts can inspect or tweak the
    % same assumptions from CSV without duplicating these fields elsewhere.
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Arlecchino', 'artifacts_Arlecchino.csv');
    writetable(struct2table(build), outputPath);
end
