function build = customArtifact_Arlecchino()
    % 阿蕾奇诺默认构筑。
    % 作为单角色入口与统一入口的共享默认面板，同时会回写 CSV。
    build = struct( ...
        'Weapon', 'CrimsonMoon', ...
        'WeaponATK', 674, ...
        'AtkBonus', 1.05, ...
        'FlatATK', 311, ...
        'CritRate', 0.78, ...
        'CritDMG', 2.10, ...
        'PyroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.35, ...
        'SkillDMGBonus', 0.15, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 40, ...
        'ResShred', 0.00 ...
    );

    % 持久化到 CSV，方便分析脚本和手工调参读取同一套字段。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Arlecchino', 'artifacts_Arlecchino.csv');
    writetable(struct2table(build), outputPath);
end
