function [totalDMG, dps, breakdown, rotationTime, audit] = simulateBeidouDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Beidou 高精度近似模拟。
    % 建模重点：
    % 1. E 默认按满层弹反建模，显式合并基础倍率与受击增伤倍率；
    % 2. Q 拆成起手爆发命中与后续雷弧持续命中；
    % 3. 为主力雷伤命中补上显式 Gauge / ICD，并接入 C6 雷抗下降窗口。
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Beidou', 'rotation_Beidou.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Beidou', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Beidou', 'talents_Beidou.csv');
    talent = readtable(talentPath);
    skillLevel = talentLevel + 3 * double(constellation >= 3);
    counterBase = getTalentValue(talent, 'Skill', 'BaseDMG', skillLevel);
    counterBonus = getTalentValue(talent, 'Skill', 'DMGBonusOnHitTaken', skillLevel);
    fullCounterMV = counterBase + 2 * counterBonus;

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    burstResShred = 0.15 * double(constellation >= 6);
    chainTimeline = [1.0, ones(1, 11)];

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "BaseDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'MVOverride', fullCounterMV, 'AllowCatalyze', double(aggravateReady), ...
        'LunarisAttackName', "ThunderCounter_Strike", ...
        'LunarisDamageParam', "Damage_PerStage|2.000000|MUL|Damage_Stage1|ADD", ...
        'ApplyGauge', 2.0, 'ICDRule', "Independent", ...
        'Note', "Tidecaller full counter");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'PostSetBurstActiveTime', 15.0, ...
        'LunarisAttackName', "ThunderShield", 'LunarisDamageParam', "BurstDamage", ...
        'ApplyGauge', 4.0, 'ICDRule', "Independent", ...
        'Note', "Stormbreaker cast");
    actions.Chain = struct('TalentGroup', "Burst", 'Param', "LightningDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'HitCount', numel(chainTimeline), 'HitTimeline', chainTimeline, ...
        'BurstWindowExtraResShred', burstResShred, ...
        'LunarisAttackName', "ThunderShield_Gadget", 'LunarisDamageParam', "ChainDamage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", ...
        'Note', "Stormbreaker chain lightning");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.85, ...
        'DefaultRotation', {{'E', 'Q', 'Chain'}}, ...
        'ActionTimeMap', struct('E', 0.85, 'Q', 1.00, 'Chain', 15.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Beidou', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
