function bonus = getArtifactLegacySetContribution(characterName, build, teamContext)
    % Estimate which set bonuses were already baked into a legacy default build.
    if nargin < 3 || isempty(teamContext)
        teamContext = struct();
    end

    if ~isfield(build, 'ArtifactCalibrationVersion')
        build = normalizeArtifactBuild(build, characterName);
    end

    currentSetBonus = getArtifactSetBonusContribution(characterName, build, teamContext);
    bonus = localEmptyStatStruct();

    switch lower(char(string(characterName)))
        case 'skirk'
            bonus.CryoDMGBonus = min(0.15, currentSetBonus.CryoDMGBonus);

        case 'escoffier'
            bonus.SkillDMGBonus = min(0.20, currentSetBonus.SkillDMGBonus);

        case 'furina'
            bonus.SkillDMGBonus = min( ...
                getFieldOrDefault(build, 'SkillDMGBonus', 0), ...
                currentSetBonus.SkillDMGBonus);

        case 'neuvillette'
            bonus.ChargeDMGBonus = min(0.15, currentSetBonus.ChargeDMGBonus);
            bonus.ChargedDMGBonus = min(0.15, currentSetBonus.ChargedDMGBonus);

        case 'arlecchino'
            bonus.AtkBonus = min(0.18, currentSetBonus.AtkBonus);

        case 'citlali'
            bonus.CryoDMGBonus = min(0.15, currentSetBonus.CryoDMGBonus);

        case {'lauma', 'nefer'}
            bonus.DendroDMGBonus = min(0.15, currentSetBonus.DendroDMGBonus);

        case {'xilonen', 'zibai', 'linnea'}
            bonus.DEFBonus = min(0.54, currentSetBonus.DEFBonus);
            bonus.GeoDMGBonus = min(0.24, currentSetBonus.GeoDMGBonus);

        otherwise
            if logical(getFieldOrDefault(build, 'ArtifactLegacyTotalsIncludeSetBonuses', 0))
                bonus = currentSetBonus;
            end
    end
end

function stats = localEmptyStatStruct()
    stats = struct( ...
        'AtkBonus', 0, ...
        'FlatATK', 0, ...
        'HPBonus', 0, ...
        'FlatHP', 0, ...
        'DEFBonus', 0, ...
        'FlatDEF', 0, ...
        'ER', 0, ...
        'EM', 0, ...
        'CritRate', 0, ...
        'CritDMG', 0, ...
        'PhysicalDMGBonus', 0, ...
        'PyroDMGBonus', 0, ...
        'HydroDMGBonus', 0, ...
        'CryoDMGBonus', 0, ...
        'ElectroDMGBonus', 0, ...
        'AnemoDMGBonus', 0, ...
        'GeoDMGBonus', 0, ...
        'DendroDMGBonus', 0, ...
        'LunarChargedBonus', 0, ...
        'NormalDMGBonus', 0, ...
        'ChargeDMGBonus', 0, ...
        'ChargedDMGBonus', 0, ...
        'PlungeDMGBonus', 0, ...
        'SkillDMGBonus', 0, ...
        'BurstDMGBonus', 0, ...
        'HealingBonus', 0, ...
        'ReactionDMGBonus', 0, ...
        'ShieldBonus', 0, ...
        'ResShred', 0);
end
