function rows = buildStructToTableData(build)
    % 将 build struct 展平为 GUI 可编辑的两列表格。
    fields = fieldnames(build);
    preferredOrder = { ...
        'Weapon', 'WeaponATK', 'WeaponSubStatType', 'WeaponSubStatValue', 'WeaponRefinement', ...
        'ArtifactUsePieceModel', 'ArtifactApplySetBonuses', 'ArtifactLegacyTotalsIncludeSetBonuses', ...
        'ArtifactAutoDistributeResidualSubstats', ...
        'ArtifactFlowerSet', 'ArtifactFlowerMainStat', 'ArtifactFlowerMainValue', 'ArtifactFlowerSubstats', ...
        'ArtifactFeatherSet', 'ArtifactFeatherMainStat', 'ArtifactFeatherMainValue', 'ArtifactFeatherSubstats', ...
        'ArtifactSandsSet', 'ArtifactSandsMainStat', 'ArtifactSandsMainValue', 'ArtifactSandsSubstats', ...
        'ArtifactGobletSet', 'ArtifactGobletMainStat', 'ArtifactGobletMainValue', 'ArtifactGobletSubstats', ...
        'ArtifactCircletSet', 'ArtifactCircletMainStat', 'ArtifactCircletMainValue', 'ArtifactCircletSubstats', ...
        'ArtifactAssumeOffFieldSkill', 'ArtifactAssumeBondOfLifeStacks', ...
        'ArtifactAssumeMarechausseeStacks', 'ArtifactAssumeObsidianActive', ...
        'ArtifactAssumeNightsoulBlessing', 'ArtifactAssumeCryoAura', 'ArtifactAssumeFrozen', ...
        'ArtifactAssumeHuskStacks', 'ArtifactAssumeMoonPhase', 'ArtifactAssumeNymphStacks', ...
        'ArtifactSet1', 'ArtifactSet1Pieces', 'ArtifactSet2', 'ArtifactSet2Pieces', 'ArtifactSet4Active', ...
        'AtkBonus', 'FlatATK', 'HPBonus', 'FlatHP', 'DEFBonus', 'FlatDEF', 'ER', 'EM', ...
        'CritRate', 'CritDMG', 'PhysicalDMGBonus', 'PyroDMGBonus', 'HydroDMGBonus', 'CryoDMGBonus', ...
        'ElectroDMGBonus', 'AnemoDMGBonus', 'GeoDMGBonus', 'DendroDMGBonus', ...
        'NormalDMGBonus', 'ChargeDMGBonus', 'ChargedDMGBonus', 'PlungeDMGBonus', ...
        'SkillDMGBonus', 'BurstDMGBonus', 'HealingBonus', 'ReactionDMGBonus', 'ShieldBonus', 'LunarChargedBonus', 'ResShred'};
    fields = localReorderFields(fields, preferredOrder);
    rows = cell(numel(fields), 2);
    for i = 1:numel(fields)
        rows{i, 1} = fields{i};
        value = build.(fields{i});
        if isstring(value)
            rows{i, 2} = char(value);
        elseif ischar(value)
            rows{i, 2} = value;
        else
            rows{i, 2} = value;
        end
    end
end

function orderedFields = localReorderFields(fields, preferredOrder)
    orderedFields = {};
    for i = 1:numel(preferredOrder)
        idx = find(strcmp(fields, preferredOrder{i}), 1, 'first');
        if ~isempty(idx)
            orderedFields{end + 1, 1} = fields{idx}; %#ok<AGROW>
        end
    end

    for i = 1:numel(fields)
        if ~any(strcmp(orderedFields, fields{i}))
            orderedFields{end + 1, 1} = fields{i}; %#ok<AGROW>
        end
    end
end
