function build = customArtifact_Xilonen()
    % Default DEF/support build for Xilonen's source samples and burst heal.
    build = struct( ...
        'Weapon', 'TrailforgedEdge', ...
        'WeaponATK', 608, ...
        'DEFBonus', 1.18, ...
        'FlatDEF', 260, ...
        'CritRate', 0.62, ...
        'CritDMG', 1.70, ...
        'GeoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'HealingBonus', 0.15, ...
        'ResShred', 0.00 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Xilonen', 'artifacts_Xilonen.csv');
    writetable(struct2table(build), outputPath);
end
