function build = customArtifact_Xilonen()
    % 希诺宁默认构筑。
    % 默认面板以防御和岩伤为主，同时保留治疗加成，适配采样与爆发治疗。
    build = struct( ...
        'Weapon', 'TrailforgedEdge', ...
        'WeaponATK', 608, ...
        'DEFBonus', 1.18, ...
        'FlatDEF', 260, ...
        'CritRate', 0.62, ...
        'CritDMG', 1.70, ...
        'GeoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'HealingBonus', 0.15, ...
        'ResShred', 0.00 ...
    );

    % 回写 CSV，供统一入口和分析脚本复用。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Xilonen', 'artifacts_Xilonen.csv');
    writetable(struct2table(build), outputPath);
end
