function build = customArtifact_Ineffa()
    % Default crit/ATK-oriented Ineffa build with enough EM to make
    % Lunar-Charged side damage visible in mixed teams.
    build = struct( ...
        'Weapon', 'VanillaVoltage', ...
        'WeaponATK', 674, ...
        'AtkBonus', 0.82, ...
        'FlatATK', 311, ...
        'CritRate', 0.78, ...
        'CritDMG', 1.96, ...
        'ElectroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 160, ...
        'ResShred', 0.00 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Ineffa', 'artifacts_Ineffa.csv');
    writetable(struct2table(build), outputPath);
end
