function build = customArtifact_Ineffa()
    % 伊涅芙默认构筑。
    % 默认面板偏向暴击和攻击，同时保留一定精通以体现月感电派生伤害。
    build = struct( ...
        'Weapon', 'VanillaVoltage', ...
        'WeaponATK', 674, ...
        'AtkBonus', 0.82, ...
        'FlatATK', 311, ...
        'CritRate', 0.78, ...
        'CritDMG', 1.96, ...
        'ElectroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 160, ...
        'ResShred', 0.00 ...
    );

    % 回写 CSV，供分析脚本和统一入口共用。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Ineffa', 'artifacts_Ineffa.csv');
    writetable(struct2table(build), outputPath);
end
