function build = customArtifact_Baizhu()
    % Default Baizhu build emphasizing HP-scaled healing, shielding, and supportive burst uptime.
    build = struct( ...
        'Weapon', '碧落之珑', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'HP', ...
        'WeaponSubStatValue', 0.496, ...
        'WeaponRefinement', 1, ...
        'HPBonus', 1.08, ...
        'FlatHP', 4780, ...
        'AtkBonus', 0.16, ...
        'FlatATK', 120, ...
        'ER', 1.80, ...
        'EM', 100, ...
        'CritRate', 0.20, ...
        'CritDMG', 0.60, ...
        'DendroDMGBonus', 0.18, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.18, ...
        'HealingBonus', 0.359, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'DeepwoodMemories', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Baizhu', 'artifacts_Baizhu.csv');
    writetable(struct2table(build), outputPath);
end
