function build = customArtifact_Furina()
    % Default Furina build shared by standalone and team-level entries.
    build = struct( ...
        'Weapon', 'Silvershower Heartstrings', ...
        'WeaponATK', 542, ...
        'HPBonus', 1.428, ...
        'FlatHP', 5000, ...
        'AtkBonus', 0.00, ...
        'FlatATK', 311, ...
        'CritRate', 0.70, ...
        'CritDMG', 2.15, ...
        'HydroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.00, ...
        'SkillDMGBonus', 0.60, ...
        'BurstDMGBonus', 0.00, ...
        'HealingBonus', 0.00, ...
        'EM', 120, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'GoldenTroupe', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Furina', 'artifacts_Furina.csv');
    writetable(struct2table(build), outputPath);
end
