function [totalDMG, dps, breakdown, rotationTime, audit] = simulateKiraraDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Kirara simulator with press / hold skill split, parcel collision hits,
    % burst cardamoms, and HP-scaling passive / C4 follow-up damage.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Kirara', 'rotation_Kirara.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Kirara', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    baseHP = 0.0004 * (getFieldOrDefault(build, 'FlatHP', 0) + getFieldOrDefault(build, 'HPBonus', 0) * 1000);
    spreadReady = getFieldOrDefault(teamContext, 'ElectroCount', 0) >= 1;
    c6AllBonus = 0.12 * double(constellation >= 6);

    workBuild = build;
    workBuild.AllDMGBonus = getFieldOrDefault(workBuild, 'AllDMGBonus', 0) + c6AllBonus;

    actions = struct();
    actions.EPress = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "TailFlickingFlyingKickDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Dendro", ...
        'BaseMultiplier', 1.00, ...
        'FlatDamageBonus', baseHP, ...
        'AllowCatalyze', double(spreadReady), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Click", ...
        'LunarisDamageParam', "Click_StrikeDamage", ...
        'Note', "Meow-teor Kick press");
    actions.EHoldStart = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "TailFlickingFlyingKickDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Dendro", ...
        'BaseMultiplier', 1.00, ...
        'FlatDamageBonus', baseHP, ...
        'AllowCatalyze', double(spreadReady), ...
        'PostSetSkillActiveTime', 10.0, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Charge_Strike", ...
        'LunarisDamageParam', "Hold_StrikeDamage", ...
        'Note', "Urgent Neko Parcel enter");
    actions.ParcelHits = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "UrgentNekoParcelHitDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Dendro", ...
        'BaseMultiplier', 1.00, ...
        'FlatDamageBonus', baseHP, ...
        'HitCount', 4, ...
        'HitTimeline', [0.55, 0.55, 0.55, 0.55], ...
        'AllowCatalyze', double(spreadReady), ...
        'PostSetStacks', 3, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_CatBox_Bullet", ...
        'LunarisDamageParam', "ElementalArt_Bullet_Damage", ...
        'Note', "Parcel collision hits");
    actions.ParcelEnd = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "FlipclawStrikeDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Dendro", ...
        'BaseMultiplier', 1.00, ...
        'FlatDamageBonus', baseHP, ...
        'AllowCatalyze', double(spreadReady), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Charge_Strike", ...
        'LunarisDamageParam', "Hold_StrikeDamage", ...
        'Note', "Parcel finishing strike");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", ...
        'BaseMultiplier', 1.00, ...
        'FlatDamageBonus', 0.75 * baseHP, ...
        'AllowCatalyze', double(spreadReady), ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_ExpressDamage", ...
        'LunarisDamageParam', "ElementalBurst_damagePercentage_Once", ...
        'Note', "Surprise Dispatch");
    actions.Cardamoms = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "CatGrassCardamomExplosionDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", ...
        'BaseMultiplier', 1.00, ...
        'FlatDamageBonus', 0.75 * baseHP, ...
        'HitCount', 4, ...
        'HitTimeline', [1.0, 1.0, 1.0, 1.0], ...
        'AllowCatalyze', double(spreadReady), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Gadget_ElementalBurst_Mine", ...
        'LunarisDamageParam', "ElementalBurst_Mine_Damage", ...
        'Note', "Cardamom explosions");
    actions.C4Follow = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "CatGrassCardamomExplosionDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", ...
        'MVOverride', 2.00 * double(constellation >= 4), ...
        'AllowCatalyze', double(spreadReady), ...
        'ApplyGauge', 1.0 * double(constellation >= 4), ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Constellation_AddAttack", ...
        'LunarisDamageParam', "Constellation4_Mine_Damage", ...
        'Note', "C4 coordinated cardamom");

    defaultRotation = {'EHoldStart', 'ParcelHits', 'ParcelEnd', 'Q', 'Cardamoms'};
    if constellation >= 4
        defaultRotation{end + 1} = 'C4Follow'; %#ok<AGROW>
    end

    spec = struct( ...
        'Element', "Dendro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.70, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct( ...
            'EPress', 0.42, ...
            'EHoldStart', 0.45, ...
            'ParcelHits', 2.20, ...
            'ParcelEnd', 0.42, ...
            'Q', 0.92, ...
            'Cardamoms', 4.00, ...
            'C4Follow', 0.10), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Kirara', workBuild, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
