function registry = getCharacterRegistry()
    % 角色注册表。
    % 为 GUI 提供统一的：
    % 1. 角色显示名与英文键；
    % 2. 武器类型，用于过滤 weapons.csv；
    % 3. 头像 key，用于缓存或联网拉取资源；
    % 4. 数据目录名与默认 rotation 文件。
    names = { ...
        'Arlecchino', '阿蕾奇诺', 'Pole', 'Arlecchino'; ...
        'Chasca', '恰斯卡', 'Bow', 'Chasca'; ...
        'Chevreuse', '夏沃蕾', 'Pole', 'Chevreuse'; ...
        'Citlali', '茜特菈莉', 'Catalyst', 'Citlali'; ...
        'Columbina', '哥伦比娅', 'Catalyst', 'Columbina'; ...
        'Durin', '杜林', 'Catalyst', 'Durin'; ...
        'Escoffier', '爱可菲', 'Pole', 'Escoffier'; ...
        'Flins', '菲林斯', 'Bow', 'Flins'; ...
        'Furina', '芙宁娜', 'Sword', 'Furina'; ...
        'Iansan', '伊安珊', 'Pole', 'Iansan'; ...
        'Ineffa', '伊涅芙', 'Sword', 'Ineffa'; ...
        'Lauma', '菈乌玛', 'Catalyst', 'Lauma'; ...
        'Linnea', '莉奈娅', 'Catalyst', 'Linnea'; ...
        'Mavuika', '玛薇卡', 'Claymore', 'Mavuika'; ...
        'Mualani', '玛拉妮', 'Catalyst', 'Mualani'; ...
        'Nefer', '奈芙尔', 'Catalyst', 'Nefer'; ...
        'Neuvillette', '那维莱特', 'Catalyst', 'Neuvillette'; ...
        'Nicole', '尼可', 'Catalyst', 'Nicole'; ...
        'Nilou', '妮露', 'Sword', 'Nilou'; ...
        'Skirk', '丝柯克', 'Sword', 'Skirk'; ...
        'Varesa', '瓦雷莎', 'Catalyst', 'Varesa'; ...
        'Xilonen', '希诺宁', 'Sword', 'Xilonen'; ...
        'Zibai', '兹白', 'Catalyst', 'Zibai' ...
    };

    registry = struct( ...
        'Key', names(:, 1), ...
        'DisplayName', names(:, 2), ...
        'WeaponType', names(:, 3), ...
        'AvatarKey', names(:, 4));
end
