function registry = getCharacterRegistry()
    % 返回 GUI 和资源层统一使用的角色注册表。
    % 武器类型以 data/<Character>/characters_*.csv 为真值；
    % 中文显示名与头像 key 仍在此集中维护，避免界面层散落硬编码。
    entries = { ...
        'Arlecchino', '阿蕾奇诺', 'Pole', 'Arlecchino'; ...
        'Chasca', '恰斯卡', 'Bow', 'Chasca'; ...
        'Chevreuse', '夏沃蕾', 'Pole', 'Chevreuse'; ...
        'Citlali', '茜特菈莉', 'Catalyst', 'Citlali'; ...
        'Columbina', '哥伦比娅', 'Catalyst', 'Columbina'; ...
        'Durin', '杜林', 'Sword', 'Durin'; ...
        'Escoffier', '爱可菲', 'Pole', 'Escoffier'; ...
        'Flins', '菲林斯', 'Pole', 'Flins'; ...
        'Furina', '芙宁娜', 'Sword', 'Furina'; ...
        'Iansan', '伊安珊', 'Pole', 'Iansan'; ...
        'Ineffa', '伊涅芙', 'Pole', 'Ineffa'; ...
        'Lauma', '菈乌玛', 'Catalyst', 'Lauma'; ...
        'Linnea', '莉奈娅', 'Bow', 'Linnea'; ...
        'Mavuika', '玛薇卡', 'Claymore', 'Mavuika'; ...
        'Mualani', '玛拉妮', 'Catalyst', 'Mualani'; ...
        'Nefer', '奈芙尔', 'Catalyst', 'Nefer'; ...
        'Neuvillette', '那维莱特', 'Catalyst', 'Neuvillette'; ...
        'Nicole', '尼可', 'Catalyst', 'Nicole'; ...
        'Nilou', '妮露', 'Sword', 'Nilou'; ...
        'Skirk', '丝柯克', 'Sword', 'Skirk'; ...
        'Varesa', '瓦雷莎', 'Catalyst', 'Varesa'; ...
        'Xianyun', '闲云', 'Catalyst', 'Liuyun'; ...
        'Xilonen', '希诺宁', 'Sword', 'Xilonen'; ...
        'Zibai', '兹白', 'Sword', 'Zibai' ...
    };

    registry = repmat(struct( ...
        'Key', "", ...
        'DisplayName', "", ...
        'WeaponType', "", ...
        'AvatarKey', ""), 1, size(entries, 1));

    for i = 1:size(entries, 1)
        registry(i).Key = string(entries{i, 1});
        registry(i).DisplayName = string(entries{i, 2});
        registry(i).WeaponType = string(entries{i, 3});
        registry(i).AvatarKey = string(entries{i, 4});
    end
end
