function build = customArtifact_Yelan()
    % Default Yelan build for HP-based skill and burst arrows.
    build = struct( ...
        'Weapon', 'AquaSimulacra', ...
        'WeaponATK', 542, ...
        'WeaponSubStatType', 'CD', ...
        'WeaponSubStatValue', 0.882, ...
        'WeaponRefinement', 1, ...
        'HPBonus', 0.46, ...
        'FlatHP', 4780, ...
        'ER', 1.55, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.20, ...
        'HydroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.25, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'EmblemOfSeveredFate', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Yelan', 'artifacts_Yelan.csv');
    writetable(struct2table(build), outputPath);
end
