function [totalDMG, dps, breakdown, rotationTime, audit] = simulateYelanDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Yelan simulator for breakthrough barb, Lifeline, and Exquisite Throw.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Yelan', 'rotation_Yelan.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Yelan', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    vapeReady = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1;
    actions = struct();
    actions.Barb = struct('TalentGroup', "Normal", 'Param', "BreakthroughBarbDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Hydro", 'ActionScalingMode', "HP", 'BaseMultiplier', 1.00, 'AllowAmplify', double(vapeReady), ...
        'LunarisAttackName', "SneakArrow", 'ApplyGauge', 1.0, 'ICDRule', "4 hits / 0.3s", 'Note', "Breakthrough Barb");
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", 'ActionScalingMode', "HP", 'BaseMultiplier', 1.00, 'AllowAmplify', double(vapeReady), ...
        'LunarisAttackName', "ElementalArt_TriggerCollision", 'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Lingering Lifeline");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", 'ActionScalingMode', "HP", 'BaseMultiplier', 1.00, 'AllowAmplify', double(vapeReady), ...
        'PostSetBurstActiveTime', 15.0, 'LunarisAttackName', "ElementalBurst_Dice", 'ApplyGauge', 2.0, 'ICDRule', "Independent", 'Note', "Depth-Clarion Dice");
    actions.Throw = struct('TalentGroup', "Burst", 'Param', "ExquisiteThrowDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", 'ActionScalingMode', "HP", 'BaseMultiplier', 1.00, 'HitCount', 9 + 3 * double(constellation >= 2), ...
        'AllowAmplify', double(vapeReady), 'LunarisAttackName', "ElementalBurst_Dice_Bullet_01", ...
        'ApplyGauge', 1.0, 'ICDRule', "3 hits / 2s", 'Note', "Exquisite Throw");

    spec = struct( ...
        'Element', "Hydro", ...
        'ScalingMode', "HP", ...
        'PreferredAmplifyAura', "Pyro", ...
        'DefaultActionTime', 0.70, ...
        'DefaultRotation', {{'Barb', 'E', 'Q', 'Throw'}}, ...
        'ActionTimeMap', struct('Barb', 0.75, 'E', 0.80, 'Q', 1.00, 'Throw', 15.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Yelan', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

