function build = customArtifact_Linnea()
    % 莉奈娅默认构筑。
    % 默认面板以防御和双暴为主，适配 Lumi 与岩系爆发段。
    build = struct( ...
        'Weapon', 'MoonstringRepeater', ...
        'WeaponATK', 608, ...
        'DEFBonus', 1.10, ...
        'FlatDEF', 240, ...
        'CritRate', 0.78, ...
        'CritDMG', 1.82, ...
        'GeoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'HealingBonus', 0.15, ...
        'EM', 80, ...
        'ResShred', 0.00 ...
    );

    % 回写 CSV，作为工程内统一默认基线。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Linnea', 'artifacts_Linnea.csv');
    writetable(struct2table(build), outputPath);
end
