function build = customArtifact_Linnea()
    % DEF-oriented baseline build for Linnea's summon and Geo burst pattern.
    build = struct( ...
        'Weapon', 'MoonstringRepeater', ...
        'WeaponATK', 608, ...
        'DEFBonus', 1.10, ...
        'FlatDEF', 240, ...
        'CritRate', 0.78, ...
        'CritDMG', 1.82, ...
        'GeoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'HealingBonus', 0.15, ...
        'EM', 80, ...
        'ResShred', 0.00 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Linnea', 'artifacts_Linnea.csv');
    writetable(struct2table(build), outputPath);
end
