function [totalDMG, dps, breakdown, rotationTime, audit] = simulateZhongliDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Zhongli simulator with Jade Shield RES shred window, stone stele
    % resonance ticks, HP-based passive addends, and meteor burst damage.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Zhongli', 'rotation_Zhongli.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Zhongli', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    shieldResShred = 0.20;

    actions = struct();
    actions.EPress = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "StoneSteleResonanceDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectHPWeight', 0.019, ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Geo", ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "SkillObj_PrimoPillar", ...
        'LunarisDamageParam', "PillarDamage1", ...
        'Note', "Stone Stele creation");
    actions.EHold = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "HoldDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectHPWeight', 0.019, ...
        'PostSetSkillActiveTime', 20.0, ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Geo", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "RockShield", ...
        'LunarisDamageParam', "Damage", ...
        'Note', "Dominus Lapidis hold");
    actions.Pillar = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "StoneSteleResonanceDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectHPWeight', 0.019, ...
        'SkillWindowExtraResShred', shieldResShred, ...
        'HitCount', 4, ...
        'HitTimeline', 2.0 * ones(1, 4), ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Geo", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "SkillObj_PrimoPillar", ...
        'LunarisDamageParam', "PillarDamage2", ...
        'Note', "Stone Stele resonance");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectHPWeight', 0.33, ...
        'SkillWindowExtraResShred', shieldResShred, ...
        'AllowTransformative', 1, ...
        'ReactionElement', "Geo", ...
        'ApplyGauge', 4.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "GeoOrder", ...
        'LunarisDamageParam', "Damage", ...
        'Note', "Planet Befall");
    actions.N1 = localZhongliNormalAction("x1HitDMG", "NormalAttack", "Attack01", "Normal 1");
    actions.N2 = localZhongliNormalAction("x2HitDMG", "NormalAttack", "Attack02", "Normal 2");
    actions.N3 = localZhongliNormalAction("x3HitDMG", "NormalAttack", "Attack03", "Normal 3");
    actions.N4 = localZhongliNormalAction("x4HitDMG", "NormalAttack", "Attack04", "Normal 4");
    actions.N5 = localZhongliNormalAction("x5HitDMG", "SkillObj_Attack05", "Attack05", "Normal 5");
    actions.N6 = localZhongliNormalAction("x6HitDMG", "NormalAttack", "Attack06", "Normal 6");
    actions.CA = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectHPWeight', 0.0139, ...
        'SkillWindowExtraResShred', shieldResShred, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "24 hits / 0.5s", ...
        'LunarisAttackName', "SkillObj_ExtraAttack", ...
        'LunarisDamageParam', "ExtraAttack", ...
        'Note', "Charged spear drill");

    spec = struct( ...
        'Element', "Geo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.55, ...
        'DefaultRotation', {{'EHold', 'Pillar', 'Q', 'N1', 'N2', 'CA'}}, ...
        'ActionTimeMap', struct( ...
            'EPress', 0.45, ...
            'EHold', 0.90, ...
            'Pillar', 8.00, ...
            'Q', 1.00, ...
            'N1', 0.28, ...
            'N2', 0.30, ...
            'N3', 0.34, ...
            'N4', 0.38, ...
            'N5', 0.44, ...
            'N6', 0.48, ...
            'CA', 0.82), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Zhongli', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function action = localZhongliNormalAction(paramName, attackName, damageParam, note)
    action = struct( ...
        'TalentGroup', "Normal", ...
        'Param', string(paramName), ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectHPWeight', 0.0139, ...
        'SkillWindowExtraResShred', 0.20, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', string(attackName), ...
        'LunarisDamageParam', string(damageParam), ...
        'Note', string(note));
end
