function build = customArtifact_Escoffier()
    % 爱可菲默认构筑。
    % 返回结构体后会同步写回 CSV，作为单角色入口与统一入口共用的
    % 默认构筑基线。
    build = struct( ...
        'Weapon', 'Symphonist', ...
        'WeaponATK', 674, ...
        'AtkBonus', 0.68, ...
        'FlatATK', 311, ...
        'CritRate', 0.72, ...
        'CritDMG', 1.80, ...
        'CryoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'HealingBonus', 0.15, ...
        'ResShred', 0.00 ...
    );

    % 将默认构筑回写到 data 目录，保证表格与脚本读取的是同一份基线。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Escoffier', 'artifacts_Escoffier.csv');
    writetable(struct2table(build), outputPath);
end
