function build = customArtifact_Escoffier()
    % Default baseline build used by standalone and unified-entry runs.
    build = struct( ...
        'Weapon', 'Symphonist', ...
        'WeaponATK', 674, ...
        'AtkBonus', 0.68, ...
        'FlatATK', 311, ...
        'CritRate', 0.72, ...
        'CritDMG', 1.80, ...
        'CryoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'HealingBonus', 0.15, ...
        'ResShred', 0.00 ...
    );

    % Write the struct back to the data folder so spreadsheet edits and
    % scripted runs stay anchored to the same baseline artifact file.
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Escoffier', 'artifacts_Escoffier.csv');
    writetable(struct2table(build), outputPath);
end
