function build = customArtifact_Amber()
    % Default Amber build for bunny explosion and burst support.
    build = struct( ...
        'Weapon', 'TheStringless', ...
        'WeaponATK', 510, ...
        'WeaponSubStatType', 'EM', ...
        'WeaponSubStatValue', 165.38, ...
        'WeaponRefinement', 5, ...
        'AtkBonus', 0.70, ...
        'FlatATK', 220, ...
        'ER', 1.45, ...
        'EM', 180, ...
        'CritRate', 0.62, ...
        'CritDMG', 1.55, ...
        'PyroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.32, ...
        'BurstDMGBonus', 0.28, ...
        'ArtifactSet1', 'NoblesseOblige', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Amber', 'artifacts_Amber.csv');
    writetable(struct2table(build), outputPath);
end
