function [totalDMG, dps, breakdown, rotationTime, audit] = simulateKeqingDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Keqing simulator with stiletto throw, blink slash infusion, burst
    % multi-slash sequence, and post-burst crit-buffed infused follow-up.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Keqing', 'rotation_Keqing.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Keqing', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    reactiveTeam = aggravateReady ...
        || getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1;
    c6ElectroDamageBonus = 0.06 * double(constellation >= 6);
    burstSlashCount = 8;

    workBuild = build;
    if constellation >= 4 && reactiveTeam
        workBuild.AtkBonus = getFieldOrDefault(workBuild, 'AtkBonus', 0) + 0.25;
    end

    actions = struct();
    actions.E1 = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "LightningStilettoDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', c6ElectroDamageBonus, ...
        'AllowCatalyze', double(aggravateReady), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "SkillBullet_Material", ...
        'LunarisDamageParam', "Damage", ...
        'Note', "Lightning Stiletto throw");
    actions.E2 = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SlashingDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', c6ElectroDamageBonus, ...
        'AllowCatalyze', double(aggravateReady), ...
        'PostSetSkillActiveTime', 5.0, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Electrans_Strike", ...
        'LunarisDamageParam', "Damage", ...
        'Note', "Blink slash and infusion");
    actions.C1BlinkStart = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "LightningStilettoDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'MVOverride', 0.50, ...
        'BaseActionDamageBonus', c6ElectroDamageBonus, ...
        'AllowCatalyze', double(aggravateReady), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Talent_Electrans_BlinkAttack1", ...
        'LunarisDamageParam', "Damage", ...
        'Note', "C1 blink start explosion");
    actions.C1BlinkEnd = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "LightningStilettoDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'MVOverride', 0.50, ...
        'BaseActionDamageBonus', c6ElectroDamageBonus, ...
        'AllowCatalyze', double(aggravateReady), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Talent_Electrans_BlinkAttack2", ...
        'LunarisDamageParam', "Damage", ...
        'Note', "C1 blink end explosion");
    actions.QStart = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', c6ElectroDamageBonus, ...
        'AllowCatalyze', double(aggravateReady), ...
        'PostSetBurstActiveTime', 8.0, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Gadget_StartAttack", ...
        'LunarisDamageParam', "Damage_Start", ...
        'Note', "Starward Sword opening slash");
    actions.QRapid = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "ConsecutiveSlashDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', c6ElectroDamageBonus, ...
        'HitCount', burstSlashCount, ...
        'HitTimeline', 0.12 * ones(1, burstSlashCount), ...
        'AllowCatalyze', double(aggravateReady), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Gadget_AttackType1", ...
        'LunarisDamageParam', "Damage", ...
        'Note', "Starward Sword rapid slashes");
    actions.QLast = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "LastAttackDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', c6ElectroDamageBonus, ...
        'AllowCatalyze', double(aggravateReady), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Gadget_Material", ...
        'LunarisDamageParam', "Damage_Last", ...
        'Note', "Starward Sword finishing strike");
    actions.N1 = localInfusedKeqingNormalAction("x1HitDMG", c6ElectroDamageBonus, aggravateReady, 0.00, "Infused normal 1");
    actions.N2 = localInfusedKeqingNormalAction("x2HitDMG", c6ElectroDamageBonus, aggravateReady, 0.00, "Infused normal 2");
    actions.N3 = localInfusedKeqingNormalAction("x3HitDMG", c6ElectroDamageBonus, aggravateReady, 0.00, "Infused normal 3");
    actions.N4 = localInfusedKeqingNormalAction("x4HitDMG", c6ElectroDamageBonus, aggravateReady, 0.00, "Infused normal 4");
    actions.N5 = localInfusedKeqingNormalAction("x5HitDMG", c6ElectroDamageBonus, aggravateReady, 0.00, "Infused normal 5");
    actions.QN1 = localInfusedKeqingNormalAction("x1HitDMG", c6ElectroDamageBonus, aggravateReady, 0.15, "Post-burst infused normal 1");
    actions.QN2 = localInfusedKeqingNormalAction("x2HitDMG", c6ElectroDamageBonus, aggravateReady, 0.15, "Post-burst infused normal 2");
    actions.QCA = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', c6ElectroDamageBonus, ...
        'CritRateBonus', 0.15, ...
        'AllowCatalyze', double(aggravateReady), ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Keqing_InfusedNormal", ...
        'ICDRule', "3 hits / 2.5s", ...
        'LunarisAttackName', "NormalAttack05_Bullet", ...
        'LunarisDamageParam', "0.720000", ...
        'Note', "Post-burst infused charged attack");
    actions.MarkCA = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "ThunderclapSlashDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', c6ElectroDamageBonus, ...
        'AllowCatalyze', double(aggravateReady), ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "TrapBurst_Material", ...
        'LunarisDamageParam', "Damage1", ...
        'Note', "Charged detonation on stiletto mark");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.50, ...
        'DefaultRotation', {{'E1', 'E2', 'C1BlinkStart', 'C1BlinkEnd', 'QStart', 'QRapid', 'QLast', 'QN1', 'QN2', 'QCA'}}, ...
        'ActionTimeMap', struct( ...
            'E1', 0.45, ...
            'E2', 0.55, ...
            'C1BlinkStart', 0.08, ...
            'C1BlinkEnd', 0.08, ...
            'QStart', 0.40, ...
            'QRapid', 1.05, ...
            'QLast', 0.25, ...
            'N1', 0.26, ...
            'N2', 0.27, ...
            'N3', 0.32, ...
            'N4', 0.36, ...
            'N5', 0.44, ...
            'QN1', 0.26, ...
            'QN2', 0.27, ...
            'QCA', 0.65, ...
            'MarkCA', 0.45), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Keqing', workBuild, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function action = localInfusedKeqingNormalAction(paramName, c6ElectroDamageBonus, aggravateReady, critRateBonus, note)
    action = struct( ...
        'TalentGroup', "Normal", ...
        'Param', string(paramName), ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', c6ElectroDamageBonus, ...
        'CritRateBonus', critRateBonus, ...
        'AllowCatalyze', double(aggravateReady), ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Keqing_InfusedNormal", ...
        'ICDRule', "3 hits / 2.5s", ...
        'Note', string(note));
end
