function build = customArtifact_Lisa()
    % Default Lisa build for hold skill and burst electro damage.
    build = struct( ...
        'Weapon', 'LostPrayerToTheSacredWinds', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.331, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.72, ...
        'FlatATK', 220, ...
        'ER', 1.35, ...
        'EM', 120, ...
        'CritRate', 0.68, ...
        'CritDMG', 1.75, ...
        'ElectroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.00, ...
        'BurstDMGBonus', 0.00, ...
        'ArtifactSet1', 'ThunderingFury', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Lisa', 'artifacts_Lisa.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
