function [totalDMG, dps, breakdown, rotationTime, audit] = simulateLisaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Lisa explicit conductive-stack / burst script.
    % Tap E, charged attack conductive application, hold E stack payoff,
    % Lightning Rose target-aware bolts, and C6 field-entry setup are
    % modeled as separate scripted actions.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Lisa', 'rotation_Lisa.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Lisa', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    burstDefReduct = 0.15;
    enemyTargetCount = max(1, round(getFieldOrDefault(enemy, 'TargetCount', ...
        getFieldOrDefault(enemy, 'EnemyCount', 1))));
    qHitCount = 12 * localResolveBurstBoltCount(constellation, enemyTargetCount);

    actions = struct();
    actions.C6Entry = struct('TalentGroup', "Skill", 'Param', "PressDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'MVOverride', 0, 'ApplyGauge', 0.0, ...
        'CanApplyAura', false, 'CanTriggerReaction', false, 'PostSetMarks', 0, ...
        'Note', "C6 field entry");
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'Note', "Normal 1");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'Note', "Normal 2");
    actions.CA = struct('TalentGroup', "Normal", 'Param', "ChargedAttackDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'PostAddMarks', 1, 'PostMaxMarks', 3, 'PostSetSkillActiveTime', 16.0, ...
        'LunarisAttackName', "FlickerWaveDamage", 'LunarisDamageParam', "Damage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Charged attack applies conductive");
    actions.ETap = struct('TalentGroup', "Skill", 'Param', "PressDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'PostAddMarks', 1, 'PostMaxMarks', 3, 'PostSetSkillActiveTime', 16.0, ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Tap skill");
    actions.EHold0 = struct('TalentGroup', "Skill", 'Param', "NonConductiveHoldDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'PostSetMarks', 0, ...
        'LunarisAttackName', "ThunderFall", 'LunarisDamageParam', "Damage_0", ...
        'ApplyGauge', 2.0, 'ICDRule', "Independent", 'Note', "Hold skill 0 stack");
    actions.EHold1 = struct('TalentGroup', "Skill", 'Param', "Stack1ConductiveHoldDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'PostSetMarks', 0, ...
        'LunarisAttackName', "ThunderFall", 'LunarisDamageParam', "Damage_1", ...
        'ApplyGauge', 2.0, 'ICDRule', "Independent", 'Note', "Hold skill 1 stack");
    actions.EHold2 = struct('TalentGroup', "Skill", 'Param', "Stack2ConductiveHoldDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'PostSetMarks', 0, ...
        'LunarisAttackName', "ThunderFall", 'LunarisDamageParam', "Damage_2", ...
        'ApplyGauge', 2.0, 'ICDRule', "Independent", 'Note', "Hold skill 2 stack");
    actions.EHold3 = struct('TalentGroup', "Skill", 'Param', "Stack3ConductiveHoldDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'PostSetMarks', 0, ...
        'LunarisAttackName', "ThunderFall", 'LunarisDamageParam', "Damage_3", ...
        'ApplyGauge', 2.0, 'ICDRule', "Independent", 'Note', "Hold skill 3 stack");
    actions.EHold = actions.EHold0;
    actions.EHold.Note = "Hold skill";
    actions.Q = struct('TalentGroup', "Burst", 'Param', "DischargeDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'HitCount', qHitCount, ...
        'AllowCatalyze', double(aggravateReady), 'EnemyDefReduct', burstDefReduct, ...
        'LunarisAttackName', "PierceLightning_Ball_Attack", 'LunarisDamageParam', "Damage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Lightning Rose");

    holdVariants = struct('EHold0', actions.EHold0, 'EHold1', actions.EHold1, ...
        'EHold2', actions.EHold2, 'EHold3', actions.EHold3);

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.75, ...
        'DefaultRotation', {{'ETap', 'CA', 'ETap', 'EHold', 'Q'}}, ...
        'ActionTimeMap', struct('C6Entry', 0.01, 'N1', 0.35, 'N2', 0.42, 'CA', 0.90, 'ETap', 0.45, ...
            'EHold', 1.35, 'EHold0', 1.35, 'EHold1', 1.35, 'EHold2', 1.35, 'EHold3', 1.35, 'Q', 1.10), ...
        'InitializeStateFn', @localInitializeState, ...
        'BeforeActionFn', @(state, actionKey, actionSpec, actionTime, note, hookContext) ...
            localBeforeAction(state, actionKey, actionSpec, actionTime, note, hookContext, holdVariants), ...
        'AfterActionFn', @localAfterAction, ...
        'AdvanceStateFn', @localAdvanceState, ...
        'Actions', actions);

    if constellation >= 6
        spec.DefaultRotation = {{'C6Entry', 'EHold', 'Q', 'CA', 'ETap', 'EHold'}};
    end

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Lisa', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function boltCount = localResolveBurstBoltCount(constellation, enemyTargetCount)
    boltCount = 1;
    if constellation >= 4
        boltCount = min(3, max(1, enemyTargetCount));
    end
end

function state = localInitializeState(state, hookContext) %#ok<INUSD>
    state.C6Cooldown = 0;
end

function [state, actionSpec, actionTime, note] = localBeforeAction( ...
        state, actionKey, actionSpec, actionTime, note, hookContext, holdVariants) %#ok<INUSD>
    if actionKey == "EHold"
        holdName = "EHold" + string(min(3, max(0, round(getFieldOrDefault(state, 'Marks', 0)))));
        actionSpec = holdVariants.(char(holdName));
        note = string(getFieldOrDefault(actionSpec, 'Note', note));
        return;
    end

    if actionKey ~= "C6Entry"
        return;
    end

    if getFieldOrDefault(hookContext, 'Constellation', 0) < 6
        actionSpec.PostSetMarks = getFieldOrDefault(state, 'Marks', 0);
        note = "C6 inactive";
        return;
    end

    if getFieldOrDefault(state, 'C6Cooldown', 0) > 1e-9
        actionSpec.PostSetMarks = getFieldOrDefault(state, 'Marks', 0);
        note = "C6 field entry cooldown";
        return;
    end

    actionSpec.PostSetMarks = 3;
    note = "C6 field entry conductive x3";
end

function [state, note] = localAfterAction(state, actionKey, actionSpec, actionDamage, reactionTags, note, hookContext) %#ok<INUSD>
    if actionKey == "C6Entry" && getFieldOrDefault(actionSpec, 'PostSetMarks', 0) >= 3
        state.C6Cooldown = 5.0;
    end
end

function state = localAdvanceState(state, actionTime, hookContext) %#ok<INUSD>
    state.C6Cooldown = max(0, getFieldOrDefault(state, 'C6Cooldown', 0) - actionTime);
end
