function build = customArtifact_YaeMiko()
    % Default Yae Miko build for turret and burst thunderbolts.
    build = struct( ...
        'Weapon', 'KagurasVerity', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CD', ...
        'WeaponSubStatValue', 0.662, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.46, ...
        'FlatATK', 140, ...
        'EM', 120, ...
        'ER', 1.40, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.20, ...
        'ElectroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.46, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'GoldenTroupe', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'YaeMiko', 'artifacts_YaeMiko.csv');
    writetable(struct2table(build), outputPath);
end
