function [totalDMG, dps, breakdown, rotationTime, audit] = simulateYaeMikoDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Yae Miko simulator with triple-totem setup, EM passive, and burst detonation.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'YaeMiko', 'rotation_YaeMiko.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'YaeMiko', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    workBuild = build;
    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    emTotal = getFieldOrDefault(workBuild, 'EM', 0) + getFieldOrDefault(teamContext, 'EMBonus', 0);
    sakuraPassiveBonus = 0.0015 * emTotal;
    if constellation >= 4
        workBuild.ElectroDMGBonus = getFieldOrDefault(workBuild, 'ElectroDMGBonus', 0) + 0.20;
    end

    totemLevelParam = "SesshouSakuraDMGLevel3";
    tickHitCount = 9 + 2 * double(constellation >= 2);

    actions = struct();
    actions.E1 = struct('TalentGroup', "Skill", 'Param', "SesshouSakuraDMGLevel1", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 0, 'AllowCatalyze', 0, 'Note', "Sesshou Sakura placement 1");
    actions.E2 = struct('TalentGroup', "Skill", 'Param', "SesshouSakuraDMGLevel2", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 0, 'AllowCatalyze', 0, 'Note', "Sesshou Sakura placement 2");
    actions.E3 = struct('TalentGroup', "Skill", 'Param', "SesshouSakuraDMGLevel3", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 0, 'AllowCatalyze', 0, 'Note', "Sesshou Sakura placement 3");
    actions.Tick = struct('TalentGroup', "Skill", 'Param', totemLevelParam, 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'HitCount', tickHitCount, 'BaseActionDamageBonus', sakuraPassiveBonus, ...
        'C6EnemyDefIgnore', 0.60, 'ApplyGauge', 1.0, 'ICDRule', "Independent", ...
        'LunarisAttackName', "FoxTower_ThunderFall_Level3", 'LunarisDamageParam', "FoxTower_Damage_Level_3", ...
        'Note', "Sesshou Sakura ticks");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'Note', "Great Secret Art");
    actions.Thunder = struct('TalentGroup', "Burst", 'Param', "TenkoThunderboltDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'HitCount', 3, 'Note', "Tenko Thunderbolt");
    actions.ResetE1 = struct('TalentGroup', "Skill", 'Param', "SesshouSakuraDMGLevel1", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 0, 'ApplyGauge', 1.0, 'ICDRule', "Independent", ...
        'LunarisAttackName', "Attack01_Bullet_Material", 'LunarisDamageParam', "Attack01_Damage", ...
        'Note', "Post-burst recast 1");
    actions.ResetE2 = struct('TalentGroup', "Skill", 'Param', "SesshouSakuraDMGLevel2", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 0, 'ApplyGauge', 1.0, 'ICDRule', "Independent", ...
        'LunarisAttackName', "Attack02_Bullet_Material", 'LunarisDamageParam', "Attack02_Damage", ...
        'Note', "Post-burst recast 2");
    actions.ResetE3 = struct('TalentGroup', "Skill", 'Param', "SesshouSakuraDMGLevel3", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 0, 'ApplyGauge', 1.0, 'ICDRule', "Independent", ...
        'LunarisAttackName', "Attack03_Bullet_Material", 'LunarisDamageParam', "Attack03_Damage", ...
        'Note', "Post-burst recast 3");

    defaultRotation = {'E1', 'E2', 'E3', 'Tick', 'Q', 'Thunder', 'ResetE1', 'ResetE2', 'ResetE3', 'Tick'};
    if constellation < 1
        defaultRotation = {'E1', 'E2', 'E3', 'Tick', 'Q', 'Thunder', 'ResetE1', 'ResetE2', 'ResetE3', 'Tick'};
    end

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.70, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct( ...
            'E1', 0.28, 'E2', 0.28, 'E3', 0.32, 'Tick', 12.60, ...
            'Q', 1.18, 'Thunder', 0.45, 'ResetE1', 0.28, 'ResetE2', 0.28, 'ResetE3', 0.32), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'YaeMiko', workBuild, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

