function build = customArtifact_Lyney()
    % Default Lyney build targeting mono-Pyro charged-shot and hat detonation output.
    build = struct( ...
        'Weapon', '最初的大魔术', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CD', ...
        'WeaponSubStatValue', 0.662, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.92, ...
        'FlatATK', 311, ...
        'ER', 1.20, ...
        'EM', 60, ...
        'CritRate', 0.76, ...
        'CritDMG', 2.40, ...
        'PyroDMGBonus', 0.466, ...
        'ChargedDMGBonus', 0.24, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'MarechausseeHunter', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Lyney', 'artifacts_Lyney.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
