function build = customArtifact_KukiShinobu()
    % Default Shinobu build for EM/aggravate ring damage with HP sustain.
    build = struct( ...
        'Weapon', 'FreedomSworn', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'EM', ...
        'WeaponSubStatValue', 198.45, ...
        'WeaponRefinement', 1, ...
        'HPBonus', 0.46, ...
        'FlatHP', 4200, ...
        'EM', 300, ...
        'CritRate', 0.55, ...
        'CritDMG', 1.30, ...
        'ElectroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.18, ...
        'HealingBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'GildedDreams', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'KukiShinobu', 'artifacts_KukiShinobu.csv');
    writetable(struct2table(build), outputPath);
end
