function build = customArtifact_Charlotte()
    % Default Charlotte build balancing burst support and some personal Cryo damage.
    build = struct( ...
        'Weapon', '西风秘典', ...
        'WeaponATK', 510, ...
        'WeaponSubStatType', 'ER', ...
        'WeaponSubStatValue', 0.4594, ...
        'WeaponRefinement', 5, ...
        'AtkBonus', 0.88, ...
        'FlatATK', 311, ...
        'ER', 1.90, ...
        'EM', 40, ...
        'CritRate', 0.42, ...
        'CritDMG', 0.90, ...
        'CryoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'HealingBonus', 0.35, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'NoblesseOblige', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Charlotte', 'artifacts_Charlotte.csv');
    writetable(struct2table(build), outputPath);
end
