function build = customArtifact_Mavuika()
    % 玛薇卡默认构筑。
    % 默认面板偏向攻击、双暴和火伤，适配战意型爆发窗口。
    build = struct( ...
        'Weapon', 'SunforgedClaymore', ...
        'WeaponATK', 741, ...
        'AtkBonus', 0.76, ...
        'FlatATK', 311, ...
        'CritRate', 0.70, ...
        'CritDMG', 2.24, ...
        'PyroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00 ...
    );

    % 回写 CSV，便于统一入口和人工调参共用。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Mavuika', 'artifacts_Mavuika.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
