function build = customArtifact_Clorinde()
    % Default Clorinde build focused on electro skill/burst damage and crit.
    build = struct( ...
        'Weapon', 'Absolution', ...
        'WeaponATK', 674, ...
        'AtkBonus', 0.94, ...
        'FlatATK', 311, ...
        'CritRate', 0.74, ...
        'CritDMG', 2.16, ...
        'ElectroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.18, ...
        'SkillDMGBonus', 0.26, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 80, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'FragmentOfHarmonicWhimsy', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Clorinde', 'artifacts_Clorinde.csv');
    writetable(struct2table(build), outputPath);
end
