function [totalDMG, dps, breakdown, rotationTime, audit] = simulateClorindeDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Clorinde simulator tracking a Night Vigil loop of Swift Hunt and Impale the Night.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Clorinde', 'rotation_Clorinde.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Clorinde', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SwiftHuntDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 0.00, 'PostSetSkillActiveTime', 7.5, 'PostSetStacks', 3, 'Note', "Enter Night Vigil");
    actions.Shot = struct('TalentGroup', "Skill", 'Param', "SwiftHuntDMG", 'DamageField', "NormalDMGBonus", ...
        'BaseMultiplier', 1.00, 'SkillWindowMultiplier', 0.10, 'AllowCatalyze', 1, 'PostAddStacks', -1, ...
        'C1DamageBonus', 0.08, 'Note', "Swift Hunt");
    actions.Lunge = struct('TalentGroup', "Skill", 'Param', "ImpaleTheNightDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'SkillWindowMultiplier', 0.12, 'AllowCatalyze', 1, 'PostSetStacks', 3, ...
        'C2CritRateBonus', 0.10, 'Note', "Impale the Night");
    actions.Surge = struct('TalentGroup', "Skill", 'Param', "SurgingBladeDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'HitCount', 2, 'Note', "Surging blade");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'AllowCatalyze', 1, 'C6CritDMGBonus', 0.35, 'Note', "Last Lightfall");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.50, ...
        'DefaultRotation', {{'E', 'Shot', 'Shot', 'Lunge', 'Surge', 'Shot', 'Shot', 'Lunge', 'Surge', 'Shot', 'Shot', 'Lunge', 'Surge', 'Q'}}, ...
        'ActionTimeMap', struct('E', 0.35, 'Shot', 0.35, 'Lunge', 0.55, 'Surge', 0.18, 'Q', 1.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Clorinde', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

