function [totalDMG, dps, breakdown, rotationTime] = simulateClorindeDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Clorinde medium-detail simulator using a stance + electro core.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Clorinde', 'rotation_Clorinde.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Clorinde', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "EnterATK", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetSkillActiveTime', 7.5, 'PostSetStacks', 2, ...
        'C1DamageBonus', 0.08, 'Note', "Night vigil enter");
    actions.Shot = struct('TalentGroup', "Skill", 'Param', "ShotATK", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PerStackMultiplier', 0.14, 'SkillWindowMultiplier', 0.08, ...
        'AllowAmplify', 1, 'ReactionBonus', 0.10, 'PostAddStacks', -1, 'Note', "Electro pistol shot");
    actions.Lunge = struct('TalentGroup', "Skill", 'Param', "LungeATK", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PerStackMultiplier', 0.18, 'SkillWindowMultiplier', 0.10, ...
        'PostSetStacks', 3, 'C2CritRateBonus', 0.10, 'Note', "Impale lunge");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "BurstATK", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'C6CritDMGBonus', 0.35, 'Note', "Burst slash");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Hydro", ...
        'DefaultActionTime', 0.75, ...
        'ActionTimeMap', struct('E', 0.55, 'Shot', 0.55, 'Lunge', 0.80, 'Q', 1.15), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Clorinde', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
