function build = customArtifact_Prune()
    % Default Prune build emphasizing converted hammer hits and burst follow-up.
    build = struct( ...
        'Weapon', 'Lost Prayer to the Sacred Winds', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.331, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.92, ...
        'FlatATK', 311, ...
        'EM', 180, ...
        'ER', 1.35, ...
        'CritRate', 0.76, ...
        'CritDMG', 1.98, ...
        'AnemoDMGBonus', 0.466, ...
        'PyroDMGBonus', 0.20, ...
        'HydroDMGBonus', 0.20, ...
        'CryoDMGBonus', 0.20, ...
        'ElectroDMGBonus', 0.20, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'ViridescentVenerer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Prune', 'artifacts_Prune.csv');
    if exist(fileparts(outputPath), 'dir') ~= 7
        mkdir(fileparts(outputPath));
    end
    writetable(struct2table(build), outputPath);
end
