function [totalDMG, dps, breakdown, rotationTime] = simulateNaviaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Navia medium-detail simulator using the shared simple-character core.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Navia', 'rotation_Navia.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Navia', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillATK", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PerStackMultiplier', 0.12, 'PostSetStacks', 0, 'PreSetStacks', 6, ...
        'C1DamageBonus', 0.10, 'C6CritDMGBonus', 0.45, 'Note', "Crystalshot cannon");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "BurstATK", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetStacks', 6, 'C2CritRateBonus', 0.12, 'Note', "Burst salvo");
    actions.Shard = struct('TalentGroup', "Skill", 'Param', "ShardATK", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PerStackMultiplier', 0.04, 'PostAddStacks', 1, 'PostMaxStacks', 6, ...
        'Note', "Crystal shrapnel");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "N2ATK", 'DamageField', "NormalDMGBonus", ...
        'BaseMultiplier', 1.00, 'Note', "Normal attack");

    spec = struct( ...
        'Element', "Geo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.8, ...
        'ActionTimeMap', struct('E', 0.75, 'Q', 1.15, 'Shard', 0.55, 'N2', 0.55), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Navia', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
