function [totalDMG, dps, breakdown, rotationTime, audit] = simulateLisaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Lisa explicit conductive-stack / burst script with approximation.
    % Tap E, charged attack conductive application, hold E stack payoff, and
    % Lightning Rose burst are modeled as separate actions.
    % Remaining approximation: C4 burst lightning uses a doubled expected
    % hit count and C6 opens from a scripted 3-stack hold-E starter.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Lisa', 'rotation_Lisa.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Lisa', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    burstDefReduct = 0.15;
    qHitCount = 12 * (1 + double(constellation >= 4));

    actions = struct();
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'Note', "Normal 1");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'Note', "Normal 2");
    actions.CA = struct('TalentGroup', "Normal", 'Param', "ChargedAttackDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'PostAddMarks', 1, 'PostMaxMarks', 3, 'PostSetSkillActiveTime', 16.0, ...
        'LunarisAttackName', "FlickerWaveDamage", 'LunarisDamageParam', "Damage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Charged attack applies conductive");
    actions.ETap = struct('TalentGroup', "Skill", 'Param', "PressDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'PostAddMarks', 1, 'PostMaxMarks', 3, 'PostSetSkillActiveTime', 16.0, ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Tap skill");
    actions.EHold0 = struct('TalentGroup', "Skill", 'Param', "NonConductiveHoldDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'PostSetMarks', 0, ...
        'LunarisAttackName', "ThunderFall", 'LunarisDamageParam', "Damage_0", ...
        'ApplyGauge', 2.0, 'ICDRule', "Independent", 'Note', "Hold skill 0 stack");
    actions.EHold1 = struct('TalentGroup', "Skill", 'Param', "Stack1ConductiveHoldDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'PostSetMarks', 0, ...
        'LunarisAttackName', "ThunderFall", 'LunarisDamageParam', "Damage_1", ...
        'ApplyGauge', 2.0, 'ICDRule', "Independent", 'Note', "Hold skill 1 stack");
    actions.EHold2 = struct('TalentGroup', "Skill", 'Param', "Stack2ConductiveHoldDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'PostSetMarks', 0, ...
        'LunarisAttackName', "ThunderFall", 'LunarisDamageParam', "Damage_2", ...
        'ApplyGauge', 2.0, 'ICDRule', "Independent", 'Note', "Hold skill 2 stack");
    actions.EHold3 = struct('TalentGroup', "Skill", 'Param', "Stack3ConductiveHoldDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'PostSetMarks', 0, ...
        'LunarisAttackName', "ThunderFall", 'LunarisDamageParam', "Damage_3", ...
        'ApplyGauge', 2.0, 'ICDRule', "Independent", 'Note', "Hold skill 3 stack");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "DischargeDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'HitCount', qHitCount, ...
        'AllowCatalyze', double(aggravateReady), 'EnemyDefReduct', burstDefReduct, ...
        'LunarisAttackName', "PierceLightning_Ball_Attack", 'LunarisDamageParam', "Damage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Lightning Rose");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.75, ...
        'DefaultRotation', {{'ETap', 'CA', 'ETap', 'EHold3', 'Q'}}, ...
        'ActionTimeMap', struct('N1', 0.35, 'N2', 0.42, 'CA', 0.90, 'ETap', 0.45, 'EHold0', 1.35, 'EHold1', 1.35, 'EHold2', 1.35, 'EHold3', 1.35, 'Q', 1.10), ...
        'Actions', actions);

    if constellation >= 6
        spec.DefaultRotation = {{'EHold3', 'Q', 'CA', 'ETap', 'EHold2'}};
    end

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Lisa', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
