function [totalDMG, dps, breakdown, rotationTime] = simulateLisaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % 丽莎高精度近似模拟。
    % 建模要点：
    % 1. 区分点按叠导电、重击附导电、长按按导电层数结算；
    % 2. Q 期间写入 A4 15% 减防，C4 用 2 段期望闪电近似；
    % 3. C6 进场 3 层导电通过默认轴近似为起手直接长按；
    % 4. 激化队环境下，E/Q/普重击均可走激化附加伤。
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Lisa', 'rotation_Lisa.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Lisa', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    burstDefReduct = 0.15;
    qHitCount = 12 * (1 + double(constellation >= 4));

    actions = struct();
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'Note', "Normal 1");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'Note', "Normal 2");
    actions.CA = struct('TalentGroup', "Normal", 'Param', "ChargedAttackDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'PostAddMarks', 1, 'PostMaxMarks', 3, 'PostSetSkillActiveTime', 16.0, 'Note', "Charged attack applies conductive");
    actions.ETap = struct('TalentGroup', "Skill", 'Param', "PressDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), ...
        'PostAddMarks', 1, 'PostMaxMarks', 3, 'PostSetSkillActiveTime', 16.0, 'Note', "Tap skill");
    actions.EHold0 = struct('TalentGroup', "Skill", 'Param', "NonConductiveHoldDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'PostSetMarks', 0, 'Note', "Hold skill 0 stack");
    actions.EHold1 = struct('TalentGroup', "Skill", 'Param', "Stack1ConductiveHoldDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'PostSetMarks', 0, 'Note', "Hold skill 1 stack");
    actions.EHold2 = struct('TalentGroup', "Skill", 'Param', "Stack2ConductiveHoldDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'PostSetMarks', 0, 'Note', "Hold skill 2 stack");
    actions.EHold3 = struct('TalentGroup', "Skill", 'Param', "Stack3ConductiveHoldDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'PostSetMarks', 0, 'Note', "Hold skill 3 stack");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "DischargeDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'HitCount', qHitCount, ...
        'AllowCatalyze', double(aggravateReady), 'EnemyDefReduct', burstDefReduct, 'Note', "Lightning Rose");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.75, ...
        'DefaultRotation', {{'ETap', 'CA', 'ETap', 'EHold3', 'Q'}}, ...
        'ActionTimeMap', struct('N1', 0.35, 'N2', 0.42, 'CA', 0.90, 'ETap', 0.45, 'EHold0', 1.35, 'EHold1', 1.35, 'EHold2', 1.35, 'EHold3', 1.35, 'Q', 1.10), ...
        'Actions', actions);

    if constellation >= 6
        spec.DefaultRotation = {{'EHold3', 'Q', 'CA', 'ETap', 'EHold2'}};
    end

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Lisa', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
