function [totalDMG, dps, breakdown, rotationTime, audit] = simulateChongyunDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Chongyun simulator with skill field setup, Cryo-infused normals, and
    % burst spirit blades.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Chongyun', 'rotation_Chongyun.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Chongyun', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    bladeCount = 3 + double(constellation >= 6);
    c6BurstBonus = 0.15 * double(constellation >= 6);

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'PostSetSkillActiveTime', 10.0, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Damage", ...
        'LunarisDamageParam', "ElementalArt_Damage", ...
        'Note', "Layered Frost field cast");
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'Note', "Cryo infused normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 0.0, ...
        'ICDRule', "Independent", ...
        'Note', "Cryo infused normal 2");
    actions.N3 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 0.0, ...
        'ICDRule', "Independent", ...
        'Note', "Cryo infused normal 3");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00 + c6BurstBonus / max(1, bladeCount), ...
        'HitCount', bladeCount, ...
        'HitTimeline', 0.12 * ones(1, bladeCount), ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "SoulUnleash_Damage", ...
        'LunarisDamageParam', "ElementalBurst_Damage", ...
        'Note', "Spirit Blade burst");

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.60, ...
        'DefaultRotation', {{'E', 'N1', 'N2', 'N3', 'Q'}}, ...
        'ActionTimeMap', struct( ...
            'E', 0.66, ...
            'N1', 0.44, ...
            'N2', 0.48, ...
            'N3', 0.56, ...
            'Q', 0.52), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Chongyun', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
