function [totalDMG, dps, breakdown, rotationTime] = simulateChioriDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Chiori medium-detail simulator emphasizing skill doll uptime.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Chiori', 'rotation_Chiori.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Chiori', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillDEF", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetSkillActiveTime', 17.0, 'PostSetStacks', 2, ...
        'C1DamageBonus', 0.10, 'Note', "Tamoto deploy");
    actions.Doll = struct('TalentGroup', "Skill", 'Param', "DollDEF", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PerStackMultiplier', 0.12, 'SkillWindowMultiplier', 0.08, ...
        'C2DamageBonus', 0.12, 'Note', "Tamoto coordinated slash");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "BurstDEF", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostAddStacks', 1, 'PostMaxStacks', 3, ...
        'C6CritDMGBonus', 0.30, 'Note', "Burst cut");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "N2ATK", 'DamageField', "NormalDMGBonus", ...
        'BaseMultiplier', 1.00, 'Note', "Normal attack");

    spec = struct( ...
        'Element', "Geo", ...
        'ScalingMode', "DEF", ...
        'DefaultActionTime', 0.8, ...
        'ActionTimeMap', struct('E', 0.55, 'Doll', 1.30, 'Q', 1.10, 'N2', 0.55), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Chiori', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
