function [totalDMG, dps, breakdown, rotationTime, audit] = simulateKaedeharaKazuhaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Kaedehara Kazuha simulator with explicit Chihayaburu, Midare Ranzan,
    % burst field ticks, and absorbed-element follow-up damage.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'KaedeharaKazuha', 'rotation_KaedeharaKazuha.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'KaedeharaKazuha', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    absorbedElement = localResolveAbsorbedElement(teamContext, enemy);
    absorbedReady = double(strlength(absorbedElement) > 0);
    emValue = getFieldOrDefault(build, 'EM', 0) + getFieldOrDefault(teamContext, 'EMBonus', 0);
    c6InfusionBonus = 0.002 * emValue * double(constellation >= 6);
    burstTickCount = 4;
    burstTickTimeline = 2.0 * ones(1, burstTickCount);

    actions = struct();
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_01", ...
        'LunarisDamageParam', "NormalAttack_01_DamagePercentage", ...
        'Note', "Normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_02", ...
        'LunarisDamageParam', "NormalAttack_02_DamagePercentage", ...
        'Note', "Normal 2");
    actions.N3 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_03", ...
        'LunarisDamageParam', "NormalAttack_03_DamagePercentage", ...
        'Note', "Normal 3");
    actions.N4 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x4HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_04", ...
        'LunarisDamageParam', "NormalAttack_04_DamagePercentage", ...
        'Note', "Normal 4");
    actions.N5 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x5HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_05", ...
        'LunarisDamageParam', "NormalAttack_05_DamagePercentage", ...
        'Note', "Normal 5");
    actions.CA = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Charged attack");
    actions.EPress = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "PressSkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'PostSetSkillActiveTime', 10.0, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_EmptyJump", ...
        'LunarisDamageParam', "ElementalArt_EmptyJump_Damage", ...
        'Note', "Chihayaburu press");
    actions.EHold = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "HoldSkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'PostSetSkillActiveTime', 10.0, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_FlyAway", ...
        'LunarisDamageParam', "ElementalArt_FlyAway_Damage", ...
        'Note', "Chihayaburu hold");
    actions.PlungeSlash = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "PlungeDMG", ...
        'DamageField', "PlungeDMGBonus", ...
        'ActionElement', "Anemo", ...
        'ActionScalingMode', "ATK", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Slash", ...
        'LunarisAttackName', "FallingAnthem", ...
        'LunarisDamageParam', "FallingAnthem_Normal_Loop_Damage", ...
        'Note', "Midare Ranzan plunge slash");
    actions.PlungeImpact = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "LowHighPlungeDMG", ...
        'DamageField', "PlungeDMGBonus", ...
        'ActionElement', "Anemo", ...
        'ActionScalingMode', "ATK", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'LunarisAttackName', "FallingAnthem", ...
        'LunarisDamageParam', "FallingAnthem_Normal_Rank_2_Damage", ...
        'Note', "Midare Ranzan plunge impact");
    actions.PlungeMix = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "HoldSkillDMG", ...
        'DamageField', "PlungeDMGBonus", ...
        'ActionElement', absorbedElement, ...
        'MVOverride', 0, ...
        'FlatDirectATKWeight', 2.00 * absorbedReady, ...
        'AllowAmplify', localElementAllowsAmplify(absorbedElement, teamContext), ...
        'AllowCatalyze', localElementAllowsCatalyze(absorbedElement, teamContext), ...
        'PreferredAmplifyAura', localElementPreferredAura(absorbedElement, teamContext), ...
        'ApplyGauge', 1.0 * absorbedReady, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'LunarisAttackName', "PermanentSkill_1_ExtraDamage", ...
        'LunarisDamageParam', "PermanentSkill_1_FallingAttack_Damage", ...
        'Note', "Soumon Swordsmanship absorbed plunge");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SlashingDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'PostSetBurstActiveTime', 8.0, ...
        'PostSetSkillActiveTime', max(5.0 * double(constellation >= 6), 0), ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Slash", ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "ElementalBurst_Strike_Damage", ...
        'Note', "Kazuha Slash");
    actions.QDoT = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "DoT", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', burstTickCount, ...
        'HitTimeline', burstTickTimeline, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Mist", ...
        'LunarisDamageParam', "ElementalBurst_MistStrike_Damage", ...
        'Note', "Autumn Whirlwind Anemo ticks");
    actions.QInfuse = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "AdditionalElementalDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', absorbedElement, ...
        'BaseMultiplier', absorbedReady, ...
        'HitCount', burstTickCount, ...
        'HitTimeline', burstTickTimeline, ...
        'AllowAmplify', localElementAllowsAmplify(absorbedElement, teamContext), ...
        'AllowCatalyze', localElementAllowsCatalyze(absorbedElement, teamContext), ...
        'PreferredAmplifyAura', localElementPreferredAura(absorbedElement, teamContext), ...
        'ApplyGauge', 1.0 * absorbedReady, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Mist", ...
        'LunarisDamageParam', "ElementalBurst_MistStrike_Damage_Mix", ...
        'Note', "Autumn Whirlwind absorbed ticks");
    actions.C6N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'FlatDamageBonus', c6InfusionBonus, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Kazuha_C6Normal", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'LunarisAttackName', "NormalAttack_01", ...
        'LunarisDamageParam', "NormalAttack_01_DamagePercentage", ...
        'Note', "C6 infused normal 1");
    actions.C6CA = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'FlatDamageBonus', c6InfusionBonus, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Kazuha_C6Normal", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'Note', "C6 infused charged attack");

    defaultRotation = {'EHold', 'PlungeSlash', 'PlungeImpact', 'PlungeMix', 'Q', 'QDoT'};
    if absorbedReady > 0
        defaultRotation{end + 1} = 'QInfuse'; %#ok<AGROW>
    end
    if constellation >= 6
        defaultRotation = [defaultRotation, {'C6N1', 'C6CA'}]; %#ok<AGROW>
    end

    spec = struct( ...
        'Element', "Anemo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.55, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct( ...
            'N1', 0.28, ...
            'N2', 0.28, ...
            'N3', 0.32, ...
            'N4', 0.34, ...
            'N5', 0.42, ...
            'CA', 0.72, ...
            'EPress', 0.55, ...
            'EHold', 0.85, ...
            'PlungeSlash', 0.20, ...
            'PlungeImpact', 0.62, ...
            'PlungeMix', 0.10, ...
            'Q', 0.95, ...
            'QDoT', 8.00, ...
            'QInfuse', 8.00, ...
            'C6N1', 0.32, ...
            'C6CA', 0.72), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'KaedeharaKazuha', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function element = localResolveAbsorbedElement(teamContext, enemy)
    if nargin >= 2 && isstruct(enemy)
        initialAura = string(getFieldOrDefault(enemy, 'InitialAuraElement', ""));
        if any(strcmpi(initialAura, ["Pyro", "Hydro", "Electro", "Cryo"]))
            element = string(initialAura);
            return;
        end
    end

    priority = ["Pyro", "Hydro", "Electro", "Cryo"];
    for i = 1:numel(priority)
        if getFieldOrDefault(teamContext, char(priority(i) + "Count"), 0) >= 1
            element = priority(i);
            return;
        end
    end
    element = "";
end

function tf = localElementAllowsAmplify(element, teamContext)
    switch lower(char(string(element)))
        case 'pyro'
            tf = double(getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1 || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1);
        case 'hydro'
            tf = double(getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1);
        case 'cryo'
            tf = double(getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1);
        otherwise
            tf = 0;
    end
end

function tf = localElementAllowsCatalyze(element, teamContext)
    switch lower(char(string(element)))
        case 'electro'
            tf = double(getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1);
        case 'dendro'
            tf = double(getFieldOrDefault(teamContext, 'ElectroCount', 0) >= 1);
        otherwise
            tf = 0;
    end
end

function aura = localElementPreferredAura(element, teamContext)
    switch lower(char(string(element)))
        case 'pyro'
            if getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1
                aura = "Hydro";
            elseif getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1
                aura = "Cryo";
            else
                aura = "";
            end
        case 'hydro'
            aura = "Pyro";
        case 'cryo'
            aura = "Pyro";
        otherwise
            aura = "";
    end
end
