function build = customArtifact_Razor()
    % Default Razor build for physical-centric on-field burst strings.
    build = struct( ...
        'Weapon', 'SerpentSpine', ...
        'WeaponATK', 510, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.276, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.78, ...
        'FlatATK', 311, ...
        'ER', 1.20, ...
        'CritRate', 0.75, ...
        'CritDMG', 1.75, ...
        'PhysicalDMGBonus', 0.583, ...
        'ElectroDMGBonus', 0.15, ...
        'NormalDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.18, ...
        'ArtifactSet1', 'PaleFlame', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Razor', 'artifacts_Razor.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
