function [totalDMG, dps, breakdown, rotationTime, audit] = simulateCynoDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Cyno high-detail simulator.
    % Focus:
    % - burst loop with real Day of the Jackal bolt cadence
    % - C1 NA SPD window
    % - C2 stack-based Electro DMG bonus propagated to follow-up Electro hits
    % - C6 Day of the Jackal bolt scheduling with Judication stack refresh
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Cyno', 'rotation_Cyno.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Cyno', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Cyno', 'talents_Cyno.csv');
    talent = readtable(talentPath);
    skillLevel = talentLevel + 3 * double(constellation >= 5);
    burstLevel = talentLevel + 3 * double(constellation >= 3);
    emBonus = getTalentValue(talent, 'Burst', 'ElementalMasteryBonus', burstLevel);
    hasStellar = logical(getFieldOrDefault(teamContext, 'StellarConductEnabled', false));
    protectionEMBonus = 200 * double(hasStellar && constellation >= 1);
    burstStateEMBonus = emBonus + protectionEMBonus;
    burstReactionEM = getFieldOrDefault(build, 'EM', 0) + getFieldOrDefault(teamContext, 'EMBonus', 0) + burstStateEMBonus;
    speedScale = 1 / (1 + 0.20 * double(constellation >= 1));

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'LunarisAttackName', "ElementalArt_Bullet", ...
        'LunarisDamageParam', "Elemental_Art_Bullet_Damage", ...
        'ICDGroup', "Cyno_ElementalArt_Bullet", ...
        'ICDRule', "7 hits / 0.2s", ...
        'AllowCatalyze', 1, ...
        'Note', "Secret Rite: Chasmic Soulfarer");
    actions.Mortuary = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "MortuaryRiteDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'LunarisAttackName', "ElementalArt_Click_BurstMode", ...
        'LunarisDamageParam', "ElementalArt_BurstMode_Damage", ...
        'ICDGroup', "Cyno_ElementalArt", ...
        'ICDRule', "1 hits / 2.5s", ...
        'AllowCatalyze', 1, ...
        'PerMarkDamageBonus', 0.10 * double(constellation >= 2), ...
        'Note', "Mortuary Rite");
    actions.Duststalker = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "MortuaryRiteDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'MVOverride', 0, ...
        'FlatDirectATKWeight', 1.0, ...
        'FlatDirectEMWeight', 2.5, ...
        'HitCount', 3, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'PerMarkDamageBonus', 0.10 * double(constellation >= 2), ...
        'Note', "Featherfall Judgment bolts");
    actions.C6Bolt = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "MortuaryRiteDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'MVOverride', 0, ...
        'FlatDirectATKWeight', 1.0, ...
        'FlatDirectEMWeight', 2.5, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'PerMarkDamageBonus', 0.10 * double(constellation >= 2), ...
        'Note', "Day of the Jackal Duststalker Bolt");
    actions.TrialBolt = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "MortuaryRiteDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'MVOverride', 0, ...
        'FlatDirectATKWeight', 1.0, ...
        'FlatDirectEMWeight', 2.5, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'PerMarkDamageBonus', 0.10 * double(constellation >= 2), ...
        'Note', "Protection of Anubis Trialseeker Bolt");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "BasicDuration", ...
        'MVOverride', 0, ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'PostSetBurstActiveTime', 10.0, ...
        'PostSetMarks', 0, ...
        'PostSetAuxCounter', 0, ...
        'Note', "Pactsworn Pathclearer");

    for i = 1:5
        actions.(sprintf('B%d', i)) = struct( ...
            'TalentGroup', "Burst", ...
            'TalentLevelOverride', burstLevel, ...
            'Param', sprintf('x%dHitDMG', i), ...
            'DamageField', "BurstDMGBonus", ...
            'ActionElement', "Electro", ...
            'BaseMultiplier', 1.00, ...
            'FlatDirectEMWeight', 1.5, ...
            'FlatDirectDamage', 1.5 * burstStateEMBonus, ...
            'ApplyGauge', 1.0, ...
            'LunarisAttackName', "BurstMode_ExtraAttack_Bullet", ...
            'LunarisDamageParam', "Cyno_BurstMode_ExtraAttack_Damage", ...
            'ICDGroup', "Avatar_Pole_ExtraAttack", ...
            'ICDRule', "24 hits / 0.5s", ...
            'AllowCatalyze', 1, ...
            'ReactionEMOverride', burstReactionEM, ...
            'PerMarkDamageBonus', 0.10 * double(constellation >= 2), ...
            'PostAddMarks', double(constellation >= 2), ...
            'PostMaxMarks', 5, ...
            'Note', sprintf('Burst normal %d', i));
    end

    actions.BurstMortuary = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "MortuaryRiteDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', 1, ...
        'ApplyGauge', 1.0, ...
        'LunarisAttackName', "ElementalArt_Click_BurstMode", ...
        'LunarisDamageParam', "ElementalArt_BurstMode_Damage", ...
        'ICDGroup', "Cyno_ElementalArt", ...
        'ICDRule', "1 hits / 2.5s", ...
        'AllowCatalyze', 1, ...
        'ReactionEMOverride', burstReactionEM, ...
        'BaseActionDamageBonus', 0.35, ...
        'PerMarkDamageBonus', 0.10 * double(constellation >= 2), ...
        'Note', "Burst Mortuary Rite");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.55, ...
        'DefaultRotation', {localBuildDefaultRotation(constellation, hasStellar, speedScale)}, ...
        'ActionTimeMap', struct('E', 0.70, 'Mortuary', 0.35, 'Q', 1.05, ...
            'B1', 0.22 * speedScale, 'B2', 0.24 * speedScale, 'B3', 0.28 * speedScale, ...
            'B4', 0.30 * speedScale, 'B5', 0.36 * speedScale, 'BurstMortuary', 0.55, ...
            'Duststalker', 0.01, 'C6Bolt', 0.01, 'TrialBolt', 0.01), ...
        'Actions', actions);

    build.ElectroDMGBonus = getFieldOrDefault(build, 'ElectroDMGBonus', 0) + 0.15;
    build.SkillDMGBonus = getFieldOrDefault(build, 'SkillDMGBonus', 0) + 0.20;
    build.BurstDMGBonus = getFieldOrDefault(build, 'BurstDMGBonus', 0) + 0.20;

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Cyno', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function rotation = localBuildDefaultRotation(constellation, hasStellar, speedScale)
    rotation = {'E', 'Q', 'B1', 'B2', 'B3', 'BurstMortuary', 'Duststalker', ...
        'B4', 'B5', 'B1', 'B2', 'BurstMortuary', 'Duststalker', 'B3', 'B4', 'B5'};
    if constellation < 6
        return;
    end

    enhanced = cell(0, 1);
    jackalStacks = 0;
    boltCooldown = 0;
    boltAction = "C6Bolt";
    if hasStellar
        boltAction = "TrialBolt";
    end

    for i = 1:numel(rotation)
        action = string(rotation{i});
        enhanced{end + 1, 1} = char(action); %#ok<AGROW>

        if action == "Q"
            jackalStacks = min(8, jackalStacks + 4);
        end

        boltCooldown = max(0, boltCooldown - localResolveActionDuration(action, speedScale));
        if action == "BurstMortuary"
            jackalStacks = min(8, jackalStacks + 4);
        end

        if jackalStacks > 0 && boltCooldown <= 1e-9 && any(action == ["B1", "B2", "B3", "B4", "B5"])
            enhanced{end + 1, 1} = char(boltAction); %#ok<AGROW>
            jackalStacks = jackalStacks - 1;
            boltCooldown = 0.40;
        end
    end
    rotation = enhanced.';
end

function actionTime = localResolveActionDuration(action, speedScale)
    switch char(string(action))
        case 'E'
            actionTime = 0.70;
        case 'Mortuary'
            actionTime = 0.35;
        case 'Q'
            actionTime = 1.05;
        case 'B1'
            actionTime = 0.22 * speedScale;
        case 'B2'
            actionTime = 0.24 * speedScale;
        case 'B3'
            actionTime = 0.28 * speedScale;
        case 'B4'
            actionTime = 0.30 * speedScale;
        case 'B5'
            actionTime = 0.36 * speedScale;
        case 'BurstMortuary'
            actionTime = 0.55;
        otherwise
            actionTime = 0.01;
    end
end
