function [totalDMG, dps, breakdown, rotationTime] = simulateCynoDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Cyno simulator for burst-mode normal loops, Mortuary Rites, and EM scaling.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Cyno', 'rotation_Cyno.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Cyno', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Cyno', 'talents_Cyno.csv');
    talent = readtable(talentPath);
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    emBonus = getTalentValue(talent, 'Burst', 'ElementalMasteryBonus', burstLevel);
    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'Note', "Secret Rite: Chasmic Soulfarer");
    actions.Mortuary = struct('TalentGroup', "Skill", 'Param', "MortuaryRiteDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'Note', "Mortuary Rite");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "BasicDuration", 'MVOverride', 0, ...
        'DamageField', "BurstDMGBonus", 'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'PostSetBurstActiveTime', 10.0, ...
        'PostSetStacks', 4, 'Note', "Pactsworn Pathclearer");
    actions.B1 = struct('TalentGroup', "Burst", 'Param', "x1HitDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'Note', "Burst normal 1");
    actions.B2 = struct('TalentGroup', "Burst", 'Param', "x2HitDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', 1, 'Note', "Burst normal 2");
    actions.B3 = struct('TalentGroup', "Burst", 'Param', "x3HitDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', 1, 'Note', "Burst normal 3");
    actions.B4 = struct('TalentGroup', "Burst", 'Param', "x4HitDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', 1, 'Note', "Burst normal 4");
    actions.B5 = struct('TalentGroup', "Burst", 'Param', "x5HitDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'Note', "Burst normal 5");
    actions.BurstMortuary = struct('TalentGroup', "Skill", 'Param', "MortuaryRiteDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'HitCount', 1 + double(constellation >= 6), ...
        'AllowCatalyze', double(aggravateReady), 'Note', "Burst Mortuary Rite");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.55, ...
        'DefaultRotation', {{'E', 'Q', 'B1', 'B2', 'B3', 'BurstMortuary', 'B4', 'B5', 'B1', 'B2', 'BurstMortuary', 'B3', 'B4', 'B5'}}, ...
        'ActionTimeMap', struct('E', 0.70, 'Mortuary', 0.35, 'Q', 1.05, 'B1', 0.22, 'B2', 0.24, 'B3', 0.28, 'B4', 0.30, 'B5', 0.36, 'BurstMortuary', 0.55), ...
        'Actions', actions);

    build.EM = getFieldOrDefault(build, 'EM', 0) + emBonus;
    build.ElectroDMGBonus = getFieldOrDefault(build, 'ElectroDMGBonus', 0) + 0.15 + 0.35 * double(constellation >= 2);
    build.SkillDMGBonus = getFieldOrDefault(build, 'SkillDMGBonus', 0) + 0.20;
    build.BurstDMGBonus = getFieldOrDefault(build, 'BurstDMGBonus', 0) + 0.20;

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Cyno', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
