function [totalDMG, dps, breakdown, rotationTime, audit] = simulateOroronDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Ororon simulator with target-aware Spirit Orb bounces, full burst
    % pulse window, and optional Hypersense follow-up handling.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Ororon', 'rotation_Ororon.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Ororon', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    electroChargedReady = logical(getFieldOrDefault(teamContext, 'ElectroChargedReady', false) ...
        || getFieldOrDefault(teamContext, 'LunarChargedEnabled', false));
    electroReactionReady = aggravateReady || electroChargedReady ...
        || getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1;
    enemyTargetCount = max(1, round(getFieldOrDefault(enemy, 'TargetCount', ...
        getFieldOrDefault(enemy, 'EnemyCount', 1))));
    spiritOrbHitCount = min(enemyTargetCount, 4 + 2 * double(constellation >= 1));
    bounceHitCount = max(0, spiritOrbHitCount - 1);
    waveInterval = 1.50 / (1 + 0.25 * double(constellation >= 4));
    waveHitCount = max(1, floor(9.0 / waveInterval));
    waveTimeline = waveInterval * ones(1, waveHitCount);
    hypersenseReady = electroChargedReady && getFieldOrDefault(teamContext, 'MemberCount', 1) > 1;
    hypersenseHitCount = 4 * double(hypersenseReady);
    c2ElectroBonus = double(constellation >= 2) * (0.08 + min(0.32, 0.08 * max(0, enemyTargetCount - 1)));

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SpiritOrbDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), 'AllowTransformative', double(electroReactionReady), ...
        'ApplyGauge', 1.0, 'ICDRule', "Standard (3h/2.5s)", ...
        'LunarisAttackName', "Bullet_ElementalArt", 'LunarisDamageParam', "ElementalArt_Damage", ...
        'Note', "Night's Sling");
    actions.Bounce = struct('TalentGroup', "Skill", 'Param', "SpiritOrbDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, ...
        'HitCount', max(1, bounceHitCount), 'HitTimeline', 0.18 * ones(1, max(1, bounceHitCount)), ...
        'AllowCatalyze', double(aggravateReady), 'AllowTransformative', double(electroReactionReady), ...
        'ApplyGauge', 1.0, 'ICDGroup', "Ororon_SpiritOrb", 'ICDRule', "Standard (3h/2.5s)", ...
        'LunarisAttackName', "Bullet_ElementalArt", 'LunarisDamageParam', "ElementalArt_Damage", ...
        'Note', "Spirit Orb bounces");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "RitualDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), 'AllowTransformative', double(electroReactionReady), ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", ...
        'PostSetBurstActiveTime', 9.0, ...
        'LunarisAttackName', "ElementalBurst", 'LunarisDamageParam', "ElementalBurst_ReleaseDamage", ...
        'Note', "Dark Voices Echo");
    actions.Wave = struct('TalentGroup', "Burst", 'Param', "SoundwaveCollisionDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, ...
        'HitCount', waveHitCount, 'HitTimeline', waveTimeline, ...
        'AllowCatalyze', double(aggravateReady), 'AllowTransformative', double(electroReactionReady), ...
        'ApplyGauge', 1.0, 'ICDGroup', "Ororon_Oculus", 'ICDRule', "7 hits / 3s", ...
        'C2DamageBonus', c2ElectroBonus, ...
        'LunarisAttackName', localWaveAttackName(constellation), ...
        'LunarisDamageParam', "ElementalBurst_RotateDamage|ElementalBurst_RotateDamage|Nyx_BurstAdd|MUL|NyxValue_BurstCache|MUL|ADD", ...
        'Note', "Supersonic Oculus pulses");
    actions.Hypersense = struct('TalentGroup', "Skill", 'Param', "SpiritOrbDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'MVOverride', 0, 'FlatDirectATKWeight', 1.60, ...
        'HitCount', max(1, hypersenseHitCount), 'HitTimeline', 1.80 * ones(1, max(1, hypersenseHitCount)), ...
        'AllowCatalyze', double(aggravateReady), ...
        'ApplyGauge', 1.0, 'ICDGroup', "Ororon_Hypersense", 'ICDRule', "Standard (3h/2.5s)", ...
        'C1DamageBonus', 0.50, 'C2DamageBonus', c2ElectroBonus, ...
        'LunarisAttackName', "NyxState", 'LunarisDamageParam', "Damage_ExpendNyx", ...
        'Note', "Nightshade Synesthesia");
    actions.C6Echo = struct('TalentGroup', "Skill", 'Param', "SpiritOrbDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'MVOverride', 0, 'FlatDirectATKWeight', 3.20, ...
        'AllowCatalyze', double(aggravateReady), ...
        'ApplyGauge', 1.0, 'ICDGroup', "Ororon_Hypersense", 'ICDRule', "Standard (3h/2.5s)", ...
        'C2DamageBonus', c2ElectroBonus, ...
        'LunarisAttackName', "Constellation_AttackUp", 'LunarisDamageParam', "Damage_Constellation6|Damage_ExpendNyx|MUL", ...
        'Note', "C6 burst-triggered Hypersense");

    defaultRotation = {'E'};
    if bounceHitCount > 0
        defaultRotation{end + 1} = 'Bounce'; %#ok<AGROW>
    end
    defaultRotation{end + 1} = 'Q'; %#ok<AGROW>
    if constellation >= 6
        defaultRotation{end + 1} = 'C6Echo'; %#ok<AGROW>
    end
    defaultRotation{end + 1} = 'Wave'; %#ok<AGROW>
    if hypersenseReady
        defaultRotation{end + 1} = 'Hypersense'; %#ok<AGROW>
    end

    bounceActionTime = max(0.20, 0.18 * bounceHitCount + 0.20);
    hypersenseActionTime = 0.01;

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.8, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct('E', 0.60, 'Bounce', bounceActionTime, 'Q', 0.95, ...
            'Wave', sum(waveTimeline), 'Hypersense', hypersenseActionTime, 'C6Echo', 0.01), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Ororon', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function attackName = localWaveAttackName(constellation)
    if constellation >= 4
        attackName = "SkillObj_ElementalBurst_Rotate_Constellation";
    else
        attackName = "SkillObj_ElementalBurst_Rotate";
    end
end

