function [totalDMG, dps, breakdown, rotationTime, audit] = simulateOroronDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Ororon high-detail simulator.
    % Focus:
    % - target-aware Spirit Orb bounce count.
    % - burst pulse cadence with C4 faster-rotation handling.
    % - A1 Hypersense proc estimation from team archetype signals.
    % - constellation-aware Nighttide, Spiritual Supersense, and C6 echo damage.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Ororon', 'rotation_Ororon.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Ororon', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    electroChargedReady = logical(getFieldOrDefault(teamContext, 'ElectroChargedReady', false) ...
        || getFieldOrDefault(teamContext, 'LunarChargedEnabled', false));
    natlanSupportReady = localCountNightsoulAllies(teamContext) >= 1;
    electroReactionReady = aggravateReady || electroChargedReady || natlanSupportReady ...
        || getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1;

    % Ororon is one of the characters whose C3 / C5 talent upgrades are reversed
    % relative to the most common pattern.
    skillLevel = localClampTalentLevel(talentLevel + 3 * double(constellation >= 5));
    burstLevel = localClampTalentLevel(talentLevel + 3 * double(constellation >= 3));

    enemyTargetCount = max(1, round(getFieldOrDefault(enemy, 'TargetCount', ...
        getFieldOrDefault(enemy, 'EnemyCount', 1))));
    spiritOrbHitCount = min(enemyTargetCount, 4 + 2 * double(constellation >= 1));
    bounceHitCount = max(0, spiritOrbHitCount - 1);
    bounceTimeline = 0.18 * ones(1, bounceHitCount);

    waveTimeline = localBuildWaveTimeline(constellation);
    waveHitCount = numel(waveTimeline);
    c2ElectroBonus = localResolveC2ElectroBonus(constellation, enemyTargetCount);

    hypersenseProcCount = localEstimateHypersenseProcCount( ...
        teamContext, electroChargedReady, natlanSupportReady, enemyTargetCount);
    hypersenseTargetCount = min(4, enemyTargetCount);
    [hypersenseHitCount, hypersenseTimeline] = localBuildTriggeredHitTimeline( ...
        hypersenseProcCount, hypersenseTargetCount, 1.80, 0.60);
    c6EchoTargetCount = min(4, enemyTargetCount);

    c1NighttideBonus = 0.50 * double(constellation >= 1);
    c6HypersenseATKBonus = 0.20 * double(constellation >= 6 && hypersenseProcCount >= 1);
    hypersenseActive = hypersenseProcCount > 0;

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "SpiritOrbDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), ...
        'AllowTransformative', double(electroReactionReady), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'PostSetSkillActiveTime', 15.0, ...
        'LunarisAttackName', "Bullet_ElementalArt", ...
        'LunarisDamageParam', "ElementalArt_Damage", ...
        'Note', "Night's Sling");
    actions.Bounce = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "SpiritOrbDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', max(1, bounceHitCount), ...
        'HitTimeline', bounceTimeline, ...
        'AllowCatalyze', double(aggravateReady), ...
        'AllowTransformative', double(electroReactionReady), ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Ororon_SpiritOrb", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'LunarisAttackName', "Bullet_ElementalArt", ...
        'LunarisDamageParam', "ElementalArt_Damage", ...
        'Note', "Spirit Orb bounces");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "RitualDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), ...
        'AllowTransformative', double(electroReactionReady), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'PostSetBurstActiveTime', 9.0, ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "ElementalBurst_ReleaseDamage", ...
        'Note', "Dark Voices Echo");
    actions.Wave = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "SoundwaveCollisionDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', waveHitCount, ...
        'HitTimeline', waveTimeline, ...
        'AllowCatalyze', double(aggravateReady), ...
        'AllowTransformative', double(electroReactionReady), ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Ororon_Oculus", ...
        'ICDRule', "7 hits / 3s", ...
        'BaseActionDamageBonus', c2ElectroBonus, ...
        'LunarisAttackName', localWaveAttackName(constellation), ...
        'LunarisDamageParam', "ElementalBurst_RotateDamage|ElementalBurst_RotateDamage|Nyx_BurstAdd|MUL|NyxValue_BurstCache|MUL|ADD", ...
        'Note', "Supersonic Oculus pulses");
    actions.Hypersense = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "SpiritOrbDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'MVOverride', 0, ...
        'FlatDirectATKWeight', 1.60 * double(hypersenseActive), ...
        'HitCount', max(1, hypersenseHitCount), ...
        'HitTimeline', hypersenseTimeline, ...
        'AllowCatalyze', double(aggravateReady && hypersenseActive), ...
        'AllowTransformative', double(electroReactionReady && hypersenseActive), ...
        'ApplyGauge', double(hypersenseActive), ...
        'ICDGroup', "Ororon_Hypersense", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'BaseActionDamageBonus', c1NighttideBonus + c2ElectroBonus, ...
        'ATKBonus', c6HypersenseATKBonus, ...
        'LunarisAttackName', "NyxState", ...
        'LunarisDamageParam', "Damage_ExpendNyx", ...
        'Note', "Nightshade Synesthesia");
    actions.C6Echo = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "SpiritOrbDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'MVOverride', 0, ...
        'FlatDirectATKWeight', 3.20, ...
        'HitCount', max(1, c6EchoTargetCount), ...
        'HitTimeline', zeros(1, max(1, c6EchoTargetCount)), ...
        'AllowCatalyze', double(aggravateReady), ...
        'AllowTransformative', double(electroReactionReady), ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Ororon_Hypersense", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'BaseActionDamageBonus', c1NighttideBonus + c2ElectroBonus, ...
        'LunarisAttackName', "Constellation_AttackUp", ...
        'LunarisDamageParam', "Damage_Constellation6|Damage_ExpendNyx|MUL", ...
        'Note', "C6 burst-triggered Hypersense");

    defaultRotation = {'E'};
    if bounceHitCount > 0
        defaultRotation{end + 1} = 'Bounce'; %#ok<AGROW>
    end
    defaultRotation{end + 1} = 'Q'; %#ok<AGROW>
    if constellation >= 6
        defaultRotation{end + 1} = 'C6Echo'; %#ok<AGROW>
    end
    defaultRotation{end + 1} = 'Wave'; %#ok<AGROW>
    if hypersenseProcCount > 0
        defaultRotation{end + 1} = 'Hypersense'; %#ok<AGROW>
    end

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.8, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct( ...
            'E', 0.60, ...
            'Bounce', max(0.20, sum(bounceTimeline)), ...
            'Q', 0.95, ...
            'Wave', 9.0, ...
            'Hypersense', 0.01, ...
            'C6Echo', 0.01), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Ororon', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function attackName = localWaveAttackName(constellation)
    if constellation >= 4
        attackName = "SkillObj_ElementalBurst_Rotate_Constellation";
    else
        attackName = "SkillObj_ElementalBurst_Rotate";
    end
end

function bonus = localResolveC2ElectroBonus(constellation, enemyTargetCount)
    if constellation < 2
        bonus = 0;
        return;
    end
    bonus = min(0.32, 0.08 * max(1, min(enemyTargetCount, 4)));
end

function waveTimeline = localBuildWaveTimeline(constellation)
    if constellation >= 4
        waveTimeline = [0.60, 1.20 * ones(1, 7)];
    else
        waveTimeline = 1.50 * ones(1, 6);
    end
end

function [hitCount, timeline] = localBuildTriggeredHitTimeline(procCount, targetCount, interval, firstDelay)
    if procCount <= 0 || targetCount <= 0
        hitCount = 0;
        timeline = [];
        return;
    end

    hitCount = procCount * targetCount;
    timeline = zeros(1, hitCount);
    writeIndex = 1;
    for procIndex = 1:procCount
        if procIndex == 1
            timeline(writeIndex) = firstDelay;
        else
            timeline(writeIndex) = interval;
        end
        writeIndex = writeIndex + targetCount;
    end
end

function procCount = localEstimateHypersenseProcCount(teamContext, electroChargedReady, natlanSupportReady, enemyTargetCount)
    procCount = 0;
    if electroChargedReady
        procCount = 3 ...
            + double(getFieldOrDefault(teamContext, 'MemberCount', 1) >= 3) ...
            + double(getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1 && getFieldOrDefault(teamContext, 'ElectroCount', 0) >= 2);
    elseif natlanSupportReady
        procCount = 2 ...
            + double(getFieldOrDefault(teamContext, 'MemberCount', 1) >= 3) ...
            + double(enemyTargetCount >= 2);
    end

    if electroChargedReady && natlanSupportReady
        procCount = procCount + 1;
    end
    procCount = min(6, procCount);
end

function count = localCountNightsoulAllies(teamContext)
    memberNames = string(getFieldOrDefault(teamContext, 'MemberNames', strings(0, 1)));
    if isempty(memberNames)
        count = 0;
        return;
    end

    nightsoulRoster = [ ...
        "Chasca", "Citlali", "Iansan", "Ifa", "Kachina", ...
        "Kinich", "Mavuika", "Ororon", "Xilonen"];
    count = sum(ismember(memberNames, nightsoulRoster)) - double(any(memberNames == "Ororon"));
    count = max(0, count);
end

function level = localClampTalentLevel(level)
    level = max(1, min(15, round(level)));
end
