function build = customArtifact_Skirk()
    % Default baseline build used by the standalone Skirk entry and the
    % unified team entry.
    build = struct( ...
        'Weapon', 'Azurelight', ...
        'WeaponATK', 674, ...
        'AtkBonus', 0.76, ...
        'FlatATK', 311, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.05, ...
        'CryoDMGBonus', 0.616, ...
        'NormalDMGBonus', 0.40, ...
        'SkillDMGBonus', 0.15, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'EM', 40 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Skirk', 'artifacts_Skirk.csv');
    writetable(struct2table(build), outputPath);
end
