function [totalDMG, dps, breakdown, rotationTime, audit] = simulateYanfeiDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Yanfei simulator with Scarlet Seal stacking, charged attack
    % consumption, brilliance window, and crit-triggered extra hit.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Yanfei', 'rotation_Yanfei.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Yanfei', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talent = readtable(char(resolveCharacterDataFile('Yanfei', 'talents')));
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    brillianceBonus = getTalentValue(talent, 'Burst', 'ChargedAttackDMGBonus', burstLevel);
    maxSeals = 3 + double(constellation >= 6);
    vaporizeReady = getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1;
    c2CritBonus = 0.20 * double(constellation >= 2);
    sealPyroBonus = 0.05;
    p2ExtraMultiplier = 0.80;

    actions = struct();
    actions.N1 = localMakeYanfeiNormalAction("x1HitDMG", "Avatar_FeiyanGadgetSkill_NormalAttackDamage01", "Feiyan_NormalAttack_01_DamagePercentage", "Normal 1");
    actions.N2 = localMakeYanfeiNormalAction("x2HitDMG", "Avatar_FeiyanGadgetSkill_NormalAttackDamage02", "Feiyan_NormalAttack_02_DamagePercentage", "Normal 2");
    actions.N3 = localMakeYanfeiNormalAction("x3HitDMG", "Avatar_FeiyanGadgetSkill_NormalAttackDamage03", "Feiyan_NormalAttack_03_DamagePercentage", "Normal 3");
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'PostSetStacks', maxSeals, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'LunarisAttackName', "ElementalArt", ...
        'LunarisDamageParam', "Feiyan_ElementalArt_DamagePercentage", ...
        'Note', "Signed Edict");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'PostSetBurstActiveTime', 15.0, ...
        'PostSetStacks', maxSeals, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "Feiyan_ElementalBurst_DamagePercentage", ...
        'Note', "Done Deal");
    actions.CA3 = localMakeYanfeiChargedAction(3, brillianceBonus, c2CritBonus, vaporizeReady, "Feiyan_ExtraAttack_Weight_Damage_Lv03", "Charged 3 seals");
    actions.CA4 = localMakeYanfeiChargedAction(4, brillianceBonus, c2CritBonus, vaporizeReady, "Feiyan_ExtraAttack_Weight_Damage_Lv04", "Charged 4 seals");
    actions.CritExtra3 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttack", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Pyro", ...
        'MVOverride', 0, ...
        'FlatDirectATKWeight', p2ExtraMultiplier, ...
        'BurstWindowDamageBonus', brillianceBonus, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'LunarisAttackName', "ExtraAttack_DoAttack", ...
        'LunarisDamageParam', "Feiyan_Talent_CriticalAttack_Damage", ...
        'Note', "A4 crit extra hit");
    actions.CritExtra4 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttack", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Pyro", ...
        'MVOverride', 0, ...
        'FlatDirectATKWeight', p2ExtraMultiplier, ...
        'BurstWindowDamageBonus', brillianceBonus, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'LunarisAttackName', "ExtraAttack_DoAttack", ...
        'LunarisDamageParam', "Feiyan_Talent_CriticalAttack_Damage", ...
        'Note', "A4 crit extra hit");

    defaultRotation = {'E', 'CA3', 'CritExtra3', 'Q'};
    if constellation >= 6
        defaultRotation = [defaultRotation, {'CA4', 'CritExtra4'}]; %#ok<AGROW>
    else
        defaultRotation = [defaultRotation, {'CA3', 'CritExtra3'}]; %#ok<AGROW>
    end

    spec = struct( ...
        'Element', "Pyro", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Hydro", ...
        'DefaultActionTime', 0.60, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct( ...
            'N1', 0.34, ...
            'N2', 0.34, ...
            'N3', 0.40, ...
            'E', 0.72, ...
            'Q', 0.98, ...
            'CA3', 0.95, ...
            'CA4', 0.98, ...
            'CritExtra3', 0.12, ...
            'CritExtra4', 0.12), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Yanfei', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function action = localMakeYanfeiNormalAction(paramName, lunarisName, lunarisParam, note)
    action = struct( ...
        'TalentGroup', "Normal", ...
        'Param', string(paramName), ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'PostAddStacks', 1, ...
        'PostMaxStacks', 4, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', string(lunarisName), ...
        'LunarisDamageParam', string(lunarisParam), ...
        'Note', string(note));
end

function action = localMakeYanfeiChargedAction(sealCount, brillianceBonus, c2CritBonus, vaporizeReady, lunarisParam, note)
    sealDamageBonus = sealCount * 0.55;
    sealPyroBonus = sealCount * 0.05;
    action = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttack", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00 + sealDamageBonus, ...
        'FlatDamageBonus', sealPyroBonus, ...
        'BurstWindowDamageBonus', brillianceBonus, ...
        'CritRateBonus', c2CritBonus, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'PreSetStacks', sealCount, ...
        'PostSetStacks', 0, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'LunarisAttackName', "Avatar_FeiyanGadgetSkill_ExtraAttack_Damage", ...
        'LunarisDamageParam', string(lunarisParam), ...
        'Note', string(note));
end
