function [totalDMG, dps, breakdown, rotationTime, audit] = simulateKujouSaraDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Kujou Sara simulator with Crowfeather detonation, charged crowfeather,
    % burst titanbreaker / stormclusters, and C2 / C4 / C6 damage effects.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'KujouSara', 'rotation_KujouSara.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'KujouSara', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    c6ElectroCritDMG = 0.60 * double(constellation >= 6);
    stormclusterCount = 4 + 2 * double(constellation >= 4);

    actions = struct();
    actions.Aimed = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "FullyChargedAimedShot", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), ...
        'CritDMGBonus', c6ElectroCritDMG, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Bullet_ShootArrow_WithElectric", ...
        'LunarisDamageParam', "DamageWithElectric", ...
        'Note', "Charged shot");
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "TenguJuuraiAmbushDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), ...
        'CritDMGBonus', c6ElectroCritDMG, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "KarasShoot_DelayAttack", ...
        'LunarisDamageParam', "KarasShoot_Thunderfall_Damage", ...
        'Note', "Tengu Juurai: Ambush");
    actions.C2Echo = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "TenguJuuraiAmbushDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 0.30 * double(constellation >= 2), ...
        'AllowCatalyze', double(aggravateReady), ...
        'CritDMGBonus', c6ElectroCritDMG, ...
        'ApplyGauge', 1.0 * double(constellation >= 2), ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "KarasShoot_DelayAttack", ...
        'LunarisDamageParam', "KarasShoot_Thunderfall_Damage|Constellation_2_Ratio|MUL", ...
        'Note', "C2 weaker Crowfeather");
    actions.QMain = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "TenguJuuraiTitanbreakerDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), ...
        'CritDMGBonus', c6ElectroCritDMG, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Bullet_Material", ...
        'LunarisDamageParam', "ThunderFall_Damage", ...
        'Note', "Tengu Juurai: Titanbreaker");
    actions.QClusters = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "TenguJuuraiStormclusterDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', stormclusterCount, ...
        'HitTimeline', 0.20 * ones(1, stormclusterCount), ...
        'AllowCatalyze', double(aggravateReady), ...
        'CritDMGBonus', c6ElectroCritDMG, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Elemental_Burst_AttackWave", ...
        'LunarisDamageParam', "Elemental_Burst_AttackWave_Damage", ...
        'Note', "Stormcluster waves");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.65, ...
        'DefaultRotation', {{'E', 'C2Echo', 'Aimed', 'QMain', 'QClusters'}}, ...
        'ActionTimeMap', struct( ...
            'Aimed', 1.00, ...
            'E', 0.52, ...
            'C2Echo', 0.10, ...
            'QMain', 1.00, ...
            'QClusters', 1.20), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'KujouSara', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
