function build = customArtifact_Flins()
    % Default crit/electro build for Flins's summon-heavy burst window.
    build = struct( ...
        'Weapon', 'NightwatchPike', ...
        'WeaponATK', 674, ...
        'AtkBonus', 0.78, ...
        'FlatATK', 311, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.10, ...
        'ElectroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.20, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 180, ...
        'ResShred', 0.00 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Flins', 'artifacts_Flins.csv');
    writetable(struct2table(build), outputPath);
end
