function build = customArtifact_Flins()
    % 菲林斯默认构筑。
    % 当前默认面板偏向双暴与雷伤，兼顾少量精通以体现月感电派生伤害。
    build = struct( ...
        'Weapon', 'NightwatchPike', ...
        'WeaponATK', 674, ...
        'AtkBonus', 0.78, ...
        'FlatATK', 311, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.10, ...
        'ElectroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.20, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 180, ...
        'ResShred', 0.00 ...
    );

    % 回写 CSV，便于后续直接从表格检查默认值。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Flins', 'artifacts_Flins.csv');
    writetable(struct2table(build), outputPath);
end
