function build = customArtifact_Cyno()
    % Default Cyno build emphasizing burst-driven Electro and Aggravate output.
    build = struct( ...
        'Weapon', 'StaffOfTheScarletSands', ...
        'WeaponATK', 542, ...
        'AtkBonus', 0.28, ...
        'FlatATK', 120, ...
        'EM', 320, ...
        'CritRate', 0.78, ...
        'CritDMG', 2.20, ...
        'ElectroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.18, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'GildedDreams', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Cyno', 'artifacts_Cyno.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
