function build = customArtifact_Xiangling()
    % Default Xiangling build for Guoba and Pyronado vaporize-oriented damage.
    build = struct( ...
        'Weapon', 'EngulfingLightning', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'ER', ...
        'WeaponSubStatValue', 0.551, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.62, ...
        'FlatATK', 220, ...
        'ER', 1.95, ...
        'EM', 180, ...
        'CritRate', 0.66, ...
        'CritDMG', 1.55, ...
        'PyroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.00, ...
        'BurstDMGBonus', 0.00, ...
        'ArtifactSet1', 'EmblemOfSeveredFate', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Xiangling', 'artifacts_Xiangling.csv');
    writetable(struct2table(build), outputPath);
end
