function [totalDMG, dps, breakdown, rotationTime] = simulateXianglingDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % 香菱高精度近似模拟。
    % 建模要点：
    % 1. 锅巴拆成持续喷火命中，并在 C1 时为后续火段挂减抗窗口；
    % 2. 旋火轮拆为起手三段 + 持续轮切段，C4 增加持续时间导致段数增加；
    % 3. 将 A4 辣椒常驻近似到后半轮转，并把 C2 末段爆炸显式加入；
    % 4. 默认轴按锅巴 -> Q -> 旋火轮站场切人近似，而不是简单聚合成一段。
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Xiangling', 'rotation_Xiangling.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Xiangling', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    vapeReady = getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1;
    guobaResShred = 0.15 * double(constellation >= 1);
    chiliAtkBonus = 0.10;
    pyronadoDurationHits = 10 + 4 * double(constellation >= 4);

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "FlameDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'HitCount', 4, ...
        'AllowAmplify', double(vapeReady), 'PostSetSkillActiveTime', 6.0, 'Note', "Guoba spray");
    actions.Chili = struct('TalentGroup', "Skill", 'Param', "FlameDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", 'MVOverride', 0, 'PostSetBurstActiveTime', 10.0, ...
        'Note', "Guoba chili buff window");
    actions.QSlash1 = struct('TalentGroup', "Burst", 'Param', "x1HitSwingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', 0.15 * double(constellation >= 6), ...
        'AllowAmplify', double(vapeReady), 'SkillWindowExtraResShred', guobaResShred, ...
        'BurstWindowMultiplier', chiliAtkBonus, 'Note', "Pyronado opening hit 1");
    actions.QSlash2 = struct('TalentGroup', "Burst", 'Param', "x2HitSwingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', 0.15 * double(constellation >= 6), ...
        'AllowAmplify', double(vapeReady), 'SkillWindowExtraResShred', guobaResShred, ...
        'BurstWindowMultiplier', chiliAtkBonus, 'Note', "Pyronado opening hit 2");
    actions.QSlash3 = struct('TalentGroup', "Burst", 'Param', "x3HitSwingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', 0.15 * double(constellation >= 6), ...
        'AllowAmplify', double(vapeReady), 'SkillWindowExtraResShred', guobaResShred, ...
        'BurstWindowMultiplier', chiliAtkBonus, 'Note', "Pyronado opening hit 3");
    actions.Pyronado = struct('TalentGroup', "Burst", 'Param', "PyronadoDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'HitCount', pyronadoDurationHits, ...
        'BaseActionDamageBonus', 0.15 * double(constellation >= 6), 'AllowAmplify', double(vapeReady), ...
        'SkillWindowExtraResShred', guobaResShred, 'BurstWindowMultiplier', chiliAtkBonus, 'Note', "Pyronado spins");
    actions.N5Explode = struct('TalentGroup', "Normal", 'Param', "x5HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Pyro", 'MVOverride', 0.75 * double(constellation >= 2), ...
        'AllowAmplify', double(vapeReady), 'ExtraResShred', guobaResShred, 'Note', "C2 implode");

    spec = struct( ...
        'Element', "Pyro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.72, ...
        'DefaultRotation', {{'E', 'Chili', 'QSlash1', 'QSlash2', 'QSlash3', 'Pyronado', 'N5Explode'}}, ...
        'ActionTimeMap', struct('E', 0.80, 'Chili', 0.10, 'QSlash1', 0.15, 'QSlash2', 0.15, 'QSlash3', 0.15, 'Pyronado', 9.80 + 4.00 * double(constellation >= 4), 'N5Explode', 0.10), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Xiangling', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
