function [totalDMG, dps, breakdown, rotationTime, audit] = simulateXianglingDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Xiangling explicit Guoba / Pyronado script with approximation.
    % Guoba sprays, Pyronado opening slashes, sustained spins, and C2
    % implode are modeled as separate scripted actions.
    % Remaining approximation: the Guoba chili pickup is modeled as a
    % delayed mid-rotation split instead of position-validated pickup timing.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Xiangling', 'rotation_Xiangling.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Xiangling', 'Constellation', constellation, 'Build', build)}, 20, struct(), enemy);
    end

    vapeReady = getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1;
    guobaResShred = 0.15 * double(constellation >= 1);
    chiliAtkBonus = 0.10;
    pyronadoDurationHits = 10 + 4 * double(constellation >= 4);
    pyronadoEarlyHits = min(5, max(1, pyronadoDurationHits - 1));
    pyronadoLateHits = max(0, pyronadoDurationHits - pyronadoEarlyHits);

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "FlameDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'HitCount', 4, ...
        'AllowAmplify', double(vapeReady), 'PostSetSkillActiveTime', 6.0, ...
        'LunarisAttackName', "PandaFire_Attack", 'LunarisDamageParam', "XiangLing_ProudSkill32_P1_Damage_Percentage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Guoba spray");
    actions.Chili = struct('TalentGroup', "Skill", 'Param', "FlameDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "None", 'MVOverride', 0, 'ApplyGauge', 0, 'CanApplyAura', false, ...
        'CanTriggerReaction', false, 'AllowAmplify', false, 'AllowCatalyze', false, ...
        'AllowTransformative', false, 'PostSetBurstActiveTime', 10.0, ...
        'Note', "Guoba chili pickup");
    actions.QSlash1 = struct('TalentGroup', "Burst", 'Param', "x1HitSwingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', 0.15 * double(constellation >= 6), ...
        'AllowAmplify', double(vapeReady), 'SkillWindowExtraResShred', guobaResShred, ...
        'LunarisAttackName', "FireCircle01", 'LunarisDamageParam', "XiangLing_ProudSkill33_P2_Damage_Percentage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Pyronado opening hit 1");
    actions.QSlash2 = struct('TalentGroup', "Burst", 'Param', "x2HitSwingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', 0.15 * double(constellation >= 6), ...
        'AllowAmplify', double(vapeReady), 'SkillWindowExtraResShred', guobaResShred, ...
        'LunarisAttackName', "FireCircle02", 'LunarisDamageParam', "XiangLing_ProudSkill33_P3_Damage_Percentage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Pyronado opening hit 2");
    actions.QSlash3 = struct('TalentGroup', "Burst", 'Param', "x3HitSwingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', 0.15 * double(constellation >= 6), ...
        'AllowAmplify', double(vapeReady), 'SkillWindowExtraResShred', guobaResShred, ...
        'LunarisAttackName', "FireCircle03", 'LunarisDamageParam', "XiangLing_ProudSkill33_P4_Damage_Percentage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Pyronado opening hit 3");
    actions.PyronadoEarly = struct('TalentGroup', "Burst", 'Param', "PyronadoDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'HitCount', pyronadoEarlyHits, ...
        'BaseActionDamageBonus', 0.15 * double(constellation >= 6), 'AllowAmplify', double(vapeReady), ...
        'SkillWindowExtraResShred', guobaResShred, ...
        'LunarisAttackName', "FireCircle03", 'LunarisDamageParam', "XiangLing_ProudSkill33_P4_Damage_Percentage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Pyronado spins before chili");
    actions.Pyronado = struct('TalentGroup', "Burst", 'Param', "PyronadoDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'HitCount', pyronadoLateHits, ...
        'BaseActionDamageBonus', 0.15 * double(constellation >= 6), 'AllowAmplify', double(vapeReady), ...
        'SkillWindowExtraResShred', guobaResShred, 'BurstWindowMultiplier', chiliAtkBonus, ...
        'LunarisAttackName', "FireCircle03", 'LunarisDamageParam', "XiangLing_ProudSkill33_P4_Damage_Percentage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Pyronado spins after chili");
    actions.N5Explode = struct('TalentGroup', "Normal", 'Param', "x5HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Pyro", 'MVOverride', 0.75 * double(constellation >= 2), ...
        'AllowAmplify', double(vapeReady), 'ExtraResShred', guobaResShred, ...
        'LunarisAttackName', "TalentBomb", 'LunarisDamageParam', "Xiangling_Talent_232_P3_Bomb_Damage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Standard (3h/2.5s)", 'Note', "C2 implode");

    spec = struct( ...
        'Element', "Pyro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.72, ...
        'DefaultRotation', {{'E', 'QSlash1', 'QSlash2', 'QSlash3', 'PyronadoEarly', 'Chili', 'Pyronado', 'N5Explode'}}, ...
        'ActionTimeMap', struct('E', 0.80, 'QSlash1', 0.15, 'QSlash2', 0.15, 'QSlash3', 0.15, 'PyronadoEarly', 4.75, 'Chili', 0.10, 'Pyronado', 5.05 + 4.00 * double(constellation >= 4), 'N5Explode', 0.10), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Xiangling', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
