function [totalDMG, dps, breakdown, rotationTime, audit] = simulateXianglingDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Xiangling explicit Guoba / Pyronado script with approximation.
    % Guoba sprays, Pyronado opening slashes, sustained spins, and C2
    % implode are modeled as separate scripted actions.
    % Remaining approximation: when CombatEventTable does not include an
    % explicit Guoba chili pickup event, the split still falls back to the
    % legacy mid-rotation timing.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Xiangling', 'rotation_Xiangling.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Xiangling', 'Constellation', constellation, 'Build', build)}, 20, struct(), enemy);
    end

    vapeReady = getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1;
    guobaResShred = 0.15 * double(constellation >= 1);
    chiliAtkBonus = 0.10;
    pyronadoDurationHits = 10 + 4 * double(constellation >= 4);
    pyronadoEarlyHits = min(5, max(1, pyronadoDurationHits - 1));
    pyronadoLateHits = max(0, pyronadoDurationHits - pyronadoEarlyHits);

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "FlameDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'HitCount', 4, ...
        'AllowAmplify', double(vapeReady), 'PostSetSkillActiveTime', 6.0, ...
        'LunarisAttackName', "PandaFire_Attack", 'LunarisDamageParam', "XiangLing_ProudSkill32_P1_Damage_Percentage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Guoba spray");
    actions.Chili = struct('TalentGroup', "Skill", 'Param', "FlameDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "None", 'MVOverride', 0, 'ApplyGauge', 0, 'CanApplyAura', false, ...
        'CanTriggerReaction', false, 'AllowAmplify', false, 'AllowCatalyze', false, ...
        'AllowTransformative', false, 'PostSetBurstActiveTime', 10.0, ...
        'Note', "Guoba chili pickup");
    actions.QSlash1 = struct('TalentGroup', "Burst", 'Param', "x1HitSwingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', 0.15 * double(constellation >= 6), ...
        'AllowAmplify', double(vapeReady), 'SkillWindowExtraResShred', guobaResShred, ...
        'LunarisAttackName', "FireCircle01", 'LunarisDamageParam', "XiangLing_ProudSkill33_P2_Damage_Percentage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Pyronado opening hit 1");
    actions.QSlash2 = struct('TalentGroup', "Burst", 'Param', "x2HitSwingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', 0.15 * double(constellation >= 6), ...
        'AllowAmplify', double(vapeReady), 'SkillWindowExtraResShred', guobaResShred, ...
        'LunarisAttackName', "FireCircle02", 'LunarisDamageParam', "XiangLing_ProudSkill33_P3_Damage_Percentage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Pyronado opening hit 2");
    actions.QSlash3 = struct('TalentGroup', "Burst", 'Param', "x3HitSwingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', 0.15 * double(constellation >= 6), ...
        'AllowAmplify', double(vapeReady), 'SkillWindowExtraResShred', guobaResShred, ...
        'LunarisAttackName', "FireCircle03", 'LunarisDamageParam', "XiangLing_ProudSkill33_P4_Damage_Percentage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Pyronado opening hit 3");
    actions.PyronadoEarly = struct('TalentGroup', "Burst", 'Param', "PyronadoDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'HitCount', pyronadoEarlyHits, ...
        'BaseActionDamageBonus', 0.15 * double(constellation >= 6), 'AllowAmplify', double(vapeReady), ...
        'SkillWindowExtraResShred', guobaResShred, ...
        'LunarisAttackName', "FireCircle03", 'LunarisDamageParam', "XiangLing_ProudSkill33_P4_Damage_Percentage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", ...
        'TotalSpinHits', pyronadoDurationHits, ...
        'TotalSpinDuration', 9.80 + 4.00 * double(constellation >= 4), ...
        'DefaultEarlyHits', pyronadoEarlyHits, ...
        'DefaultEarlyDuration', 4.75, ...
        'DefaultLateDuration', 5.05 + 4.00 * double(constellation >= 4), ...
        'Note', "Pyronado spins before chili");
    actions.Pyronado = struct('TalentGroup', "Burst", 'Param', "PyronadoDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", 'BaseMultiplier', 1.00, 'HitCount', pyronadoLateHits, ...
        'BaseActionDamageBonus', 0.15 * double(constellation >= 6), 'AllowAmplify', double(vapeReady), ...
        'SkillWindowExtraResShred', guobaResShred, 'BurstWindowMultiplier', chiliAtkBonus, ...
        'LunarisAttackName', "FireCircle03", 'LunarisDamageParam', "XiangLing_ProudSkill33_P4_Damage_Percentage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", 'Note', "Pyronado spins after chili");
    actions.N5Explode = struct('TalentGroup', "Normal", 'Param', "x5HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Pyro", 'MVOverride', 0.75 * double(constellation >= 2), ...
        'AllowAmplify', double(vapeReady), 'ExtraResShred', guobaResShred, ...
        'LunarisAttackName', "TalentBomb", 'LunarisDamageParam', "Xiangling_Talent_232_P3_Bomb_Damage", ...
        'ApplyGauge', 1.0, 'ICDRule', "Standard (3h/2.5s)", 'Note', "C2 implode");

    spec = struct( ...
        'Element', "Pyro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.72, ...
        'InitializeStateFn', @localInitializeState, ...
        'BeforeActionFn', @localBeforeAction, ...
        'DefaultRotation', {{'E', 'QSlash1', 'QSlash2', 'QSlash3', 'PyronadoEarly', 'Chili', 'Pyronado', 'N5Explode'}}, ...
        'ActionTimeMap', struct('E', 0.80, 'QSlash1', 0.15, 'QSlash2', 0.15, 'QSlash3', 0.15, 'PyronadoEarly', 4.75, 'Chili', 0.10, 'Pyronado', 5.05 + 4.00 * double(constellation >= 4), 'N5Explode', 0.10), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Xiangling', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function state = localInitializeState(state, hookContext) %#ok<INUSD>
    state.PyronadoPlan = struct('Resolved', false);
end

function [state, actionSpec, actionTime, note] = localBeforeAction( ...
        state, actionKey, actionSpec, actionTime, note, hookContext)
    if any(actionKey == ["PyronadoEarly", "Chili", "Pyronado"])
        [state, plan] = localResolvePyronadoPickupPlan(state, actionSpec, hookContext);
        if actionKey == "PyronadoEarly"
            actionSpec.HitCount = plan.EarlyHits;
            actionTime = plan.EarlyDuration;
        elseif actionKey == "Pyronado"
            actionSpec.HitCount = plan.LateHits;
            actionTime = plan.LateDuration;
        end

        if plan.ExplicitPickup
            note = localAppendNote(note, sprintf('pickup@%.2fs', plan.PickupTime));
        end
    end
end

function [state, plan] = localResolvePyronadoPickupPlan(state, actionSpec, hookContext)
    plan = getFieldOrDefault(state, 'PyronadoPlan', struct('Resolved', false));
    if isstruct(plan) && logical(getFieldOrDefault(plan, 'Resolved', false))
        return;
    end

    totalHits = max(2, round(double(getFieldOrDefault(actionSpec, 'TotalSpinHits', 10))));
    totalSpinDuration = max(0, double(getFieldOrDefault(actionSpec, 'TotalSpinDuration', 9.80)));
    defaultEarlyHits = max(1, min(totalHits - 1, round(double(getFieldOrDefault(actionSpec, 'DefaultEarlyHits', 5)))));
    defaultEarlyDuration = max(0, double(getFieldOrDefault(actionSpec, 'DefaultEarlyDuration', 4.75)));
    defaultLateDuration = max(0, double(getFieldOrDefault(actionSpec, 'DefaultLateDuration', totalSpinDuration - defaultEarlyDuration)));

    plan = struct( ...
        'Resolved', true, ...
        'ExplicitPickup', false, ...
        'PickupTime', NaN, ...
        'EarlyHits', defaultEarlyHits, ...
        'LateHits', max(1, totalHits - defaultEarlyHits), ...
        'EarlyDuration', defaultEarlyDuration, ...
        'LateDuration', defaultLateDuration);

    currentTime = double(getFieldOrDefault(hookContext, 'ElapsedTime', 0));
    if totalSpinDuration <= 0
        state.PyronadoPlan = plan;
        return;
    end

    pickupRows = queryCombatEvents(getFieldOrDefault(hookContext, 'TeamContext', struct()), struct( ...
        'EventKind', "Pickup", ...
        'EventName', ["GuobaChili", "Chili"], ...
        'TimeRange', [currentTime, currentTime + totalSpinDuration]));
    if isempty(pickupRows)
        state.PyronadoPlan = plan;
        return;
    end

    pickupTime = double(pickupRows.Time(1));
    if ~isfinite(pickupTime)
        state.PyronadoPlan = plan;
        return;
    end

    earlyDuration = min(totalSpinDuration, max(0, pickupTime - currentTime));
    lateDuration = max(0, totalSpinDuration - earlyDuration);
    interval = totalSpinDuration / max(totalHits, 1);
    hitTimes = interval * 0.5 + interval * (0:(totalHits - 1));
    earlyHits = sum(hitTimes <= earlyDuration + 1e-9);
    earlyHits = max(1, min(totalHits - 1, earlyHits));

    plan.ExplicitPickup = true;
    plan.PickupTime = pickupTime;
    plan.EarlyDuration = earlyDuration;
    plan.LateDuration = lateDuration;
    plan.EarlyHits = earlyHits;
    plan.LateHits = totalHits - earlyHits;
    state.PyronadoPlan = plan;
end

function note = localAppendNote(baseNote, suffix)
    if strlength(string(baseNote)) == 0
        note = string(suffix);
    else
        note = string(baseNote) + ", " + string(suffix);
    end
end
