function build = customArtifact_AratakiItto()
    % Default Itto build for DEF-scaling Geo burst loops.
    build = struct( ...
        'Weapon', 'RedhornStonethresher', ...
        'WeaponATK', 542, ...
        'WeaponSubStatType', 'CD', ...
        'WeaponSubStatValue', 0.882, ...
        'WeaponRefinement', 1, ...
        'DEFBonus', 0.58, ...
        'FlatDEF', 300, ...
        'AtkBonus', 0.20, ...
        'ER', 1.20, ...
        'CritRate', 0.75, ...
        'CritDMG', 2.40, ...
        'GeoDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.40, ...
        'SkillDMGBonus', 0.30, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'HuskOfOpulentDreams', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'AratakiItto', 'artifacts_AratakiItto.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
