function [totalDMG, dps, breakdown, rotationTime, audit] = simulateAratakiIttoDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Itto simulator with burst conversion, Superlative Superstrength economy, and DEF conversion.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'AratakiItto', 'rotation_AratakiItto.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'AratakiItto', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'AratakiItto', 'talents_AratakiItto.csv');
    talent = readtable(talentPath);
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    burstAtkBonus = getTalentValue(talent, 'Burst', 'ATKBonus', burstLevel);
    c6KesagiriCritDMG = 0.70 * double(constellation >= 6);
    effectiveKesagiriCount = 4 + 2 * double(constellation >= 6) * 0.50;

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Geo", 'BaseMultiplier', 1.00, 'PostSetStacks', 1, ...
        'Note', "Ushi hit");
    actions.UshiExit = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Geo", 'BaseMultiplier', 0, 'PostAddStacks', 1, 'PostMaxStacks', 5, ...
        'Note', "Ushi leaves");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "ATKBonus", 'MVOverride', 0, ...
        'DamageField', "BurstDMGBonus", 'ActionElement', "Geo", 'BaseMultiplier', 1.00, ...
        'PostSetBurstActiveTime', 11.0, 'PostSetStacks', 2 + double(constellation >= 1), ...
        'PostC1AddStacks', 2, 'PostMaxStacks', 5, 'Note', "Raging Oni King");
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Geo", 'BaseMultiplier', 1.00, 'BurstWindowDamageBonus', 0.00, ...
        'FlatDirectDEFWeight', burstAtkBonus, 'BurstWindowExtraResShred', 0.20, 'Note', "Burst normal 1");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Geo", 'BaseMultiplier', 1.00, 'PostAddStacks', 1, 'PostMaxStacks', 5, ...
        'FlatDirectDEFWeight', burstAtkBonus, 'BurstWindowExtraResShred', 0.20, 'Note', "Burst normal 2");
    actions.N3 = struct('TalentGroup', "Normal", 'Param', "x3HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Geo", 'BaseMultiplier', 1.00, 'PostAddStacks', 1, 'PostMaxStacks', 5, ...
        'FlatDirectDEFWeight', burstAtkBonus, 'BurstWindowExtraResShred', 0.20, 'Note', "Burst normal 3");
    actions.N4 = struct('TalentGroup', "Normal", 'Param', "x4HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Geo", 'BaseMultiplier', 1.00, 'PostAddStacks', 2, 'PostMaxStacks', 5, ...
        'FlatDirectDEFWeight', burstAtkBonus, 'BurstWindowExtraResShred', 0.20, 'Note', "Burst normal 4");
    actions.Combo = struct('TalentGroup', "Normal", 'Param', "AratakiKesagiriComboSlashDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Geo", 'BaseMultiplier', 1.00, 'HitCount', effectiveKesagiriCount, ...
        'FlatDirectDEFWeight', burstAtkBonus + 0.35, 'CritDMGBonus', c6KesagiriCritDMG, ...
        'BurstWindowExtraResShred', 0.20, 'Note', "Arataki Kesagiri combo");
    actions.Final = struct('TalentGroup', "Normal", 'Param', "AratakiKesagiriFinalSlashDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Geo", 'BaseMultiplier', 1.00, 'FlatDirectDEFWeight', burstAtkBonus + 0.35, ...
        'CritDMGBonus', c6KesagiriCritDMG, 'BurstWindowExtraResShred', 0.20, 'PostSetStacks', 0, ...
        'Note', "Arataki Kesagiri final");
    actions.Saichimonji = struct('TalentGroup', "Normal", 'Param', "SaichimonjiSlashDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Geo", 'BaseMultiplier', 1.00, 'FlatDirectDEFWeight', burstAtkBonus, ...
        'BurstWindowExtraResShred', 0.20, 'Note', "Saichimonji slash");

    build.AtkBonus = getFieldOrDefault(build, 'AtkBonus', 0) + 0.20 * double(constellation >= 4);

    spec = struct( ...
        'Element', "Geo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.65, ...
        'DefaultRotation', {{'E', 'Q', 'N1', 'N2', 'N3', 'N4', 'Combo', 'Final', 'UshiExit', 'Combo', 'Final'}}, ...
        'ActionTimeMap', struct( ...
            'E', 0.72, 'UshiExit', 2.00, 'Q', 1.08, ...
            'N1', 0.24, 'N2', 0.26, 'N3', 0.30, 'N4', 0.40, ...
            'Combo', 1.20, 'Final', 0.42, 'Saichimonji', 0.52), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'AratakiItto', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

