function [totalDMG, dps, breakdown, rotationTime, audit] = simulateXingqiuDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Xingqiu simulator for rain swords, skill hit, and sword rain burst.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Xingqiu', 'rotation_Xingqiu.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Xingqiu', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    hydroReady = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1;
    rainCount = 8 + 2 * double(constellation >= 2);

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(hydroReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Spoondrift", ...
        'LunarisDamageParam', "Spoondrift_Damage", ...
        'Note', "Fatal Rainscreen");
    actions.Rain1 = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SwordRainDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', rainCount, ...
        'HitTimeline', 1.00 * ones(1, rainCount), ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Xingqiu_Rain", ...
        'ICDRule', "3 hits / 2.0s", ...
        'LunarisAttackName', "Bullet_PhantomBurst1", ...
        'LunarisDamageParam', "BounceWater_Damage", ...
        'Note', "Rain sword wave 1");
    actions.Rain2 = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SwordRainDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', rainCount, ...
        'HitTimeline', 1.00 * ones(1, rainCount), ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Xingqiu_Rain", ...
        'ICDRule', "3 hits / 2.0s", ...
        'LunarisAttackName', "Bullet_PhantomBurstS1", ...
        'LunarisDamageParam', "BounceWater_Damage", ...
        'Note', "Rain sword wave 2");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SwordRainDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', 1, ...
        'PreferredAmplifyAura', "Pyro", ...
        'PostSetBurstActiveTime', 15.0, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Bullet_PhantomBurst1", ...
        'LunarisDamageParam', "BounceWater_Damage", ...
        'Note', "Raincutter cast");

    spec = struct( ...
        'Element', "Hydro", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Pyro", ...
        'DefaultActionTime', 0.60, ...
        'DefaultRotation', {{'E', 'Q', 'Rain1', 'Rain2'}}, ...
        'ActionTimeMap', struct('E', 0.80, 'Q', 1.00, 'Rain1', 15.00, 'Rain2', 15.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Xingqiu', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
