function [totalDMG, dps, breakdown, rotationTime, audit] = simulateQiqiDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Qiqi high-detail simulator.
    % 重点：
    % - Herald of Frost 的施放、协同攻击与持续伤害
    % - Fortune-Preserving Talisman 的标记与 C1 能量回收
    % - C4 攻击下降、C6 星超导平伤
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Qiqi', 'rotation_Qiqi.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Qiqi', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    workBuild = build;
    radianceStellar = logical(getFieldOrDefault(teamContext, 'StellarConductEnabled', false));
    if constellation >= 2 && radianceStellar
        workBuild.AtkBonus = getFieldOrDefault(workBuild, 'AtkBonus', 0) + 0.50;
    end

    talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Qiqi', 'talents_Qiqi.csv');
    talent = readtable(talentPath);
    normalLevel = talentLevel;
    skillLevel = talentLevel + 3 * double(constellation >= 5);
    burstLevel = talentLevel + 3 * double(constellation >= 3);

    cryoBonusVsAura = 0.15 * double(constellation >= 2);
    meltReady = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1;
    c6StellarFlat = 6.0 * getApproxATK(workBuild, 287) * double(constellation >= 6) * double(radianceStellar);

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'PostSetSkillActiveTime', 15.0, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Bullet", ...
        'LunarisDamageParam', "Elemental_Art_Damage", ...
        'Note', "Herald of Frost cast");
    actions.Herald = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "HeraldOfFrostDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', 5, ...
        'HitTimeline', 3.0 * ones(1, 5), ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Bullet", ...
        'LunarisDamageParam', "Elemental_Art_Damage", ...
        'Note', "Herald orbit damage");
    actions.HeraldCoord = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "HeraldOfFrostCoordinatedAttackDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "PermanentSkill_3", ...
        'LunarisDamageParam', "ElementalArt_StarStrengthen_AOE_Damage", ...
        'Note', "Herald coordinated strike");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(meltReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_TriggerAttack", ...
        'LunarisDamageParam', "ElementalBurst_Damage", ...
        'Note', "Preserver of Fortune");
    actions.QStellar = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "StellarConductDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', getFieldOrDefault(teamContext, 'StellarConductTaggedDMGBonus', 0) ...
            + getFieldOrDefault(teamContext, 'StellarGlimmerBonus', 0), ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_TriggerAttack", ...
        'Note', "Radiance Stellar-Conduct burst strike");
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'EnemyAuraDamageBonusElement', "Cryo", ...
        'EnemyAuraDamageBonus', cryoBonusVsAura, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'EnemyAuraDamageBonusElement', "Cryo", ...
        'EnemyAuraDamageBonus', cryoBonusVsAura, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Normal 2");
    actions.CA = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'EnemyAuraDamageBonusElement', "Cryo", ...
        'EnemyAuraDamageBonus', cryoBonusVsAura, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Charged attack");

    defaultRotation = {'E', 'Q'};
    if radianceStellar
        defaultRotation = {'E', 'Q', 'QStellar'};
    end
    defaultRotation = [defaultRotation, {'HeraldCoord', 'N1', 'HeraldCoord', 'N2', 'HeraldCoord', 'CA', 'HeraldCoord', 'Herald'}];

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Pyro", ...
        'DefaultActionTime', 0.65, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct( ...
            'E', 0.62, ...
            'Herald', 15.00, ...
            'Q', 0.95, ...
            'QStellar', 0.01, ...
            'HeraldCoord', 0.01, ...
            'N1', 0.32, ...
            'N2', 0.36, ...
            'CA', 0.82), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Qiqi', workBuild, enemy, seqFile, talentLevel, constellation, teamContext, spec);

    if constellation >= 6 && radianceStellar
        audit = localAttachC6Audit(audit, c6StellarFlat);
    end
end

function atk = getApproxATK(build, baseAtk)
    atk = (baseAtk + getFieldOrDefault(build, 'WeaponATK', 0)) * (1 + getFieldOrDefault(build, 'AtkBonus', 0)) ...
        + getFieldOrDefault(build, 'FlatATK', 0);
end

function audit = localAttachC6Audit(audit, flatDamage)
    if isempty(fieldnames(audit))
        return;
    end
    if isfield(audit, 'Rows') && istable(audit.Rows)
        extra = table(string("Qiqi"), string("C6StellarConduct"), flatDamage, string("team flat"), ...
            'VariableNames', {'Character', 'Action', 'FlatDamage', 'Note'});
        audit.C6Audit = extra;
    end
end
