function build = customArtifact_Lohen()
    % Default Lohen build oriented around cryo on-field stance damage.
    build = struct( ...
        'Weapon', 'Staff of Homa', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CD', ...
        'WeaponSubStatValue', 0.662, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.82, ...
        'FlatATK', 311, ...
        'EM', 160, ...
        'ER', 1.25, ...
        'CritRate', 0.78, ...
        'CritDMG', 2.38, ...
        'CryoDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.18, ...
        'ChargedDMGBonus', 0.18, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'BlizzardStrayer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Lohen', 'artifacts_Lohen.csv');
    if exist(fileparts(outputPath), 'dir') ~= 7
        mkdir(fileparts(outputPath));
    end
    writetable(struct2table(build), outputPath);
end
