function [totalDMG, dps, breakdown, rotationTime] = simulateLohenDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Lohen simulator modeling Masterstroke stance, Joy spenders, and Will to Win scaling.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Lohen', 'rotation_Lohen.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Lohen', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    willCap = 100 * (1 + 2 * double(constellation >= 1));
    burstWillBonus = 0.4 * double(constellation >= 4);

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "x1HitDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 1, ...
        'PostSetSkillActiveTime', 13.0, 'PostSetCustomValue', willCap, 'Note', "Masterstroke enter");
    actions.N1 = struct('TalentGroup', "Skill", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'SkillWindowMultiplier', 0.08, 'PostAddMarks', 17, 'Note', "Masterstroke normal 1");
    actions.N2 = struct('TalentGroup', "Skill", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'SkillWindowMultiplier', 0.08, 'PostAddMarks', 17, 'Note', "Masterstroke normal 2");
    actions.N3 = struct('TalentGroup', "Skill", 'Param', "x3HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 3, 'SkillWindowMultiplier', 0.08, 'PostAddMarks', 17, 'Note', "Masterstroke normal 3");
    actions.N4 = struct('TalentGroup', "Skill", 'Param', "x4HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'SkillWindowMultiplier', 0.08, 'PostAddMarks', 17, 'Note', "Masterstroke normal 4");
    actions.N5 = struct('TalentGroup', "Skill", 'Param', "x5HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 2, 'SkillWindowMultiplier', 0.08, 'PostAddMarks', 17, 'Note', "Masterstroke normal 5");
    actions.CA = struct('TalentGroup', "Skill", 'Param', "ChargedAttackDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 2, 'SkillWindowMultiplier', 0.10, 'PostAddMarks', 34, 'Note', "Masterstroke charged");
    actions.Etched = struct('TalentGroup', "Skill", 'Param', "EtchedIntoBoneAndSoulDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'PerCustomMultiplier', 0.004, 'PreSetMarks', 100, ...
        'PostSetMarks', 0, 'PostSetCustomValue', 0, 'C6CritDMGBonus', 1.75, 'Note', "Etched into Bone and Soul");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00 + burstWillBonus, 'PerCustomMultiplier', 0.004, ...
        'PostSetBurstActiveTime', 15.0, 'PostSetCustomValue', 0, 'C6CritDMGBonus', 1.75, 'Note', "Manifest Judgment");
    actions.C2Follow = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", 'MVOverride', 3.00, 'FlatMVBonus', 0, 'Note', "C2 Evilsbane Blade");

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.78, ...
        'DefaultRotation', {{'E', 'N1', 'N2', 'N3', 'CA', 'Etched', 'N4', 'N5', 'Etched', 'Q'}}, ...
        'ActionTimeMap', struct('E', 0.70, 'N1', 0.45, 'N2', 0.45, 'N3', 0.55, 'N4', 0.55, 'N5', 0.65, 'CA', 0.75, 'Etched', 0.80, 'Q', 1.00, 'C2Follow', 0.10), ...
        'Actions', actions);

    if constellation >= 2
        spec.DefaultRotation = {{'E', 'N1', 'N2', 'N3', 'Etched', 'C2Follow', 'N4', 'CA', 'Etched', 'Q', 'C2Follow'}};
    end
    if constellation >= 6
        spec.DefaultRotation = {{'E', 'N1', 'N2', 'N3', 'Etched', 'C2Follow', 'N4', 'CA', 'Etched', 'N5', 'Etched', 'Q', 'C2Follow'}};
    end

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Lohen', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
