function [totalDMG, dps, breakdown, rotationTime] = simulateGorouDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Gorou simulator with Geo-count field buffs and DEF-based personal damage.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Gorou', 'rotation_Gorou.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Gorou', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Gorou', 'talents_Gorou.csv');
    talent = readtable(talentPath);
    geoCount = getFieldOrDefault(teamContext, 'GeoCount', 0);
    bannerLevel = min(3, max(1, geoCount));
    skillLevel = talentLevel + 3 * double(constellation >= 3);
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    defBoost = getTalentValue(talent, 'Skill', 'DEFIncrease', skillLevel) / 1000;
    geoBonus = getTalentValue(talent, 'Skill', 'GeoDMGBonus', skillLevel);
    c2CollapseBonus = 0.20 * double(constellation >= 2);
    c6GeoCritDMG = 0.10 * double(bannerLevel == 1 && constellation >= 6) ...
        + 0.20 * double(bannerLevel == 2 && constellation >= 6) ...
        + 0.40 * double(bannerLevel >= 3 && constellation >= 6);
    if geoCount >= 3
        bannerGeoBonus = 0.40;
    elseif geoCount >= 2
        bannerGeoBonus = 0.00;
    else
        bannerGeoBonus = 0.00;
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Geo", 'BaseMultiplier', 1.00, ...
        'PostSetBurstActiveTime', 0, 'PostSetStacks', 0, ...
        'FlatDirectDEFWeight', 1.56, 'PostSetCustomValue', bannerLevel, 'Note', "Inuzaka All-Round Defense");
    actions.EHold = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Geo", 'BaseMultiplier', 1.00, ...
        'FlatDirectDEFWeight', 1.56, 'PostSetCustomValue', bannerLevel, 'Note', "Inuzaka hold");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Geo", 'ActionScalingMode', "DEF", 'BaseMultiplier', 1.00, ...
        'FlatDirectDEFWeight', 0.156, ...
        'PostSetBurstActiveTime', 9.0, 'PostSetCustomValue', bannerLevel, 'Note', "Juuga: Forward Unto Victory");
    actions.Collapse = struct('TalentGroup', "Burst", 'Param', "CrystalCollapseDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Geo", 'ActionScalingMode', "DEF", 'BaseMultiplier', 1.00, ...
        'HitCount', 6, 'FlatDirectDEFWeight', 0.156, 'C2ActionDamageBonus', c2CollapseBonus, 'PostSetBurstActiveTime', 9.0, ...
        'PostSetCustomValue', bannerLevel, 'Note', "Crystal Collapse");
    actions.GeoWave = struct('TalentGroup', "Burst", 'Param', "CrystalCollapseDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Geo", 'ActionScalingMode', "DEF", 'BaseMultiplier', 1.00, ...
        'HitCount', 2, 'FlatDirectDEFWeight', 0.156, 'C2ActionDamageBonus', c2CollapseBonus, 'BurstWindowDamageBonus', bannerGeoBonus, ...
        'CritDMGBonus', c6GeoCritDMG, 'Note', "Field follow-up");

    build.DEFBonus = getFieldOrDefault(build, 'DEFBonus', 0) + defBoost;
    build.GeoDMGBonus = getFieldOrDefault(build, 'GeoDMGBonus', 0) + geoBonus * double(geoCount >= 3);

    spec = struct( ...
        'Element', "Geo", ...
        'ScalingMode', "DEF", ...
        'DefaultActionTime', 0.75, ...
        'DefaultRotation', {{'E', 'Q', 'Collapse', 'GeoWave'}}, ...
        'ActionTimeMap', struct('E', 0.72, 'EHold', 0.92, 'Q', 1.05, 'Collapse', 0.55, 'GeoWave', 1.50), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Gorou', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
