function [totalDMG, dps, breakdown, rotationTime, audit] = simulateMonaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Mona simulator with explicit phantom ticks, omen window, and bubble
    % detonation handling.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Mona', 'rotation_Mona.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Mona', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talent = readtable(char(resolveCharacterDataFile('Mona', 'talents')));
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    omenBonus = getTalentValue(talent, 'Burst', 'DMGBonus', burstLevel);
    omenDuration = getTalentValue(talent, 'Burst', 'OmenDuration', burstLevel);
    vaporizeReady = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1;
    c1ReactionBonus = 0.15 * double(constellation >= 1);
    c4CritRateBonus = 0.15 * double(constellation >= 4);

    actions = struct();
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_01", ...
        'LunarisDamageParam', "AS_Mona_NormalAttack_01", ...
        'Note', "Normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_02", ...
        'LunarisDamageParam', "AS_Mona_NormalAttack_02", ...
        'Note', "Normal 2");
    actions.N3 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_03", ...
        'LunarisDamageParam', "AS_Mona_NormalAttack_03", ...
        'Note', "Normal 3");
    actions.N4 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x4HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_04_Hit", ...
        'LunarisDamageParam', "AS_Mona_NormalAttack_04", ...
        'Note', "Normal 4");
    actions.CA = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'Note', "Charged attack");
    actions.CAOmen = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'BurstWindowDamageBonus', omenBonus, ...
        'CritRateBonus', c4CritRateBonus, ...
        'ReactionBonus', c1ReactionBonus, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'Note', "Charged attack under Omen");
    actions.N1Omen = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'BurstWindowDamageBonus', omenBonus, ...
        'CritRateBonus', c4CritRateBonus, ...
        'ReactionBonus', c1ReactionBonus, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_01", ...
        'LunarisDamageParam', "AS_Mona_NormalAttack_01", ...
        'Note', "Normal 1 under Omen");
    actions.AutoCA = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'BurstWindowDamageBonus', omenBonus, ...
        'CritRateBonus', c4CritRateBonus, ...
        'ReactionBonus', c1ReactionBonus, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'LunarisAttackName', "ExtraAttack_Damage", ...
        'LunarisDamageParam', "AS_Mona_ExtraAttack_Damge", ...
        'Note', "C2 automatic charged attack");
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "DoT", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", ...
        'MVOverride', 0, ...
        'PostSetSkillActiveTime', 5.0, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Mirror Reflection summon");
    actions.EDoT = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "DoT", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', 4, ...
        'HitTimeline', 1.0 * ones(1, 4), ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Avatar_MonaGadgetSkill_Phantom", ...
        'LunarisDamageParam', "AS_Mona_Phantom_ThinkDamageRate", ...
        'Note', "Phantom ticks");
    actions.EExplode = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "ExplosionDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Avatar_MonaGadgetSkill_PhantomLastAttack", ...
        'LunarisDamageParam', "AS_Mona_Phantom_LastDamageRate", ...
        'Note', "Phantom explosion");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "IllusoryBubbleDuration", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", ...
        'MVOverride', 0, ...
        'PostSetBurstActiveTime', omenDuration, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "StarChart", ...
        'LunarisDamageParam', "-", ...
        'Note', "Stellaris Phantasm cast");
    actions.Bubble = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "IllusoryBubbleExplosionDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'ReactionBonus', c1ReactionBonus, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'PostSetBurstActiveTime', 0.0, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "StarChart", ...
        'LunarisDamageParam', "AS_Mona_StarChart_Bubble_RemovedDamage", ...
        'Note', "Illusory Bubble detonation");

    if constellation >= 2
        defaultRotation = {'E', 'EDoT', 'Q', 'N1Omen', 'AutoCA', 'Bubble', 'EExplode'};
    else
        defaultRotation = {'E', 'EDoT', 'Q', 'CAOmen', 'Bubble', 'EExplode'};
    end

    spec = struct( ...
        'Element', "Hydro", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Pyro", ...
        'DefaultActionTime', 0.60, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct( ...
            'N1', 0.34, ...
            'N2', 0.36, ...
            'N3', 0.40, ...
            'N4', 0.48, ...
            'CA', 0.92, ...
            'CAOmen', 0.92, ...
            'N1Omen', 0.34, ...
            'AutoCA', 0.82, ...
            'E', 0.40, ...
            'EDoT', 4.00, ...
            'EExplode', 0.55, ...
            'Q', 0.95, ...
            'Bubble', 0.45), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Mona', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
