function [totalDMG, dps, breakdown, rotationTime] = simulateYaoyaoDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Yaoyao simulator covering Yuegui radishes and Adeptal Legacy barrages.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Yaoyao', 'rotation_Yaoyao.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Yaoyao', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    skillHits = 4 + double(constellation >= 1);
    burstHits = 6 + 2 * double(constellation >= 6);
    spreadReady = getFieldOrDefault(teamContext, 'ElectroCount', 0) >= 1;

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "WhiteJadeRadishDMG", 'MVOverride', 0, ...
        'DamageField', "SkillDMGBonus", 'PostSetSkillActiveTime', 10.0, 'Note', "Yuegui deploy");
    actions.Radish = struct('TalentGroup', "Skill", 'Param', "WhiteJadeRadishDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'HitCount', skillHits, ...
        'ApplyGauge', 1.0, 'LunarisAttackName', "Turnip_Bullet", 'LunarisDamageParam', "Yaoyao_Turnip_ElementalArt_Damage", ...
        'ICDGroup', "Yaoyao_GrassAttack", 'ICDRule', "6 hits / 2.5s", 'HitIntervals', 1.9 * ones(1, max(0, skillHits - 1)), ...
        'AllowCatalyze', double(spreadReady), 'Note', "White Jade Radishes");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'AllowCatalyze', 1, 'ApplyGauge', 1.0, ...
        'LunarisAttackName', "ElementalBurst", 'LunarisDamageParam', "ElementalBurst_Damage", ...
        'ICDRule', "Independent", ...
        'PostSetBurstActiveTime', 5.0, 'Note', "Moonjade Descent");
    actions.BurstRadish = struct('TalentGroup', "Burst", 'Param', "AdeptalLegacyWhiteJadeRadishDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", 'BaseMultiplier', 1.00, 'HitCount', burstHits, ...
        'ApplyGauge', 1.0, 'LunarisAttackName', "Turnip_Bullet", 'LunarisDamageParam', "Yaoyao_Turnip_ElementalBurst_Damage", ...
        'ICDGroup', "Yaoyao_ElementalBurst", 'ICDRule', "6 hits / 1.5s", 'HitIntervals', 0.6 * ones(1, max(0, burstHits - 1)), ...
        'AllowCatalyze', double(spreadReady), 'Note', "Adeptal Legacy radishes");

    spec = struct( ...
        'Element', "Dendro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.80, ...
        'DefaultRotation', {{'E', 'Radish', 'Q', 'BurstRadish'}}, ...
        'ActionTimeMap', struct('E', 0.70, 'Radish', 10.00, 'Q', 0.95, 'BurstRadish', 5.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Yaoyao', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
