function build = customArtifact_Nefer()
    % 奈芙尔默认构筑。
    % 默认面板强调精通和草伤，适配影舞与月绽放核心玩法。
    build = struct( ...
        'Weapon', 'SecretArchive', ...
        'WeaponATK', 608, ...
        'AtkBonus', 0.22, ...
        'FlatATK', 150, ...
        'EM', 900, ...
        'CritRate', 0.68, ...
        'CritDMG', 2.08, ...
        'DendroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'DeepwoodMemories', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1 ...
    );

    % 回写 CSV，方便统一入口和单角色入口共用同一基线。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Nefer', 'artifacts_Nefer.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
