function build = customArtifact_Chevreuse()
    % 夏沃蕾默认构筑。
    % 默认面板偏向生命值与充能，同时保留一定双暴与火伤，
    % 便于在超载队中同时承担减抗辅助与少量副C输出。
    build = struct( ...
        'Weapon', 'RightfulReward', ...
        'WeaponATK', 565, ...
        'HPBonus', 1.46, ...
        'FlatHP', 4780, ...
        'ER', 1.90, ...
        'CritRate', 0.52, ...
        'CritDMG', 1.18, ...
        'PyroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'HealingBonus', 0.15, ...
        'EM', 120, ...
        'ResShred', 0.00 ...
    );

    % 回写默认构筑，便于后续直接查看或继续微调。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Chevreuse', 'artifacts_Chevreuse.csv');
    writetable(struct2table(build), outputPath);
end
