function build = customArtifact_Dahlia()
    % Default Dahlia build balancing direct ATK-scaled damage and shield utility.
    build = struct( ...
        'Weapon', 'Favonius Sword', ...
        'WeaponATK', 454, ...
        'WeaponSubStatType', 'ER', ...
        'WeaponSubStatValue', 0.613, ...
        'WeaponRefinement', 5, ...
        'AtkBonus', 0.72, ...
        'FlatATK', 220, ...
        'HPBonus', 0.35, ...
        'FlatHP', 1200, ...
        'ER', 1.70, ...
        'EM', 80, ...
        'CritRate', 0.58, ...
        'CritDMG', 1.32, ...
        'HydroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.24, ...
        'HealingBonus', 0.15, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'NoblesseOblige', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Dahlia', 'artifacts_Dahlia.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
