function build = customArtifact_Sethos()
    % Default Sethos build emphasizing EM-electro charged output.
    build = struct( ...
        'Weapon', 'Slingshot', ...
        'WeaponATK', 354, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.311, ...
        'WeaponRefinement', 5, ...
        'AtkBonus', 0.28, ...
        'FlatATK', 180, ...
        'EM', 620, ...
        'ER', 1.20, ...
        'CritRate', 0.74, ...
        'CritDMG', 1.72, ...
        'ElectroDMGBonus', 0.466, ...
        'ChargedDMGBonus', 0.35, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.18, ...
        'ReactionDMGBonus', 0.15, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'WanderersTroupe', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Sethos', 'artifacts_Sethos.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
