function build = customArtifact_Alhaitham()
    % Default Alhaitham build emphasizing EM-driven mirror and burst damage.
    build = struct( ...
        'Weapon', 'LightOfFoliarIncision', ...
        'WeaponATK', 542, ...
        'AtkBonus', 0.28, ...
        'FlatATK', 120, ...
        'EM', 320, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.18, ...
        'DendroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.15, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.18, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'GildedDreams', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Alhaitham', 'artifacts_Alhaitham.csv');
    writetable(struct2table(build), outputPath);
end
