function [totalDMG, dps, breakdown, rotationTime] = simulateAlhaithamDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Alhaitham simulator for mirror generation, projection attacks, and burst instance scaling.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Alhaitham', 'rotation_Alhaitham.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Alhaitham', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Alhaitham', 'talents_Alhaitham.csv');
    talent = readtable(talentPath);
    skillLevel = talentLevel + 3 * double(constellation >= 3);
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    projectionEMBonus = min(1.00, 0.001 * getFieldOrDefault(build, 'EM', 0));
    if projectionEMBonus <= 0
        projectionEMBonus = 0;
    end
    spreadReady = getFieldOrDefault(teamContext, 'ElectroCount', 0) >= 1;

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "RushAttackDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Dendro", 'ActionScalingMode', "EM", 'BaseMultiplier', 1.00, ...
        'PostSetSkillActiveTime', 12.0, 'PostSetStacks', 3, 'AllowCatalyze', double(spreadReady), ...
        'LunarisAttackName', "ElementalArt", 'LunarisDamageParam', "ElementalArt_Damage", 'Note', "Chisel-Light Mirror setup");
    actions.Mirror3 = struct('TalentGroup', "Skill", 'Param', "x3MirrorProjectionAttackDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Dendro", 'ActionScalingMode', "EM", 'BaseMultiplier', 1.00, ...
        'HitCount', 2, 'PostSetStacks', 2, 'AllowCatalyze', double(spreadReady), ...
        'LunarisDamageParam', "ForlornLotus_Attack_03_Damage", 'Note', "Three-mirror projection");
    actions.Mirror2 = struct('TalentGroup', "Skill", 'Param', "x2MirrorProjectionAttackDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Dendro", 'ActionScalingMode', "EM", 'BaseMultiplier', 1.00, ...
        'HitCount', 1, 'PostSetStacks', 1, 'AllowCatalyze', double(spreadReady), ...
        'LunarisDamageParam', "ForlornLotus_Attack_02_Damage", 'Note', "Two-mirror projection");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SingleInstanceDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", 'ActionScalingMode', "EM", 'BaseMultiplier', 1.00, ...
        'HitCount', getTalentValue(talent, 'Burst', 'BasicAttackInstances', burstLevel), ...
        'AllowCatalyze', double(spreadReady), 'PostSetBurstActiveTime', 4.0, ...
        'LunarisAttackName', "SkillObj_ElementalBurst_Dummy", 'LunarisDamageParam', "ElementalBurst_Damage", 'Note', "Fetters of Phenomena");
    actions.QMirror = struct('TalentGroup', "Burst", 'Param', "SingleInstanceDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Dendro", 'ActionScalingMode', "EM", 'BaseMultiplier', 1.00, ...
        'HitCount', max(0, getTalentValue(talent, 'Burst', 'x3MirrorAttackInstances', burstLevel) ...
            - getTalentValue(talent, 'Burst', 'BasicAttackInstances', burstLevel)), ...
        'AllowCatalyze', double(spreadReady), 'LunarisAttackName', "SkillObj_ElementalBurst_Dummy", 'LunarisDamageParam', "ElementalBurst_Damage", 'Note', "Burst mirror follow-up");
    actions.C6Mirror = struct('TalentGroup', "Skill", 'Param', "x3MirrorProjectionAttackDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Dendro", 'ActionScalingMode', "EM", 'BaseMultiplier', 1.00, ...
        'HitCount', 2, 'CritRateBonus', 0.10 * double(constellation >= 6), 'CritDMGBonus', 0.70 * double(constellation >= 6), ...
        'AllowCatalyze', double(spreadReady), 'Note', "C6 mirror overflow");

    defaultRotation = {'E', 'Mirror3', 'Mirror2', 'Q', 'QMirror'};
    if constellation >= 6
        defaultRotation = {'E', 'Mirror3', 'Mirror2', 'Q', 'QMirror', 'C6Mirror'};
    end

    spec = struct( ...
        'Element', "Dendro", ...
        'ScalingMode', "EM", ...
        'DefaultActionTime', 0.85, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct('E', 0.80, 'Mirror3', 1.00, 'Mirror2', 1.00, 'Q', 1.10, 'QMirror', 0.50, 'C6Mirror', 0.20), ...
        'Actions', actions);

    build.EM = getFieldOrDefault(build, 'EM', 0) + 200 * double(constellation >= 2);
    build.DendroDMGBonus = getFieldOrDefault(build, 'DendroDMGBonus', 0) + projectionEMBonus;

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Alhaitham', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
