function [totalDMG, dps, breakdown, rotationTime, audit] = simulateYoimiyaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Yoimiya high-precision simulator with Niwabi conversion, Trouble-Maker
    % ramping, expected C6 extra arrows, and Aurous Blaze follow-up timing.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Yoimiya', 'rotation_Yoimiya.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Yoimiya', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talent = readtable(char(resolveCharacterDataFile('Yoimiya', 'talents')));
    skillLevel = talentLevel + 3 * double(constellation >= 3);
    reverseVapeReady = getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1;
    niwabiMultiplier = getTalentValue(talent, 'Skill', 'BlazingArrowDMG', skillLevel);
    infusedNormalMultiplier = niwabiMultiplier * (1 + 0.30 * double(constellation >= 6));
    c2PyroDamageBonus = 0.25 * double(constellation >= 2);
    aurousDuration = 10.0 + 4.0 * double(constellation >= 1);
    aurousHitCount = 5 + 2 * double(constellation >= 1);
    aurousTimeline = [0.6, 2.0 * ones(1, max(0, aurousHitCount - 1))];

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "BlazingArrowDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", ...
        'MVOverride', 0, ...
        'PostSetSkillActiveTime', 10.0, ...
        'PostSetStacks', 0, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'LunarisAttackName', "ElementalArt", ...
        'LunarisDamageParam', "-", ...
        'Note', "Niwabi Fire-Dance");
    actions.N1 = localInfusedNormalAction("x1HitDMG", infusedNormalMultiplier, c2PyroDamageBonus, reverseVapeReady, "Blazing arrow 1");
    actions.N2 = localInfusedNormalAction("x2HitDMG", infusedNormalMultiplier, c2PyroDamageBonus, reverseVapeReady, "Blazing arrow 2");
    actions.N3 = localInfusedNormalAction("x3HitDMG", infusedNormalMultiplier, c2PyroDamageBonus, reverseVapeReady, "Blazing arrow 3");
    actions.N4 = localInfusedNormalAction("x4HitDMG", infusedNormalMultiplier, c2PyroDamageBonus, reverseVapeReady, "Blazing arrow 4");
    actions.N5 = localInfusedNormalAction("x5HitDMG", infusedNormalMultiplier, c2PyroDamageBonus, reverseVapeReady, "Blazing arrow 5");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', c2PyroDamageBonus, ...
        'PerStackDamageBonus', 0.02, ...
        'AllowAmplify', double(reverseVapeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'PostSetBurstActiveTime', aurousDuration, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Bullet_ElementalBurst_Material", ...
        'LunarisDamageParam', "ElementalBurst_Damage", ...
        'Note', "Ryuukin Saxifrage");
    actions.BurstMark = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "AurousBlazeExplosionDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', c2PyroDamageBonus, ...
        'HitCount', aurousHitCount, ...
        'HitTimeline', aurousTimeline, ...
        'AllowAmplify', double(reverseVapeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_SetTag", ...
        'LunarisDamageParam', "Damage_Perhit", ...
        'Note', "Aurous Blaze explosions");

    spec = struct( ...
        'Element', "Pyro", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Hydro", ...
        'DefaultActionTime', 0.55, ...
        'DefaultRotation', {{'E', 'N1', 'N2', 'N3', 'N4', 'N5', 'N1', 'N2', 'N3', 'N4', 'N5', 'Q', 'BurstMark'}}, ...
        'ActionTimeMap', struct( ...
            'E', 0.50, ...
            'N1', 0.33, ...
            'N2', 0.33, ...
            'N3', 0.34, ...
            'N4', 0.36, ...
            'N5', 0.42, ...
            'Q', 1.00, ...
            'BurstMark', aurousDuration), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Yoimiya', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function action = localInfusedNormalAction(paramName, infusedMultiplier, c2PyroDamageBonus, reverseVapeReady, note)
    action = struct( ...
        'TalentGroup', "Normal", ...
        'Param', string(paramName), ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', infusedMultiplier, ...
        'BaseActionDamageBonus', c2PyroDamageBonus, ...
        'PerStackDamageBonus', 0.02, ...
        'AllowAmplify', double(reverseVapeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'PostAddStacks', 1, ...
        'PostMaxStacks', 10, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "Bullet_Arrow_WithFire_Material", ...
        'LunarisDamageParam', "WithFireDamage", ...
        'Note', string(note));
end
