function [totalDMG, dps, breakdown, rotationTime, audit] = simulateNoelleDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Noelle simulator with Breastplate, Sweeping Time DEF-to-ATK
    % conversion, Geo infusion, and burst charged sequence handling.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Noelle', 'rotation_Noelle.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Noelle', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talent = readtable(char(resolveCharacterDataFile('Noelle', 'talents')));
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    burstAtkBonus = getTalentValue(talent, 'Burst', 'ATKBonus', burstLevel) + 0.50 * double(constellation >= 6);
    burstDuration = 15.0 + 5.0 * double(constellation >= 6);
    chargedBonus = 0.15 * double(constellation >= 2);

    actions = struct();
    actions.N1 = localMakePhysicalClaymoreAction("x1HitDMG", "NormalDMGBonus", "Normal 1");
    actions.N2 = localMakePhysicalClaymoreAction("x2HitDMG", "NormalDMGBonus", "Normal 2");
    actions.N3 = localMakePhysicalClaymoreAction("x3HitDMG", "NormalDMGBonus", "Normal 3");
    actions.N4 = localMakePhysicalClaymoreAction("x4HitDMG", "NormalDMGBonus", "Normal 4");
    actions.Spin = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackCyclicDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', chargedBonus, ...
        'HitCount', 3, ...
        'HitTimeline', 0.45 * ones(1, 3), ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDGroup', "Noelle_Charged", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'Note', "Charged spin");
    actions.SpinFinal = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackFinalDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'BaseActionDamageBonus', chargedBonus, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDGroup', "Noelle_Charged", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'Note', "Charged finisher");
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Geo", ...
        'ActionScalingMode', "DEF", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'PostSetSkillActiveTime', 12.0, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'LunarisAttackName', "Skill_S", ...
        'LunarisDamageParam', "AS_Skill_S_ShieldBrokenDamage_Talent_334", ...
        'Note', "Breastplate cast");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "BurstDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'PostSetBurstActiveTime', burstDuration, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'LunarisAttackName', "Skill_E", ...
        'LunarisDamageParam', "AS_Skill_E_OnceAttackDamage_PS33_P2", ...
        'Note', "Sweeping Time cast");
    actions.B1 = localMakeBurstGeoAction("x1HitDMG", "NormalDMGBonus", burstAtkBonus, 0.00, "Burst normal 1");
    actions.B2 = localMakeBurstGeoAction("x2HitDMG", "NormalDMGBonus", burstAtkBonus, 0.00, "Burst normal 2");
    actions.B3 = localMakeBurstGeoAction("x3HitDMG", "NormalDMGBonus", burstAtkBonus, 0.00, "Burst normal 3");
    actions.B4 = localMakeBurstGeoAction("x4HitDMG", "NormalDMGBonus", burstAtkBonus, 0.00, "Burst normal 4");
    actions.BSpin = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackCyclicDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'DEFWeight', burstAtkBonus, ...
        'BaseActionDamageBonus', chargedBonus, ...
        'HitCount', 3, ...
        'HitTimeline', 0.45 * ones(1, 3), ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Noelle_BurstCharged", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'Note', "Burst charged spin");
    actions.BSpinFinal = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackFinalDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'DEFWeight', burstAtkBonus, ...
        'BaseActionDamageBonus', chargedBonus, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Noelle_BurstCharged", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'Note', "Burst charged finisher");
    actions.BPlungeSlash = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "PlungeDMG", ...
        'DamageField', "PlungeDMGBonus", ...
        'ActionElement', "Geo", ...
        'ActionScalingMode', "ATK", ...
        'DEFWeight', burstAtkBonus, ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Slash", ...
        'LunarisAttackName', "FallingAnthem", ...
        'LunarisDamageParam', "FallingAnthem_Normal_Loop_Damage", ...
        'Note', "Burst plunge slash");
    actions.BPlungeImpact = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "LowHighPlungeDMG", ...
        'DamageField', "PlungeDMGBonus", ...
        'ActionElement', "Geo", ...
        'ActionScalingMode', "ATK", ...
        'DEFWeight', burstAtkBonus, ...
        'BaseMultiplier', 1.00, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'LunarisAttackName', "FallingAnthem", ...
        'LunarisDamageParam', "FallingAnthem_Normal_Rank_2_Damage", ...
        'Note', "Burst plunge impact");

    spec = struct( ...
        'Element', "Geo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.60, ...
        'DefaultRotation', {{'E', 'Q', 'B1', 'B2', 'B3', 'B4', 'BSpin', 'BSpinFinal', 'B1', 'B2'}}, ...
        'ActionTimeMap', struct( ...
            'N1', 0.36, ...
            'N2', 0.38, ...
            'N3', 0.42, ...
            'N4', 0.55, ...
            'Spin', 1.35, ...
            'SpinFinal', 0.45, ...
            'E', 0.68, ...
            'Q', 1.05, ...
            'B1', 0.36, ...
            'B2', 0.38, ...
            'B3', 0.42, ...
            'B4', 0.55, ...
            'BSpin', 1.35, ...
            'BSpinFinal', 0.45, ...
            'BPlungeSlash', 0.20, ...
            'BPlungeImpact', 0.62), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Noelle', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function action = localMakePhysicalClaymoreAction(paramName, damageField, note)
    action = struct( ...
        'TalentGroup', "Normal", ...
        'Param', string(paramName), ...
        'DamageField', string(damageField), ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDGroup', "Noelle_Normal", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'Note', string(note));
end

function action = localMakeBurstGeoAction(paramName, damageField, burstAtkBonus, actionBonus, note)
    action = struct( ...
        'TalentGroup', "Normal", ...
        'Param', string(paramName), ...
        'DamageField', string(damageField), ...
        'ActionElement', "Geo", ...
        'BaseMultiplier', 1.00, ...
        'DEFWeight', burstAtkBonus, ...
        'BaseActionDamageBonus', actionBonus, ...
        'AllowTransformative', 1, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Noelle_BurstNormal", ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'Note', string(note));
end
