function build = customArtifact_Durin()
    % 杜林默认构筑。
    % 默认面板偏向攻击、双暴与火伤，保留适量充能与精通，
    % 以兼顾白焰后台支援形态和暗蚀反应输出形态。
    build = struct( ...
        'Weapon', 'FlamelitLongsword', ...
        'WeaponATK', 674, ...
        'AtkBonus', 1.08, ...
        'FlatATK', 311, ...
        'ER', 1.45, ...
        'EM', 140, ...
        'CritRate', 0.74, ...
        'CritDMG', 2.10, ...
        'PyroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.24, ...
        'ResShred', 0.00 ...
    );

    % 回写默认构筑，便于在表格中直接检查。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Durin', 'artifacts_Durin.csv');
    writetable(struct2table(build), outputPath);
end
