function build = customArtifact_Kinich()
    % Default Kinich build focused on dendro skill damage and crit.
    build = struct( ...
        'Weapon', 'FangOfTheMountainKing', ...
        'WeaponATK', 608, ...
        'AtkBonus', 0.90, ...
        'FlatATK', 311, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.20, ...
        'DendroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.34, ...
        'BurstDMGBonus', 0.18, ...
        'EM', 120, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'ObsidianCodex', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Kinich', 'artifacts_Kinich.csv');
    writetable(struct2table(build), outputPath);
end
