function [totalDMG, dps, breakdown, rotationTime] = simulateKinichDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Kinich medium-detail simulator emphasizing skill loop and burst.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Kinich', 'rotation_Kinich.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Kinich', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "HookATK", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PostSetSkillActiveTime', 10.0, 'PostSetStacks', 1, ...
        'Note', "Hook enter");
    actions.Slash = struct('TalentGroup', "Skill", 'Param', "SlashATK", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PerStackMultiplier', 0.16, 'SkillWindowMultiplier', 0.10, ...
        'PostAddStacks', 1, 'PostMaxStacks', 3, 'C1DamageBonus', 0.10, 'Note', "Loop slash");
    actions.Cannon = struct('TalentGroup', "Skill", 'Param', "CannonATK", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PerStackMultiplier', 0.24, 'SkillWindowMultiplier', 0.12, ...
        'AllowAmplify', 1, 'ReactionBonus', 0.12, 'PostSetStacks', 1, 'C2CritRateBonus', 0.10, ...
        'Note', "Finisher cannon");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "BurstATK", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'C6CritDMGBonus', 0.35, 'Note', "Burst");

    spec = struct( ...
        'Element', "Dendro", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Pyro", ...
        'DefaultActionTime', 0.8, ...
        'ActionTimeMap', struct('E', 0.60, 'Slash', 0.85, 'Cannon', 1.05, 'Q', 1.10), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Kinich', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
