function build = customArtifact_Sigewinne()
    % Default Sigewinne build focused on HP scaling and burst damage.
    build = struct( ...
        'Weapon', 'SilvershowerHeartstrings', ...
        'WeaponATK', 542, ...
        'HPBonus', 1.46, ...
        'FlatHP', 4780, ...
        'CritRate', 0.58, ...
        'CritDMG', 1.88, ...
        'HydroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.28, ...
        'HealingBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'SongOfDaysPast', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Sigewinne', 'artifacts_Sigewinne.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
