function build = customArtifact_Aino()
    % Default Aino build emphasizing ATK-scaling hydro frontline output.
    build = struct( ...
        'Weapon', 'Beacon of the Reed Sea', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.331, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.84, ...
        'FlatATK', 311, ...
        'HPBonus', 0.18, ...
        'FlatHP', 1200, ...
        'CritRate', 0.76, ...
        'CritDMG', 1.98, ...
        'HydroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.18, ...
        'SkillDMGBonus', 0.22, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'MarechausseeHunter', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Aino', 'artifacts_Aino.csv');
    if exist(fileparts(outputPath), 'dir') ~= 7
        mkdir(fileparts(outputPath));
    end
    writetable(struct2table(build), outputPath);
end
