function [totalDMG, dps, breakdown, rotationTime, audit] = simulateAinoDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Aino simulator with staged skill hits, burst ducky cadence, EM burst
    % conversion, and constellation-driven supplemental water balls.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Aino', 'rotation_Aino.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Aino', 'Constellation', constellation, 'Build', build)}, 20, struct(), enemy);
    end

    normalLevel = localClampTalentLevel(talentLevel);
    skillLevel = localClampTalentLevel(talentLevel + 3 * double(constellation >= 5));
    burstLevel = localClampTalentLevel(talentLevel + 3 * double(constellation >= 3));
    bloomReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    electroChargedReady = logical(getFieldOrDefault(teamContext, 'ElectroChargedReady', false) ...
        || getFieldOrDefault(teamContext, 'LunarChargedEnabled', false));
    hydroReactionReady = bloomReady || electroChargedReady || getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1;
    moonsignActive = hasAscendantMoonsign(teamContext);
    c6ReactionBonus = (0.15 + 0.20 * double(moonsignActive)) * double(constellation >= 6);

    burstInterval = 2.0;
    if moonsignActive
        burstInterval = 1.5;
    end
    burstHitCount = max(1, floor(14.0 / burstInterval));
    burstTimeline = burstInterval * ones(1, burstHitCount);
    c2HitCount = 3 * double(constellation >= 2);
    c2Timeline = [0.60, 5.00, 5.00];
    c2Timeline = c2Timeline(1:max(1, c2HitCount));
    c1EM = 80 * double(constellation >= 1);
    c2AtkWeight = 0.25 * double(constellation >= 2);
    c2EMWeight = 1.00 * double(constellation >= 2);
    burstEMWeight = 0.50;

    actions = struct();
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'CanApplyAura', false, ...
        'StrikeType', "Blunt", ...
        'Note', "Normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'CanApplyAura', false, ...
        'StrikeType', "Blunt", ...
        'Note', "Normal 2");
    actions.N3 = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'CanApplyAura', false, ...
        'StrikeType', "Blunt", ...
        'Note', "Normal 3");
    actions.E1 = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "Stage1DMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'LunarisAttackName', "ElementalArt", ...
        'LunarisDamageParam', "Art01_Damage", ...
        'AllowAmplify', double(getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1 || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1), ...
        'AllowTransformative', double(hydroReactionReady), ...
        'PreferredAmplifyAura', localResolveAinoAura(teamContext), ...
        'Note', "Musecatcher throw");
    actions.E2 = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "Stage2DMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Standard (3h/2.5s)", ...
        'LunarisAttackName', "ElementalArt", ...
        'LunarisDamageParam', "Art02_Damage", ...
        'AllowAmplify', double(getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1 || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1), ...
        'AllowTransformative', double(hydroReactionReady), ...
        'PreferredAmplifyAura', localResolveAinoAura(teamContext), ...
        'PostSetSkillActiveTime', 15.0 * double(constellation >= 1), ...
        'Note', "Musecatcher landing");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "WaterBallDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectEMWeight', burstEMWeight, ...
        'HitCount', burstHitCount, ...
        'HitTimeline', burstTimeline, ...
        'PostSetBurstActiveTime', 14.0, ...
        'ApplyGauge', 1.0, ...
        'ICDGroup', "Aino_Ducky", ...
        'ICDRule', "4 hits / 1.8s", ...
        'LunarisAttackName', "ElementalBurst_Gadget", ...
        'LunarisDamageParam', "Burst_Damage", ...
        'AllowAmplify', double(getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1 || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1), ...
        'AllowTransformative', double(hydroReactionReady), ...
        'PreferredAmplifyAura', localResolveAinoAura(teamContext), ...
        'SkillWindowEMBonus', c1EM, ...
        'PostSetSkillActiveTime', 15.0 * double(constellation >= 1), ...
        'Note', "Precision Hydronic Cooler");
    actions.C2Ball = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "WaterBallDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", ...
        'MVOverride', 0, ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectATKWeight', c2AtkWeight, ...
        'FlatDirectEMWeight', c2EMWeight, ...
        'HitCount', max(1, c2HitCount), ...
        'HitTimeline', c2Timeline, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_ConsExtra_Bullet", ...
        'LunarisDamageParam', "Attack_Cons_Ratio", ...
        'AllowAmplify', double(getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1 || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1), ...
        'AllowTransformative', double(hydroReactionReady), ...
        'PreferredAmplifyAura', localResolveAinoAura(teamContext), ...
        'SkillWindowEMBonus', c1EM, ...
        'Note', "C2 extra water balls");

    defaultRotation = {'E1', 'E2', 'Q'};
    if constellation >= 2
        defaultRotation{end + 1} = 'C2Ball'; %#ok<AGROW>
    end
    defaultRotation{end + 1} = 'N1'; %#ok<AGROW>
    defaultRotation{end + 1} = 'N2'; %#ok<AGROW>
    defaultRotation{end + 1} = 'N3'; %#ok<AGROW>

    spec = struct( ...
        'Element', "Hydro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.8, ...
        'DefaultRotation', {defaultRotation}, ...
        'ActionTimeMap', struct('N1', 0.36, 'N2', 0.38, 'N3', 0.46, 'E1', 0.45, 'E2', 0.65, ...
            'Q', 1.10, 'C2Ball', 0.01), ...
        'InitializeStateFn', @(state, hookContext) localInitializeState(state, hookContext, c6ReactionBonus), ...
        'BeforeActionFn', @localBeforeAction, ...
        'AfterActionFn', @localAfterAction, ...
        'AdvanceStateFn', @localAdvanceState, ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Aino', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function aura = localResolveAinoAura(teamContext)
    if getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1
        aura = "Pyro";
    elseif getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1
        aura = "Cryo";
    else
        aura = "";
    end
end

function state = localInitializeState(state, hookContext, c6ReactionBonus) %#ok<INUSD>
    state.AinoReactionBuffTime = 0;
    state.AinoReactionBuffBonus = c6ReactionBonus;
    state.SkillRefundCooldown = 0;
end

function [state, actionSpec, actionTime, note] = localBeforeAction( ...
        state, actionKey, actionSpec, actionTime, note, hookContext) %#ok<INUSD>
    if getFieldOrDefault(state, 'AinoReactionBuffTime', 0) > 1e-6 ...
            && any(actionKey == ["E1", "E2", "Q", "C2Ball"]) ...
            && localAinoReactionBuffRelevant(hookContext.TeamContext)
        actionSpec.ReactionBonus = getFieldOrDefault(actionSpec, 'ReactionBonus', 0) ...
            + getFieldOrDefault(state, 'AinoReactionBuffBonus', 0);
        note = localAppendNote(note, "C6 reaction");
    end
end

function [state, note] = localAfterAction(state, actionKey, actionSpec, actionDamage, reactionTags, note, hookContext) %#ok<INUSD>
    if any(actionKey == ["E1", "E2"]) && getFieldOrDefault(hookContext, 'Constellation', 0) >= 4 ...
            && getFieldOrDefault(state, 'SkillRefundCooldown', 0) <= 1e-6
        state.SkillRefundCooldown = 10.0;
        note = localAppendNote(note, "C4 +10E");
    end

    if actionKey == "Q" && getFieldOrDefault(state, 'AinoReactionBuffBonus', 0) > 0
        state.AinoReactionBuffTime = 15.0;
        note = localAppendNote(note, "C6 ready");
    end
end

function state = localAdvanceState(state, actionTime, hookContext) %#ok<INUSD>
    state.AinoReactionBuffTime = max(0, getFieldOrDefault(state, 'AinoReactionBuffTime', 0) - actionTime);
    state.SkillRefundCooldown = max(0, getFieldOrDefault(state, 'SkillRefundCooldown', 0) - actionTime);
end

function tf = localAinoReactionBuffRelevant(teamContext)
    if getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1 || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1
        tf = false;
        return;
    end

    tf = logical(getFieldOrDefault(teamContext, 'ElectroChargedReady', false) ...
        || getFieldOrDefault(teamContext, 'LunarChargedEnabled', false) ...
        || getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'LunarBloomEnabled', false) ...
        || getFieldOrDefault(teamContext, 'LunarCrystallizeEnabled', false));
end

function note = localAppendNote(baseNote, suffix)
    if strlength(string(baseNote)) == 0
        note = string(suffix);
    else
        note = string(baseNote) + ", " + string(suffix);
    end
end

function level = localClampTalentLevel(level)
    level = max(1, min(15, round(level)));
end
