function [totalDMG, dps, breakdown, rotationTime, audit] = simulateSethosDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Sethos high-detail simulator.
    % Focus:
    % - Shadowpiercing Shot mixed ATK + EM scaling.
    % - A1 fast-charge assumption based on a pre-burst full-energy opener.
    % - A4 Scorching Sandshade applied to the default pre-burst Shadow shots.
    % - Burst Dusk Bolt sequence split by the transformed normal-hit pattern.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Sethos', 'rotation_Sethos.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Sethos', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talentPath = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Sethos', 'talents_Sethos.csv');
    talent = readtable(talentPath);

    normalLevel = localClampTalentLevel(talentLevel);
    skillLevel = localClampTalentLevel(talentLevel + 3 * double(constellation >= 3));
    burstLevel = localClampTalentLevel(talentLevel + 3 * double(constellation >= 5));

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    electroReactionReady = aggravateReady ...
        || getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1;
    enemyTargetCount = max(1, round(getFieldOrDefault(enemy, 'TargetCount', ...
        getFieldOrDefault(enemy, 'EnemyCount', 1))));

    % C4 is a team EM share triggered by AoE Shadow / Dusk hits.
    % For the default AoE case, approximate it as a sustained mid-rotation buff.
    if constellation >= 4 && enemyTargetCount >= 2
        build.EM = getFieldOrDefault(build, 'EM', 0) + 80;
    end

    c2InitialStacks = double(constellation >= 2 && electroReactionReady);
    c2PerStackBonus = 0.15 * double(constellation >= 2);

    normalCoeffs = localResolveNormalBoltCoefficients(talent, normalLevel);
    shadowATKCoeff = localResolveShadowATKCoeff(normalLevel);
    shadowEMCoeff = localResolveShadowEMCoeff(normalLevel);
    duskEMCoeff = getTalentValue(talent, 'Burst', 'DuskBoltDMGIncrease', burstLevel);

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'AllowCatalyze', double(aggravateReady), ...
        'AllowTransformative', double(electroReactionReady), ...
        'PostAddMarks', c2InitialStacks, ...
        'PostMaxMarks', 2, ...
        'LunarisAttackName', "ElementalArt", ...
        'LunarisDamageParam', "ElementalArtDamage", ...
        'Note', "Ancient Rite: The Thundering Sands");
    actions.Aimed = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "AimedShotChargeLevel1", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'AllowCatalyze', double(aggravateReady), ...
        'AllowTransformative', double(electroReactionReady), ...
        'LunarisAttackName', "Bullet_ShootArrow_WithElec", ...
        'LunarisDamageParam', "DamageWithElec", ...
        'Note', "Charge level 1 shot");
    actions.ShadowBuffed = localMakeShadowAction( ...
        shadowATKCoeff, shadowEMCoeff + 7.0, normalLevel, c2PerStackBonus, aggravateReady, electroReactionReady);
    actions.ShadowBuffed.Note = "Shadowpiercing Shot with Scorching Sandshade";
    actions.Shadow = localMakeShadowAction( ...
        shadowATKCoeff, shadowEMCoeff, normalLevel, c2PerStackBonus, aggravateReady, electroReactionReady);
    actions.Shadow.Note = "Shadowpiercing Shot";
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "TwilightMeditationDuration", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", ...
        'MVOverride', 0, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'PostSetBurstActiveTime', 8.0, ...
        'PostAddMarks', double(constellation >= 2), ...
        'PostMaxMarks', 2, ...
        'Note', "Secret Rite: Twilight Shadowpiercer");
    actions.D1 = localMakeDuskBoltAction( ...
        "Bullet_ShootArrow_Lightning_Burst_01", "LightningArrowDamage_Burst_01", ...
        "Dusk Bolt 1", normalCoeffs(1), duskEMCoeff, c2PerStackBonus, aggravateReady, electroReactionReady);
    actions.D2 = localMakeDuskBoltAction( ...
        "Bullet_ShootArrow_Lightning_Burst_02", "LightningArrowDamage_Burst_02", ...
        "Dusk Bolt 2", normalCoeffs(2), duskEMCoeff, c2PerStackBonus, aggravateReady, electroReactionReady);
    actions.D3 = localMakeDuskBoltAction( ...
        "Bullet_ShootArrow_Lightning_Burst_03", "LightningArrowDamage_Burst_03", ...
        "Dusk Bolt 3", normalCoeffs(3), duskEMCoeff, c2PerStackBonus, aggravateReady, electroReactionReady);
    actions.D4 = localMakeDuskBoltAction( ...
        "Bullet_ShootArrow_Lightning_Burst_04", "LightningArrowDamage_Burst_04", ...
        "Dusk Bolt 4", normalCoeffs(4), duskEMCoeff, c2PerStackBonus, aggravateReady, electroReactionReady);

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.75, ...
        'DefaultRotation', {{ ...
            'E', 'ShadowBuffed', 'ShadowBuffed', 'Q', ...
            'D1', 'D2', 'D3', 'D4', ...
            'D1', 'D2', 'D3', 'D4', ...
            'D1', 'D2', 'D3', 'D4'}}, ...
        'ActionTimeMap', struct( ...
            'E', 0.58, ...
            'Aimed', 0.84, ...
            'ShadowBuffed', 0.62, ...
            'Shadow', 0.62, ...
            'Q', 0.72, ...
            'D1', 0.64, ...
            'D2', 0.58, ...
            'D3', 0.50, ...
            'D4', 0.78), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Sethos', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function action = localMakeShadowAction(shadowATKCoeff, shadowEMCoeff, normalLevel, c2PerStackBonus, aggravateReady, electroReactionReady)
    action = struct( ...
        'TalentGroup', "Normal", ...
        'TalentLevelOverride', normalLevel, ...
        'Param', "ShadowpiercingShotDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Electro", ...
        'ActionScalingMode', "ATK", ...
        'MVOverride', shadowATKCoeff, ...
        'FlatDirectEMWeight', shadowEMCoeff, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'AllowCatalyze', double(aggravateReady), ...
        'AllowTransformative', double(electroReactionReady), ...
        'PerMarkDamageBonus', c2PerStackBonus, ...
        'C1CritRateBonus', 0.15, ...
        'PostAddMarks', double(c2PerStackBonus > 0), ...
        'PostMaxMarks', 2, ...
        'LunarisAttackName', "Bullet_ShootArrow_Lightning", ...
        'LunarisDamageParam', "LightningArrowDamage_AttackRatio");
end

function action = localMakeDuskBoltAction( ...
        attackName, damageParam, note, normalCoeff, duskEMCoeff, c2PerStackBonus, aggravateReady, electroReactionReady)
    action = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "DuskBoltDMGIncrease", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Electro", ...
        'ActionScalingMode', "ATK", ...
        'MVOverride', normalCoeff, ...
        'FlatDirectEMWeight', duskEMCoeff, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'AllowCatalyze', double(aggravateReady), ...
        'AllowTransformative', double(electroReactionReady), ...
        'PerMarkDamageBonus', c2PerStackBonus, ...
        'LunarisAttackName', string(attackName), ...
        'LunarisDamageParam', string(damageParam), ...
        'Note', string(note));
end

function coeffs = localResolveNormalBoltCoefficients(talent, normalLevel)
    secondHitFirstRatio = 0.2380 / (0.2380 + 0.2661);
    n1 = getTalentValue(talent, 'Normal', 'x1HitDMG', normalLevel);
    n2 = getTalentValue(talent, 'Normal', 'x2HitDMG', normalLevel);
    n3 = getTalentValue(talent, 'Normal', 'x3HitDMG', normalLevel);

    coeffs = [ ...
        n1, ...
        n2 * secondHitFirstRatio, ...
        n2 * (1 - secondHitFirstRatio), ...
        n3];
end

function value = localResolveShadowATKCoeff(level)
    curve = [ ...
        1.4000, 1.5050, 1.6100, 1.7500, 1.8550, ...
        1.9600, 2.1000, 2.2400, 2.3800, 2.5200, ...
        2.6600, 2.8000, 2.9750, 3.1500, 3.3250];
    value = curve(localClampTalentLevel(level));
end

function value = localResolveShadowEMCoeff(level)
    curve = [ ...
        1.3456, 1.4465, 1.5474, 1.6820, 1.7829, ...
        1.8838, 2.0184, 2.1530, 2.2875, 2.4221, ...
        2.5566, 2.6912, 2.8594, 3.0276, 3.1958];
    value = curve(localClampTalentLevel(level));
end

function level = localClampTalentLevel(level)
    level = max(1, min(15, round(level)));
end
