function [totalDMG, dps, breakdown, rotationTime, audit] = simulateSethosDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Sethos simulator with charge-2 shadow shots, EM passive scaling,
    % and explicit burst dusk-bolt sequencing.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Sethos', 'rotation_Sethos.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Sethos', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    electroReactionReady = aggravateReady ...
        || getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1;

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", ...
        'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), ...
        'AllowTransformative', double(electroReactionReady), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt", ...
        'LunarisDamageParam', "ElementalArtDamage", ...
        'Note', "Ancient Rite: The Thundering Sands");
    actions.Aimed = struct('TalentGroup', "Normal", 'Param', "AimedShotChargeLevel1", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), 'AllowTransformative', double(electroReactionReady), ...
        'ApplyGauge', 1.0, 'ICDRule', "Independent", ...
        'LunarisAttackName', "Bullet_ShootArrow_WithElec", 'LunarisDamageParam', "DamageWithElec", ...
        'Note', "Charge level 1 shot");
    actions.Shadow = struct('TalentGroup', "Normal", 'Param', "ShadowpiercingShotDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'ActionScalingMode', "EM", ...
        'FlatDirectEMWeight', 7.0, ...
        'AllowCatalyze', double(aggravateReady), 'AllowTransformative', double(electroReactionReady), ...
        'ApplyGauge', 2.0, 'ICDRule', "Independent", ...
        'C1CritRateBonus', 0.15, 'C2DamageBonus', 0.30, ...
        'LunarisAttackName', "Bullet_ShootArrow_Lightning", 'LunarisDamageParam', "LightningArrowDamage_AttackRatio", ...
        'Note', "Charge level 2 Shadowpiercing Shot");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "DuskBoltDMGIncrease", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 0.00, ...
        'CanApplyAura', false, 'CanTriggerReaction', false, 'ApplyGauge', 0.0, ...
        'PostSetBurstActiveTime', 8.0, 'Note', "Twilight Meditation");
    actions.Bolt1 = localMakeDuskBoltAction("Bullet_ShootArrow_Lightning_Burst_01", "LightningArrowDamage_Burst_01", ...
        "Dusk Bolt 1", aggravateReady, electroReactionReady);
    actions.Bolt2 = localMakeDuskBoltAction("Bullet_ShootArrow_Lightning_Burst_02", "LightningArrowDamage_Burst_02", ...
        "Dusk Bolt 2", aggravateReady, electroReactionReady);
    actions.Bolt3 = localMakeDuskBoltAction("Bullet_ShootArrow_Lightning_Burst_03", "LightningArrowDamage_Burst_03", ...
        "Dusk Bolt 3", aggravateReady, electroReactionReady);
    actions.Bolt4 = localMakeDuskBoltAction("Bullet_ShootArrow_Lightning_Burst_04", "LightningArrowDamage_Burst_04", ...
        "Dusk Bolt 4", aggravateReady, electroReactionReady);

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "EM", ...
        'DefaultActionTime', 0.75, ...
        'DefaultRotation', {{'E', 'Shadow', 'Shadow', 'Q', 'Bolt1', 'Bolt2', 'Bolt3', 'Bolt4', 'Bolt1', 'Bolt2'}}, ...
        'ActionTimeMap', struct('Aimed', 0.80, 'Shadow', 0.92, 'E', 0.58, 'Q', 0.72, ...
            'Bolt1', 0.72, 'Bolt2', 0.72, 'Bolt3', 0.72, 'Bolt4', 0.72), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Sethos', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function action = localMakeDuskBoltAction(attackName, damageParam, note, aggravateReady, electroReactionReady)
    action = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "DuskBoltDMGIncrease", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Electro", ...
        'ActionScalingMode', "EM", ...
        'BaseMultiplier', 1.00, ...
        'AllowCatalyze', double(aggravateReady), ...
        'AllowTransformative', double(electroReactionReady), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'C2DamageBonus', 0.30, ...
        'LunarisAttackName', string(attackName), ...
        'LunarisDamageParam', string(damageParam), ...
        'Note', string(note));
end

