function [totalDMG, dps, breakdown, rotationTime, audit] = simulateSethosDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Sethos simulator emphasizing EM-scaled Shadowpiercing shots and burst bolts.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Sethos', 'rotation_Sethos.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Sethos', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'Note', "Ancient Rite: Thundering Sands");
    actions.Aimed = struct('TalentGroup', "Normal", 'Param', "AimedShotChargeLevel1", 'DamageField', "ChargedDMGBonus", ...
        'BaseMultiplier', 1.00, 'AllowCatalyze', 1, 'ReactionBonus', 0.08, 'Note', "Charged shot");
    actions.Shadow = struct('TalentGroup', "Normal", 'Param', "ShadowpiercingShotDMG", 'DamageField', "ChargedDMGBonus", ...
        'BaseMultiplier', 1.00, 'ActionScalingMode', "EM", 'AllowCatalyze', 1, 'ReactionBonus', 0.12, 'Note', "Shadowpiercing shot");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "DuskBoltDMGIncrease", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 0.00, 'PostSetBurstActiveTime', 8.0, 'Note', "Burst state");
    actions.BurstBolt = struct('TalentGroup', "Burst", 'Param', "DuskBoltDMGIncrease", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'ActionScalingMode', "EM", 'AllowCatalyze', 1, 'ReactionBonus', 0.12, ...
        'BurstWindowMultiplier', 0.10, 'Note', "Twilight bolt");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "EM", ...
        'DefaultActionTime', 0.75, ...
        'DefaultRotation', {{'E', 'Shadow', 'Shadow', 'Q', 'BurstBolt', 'BurstBolt', 'BurstBolt', 'BurstBolt', 'BurstBolt', 'BurstBolt'}}, ...
        'ActionTimeMap', struct('Aimed', 0.70, 'Shadow', 0.82, 'E', 0.60, 'Q', 0.80, 'BurstBolt', 0.45), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Sethos', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

