clear; clc; close all;
addpath('../functions');  % 自动添加函数路径

% ================== 示例数据 ==================
enemy = struct('Level',90,'Res',0.10,'DefReduct',0);

build = struct(...
    'WeaponATK', 608, ...
    'AtkBonus', 0.50 + 0.466, ...
    'FlatATK', 300, ...
    'CritRate', 0.70, ...
    'CritDMG', 1.80 + 0.88, ...
    'DMGBonus', 0.466 + 0.20, ...
    'ResShred', 0.30, ...
    'ScalingType', 'ATK');

rotation = table([3; 5; 2], [1.5; 2.0; 3.0], [1.0; 0.8; 1.5], ...
    'VariableNames',{'Hits','TalentMV','Time'});

% ================== 计算 ==================
dps = simulateDPS('SampleATKChar', build, enemy, rotation);

% ================== 保存报告 ==================
mkdir('output/reports');
writetable(table({'SampleATKChar'}, dps, 'VariableNames',{'Character','DPS'}), ...
    'output/reports/report.xlsx');