function [totalDMG, dps, breakdown, rotationTime, audit] = simulateThomaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Thoma simulator with skill impact, Crimson Ooyoroi start, Fiery Collapse
    % sequence, HP-scaling passive bonus, and C2 / C6 burst window handling.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Thoma', 'rotation_Thoma.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Thoma', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    workBuild = build;
    workBuild.NormalDMGBonus = getFieldOrDefault(workBuild, 'NormalDMGBonus', 0) + 0.15 * double(constellation >= 6);
    workBuild.ChargedDMGBonus = getFieldOrDefault(workBuild, 'ChargedDMGBonus', 0) + 0.15 * double(constellation >= 6);
    workBuild.PlungeDMGBonus = getFieldOrDefault(workBuild, 'PlungeDMGBonus', 0) + 0.15 * double(constellation >= 6);

    hpValueApprox = getFieldOrDefault(build, 'FlatHP', 0);
    fieryCollapseFlat = 0.022 * hpValueApprox;
    vaporizeReady = getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1;
    burstDuration = 15 + 3 * double(constellation >= 2);
    collapseCount = 8;

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Strike", ...
        'LunarisDamageParam', "ElementalArt_Damage", ...
        'Note', "Blazing Blessing");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'PostSetBurstActiveTime', burstDuration, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Start", ...
        'LunarisDamageParam', "ElementalBurst_Damage", ...
        'Note', "Crimson Ooyoroi");
    actions.Collapse = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "FieryCollapseDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'FlatDirectDamage', fieryCollapseFlat, ...
        'HitCount', collapseCount, ...
        'HitTimeline', (burstDuration / collapseCount) * ones(1, collapseCount), ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_TriggerAttack", ...
        'LunarisDamageParam', "ElementalBurst_TriggerDamage", ...
        'Note', "Fiery Collapse");
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Normal 1");

    spec = struct( ...
        'Element', "Pyro", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Hydro", ...
        'DefaultActionTime', 0.65, ...
        'DefaultRotation', {{'E', 'Q', 'Collapse', 'N1'}}, ...
        'ActionTimeMap', struct( ...
            'E', 0.56, ...
            'Q', 0.92, ...
            'Collapse', burstDuration, ...
            'N1', 0.32), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Thoma', workBuild, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
