function build = customArtifact_Nefer()
    % EM/Dendro damage baseline for Nefer's Shadow Dance and Lunar-Bloom
    % focused field time.
    build = struct( ...
        'Weapon', 'SecretArchive', ...
        'WeaponATK', 608, ...
        'AtkBonus', 0.22, ...
        'FlatATK', 150, ...
        'EM', 900, ...
        'CritRate', 0.68, ...
        'CritDMG', 2.08, ...
        'DendroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Nefer', 'artifacts_Nefer.csv');
    writetable(struct2table(build), outputPath);
end
