function build = customArtifact_Citlali()
    % Default EM/Cryo support build for Citlali's shield and burst window.
    build = struct( ...
        'Weapon', 'ObsidianWhisper', ...
        'WeaponATK', 542, ...
        'EM', 980, ...
        'CritRate', 0.28, ...
        'CritDMG', 0.90, ...
        'CryoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00 ...
    );

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Citlali', 'artifacts_Citlali.csv');
    writetable(struct2table(build), outputPath);
end
