function build = customArtifact_Citlali()
    % 茜特菈莉默认构筑。
    % 默认面板强调精通和冰伤，适配护盾、追击星体和爆发头骨段。
    build = struct( ...
        'Weapon', 'ObsidianWhisper', ...
        'WeaponATK', 542, ...
        'EM', 980, ...
        'CritRate', 0.28, ...
        'CritDMG', 0.90, ...
        'CryoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.24, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'BlizzardStrayer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1 ...
    );

    % 回写 CSV，便于后续直接在表格中查看或微调。
    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Citlali', 'artifacts_Citlali.csv');
    writetable(struct2table(build), outputPath);
end
