function [totalDMG, dps, breakdown, rotationTime] = simulateDoriDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Dori simulator covering skill shot, service rounds, and burst connector ticks.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Dori', 'rotation_Dori.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Dori', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    aggravateReady = getFieldOrDefault(teamContext, 'DendroCount', 0) >= 1;
    actions = struct();
    actions.E = struct('TalentGroup', "Skill", 'Param', "TroubleshooterShotDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'AllowCatalyze', double(aggravateReady), 'Note', "Troubleshooter shot");
    actions.Round = struct('TalentGroup', "Skill", 'Param', "AfterSalesServiceRoundDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'HitCount', 2 + double(constellation >= 4), ...
        'AllowCatalyze', double(aggravateReady), 'Note', "After-sales rounds");
    actions.Q = struct('TalentGroup', "Burst", 'Param', "ConnectorDMG", 'MVOverride', 0, ...
        'DamageField', "BurstDMGBonus", 'PostSetBurstActiveTime', 12.0, 'Note', "Alcazarzaray's Exactitude");
    actions.Connector = struct('TalentGroup', "Burst", 'Param', "ConnectorDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Electro", 'BaseMultiplier', 1.00, 'HitCount', 7, ...
        'AllowCatalyze', double(aggravateReady), 'Note', "Jinni connector ticks");

    spec = struct( ...
        'Element', "Electro", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.75, ...
        'DefaultRotation', {{'E', 'Round', 'Q', 'Connector'}}, ...
        'ActionTimeMap', struct('E', 0.75, 'Round', 1.10, 'Q', 0.95, 'Connector', 12.00), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'Dori', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
