function build = customArtifact_Mizuki()
    % Default Mizuki build balancing personal anemo damage and EM-based support.
    build = struct( ...
        'Weapon', 'Sunny Morning Sleep-In', ...
        'WeaponATK', 542, ...
        'WeaponSubStatType', 'EM', ...
        'WeaponSubStatValue', 265, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.48, ...
        'FlatATK', 220, ...
        'EM', 780, ...
        'ER', 1.35, ...
        'CritRate', 0.42, ...
        'CritDMG', 0.98, ...
        'AnemoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.18, ...
        'BurstDMGBonus', 0.18, ...
        'ReactionDMGBonus', 0.15, ...
        'HealingBonus', 0.15, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'ViridescentVenerer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Mizuki', 'artifacts_Mizuki.csv');
    if exist(fileparts(outputPath), 'dir') ~= 7
        mkdir(fileparts(outputPath));
    end
    writetable(struct2table(build), outputPath);
end
