function [totalDMG, dps, breakdown, rotationTime, audit] = simulateMizukiDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Yumemizuki Mizuki high-detail simulator.
    % Focus:
    % - Dreamdrifter periodic Anemo hits routed through the unified reaction engine
    % - P4 next-tick EM bonus and C1 Twenty-Three Nights' Awaiting swirl package
    % - C2 RES shred / elemental DMG support and C6 swirl CRIT modeling
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Mizuki', 'rotation_Mizuki.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Mizuki', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    workTeamContext = teamContext;
    workBuild = build;
    selfEMShare = 0.10 * getFieldOrDefault(build, 'EM', 0);
    workTeamContext.EMBonus = getFieldOrDefault(workTeamContext, 'EMBonus', 0) - selfEMShare;
    skillExtraResShred = 0;
    if constellation >= 2
        skillExtraResShred = 0.20;
        workTeamContext.PyroResShred = getFieldOrDefault(workTeamContext, 'PyroResShred', 0) - skillExtraResShred;
        workTeamContext.HydroResShred = getFieldOrDefault(workTeamContext, 'HydroResShred', 0) - skillExtraResShred;
        workTeamContext.CryoResShred = getFieldOrDefault(workTeamContext, 'CryoResShred', 0) - skillExtraResShred;
        workTeamContext.ElectroResShred = getFieldOrDefault(workTeamContext, 'ElectroResShred', 0) - skillExtraResShred;
        workTeamContext.AnemoResShred = getFieldOrDefault(workTeamContext, 'AnemoResShred', 0) - skillExtraResShred;
    end

    if localHasReactiveTeammate(workTeamContext)
        workBuild.EM = getFieldOrDefault(workBuild, 'EM', 0) + 100;
    end

    skillLevel = talentLevel + 3 * double(constellation >= 3);
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    swirlElement = localResolvePreferredSwirlElement(workTeamContext);
    swirlReady = strlength(swirlElement) > 0;
    driftTickCount = 4 + 4 * double(swirlReady);
    p4ProcTicks = [1, 3, 5, 7];
    c1ProcTicks = [1, 4, 7];
    forcedSwirlBonus = localResolveForcedSwirlBonus(workTeamContext, swirlElement);

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ExtraResShred', skillExtraResShred, ...
        'PostSetSkillActiveTime', 5.0 + 5.0 * double(swirlReady), ...
        'LunarisAttackName', "ElementalArt", ...
        'LunarisDamageParam', "SkillDMG", ...
        'Note', "Dreamdrifter entry");
    actions.Drift = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "ContinuousAttackDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'ExtraResShred', skillExtraResShred, ...
        'ApplyGauge', 1.0, ...
        'LunarisAttackName', "ElementalArt_WindAttack_Attacker", ...
        'LunarisDamageParam', "DamageRatio", ...
        'Note', "Dreamdrifter tick");
    actions.P4Bonus = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "ContinuousAttackDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'MVOverride', 0, ...
        'FlatDirectEMWeight', 10.0, ...
        'ExtraResShred', skillExtraResShred, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'Note', "P4 next periodic hit bonus");
    actions.C1Swirl = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "ElementalMasteryBasedSwirlDMGIncrease", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'MVOverride', 0, ...
        'AllowTransformative', 1, ...
        'ForceReactionName', "Swirl", ...
        'ReactionElement', swirlElement, ...
        'ExtraResShred', skillExtraResShred, ...
        'ReactionEMWeight', 11.0, ...
        'ReactionBonus', forcedSwirlBonus, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'Note', "C1 empowered swirl");
    actions.C1Anemo = struct( ...
        'TalentGroup', "Skill", ...
        'TalentLevelOverride', skillLevel, ...
        'Param', "ContinuousAttackDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Anemo", ...
        'MVOverride', 0, ...
        'FlatDirectEMWeight', 10.0, ...
        'ExtraResShred', skillExtraResShred, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'CanTriggerReaction', false, ...
        'Note', "C1 follow-up Anemo strike");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'PostSetBurstActiveTime', 12.0, ...
        'LunarisAttackName', "ElementalBurst", ...
        'LunarisDamageParam', "SkillDMG", ...
        'Note', "Anraku Secret Spring Therapy");
    actions.Shockwave = struct( ...
        'TalentGroup', "Burst", ...
        'TalentLevelOverride', burstLevel, ...
        'Param', "MunenShockwaveDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Anemo", ...
        'BaseMultiplier', 1.00, ...
        'LunarisAttackName', "ElementalBurst_DreamGadget_WindAttack", ...
        'LunarisDamageParam', "MunenShockwaveDMG", ...
        'Note', "Special Snack shockwave");

    spec = struct( ...
        'Element', "Anemo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.85, ...
        'DefaultRotation', {localBuildDefaultRotation(driftTickCount, swirlReady, constellation, p4ProcTicks, c1ProcTicks)}, ...
        'ActionTimeMap', struct('E', 0.75, 'Drift', 1.25, 'P4Bonus', 0.01, 'C1Swirl', 0.01, 'C1Anemo', 0.01, ...
            'Q', 1.05, 'Shockwave', 2.20), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Mizuki', workBuild, enemy, seqFile, talentLevel, constellation, workTeamContext, spec);
end

function rotation = localBuildDefaultRotation(driftTickCount, swirlReady, constellation, p4ProcTicks, c1ProcTicks)
    rotation = {'Q', 'Shockwave', 'Shockwave', 'Shockwave', 'Shockwave', 'E'};
    for i = 1:driftTickCount
        rotation{end + 1} = 'Drift'; %#ok<AGROW>
        if swirlReady && any(p4ProcTicks == i)
            rotation{end + 1} = 'P4Bonus'; %#ok<AGROW>
        end
        if swirlReady && constellation >= 1 && any(c1ProcTicks == i)
            rotation{end + 1} = 'C1Swirl'; %#ok<AGROW>
            rotation{end + 1} = 'C1Anemo'; %#ok<AGROW>
        end
    end
end

function element = localResolvePreferredSwirlElement(teamContext)
    if getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1
        element = "Pyro";
    elseif getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1
        element = "Hydro";
    elseif getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1
        element = "Cryo";
    elseif getFieldOrDefault(teamContext, 'ElectroCount', 0) >= 1
        element = "Electro";
    else
        element = "";
    end
end

function bonus = localResolveForcedSwirlBonus(teamContext, swirlElement)
    bonus = 0;
    if strcmpi(char(swirlElement), 'Cryo')
        bonus = bonus + getFieldOrDefault(teamContext, 'CryoSwirlBonus', 0);
    end
end

function tf = localHasReactiveTeammate(teamContext)
    tf = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'CryoCount', 0) >= 1 ...
        || getFieldOrDefault(teamContext, 'ElectroCount', 0) >= 1;
end
