function [totalDMG, dps, breakdown, rotationTime, audit] = simulateSangonomiyaKokomiDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Sangonomiya Kokomi simulator with Bake-Kurage field uptime, burst HP
    % bonus conversion, and on-field ceremonial normal strings.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'SangonomiyaKokomi', 'rotation_SangonomiyaKokomi.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'SangonomiyaKokomi', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    talent = readtable(char(resolveCharacterDataFile('SangonomiyaKokomi', 'talents')));
    burstLevel = talentLevel + 3 * double(constellation >= 5);
    normalHPBonus = getTalentValue(talent, 'Burst', 'NormalAttackDMGBonus', burstLevel);
    chargedHPBonus = getTalentValue(talent, 'Burst', 'ChargedAttackDMGBonus', burstLevel);
    kurageHPBonus = getTalentValue(talent, 'Burst', 'BakeKurageDMGBonus', burstLevel);
    healingBonus = getFieldOrDefault(build, 'HealingBonus', 0);
    burstA4Bonus = 0.15 * healingBonus;
    burstDuration = 10.0;
    burstHydroBonus = 0.40 * double(constellation >= 6);
    vaporizeReady = getFieldOrDefault(teamContext, 'PyroCount', 0) >= 1;

    actions = struct();
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "RippleDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'ActionScalingMode', "ATK", ...
        'PostSetSkillActiveTime', 12.0, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Gadget_Controller", ...
        'LunarisDamageParam', "ElementalArt_Damage_Percentage", ...
        'Note', "Kurage's Oath cast");
    actions.Jelly = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "RippleDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'HPWeight', kurageHPBonus, ...
        'BurstWindowDamageBonus', burstHydroBonus, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'HitCount', 6, ...
        'HitTimeline', 2.0 * ones(1, 6), ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Gadget_Controller", ...
        'LunarisDamageParam', "ElementalArt_Damage_Percentage", ...
        'Note', "Bake-Kurage ticks");
    actions.Q = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Hydro", ...
        'ActionScalingMode', "HP", ...
        'BaseMultiplier', 1.00, ...
        'PostSetBurstActiveTime', burstDuration, ...
        'PostSetSkillActiveTime', 12.0, ...
        'ApplyGauge', 2.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Initiate", ...
        'LunarisDamageParam', "-", ...
        'Note', "Nereid's Ascension");
    actions.BN1 = localMakeKokomiBurstNormalAction("x1HitDMG", "NormalAttack_Bullet_1_Burst_Damage", "NormalAttack_01_Damage", normalHPBonus + burstA4Bonus + burstHydroBonus, "Burst normal 1");
    actions.BN2 = localMakeKokomiBurstNormalAction("x2HitDMG", "NormalAttack_Bullet_2_Burst_Damage", "NormalAttack_02_Damage", normalHPBonus + burstA4Bonus + burstHydroBonus, "Burst normal 2");
    actions.BN3 = localMakeKokomiBurstNormalAction("x3HitDMG", "NormalAttack_Bullet_3_Burst_Damage", "NormalAttack_03_Damage", normalHPBonus + burstA4Bonus + burstHydroBonus, "Burst normal 3");
    actions.BCA = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Hydro", ...
        'ActionScalingMode', "ATK", ...
        'BaseMultiplier', 1.00, ...
        'HPWeight', chargedHPBonus + burstA4Bonus, ...
        'FlatDamageBonus', burstHydroBonus, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'Note', "Burst charged attack");
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", ...
        'BaseMultiplier', 1.00, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Pyro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "NormalAttack_Bullet_1_Damage", ...
        'LunarisDamageParam', "NormalAttack_01_Damage", ...
        'Note', "Normal 1");

    spec = struct( ...
        'Element', "Hydro", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Pyro", ...
        'DefaultActionTime', 0.60, ...
        'DefaultRotation', {{'E', 'Jelly', 'Q', 'BN1', 'BN2', 'BN3', 'BCA'}}, ...
        'ActionTimeMap', struct( ...
            'E', 0.62, ...
            'Jelly', 12.00, ...
            'Q', 0.95, ...
            'BN1', 0.34, ...
            'BN2', 0.34, ...
            'BN3', 0.42, ...
            'BCA', 0.90, ...
            'N1', 0.34), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'SangonomiyaKokomi', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

function action = localMakeKokomiBurstNormalAction(paramName, lunarisName, lunarisParam, hpBonus, note)
    action = struct( ...
        'TalentGroup', "Normal", ...
        'Param', string(paramName), ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Hydro", ...
        'ActionScalingMode', "ATK", ...
        'BaseMultiplier', 1.00, ...
        'HPWeight', hpBonus, ...
        'AllowAmplify', 0, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', string(lunarisName), ...
        'LunarisDamageParam', string(lunarisParam), ...
        'Note', string(note));
end
