function [totalDMG, dps, breakdown, rotationTime, audit] = simulateXinyanDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Xinyan simulator with physical normal / charged string, shield DoT,
    % burst physical plus Pyro wave, and DEF-based charged / C2 burst logic.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Xinyan', 'rotation_Xinyan.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Xinyan', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    chargedDefBonus = 0.50 * double(constellation >= 6);
    burstCritBonus = 1.00 * double(constellation >= 2);
    skillPhysicalShred = 0.15 * double(constellation >= 4);
    vaporizeReady = getFieldOrDefault(teamContext, 'HydroCount', 0) >= 1;

    actions = struct();
    actions.N1 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x1HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Normal 1");
    actions.N2 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x2HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Normal 2");
    actions.N3 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x3HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Normal 3");
    actions.N4 = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "x4HitDMG", ...
        'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'Note', "Normal 4");
    actions.Spin = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackCyclicDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'DEFWeight', chargedDefBonus, ...
        'HitCount', 3, ...
        'HitTimeline', 0.45 * ones(1, 3), ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'Note', "Charged spin");
    actions.SpinFinal = struct( ...
        'TalentGroup', "Normal", ...
        'Param', "ChargedAttackFinalDMG", ...
        'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'DEFWeight', chargedDefBonus, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'CanShatter', true, ...
        'Note', "Charged finisher");
    actions.E = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "SwingDMG", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'EnemyDefReduct', skillPhysicalShred, ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'PostSetSkillActiveTime', 12.0, ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'StrikeType', "Blunt", ...
        'LunarisAttackName', "ElementalArt_Hit", ...
        'LunarisDamageParam', "Xinyan_ElementalArt_Damage", ...
        'Note', "Sweeping Fervor");
    actions.ShieldDoT = struct( ...
        'TalentGroup', "Skill", ...
        'Param', "DoT", ...
        'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', 3, ...
        'HitTimeline', 2.0 * ones(1, 3), ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalArt_Shield_3", ...
        'LunarisDamageParam', "Xinyan_ElementalArt_Damage_Percentage", ...
        'Note', "Rave shield DoT");
    actions.QPhysical = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "SkillDMG", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Physical", ...
        'BaseMultiplier', 1.00, ...
        'CritRateBonus', burstCritBonus, ...
        'ApplyGauge', 0.0, ...
        'CanApplyAura', false, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Hit", ...
        'LunarisDamageParam', "Xinyan_ElementalBurst_PhysicalDamage", ...
        'Note', "Riff Revolution physical");
    actions.QPyro = struct( ...
        'TalentGroup', "Burst", ...
        'Param', "PyroDoT", ...
        'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Pyro", ...
        'BaseMultiplier', 1.00, ...
        'HitCount', 2, ...
        'HitTimeline', [0.10, 0.10], ...
        'AllowAmplify', double(vaporizeReady), ...
        'PreferredAmplifyAura', "Hydro", ...
        'ApplyGauge', 1.0, ...
        'ICDRule', "Independent", ...
        'LunarisAttackName', "ElementalBurst_Fire", ...
        'LunarisDamageParam', "Xinyan_ElementalBurst_FireDamage", ...
        'Note', "Riff Revolution pyro wave");

    spec = struct( ...
        'Element', "Pyro", ...
        'ScalingMode', "ATK", ...
        'PreferredAmplifyAura', "Hydro", ...
        'DefaultActionTime', 0.70, ...
        'DefaultRotation', {{'E', 'ShieldDoT', 'QPhysical', 'QPyro', 'N1', 'N2', 'Spin', 'SpinFinal'}}, ...
        'ActionTimeMap', struct( ...
            'N1', 0.36, ...
            'N2', 0.38, ...
            'N3', 0.44, ...
            'N4', 0.58, ...
            'Spin', 1.35, ...
            'SpinFinal', 0.46, ...
            'E', 0.62, ...
            'ShieldDoT', 6.00, ...
            'QPhysical', 0.90, ...
            'QPyro', 0.20), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Xinyan', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
