function build = customArtifact_KamisatoAyaka()
    % Default Ayaka build for freeze-oriented burst and infused normal strings.
    build = struct( ...
        'Weapon', 'MistsplitterReforged', ...
        'WeaponATK', 674, ...
        'WeaponSubStatType', 'CD', ...
        'WeaponSubStatValue', 0.441, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.92, ...
        'FlatATK', 311, ...
        'ER', 1.20, ...
        'CritRate', 0.45, ...
        'CritDMG', 2.35, ...
        'CryoDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.00, ...
        'BurstDMGBonus', 0.00, ...
        'ArtifactSet1', 'BlizzardStrayer', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'KamisatoAyaka', 'artifacts_KamisatoAyaka.csv');
    writetable(struct2table(build), outputPath);
end
