function [totalDMG, dps, breakdown, rotationTime, audit] = simulateKamisatoAyakaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Ayaka explicit infused string / burst storm script with approximation.
    % Senho, infused normals and charged attacks, and burst storm segments
    % are modeled as separate actions with C6 first-CA handling.
    % Remaining approximation: C2 side storms use expected-damage rows
    % instead of target-position-resolved hit confirmation.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'KamisatoAyaka', 'rotation_KamisatoAyaka.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'KamisatoAyaka', 'Constellation', constellation, 'Build', build)}, 20, struct(), enemy);
    end

    dashCryoBonus = 0.18;
    skillWindowBonus = 0.30;
    c6ChargedBonus = 2.98;
    burstReducedDef = 0.30 * double(constellation >= 4);
    burstSmallStormRatio = 0.40 * double(constellation >= 2);

    actions = struct();
    actions.Senho = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'MVOverride', 0, 'BaseActionDamageBonus', dashCryoBonus, ...
        'PostSetBurstActiveTime', 10.0, 'Note', "Kamisato Art: Senho end hit aura");
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', dashCryoBonus, ...
        'PostSetSkillActiveTime', 6.0, 'Note', "Kamisato Art: Hyouka");
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', dashCryoBonus, ...
        'SkillWindowDamageBonus', skillWindowBonus, 'Note', "Cryo-infused normal 1");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', dashCryoBonus, ...
        'SkillWindowDamageBonus', skillWindowBonus, 'Note', "Cryo-infused normal 2");
    actions.N3 = struct('TalentGroup', "Normal", 'Param', "x3HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', dashCryoBonus, ...
        'SkillWindowDamageBonus', skillWindowBonus, 'Note', "Cryo-infused normal 3");
    actions.N4 = struct('TalentGroup', "Normal", 'Param', "x4HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 2, 'BaseActionDamageBonus', dashCryoBonus, ...
        'SkillWindowDamageBonus', skillWindowBonus, 'Note', "Cryo-infused normal 4");
    actions.N5 = struct('TalentGroup', "Normal", 'Param', "x5HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', dashCryoBonus, ...
        'SkillWindowDamageBonus', skillWindowBonus, 'Note', "Cryo-infused normal 5");
    actions.CA6 = struct('TalentGroup', "Normal", 'Param', "ChargedAttackDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 3, 'BaseActionDamageBonus', dashCryoBonus, ...
        'SkillWindowDamageBonus', skillWindowBonus, 'C6ActionDamageBonus', c6ChargedBonus, ...
        'Note', "Cryo-infused charged attack (C6 first CA)");
    actions.CA = struct('TalentGroup', "Normal", 'Param', "ChargedAttackDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 3, 'BaseActionDamageBonus', dashCryoBonus, ...
        'SkillWindowDamageBonus', skillWindowBonus, ...
        'Note', "Cryo-infused charged attack");
    actions.QCut = struct('TalentGroup', "Burst", 'Param', "CuttingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 20, 'BaseActionDamageBonus', dashCryoBonus, ...
        'EnemyDefReduct', burstReducedDef, 'Note', "Soumetsu main storm");
    actions.QCutC2 = struct('TalentGroup', "Burst", 'Param', "CuttingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', burstSmallStormRatio, 'HitCount', 20, ...
        'BaseActionDamageBonus', dashCryoBonus, 'EnemyDefReduct', burstReducedDef, ...
        'Note', "C2 side storm x2 expected");
    actions.QBloom = struct('TalentGroup', "Burst", 'Param', "BloomDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 2, 'BaseActionDamageBonus', dashCryoBonus, ...
        'EnemyDefReduct', burstReducedDef, 'Note', "Soumetsu bloom");
    actions.QBloomC2 = struct('TalentGroup', "Burst", 'Param', "BloomDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', burstSmallStormRatio, 'HitCount', 2, ...
        'BaseActionDamageBonus', dashCryoBonus, 'EnemyDefReduct', burstReducedDef, ...
        'Note', "C2 side storm bloom x2 expected");

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.72, ...
        'DefaultRotation', {{'Senho', 'E', 'QCut', 'QBloom', 'N1', 'N2', 'N3', 'N4', 'CA', 'Senho', 'N1', 'N2', 'CA'}}, ...
        'ActionTimeMap', struct( ...
            'Senho', 0.35, 'E', 0.70, ...
            'N1', 0.32, 'N2', 0.38, 'N3', 0.42, 'N4', 0.45, 'N5', 0.55, 'CA6', 0.82, 'CA', 0.82, ...
            'QCut', 2.20, 'QCutC2', 0.05, 'QBloom', 0.10, 'QBloomC2', 0.05), ...
        'Actions', actions);

    if constellation >= 2
        spec.DefaultRotation = {{'Senho', 'E', 'QCut', 'QCutC2', 'QBloom', 'QBloomC2', 'N1', 'N2', 'N3', 'N4', 'CA', 'Senho', 'N1', 'N2', 'CA'}};
    end
    if constellation >= 6
        spec.DefaultRotation = {{'Senho', 'E', 'QCut', 'QCutC2', 'QBloom', 'QBloomC2', 'N1', 'N2', 'N3', 'N4', 'CA6', 'Senho', 'N1', 'N2', 'CA'}};
    end

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'KamisatoAyaka', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
