function [totalDMG, dps, breakdown, rotationTime] = simulateKamisatoAyakaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % 神里绫华高精度近似模拟。
    % 建模要点：
    % 1. 显式区分冲刺附魔后的普攻/重击、E 后 6 秒普重击增伤、冲刺后 10 秒冰伤加成；
    % 2. 将 Q 拆分为主风暴切割段、终结绽放段，以及 C2 两道小风暴的期望伤害；
    % 3. C4 通过 Q 段内减防直接写入敌方防御区，C6 按“首个重击大幅强化”建模；
    % 4. 默认轮转改为更接近冻结队的冲刺起手轴，而不是依赖 AUTO 兜底。
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'KamisatoAyaka', 'rotation_KamisatoAyaka.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'KamisatoAyaka', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    dashCryoBonus = 0.18;
    skillWindowBonus = 0.30;
    c6ChargedBonus = 2.98;
    burstReducedDef = 0.30 * double(constellation >= 4);
    burstSmallStormRatio = 0.20 * double(constellation >= 2);

    actions = struct();
    actions.Senho = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'MVOverride', 0, 'BaseActionDamageBonus', dashCryoBonus, ...
        'PostSetBurstActiveTime', 10.0, 'Note', "Kamisato Art: Senho end hit aura");
    actions.E = struct('TalentGroup', "Skill", 'Param', "SkillDMG", 'DamageField', "SkillDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', dashCryoBonus, ...
        'PostSetSkillActiveTime', 6.0, 'Note', "Kamisato Art: Hyouka");
    actions.N1 = struct('TalentGroup', "Normal", 'Param', "x1HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', dashCryoBonus, ...
        'SkillWindowDamageBonus', skillWindowBonus, 'Note', "Cryo-infused normal 1");
    actions.N2 = struct('TalentGroup', "Normal", 'Param', "x2HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', dashCryoBonus, ...
        'SkillWindowDamageBonus', skillWindowBonus, 'Note', "Cryo-infused normal 2");
    actions.N3 = struct('TalentGroup', "Normal", 'Param', "x3HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', dashCryoBonus, ...
        'SkillWindowDamageBonus', skillWindowBonus, 'Note', "Cryo-infused normal 3");
    actions.N4 = struct('TalentGroup', "Normal", 'Param', "x4HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 2, 'BaseActionDamageBonus', dashCryoBonus, ...
        'SkillWindowDamageBonus', skillWindowBonus, 'Note', "Cryo-infused normal 4");
    actions.N5 = struct('TalentGroup', "Normal", 'Param', "x5HitDMG", 'DamageField', "NormalDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'BaseActionDamageBonus', dashCryoBonus, ...
        'SkillWindowDamageBonus', skillWindowBonus, 'Note', "Cryo-infused normal 5");
    actions.CA = struct('TalentGroup', "Normal", 'Param', "ChargedAttackDMG", 'DamageField', "ChargedDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 3, 'BaseActionDamageBonus', dashCryoBonus, ...
        'SkillWindowDamageBonus', skillWindowBonus, 'C6ActionDamageBonus', c6ChargedBonus, ...
        'Note', "Cryo-infused charged attack");
    actions.QCut = struct('TalentGroup', "Burst", 'Param', "CuttingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 20, 'BaseActionDamageBonus', dashCryoBonus, ...
        'EnemyDefReduct', burstReducedDef, 'Note', "Soumetsu main storm");
    actions.QCutC2 = struct('TalentGroup', "Burst", 'Param', "CuttingDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', burstSmallStormRatio, 'HitCount', 20, ...
        'BaseActionDamageBonus', dashCryoBonus, 'EnemyDefReduct', burstReducedDef, ...
        'Note', "C2 side storm x2 expected");
    actions.QBloom = struct('TalentGroup', "Burst", 'Param', "BloomDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', 1.00, 'HitCount', 2, 'BaseActionDamageBonus', dashCryoBonus, ...
        'EnemyDefReduct', burstReducedDef, 'Note', "Soumetsu bloom");
    actions.QBloomC2 = struct('TalentGroup', "Burst", 'Param', "BloomDMG", 'DamageField', "BurstDMGBonus", ...
        'ActionElement', "Cryo", 'BaseMultiplier', burstSmallStormRatio, 'HitCount', 2, ...
        'BaseActionDamageBonus', dashCryoBonus, 'EnemyDefReduct', burstReducedDef, ...
        'Note', "C2 side storm bloom x2 expected");

    spec = struct( ...
        'Element', "Cryo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.72, ...
        'DefaultRotation', {{'Senho', 'E', 'QCut', 'QBloom', 'N1', 'N2', 'N3', 'N4', 'CA', 'Senho', 'N1', 'N2', 'CA'}}, ...
        'ActionTimeMap', struct( ...
            'Senho', 0.35, 'E', 0.70, ...
            'N1', 0.32, 'N2', 0.38, 'N3', 0.42, 'N4', 0.45, 'N5', 0.55, 'CA', 0.82, ...
            'QCut', 2.20, 'QCutC2', 0.05, 'QBloom', 0.10, 'QBloomC2', 0.05), ...
        'Actions', actions);

    if constellation >= 2
        spec.DefaultRotation = {{'Senho', 'E', 'QCut', 'QCutC2', 'QBloom', 'QBloomC2', 'N1', 'N2', 'N3', 'N4', 'CA', 'Senho', 'N1', 'N2', 'CA'}};
    end

    [totalDMG, dps, breakdown, rotationTime] = simulateSimpleCharacterDPS( ...
        'KamisatoAyaka', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end
