function build = customArtifact_KamisatoAyato()
    % Default Ayato build for Takimeguri Kanka slashes and burst support.
    build = struct( ...
        'Weapon', 'HaranGeppakuFutsu', ...
        'WeaponATK', 608, ...
        'WeaponSubStatType', 'CR', ...
        'WeaponSubStatValue', 0.331, ...
        'WeaponRefinement', 1, ...
        'AtkBonus', 0.46, ...
        'FlatATK', 160, ...
        'HPBonus', 0.20, ...
        'CritRate', 0.75, ...
        'CritDMG', 2.05, ...
        'HydroDMGBonus', 0.466, ...
        'NormalDMGBonus', 0.20, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'HeartOfDepth', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'KamisatoAyato', 'artifacts_KamisatoAyato.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
