function build = customArtifact_Chasca()
    % Default Chasca build shared by standalone and team simulations.
    build = struct( ...
        'Weapon', 'Astral Vulture Bow', ...
        'WeaponATK', 608, ...
        'AtkBonus', 0.85, ...
        'FlatATK', 311, ...
        'CritRate', 0.74, ...
        'CritDMG', 2.05, ...
        'AnemoDMGBonus', 0.466, ...
        'ChargedDMGBonus', 0.35, ...
        'SkillDMGBonus', 0.20, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 80, ...
        'ResShred', 0.00);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Chasca', 'artifacts_Chasca.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
