function build = customArtifact_Navia()
    % Default Navia build focused on geo skill/burst damage and crit.
    build = struct( ...
        'Weapon', 'Verdict', ...
        'WeaponATK', 674, ...
        'AtkBonus', 0.92, ...
        'FlatATK', 311, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.18, ...
        'GeoDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.28, ...
        'BurstDMGBonus', 0.20, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'NighttimeWhispersInTheEchoingWoods', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Navia', 'artifacts_Navia.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
