function [totalDMG, dps, breakdown, rotationTime, audit] = simulateNaviaDPS(build, enemy, seqFile, talentLevel, constellation, teamContext)
    % Navia simulator using full Lunaris multipliers for skill shells and burst support fire.
    if nargin < 3 || isempty(seqFile)
        seqFile = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'data', 'Navia', 'rotation_Navia.txt');
    end
    if nargin < 4 || isempty(talentLevel)
        talentLevel = 10;
    end
    if nargin < 5 || isempty(constellation)
        constellation = 0;
    end
    if nargin < 6 || isempty(teamContext)
        teamContext = buildTeamContext({struct('Name', 'Navia', 'Constellation', constellation, 'Build', build)}, 20, struct());
    end

    actions = struct();
    actions.Q = struct('TalentGroup', "Burst", 'Param', "SkillDMG", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'Note', "As the Sunlit Sky's Singing Salute");
    actions.Support = struct('TalentGroup', "Burst", 'Param', "CannonFireSupportDMG", 'DamageField', "BurstDMGBonus", ...
        'BaseMultiplier', 1.00, 'Note', "Burst support fire");
    actions.E = struct('TalentGroup', "Skill", 'Param', "RosulaShardshotBaseDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'PerStackMultiplier', 0.14, 'PreSetStacks', 6, 'PostSetStacks', 0, ...
        'C2CritRateBonus', 0.12, 'C6CritDMGBonus', 0.45, 'Note', "Rosula Shardshot");
    actions.Blade = struct('TalentGroup', "Skill", 'Param', "SurgingBladeDMG", 'DamageField', "SkillDMGBonus", ...
        'BaseMultiplier', 1.00, 'Note', "Surging blade");

    spec = struct( ...
        'Element', "Geo", ...
        'ScalingMode', "ATK", ...
        'DefaultActionTime', 0.75, ...
        'DefaultRotation', {{'Q', 'Support', 'Support', 'Support', 'Support', 'E', 'Blade', 'Blade'}}, ...
        'ActionTimeMap', struct('Q', 1.10, 'Support', 1.80, 'E', 0.75, 'Blade', 0.35), ...
        'Actions', actions);

    [totalDMG, dps, breakdown, rotationTime, audit] = simulateSimpleCharacterDPS( ...
        'Navia', build, enemy, seqFile, talentLevel, constellation, teamContext, spec);
end

