function build = customArtifact_Emilie()
    % Default Emilie build focused on dendro skill/burst damage and crit.
    build = struct( ...
        'Weapon', 'LumidouceElegy', ...
        'WeaponATK', 608, ...
        'AtkBonus', 0.88, ...
        'FlatATK', 311, ...
        'CritRate', 0.72, ...
        'CritDMG', 2.10, ...
        'DendroDMGBonus', 0.466, ...
        'SkillDMGBonus', 0.32, ...
        'BurstDMGBonus', 0.20, ...
        'EM', 80, ...
        'ResShred', 0.00, ...
        'ArtifactSet1', 'UnfinishedReverie', ...
        'ArtifactSet1Pieces', 4, ...
        'ArtifactSet2', 'None', ...
        'ArtifactSet2Pieces', 0, ...
        'ArtifactSet4Active', 1);

    thisFolder = fileparts(mfilename('fullpath'));
    outputPath = fullfile(thisFolder, '..', '..', 'data', 'Emilie', 'artifacts_Emilie.csv');
    writeDefaultArtifactBuild(build, outputPath);
end
